### ISSUE TITLE
versions of securedrop for independent journalists, not affiliated with media orgs?

### ISSUE THREAD

**Issue by thomasdoig** [freedomofpress/securedrop#1011]
Hi SecureDrop people, 

This looks and sounds like a fantastic service. However, I am an independent long-form journalist, not affiliated with any media organisation.

Is there a version of SecureDrop I should use? Failing that, is there a comparable service I should use? I can't afford $2400 of new hardware right now!

Thanks in advance,

Tom Doig

**Comment by humanitiesNerd** [comment]
@thomasdoig  There's Globaleaks ! 

Why is it designed to run on a $5/month vps ? Just to enable grassroots organizations, like you 

https://github.com/globaleaks/GlobaLeaks

**Comment by dolanjs** [comment]
@thomasdoig While purchasing small form factor devices for the SecureDrop environment will cost ~ $2400, hardware can be purchased to meet the minimum requirements extremely cheaper.

* The App and Monitor servers can be any PC or laptop that can run Ubuntu. For some orgs sourcing new hardware is easier than re purposing other hardware. But the SecureDrop App and Monitor servers have run fine on some old Dell Optiplexes that were purchased from a hardware liquidator for less than $100 a piece with about 2GB of RAM. (Tor is going to be the bottleneck not the physical hardware usually)

* The network firewall can also run on a PC if additional NICs are installed. But again pfsense does not need any beefy hardware to support the SecureDrop environment. For selecting hardware components for pfsense please see their  [Hardware Requirements and Guidance](https://www.pfsense.org/hardware/) section.

* The SVS also does not need any beefy hardware and can be most low budget laptop models.

### VPS vs physical
We do not recommend  hosting the SecureDrop environment or any sensitive submission platform on VPSs. While the price and management free features of VPS solutions would reduce the upfront costs, it also means that the VPS provider can access the clear text content of submissions while in memory prior to be encrypted and written to disk. The VPS provider could be coerced (intentionally or not) to turn that information over. Other attack vectors could also be introduced in the VPS model and is a risk that we do not recommend accepting.

**Comment by garrettr** [comment]
Hey @thomasdoig, thanks for filing this issue. We'd love to hear more from independent journalists about what they think it would take to make SecureDrop work for them. The current constraints, as I see them, are:

1. Freedom of the Press Foundation cannot run SecureDrop "as a service", since that would be a legal risk of the context of the third party doctrine in the US, as well as a single point of failure security-wise. Instead, we require all interested users of SecureDrop to deploy their own independent instances.
2. While it is possible to run SecureDrop on a VPS, it is not possible "out of the box" and it is definitely not recommended for the reasons @dolanjs described in his comment.
3. While we have worked (and are continuing to work) hard on simplifying the installation and maintenance of a SecureDrop instance, it still requires a nontrivial amount of technical skill. One of the biggest tradeoffs we face is allowing less-experienced sysadmins to operate SecureDrop instances on their own, which is strictly better in a legal context but may not be better in a computer security context.

Again, we recommend running your own independent instance on dedicated hardware for the best security and legal protection. As @dolanjs pointed out, you can repurpose existing hardware or buy cheap used hardware if the cost of the default setup we describe in `hardware.md` is prohibitive.

Please let us know if you have any more questions!

**Comment by Taipo** [comment]
Just a thought.

Since not all journalist organisations are your standard office/server room/IT person arrangement, has anyone looked at the potential of running the 'Monitor Server' on VirtualBox i.e a standalone App Server and a current journo workstation (or in the instance of a single journo operation as above - their home PC) running VirtualBox or similar running the Monitor Server.

**Comment by redshiftzero** [comment]
An interesting point - but I would discourage freelance journalists from cobbling together a virtualized environment to run the application and monitor servers due to the loss of hardware isolation significantly changing [SecureDrop's threat model](https://docs.securedrop.org/en/stable/development/threat_model.html). We have talked internally about potentially using another isolation method in the future but such a change should be carefully considered. 

A freelance journalist interested in working with SecureDrop could [work with one of the non-profits or news organizations listed in the directory](https://securedrop.org/directory), use cheaper hardware instead of the official recommendations to deploy their own SecureDrop instance as @garrettr and @dolanjs describe ([while being careful to avoid cloud servers](https://docs.securedrop.org/en/stable/hardware.html#required-hardware)), or use another whistleblowing platform that is easier to deploy (e.g. GlobalLeaks). 

I think this is fully answered, so am closing this issue for now! Please feel free to open another issue if there are other questions not addressed here.
