### ISSUE TITLE
Rethink javascript warning

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#1024]
Tor Browser 4.5 (and Tails 1.4) include much more fine-grained security settings than before. Rather than telling users to disable js using NoScript, I think it makes more sense to tell them to adjust to a more secure setting -- either High or Medium-High.

![screenshot from 2015-05-13 19 23 50](https://cloud.githubusercontent.com/assets/156128/7620021/a8acf220-f971-11e4-911f-358a548a29c0.png)

**Comment by Taipo** [comment]
Makes sense.

**Comment by garrettr** [comment]
Agreed, although NoScript still works for now (in current release TB 4.5.1) so I don't think it is urgent to make this change. The protection from the Security Slider is more holistic, so it would be good to switch over eventually.

Note that the "High" security setting breaks our cute icon fonts (via Font Awesome), probably due to "some font rendering features are disabled". The breakage looks bad/sketchy. We should look into this more before recommending people switch the Security Level to "High". There are no issues on "Medium-High".

![screen shot 2015-05-13 at 4 16 35 pm](https://cloud.githubusercontent.com/assets/407302/7623104/70ea393c-f98b-11e4-9684-70051969dc58.png)

**Comment by fowlslegs** [comment]
Medium-High does not block JavaScript on non-HTTPS webpages. It would be best to figure out a different icon solution, so the page loads properly under High. I agree it looks sketchy and could potentially turn a source away.

Also, users should be instructed to reset their identity after switching to the High setting.

**Comment by micahflee** [comment]
It should be easy enough to replace the Font Awesome icons with images, instead of characters in a font. We only use a handful of them anyway.

**Comment by fowlslegs** [comment]
Should be noted this also breaks icons on the SecureDrop website and ReadTheDocs.
