### ISSUE TITLE
Server Setup doc clarifications

### ISSUE THREAD

**Issue by harlo** [freedomofpress/securedrop#1027]
1) specify that username + pwd have to be the same for both app and mon.  
2) admin ssh key should be passwordless (prefered) or diceword-generated. this is because pinentry doesn't let you copy/paste.

see:
https://github.com/freedomofpress/securedrop/blob/0.3.3/docs/install.md#set-up-the-servers

**Comment by conorsch** [comment]
Reformatting for clarity:

### Things to change:

* [x] Specify that username and password must be the same for both servers.
* [x] Passphrase on Admin SSH key should be absent (prefered) or diceword-generated. (This is because pinentry doesn't let you copy/paste.)

Both concerns are addressed in #1061.
