### ISSUE TITLE
Session token in URL

### ISSUE THREAD

**Issue by danyalzafar420** [freedomofpress/securedrop#1041]
Session token in URL
Vulnerability description
This application contains a session token in the query parameters. A session token is sensitive information and should not be stored in the URL. URLs could be logged or leaked via the Referer header.
Affected items
/image_captcha (1c57d3b806c0e6d55591a2203a5164b4) 
/image_captcha (2ea0ed06efabef88e00a6e636222b796) 
/image_captcha (468d2904642a128740dd17b08e1195a4) 
/image_captcha (5fa8c30fb144307e65c7256d0142bdac) 
 
Impact ?
Possible sensitive information disclosure.

How to fix ?
The session should be maintained using cookies (or hidden input fields).

Best Regards:
Danyal Zafar

**Comment by garrettr** [comment]
@danyalzafar420 Hey Danny, I'm not sure what you are talking about. There is no `/image_captcha` route on either the source or document interfaces. The `Affected items` that you've listed do not correspond to anything in SecureDrop (and are not valid URL's to begin with). FWIW, we do maintain our sessions using the default Flask session implementation, which uses signed cookies.

Are your sure this is a vulnerability in SecureDrop you are reporting? If so, can you provide some more detail so I can better understand the issue? Otherwise I am going to close this issue as invalid.

**Comment by garrettr** [comment]
@danyalzafar420 Ping

**Comment by garrettr** [comment]
@dolanjs Does this look like a SecureDrop issue to you? I can't understand the original post.

**Comment by dolanjs** [comment]
@garrettr I don't think this is a legitimate issue. That page does not and never has existed in the code. I would close the issue. If @danyalzafar420 adds more info later we can re-open it.

**Comment by garrettr** [comment]
@danyalzafar420 Closing this issue as invalid for now. In the future, please submit security-sensitive issues to our [bug bounty program](bugcrowd.com/freedomofpress) instead of creating a public issue on Github.

To make this clear, I added a note to our README to explain the proper procedure for reporting security issues in #1042.
