### ISSUE TITLE
Rename keepass password entries

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#1068]
The default width of the `Title` column in the provided keepass password database template can cut off some of the password entries names. A few of our entries start off with the same words. This can confuse a journalist leading them to copy and paste the wrong password into the document interface.
### Similar values
- In the journalist group
  - `Document Interface` compared to `Document Interface Hidden Service`
- In the Admin group
  - `App and Monitor Server` compared to `App and Monitor SSH Key`
  - `OSSEC email account` compared to `OSSEC gpg key`

**Comment by conorsch** [comment]
Adding a readable list of the current KeePass XML template, as well as suggested changes, to facilitate discussion.

### Admin
* `App and Monitor Server` -> `Admin account username`
* `App and Monitor Server SSH key` -> remove, since passphrase here is unnecessary
* `App Server Hidden Service` -> `App Server SSH Onion URL` (necessary to add the auth cookies? they're in plaintext on the Admin Workstation anyway...)
* `Monitor Server Hidden Service` -> `Monitor Server SSH Onion URL` (necessary to add the auth cookies? they're in plaintext on the Admin Workstation anyway...)
* `Network firewall` -> `Network firewall admin credentials`
* `OSSEC email account` -> `Email account for sending OSSEC alerts`
* `OSSEC GPG key` -> remove, since passphrase is unnecessary here
* `Personal GPG key` -> remove, since admins use GPG on their primary workstations
* `SASL credentials` -> remove, since redundant with `OSSEC email account`

### Journalist
* `Document Interface` -> `Document Interface Onion URL`
* `Document Interface Hidden Service` -> `Document Interface Hidden Service Auth Value` (seems clunky.. shouldn't the Admin back this up? Do Journalists need it in their own KeePass databases)?
* `Personal GPG key`

### Secure Viewing Station
* `SecureDrop GPG key`

In general, the docs for setting up the KeePass database really need to be fleshed out. Right now, we're essentially saying "fill it out and save it," with no further guidance.

**Comment by garrettr** [comment]
These are useful improvements, but I think we have more important issues to focus on for 0.4.

**Comment by fowlslegs** [comment]
`Document Interface` -> `Journalist Interface`
