### ISSUE TITLE
OSSEC kernel upgrade spam

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#1090]
The file ` /etc/apt/apt.conf.d/01autoremove-kernels` should be added to the OSSEC's file integrity ignore list. This file is expected to change and should not be alerted on.

```
Received From: mon->syscheck
Rule: 550 fired (level 7) -> "Integrity checksum changed."
Portion of the log(s):

Integrity checksum changed for: '/etc/apt/apt.conf.d/01autoremove-kernels'
Size changed from '1014' to '970'
What changed:
5c5
<    "^linux-image-3\.16\.0-30-generic$";
---
>    "^linux-image-3\.14\.48-grsec$";
7c7
<    "^linux-headers-3\.16\.0-30-generic$";
---
>    "^linux-headers-3\.14\.48-grsec$";
9c9
<    "^linux-image-extra-3\.16\.0-30-generic$";
---
>    "^linux-image-extra-3\.14\.48-grsec$";
11c11
<    "^linux-signed-image-3\.16\.0-30-generic$";
---
```

Adding ` /etc/apt/apt.conf.d/01autoremove-kernels` to the block of ignore file in the ossec.conf for the agent and server should resolve this.

`install_files/securedrop-ossec-server/var/ossec/etc/ossec.conf`
`install_files/securedrop-ossec-agent/var/ossec/etc/ossec.conf`

**Comment by ageis** [comment]
PR: https://github.com/freedomofpress/securedrop/pull/1162

**Comment by garrettr** [comment]
> This file is expected to change and should not be alerted on.

Why is this file expected to change? What changes it? Is there any possibility that ignoring changes to this file could create a security vulnerability?

**Comment by ageis** [comment]
@garrettr This file is modified by the post-install hooks in each kernel package. So every time we issue an updated grsec kernel, it's expected to change.

The file defines a block of kernels and regexes under "APT::NeverAutoRemove". This is specifying that since the kernel was manually installed, it should never be auto-removed, whether a dependency is uninstalled or as part of any other dpkg operation (for example, removing a kernel that's running in-place can be disastrous).

I guess there's a low theoretical vulnerability that we're opening up, so let's say you have malware or a vulnerable package that was installed through apt, and it's a dependency of something else, so when you remove that something else, the malware package should get marked for auto-removal, and get removed whenever cron-apt or our playbooks run or whatever. Perhaps the package could persist itself on the system by adding its name to this file, and OSSEC wouldn't notice.

**Comment by garrettr** [comment]
Thanks for the explanation, @ageis!
