### ISSUE TITLE
Additional admin alert options

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1124]
Even without replacing OSSEC, it would be fantastic to be able to supplement it. Email is (at best) the second-best solution to any problem. I like to be notified of interesting occurrences via a service called [Pushover](https://pushover.net). Perhaps someone else wants to TextSecure themself. I'm sure that other admins have their own favorite ways to be alerted when something happens.

Alternative alerts wouldn't have to compromise OSSEC's secure alert feature — an supplemental alert tool could use the OSSEC subject line only, or use an end-to-end cryptosystem. Ideally, I'd want a way for an admin to specify a shell script to be run for every alert with certain environment variables or call parameters specifying the OSSEC alert details.

**Comment by conorsch** [comment]
Take a look at [Reimann](http://riemann.io/concepts.html), mentioned in #1123. It seems open-ended enough that it can support essentially any API, but realistically we can't ship support for more than one or two services. Since you mention Pushover, it looks like hooking up Logstash to the Pushover API ]can be fairly trivial](https://github.com/jasperla/logstash-output-pushover).

We've got to be cautious about the amount of information disclosed by the alerts themselves. Though the workflow of decrypting the OSSEC email notifications is painful, it does have the benefit of disclosing very little about the nature of the alerts to third-parties.

**Comment by fowlslegs** [comment]
Going off some of the ideas of the quickly demised #1213 from @garrettr, @mark-in, and myself regarding this idea I think we'd all like to see:

1. **Accessibility** (i.e., notifications should be available for a large range of platforms such as iOS, and also that setting up support for notifications on a new device is simple)
* **Confidentiality** using PFS (or at least e2e)
* **Anonymity** using Tor
    * I'd argue this is important (esp. for anonymous instances), but less so than accessibility. Since there is no practical way to get Tor running on iOS, we'll either have to put this on the back burner for now *or* offer two options--perhaps using a solution such as Riemann as @conorsch suggested. On that note, I do think Riemann looks cool and would be trying to write a couple streams. I am fluent in Clojure.
* **Push notifications** should be supported for admins who wish to receive them on their mobile phone
* **Asynchronicity**
    * We could use a synchronous protocol like OTR over XMPP, but we'd have to program the notification process to wait until the admin was online to send "backed up" notifications.
* **Multi-device support** (i.e., it should allow admins to receive all notifications on multiple devices)

With this in mind:

* PGP-email does offer e2e and push notifications, but there is no open-source OpenPGP iOS app. Also, no PFS and using Tor is problematics with many email providers.
* OTR over XMPP is synchronous and does not have multi-device support. Its strengths over Signal include that it's decentralized and one is able to route it over Tor easily (and Tor Hidden XMPP services). OMEMO (an implementation of Axolotl over XMPP) is an option for the future when more than the Android client Conversations has support for it.

My opinion is that the using the Signal API would be the best solution overall as it is very stable and satisfies 1, 2, 4, 5, and 6. We could within reason tone down the volume and time alerts are delivered via configuration options (e.g., don't send alerts of level X and under after 11PM and before 8AM--then at 8AM one would receive any "backed up" alerts, which would be timestamped). @conorsch Do you think that if we used Riemann it would be easy to port such a notification scheme if we ever replace OSSEC? Seems like it.

As a secondary solution for those requiring 3 (anonymity) we could either use OTR over Tor or PGP-email over Tor. Neither of these options support the iPhone, which is an unavoidable compromise at the time. IMO PGP-email over Tor Hidden Services is the best option in this regard because of support for 5 (asynchronicity) and 6 (multi-device support). Of course people who want to use this will have to make sure their email provider is Tor friendly. Ideally, they'd use a provider who offers Tor Hidden IMAP and SMTP servers. Perhaps we could list a few recommended providers who offer this in our documentation. I believe that you can use K9 Mail + Orbot + OpenKeychain on Android (no root access needed) if you wish to have alerts on your mobile phone, but have never tried myself.

**Comment by mark-in** [comment]
@flamsmark, it becomes too sophisticated. There are a lot of options and each of them complies to some threat model. Maybe we should let admin to choose which option is better for them and set no default option?
It can be done by creating a simple universal event emitter (JSON-like) and some "distribution" methods to choose from that are connecting to emitter (modules). These methods should have some explanation of what trade-offs are made.
Some admins would like to get notification via email, another via pigeon post etc.

P.S. Maybe it's too much Gentoo in me. :smile:

**Comment by fowlslegs** [comment]
@mark-in The way Gentoo emphasizes choice is actually the opposite of what we're going for. We don't want to present the opportunity for an inexperienced or less than perfectly careful admin to compromise the security of the SD system. It would damage the SD name if we in any way encouraged admins to work out any significant portion of the notification delivery mechanism and they didn't do a solid job in doing so. We prefer to make one (or two) things that we can assure are secure and reliable with as few as possible configuration options.

We're not stopping anyone from taking our AGPL code and creating a custom delivery mechanism, we're just not officially supporting doing so.

**Comment by eloquence** [comment]
This is now WIP; see https://github.com/freedomofpress/securedrop/issues/3182 - closing this discussion.
