### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1127]
Issue #606 talks about disaster recovery, but doesn't offer a full recovery option. In my SecureDrop setup, I elected to attach an external hard drive to the application server for nightly incremental backups. Other admins may prefer to rotate backup hard disks, or execute periodic backups to a remote networked machine.

None of this is covered by current documentation. Encouraging good and safe backup practices should be part of the setup instructions.

**Comment by conorsch** [comment]
The backup/restore role isn't documented because it needs work. For 0.4, I'm leaning toward splitting the backup role up into two types, one for critical server info like ATHS values, the other a backup of all the submissions on the App Server. See #942 for discussion of around chaging the backup role.

One the backup role is rewritten, documenting the recovery process is mandatory.

**Comment by conorsch** [comment]
#1273 provides an overhaul of the backup strategy, and creates a Topic Guide in the docs dedicated to explaining the steps necessary for backup and restore. Scheduled for the 0.3.7 release.

**Comment by garrettr** [comment]
#1273 significantly improved the backup and restore processes, and included detailed documentation. The process is still overly complex and requires care and attention from administrators who are performing backups, but for the purposes of the current Docs Sprint I think the current state is sufficient.

## Suggested next steps

* Test backup/restore for 0.4, using the current backup roles and documentation.
* Consider creating one or more helper scripts to assist in dealing with some of the current complexity in backups/restores.
  * For example, one pain point is systems that may have a large number of stored submissions. Currently, administrators are advised to check the total size of the stored submissions, and manually verify that they have sufficient disk space on both the App Server (where the backup archive is built, before being transferred to the Admin Workstation) and the Admin Workstation (where the backup archive is stored). This could be scripted fairly easily, assuming the script is run from the Admin Workstation and has SSH access to the servers.
  * Another pain point is the extremely slow transfer time (and potential for interruptions) when transferring a potentially large (multi-GB) backup archive over a Tor Hidden Service connection. This is harder to deal with, since SecureDrop's hardening limits all connectivity to the servers to be over Tor Hidden Services.

If folks are interested in prioritizing one or more of these next steps, we should file separate issues for each of them.

**Comment by redshiftzero** [comment]
Reviewing the changes in #1273 I agree that addresses this issue. I've added a note for the 0.4 hardware testing to run through the backup/restore process as time permits. Do you want to add your point re: creating a helper script to a new issue? Then I think this is good to close :metal:

**Comment by conorsch** [comment]
Helper scripts are OK, but would be more straightforward and consistent with existing Admin workflow to create a dedicated backup playbook. Then we could remove the backup logic from the prod playbook altogether, along with the tricky var declarations along with it. 

Using dedicated playbooks let's us target common Admin tasks, e.g. 

* perform backup and fetch tarball back to Admin Workstation
* collect logs, encrypt to FPF support key, fetch back encrypted tarball to Admin Workstation
* rotate SecureDrop Application GPG Key (including cleaning up references to old pubkeys in the app keyring)

And so on.

**Comment by conorsch** [comment]
Opened #1742 to discuss the dedicated playbooks.

**Comment by redshiftzero** [comment]
Great thanks @conorsch! Given the changes in #1273, @garrettr's comments above, and the followup ticket in #1741 I'm going to go ahead and close this one.
