### ISSUE TITLE
Document disaster recovery and cold storage procedures

### ISSUE THREAD

**Issue by tomlowenthal** [freedomofpress/securedrop#1128]
Issue #606 talks about disaster recovery, but doesn't offer a full recovery option. Issue #1127 discusses routine administrative backups of the app/mon infrastructure. I would like to be able to recover my SecureDrop instance when everything goes wrong — potentially including loosing the admin workstation, SVS, and all other machines.

This would require the ability to recreate those machines from sources outside the normal production environment. I've decided to back up images of all the key SecureDrop machines/thumb-drives to an offsite “cold storage” disk from which I can recreate everything, given backup hardware. 

None of this is covered by current documentation. Encouraging good and safe backup practices should be part of the setup instructions.

**Comment by conorsch** [comment]
See also #1091.

**Comment by eloquence** [comment]
Since this was filed, a lot of docs have been added. https://docs.securedrop.org/en/stable/backup_workstations.html documents how to maintain a series of backups of the Tails USBs, and https://docs.securedrop.org/en/stable/backup_and_restore.html documents server backup/restore. We also routinely include reminders to back up Tails workstations as part of upgrade instructions. 

That said, the information could still be better organized; see https://github.com/freedomofpress/securedrop-docs/issues/43. Closing this issue, in favor of up-to-date and clearly scoped organizational improvements.
