### ISSUE TITLE
General configurability of individual deployments

### ISSUE THREAD

**Issue by tomlowenthal** [freedomofpress/securedrop#1129]
As I was pondering issue #1118, I felt a twinge of something that I was repeatedly in the back of my head during the install and configuration of @pressfreedom's system. It seemed a little long & off-topic for that issue, so I decided to separate it out here.

I feel a little queasy about the use of Ansible and adding more options to `prod-specific.yml`. `tmux` versus `byobu` is a primarily cosmetic/usability/convenience change. It's one that helps admins who run their systems a particular way make SecureDrop easy-to-use, convenient, and consistent with their other environments. It may be worth considering this category of configuration changes and how best to manage it in general. What about an admin who prefers a different default shell, or one with plenty of custom shell config files, or… &c. 

My point is that having general configurability depend on upstream SecureDrop development of specific support for options like this is not an ideal solution. This directly impinges on the automatic-update process and use of Ansible for continuous provisioning. This makes it difficult to (confidently) execute minor tweaks to the system — like `tmux` versus `byobu` — but also makes more important changes less reliable. If I edit my `fstab` or add new `cron` jobs or so on: will those changes persist, or will they be lost like tears in rain to some future update, or (worse) conflict with a future unattended change and result in things breaking?

I think that an ideal approach would carefully delineate what SecureDrop relies on and updates/changes automatically, giving admins plenty of room to color inside the lines. Then — when configuration details are determined in the Ansible roles — provide room for configuration. I would suggest that `prod-specific.yml` should remain a place primarily for SecureDrop-specific core configuration which relates to the fundamental functionality of the system. Additional configuration choices (like — say — which terminal multiplexer to use) should probably live in another file.which might be longer and more convoluted, but which there would be no general obligation to edit.

**Comment by flamsmark** [comment]
This general tenor of approach might also present a way forward for #67.

**Comment by conorsch** [comment]
Since we're currently using Ansible to handle deployment and configuration, the most straightforward approach to providing site-specific configurability is via variable overrides. Right now the prod playbook expects all site-specific vars to be found in `prod-specific.yml`, which is version controlled with default vars, and forces admins to use a stash-pull-pop workflow to upgrade versions of securedrop.

Some work's already been done on variable reorganization in the develop branch, but is still a work in progress. Using `with_first_found` [to include vars files](http://docs.ansible.com/ansible/playbooks_conditionals.html#selecting-files-and-templates-based-on-variables), and placing `prod-specific.yml` _last_ in the list would provide a sane way for admins to maintain their own variables that won't be clobbered when upgrading the SecureDrop playbooks.

**Comment by eloquence** [comment]
Since this issue was filed in 2015, SecureDrop has introduced additional tooling for managing the server configuration, which can now be done using the `securedrop-admin sdconfig` wrapper script. Where appropriate, we are aiming to move more configuration options to the web interface (or admin tooling using an admin API), and store the settings in the database.

Generally, our bias is towards _reducing_ the need for low-level configuration changes, because high configuration drift makes it difficult to provide consistent support and documentation, and because it increases the risk of configuration munging during updates. So, for something like `tmux` vs. `byobu`, we should IMO pick what we think is the best solution and stick with it, not aim to support both.

Since this is a very dated discussion issue, I'm going to close it, but please don't hesitate to open specific issues for configuration options you'd like to see supported (bearing in mind that, per the above, our bias may be to provide sane defaults, rather than high configurability).
