### ISSUE TITLE
Expand `terminology.md` into comprehensive encyclopedia

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1131]
Currently, `terminology.md` contains a stub summary for each item/component in the SecureDrop system. It should be expanded to be a full and comprehensive definition and explanation of each component.

**Comment by conorsch** [comment]
The current docs include the following definitions in the **Terminology** guide:

* [ ] App Server
* [ ] Monitor Server
* [ ] Source Interface
* [ ] Document Interface
* [ ] Journalist Workstation
* [ ] Admin Workstation
* [ ] Secure Viewing Station
* [ ] Two-Factor Authenticator
* [ ] Transfer Device

Then there's a separate page for **Passphrases** that also includes explanations of the various user roles:

* [ ] Admin
* [ ] Journalist
  * [ ] Secure Viewing Station

Are there more terms that should be defined? Should the user role definitions be moved into the **Terminology** guide?

**Comment by thisisparker** [comment]
To respond to @conorsch's question: I think that user role definitions should be moved into **Terminology** and have submitted PR #1741 which does that (among other clarifications). The **Overview** page also links to **Passphrases** for an explanation of roles, which imo should also be moved here. **Passphrases** is a great document but would best be limited to a list of what access each role needs, and not the fuller description that we can offer on the **Terminology** page.

(Note: the current PR does not define *Admin*, in part because I think it's not being used in the same kind of domain-specific way that *Source* and *Journalist* are, but I could be convinced.)

**Comment by thisisparker** [comment]
Also, this may be a failure of imagination (or the document may have changed in the meantime), but I think most of the short descriptions are sufficient and I don't see how they can be usefully expanded.

**Comment by redshiftzero** [comment]
Just approved your PR #1741, which are sufficient to address this ticket. And I agree with your assessment here @thisisparker, it would make more sense if the Roles link pointed to the Terminology document.
