### ISSUE TITLE
Installation checklist

### ISSUE THREAD

**Issue by flamsmark** [freedomofpress/securedrop#1144]
On SecureDrop install day (or days!), there's loads to do, passphrases to remember, and chaos all around. Solution: a worksheet. The prospective admin prints this out and then checks things off, writes down passphrases and fingerprints and so on as they go, and then they can be sure what they've done and what they haven't and put everything away safely when it's over.

**Comment by freddymartinez9** [comment]
I have begun work on a prototype of one of these worksheets, it is about 4 pages long right now. It includes: 
 * All the Tails workstations
 * Transfer USB
 * Firewall configurations 
 * Ubuntu server configurations
 * a section for on-boarded users.  

Furthermore, it has a glaring **this document is for planning purposes only** so that people don't leave these laying around.
