### ISSUE TITLE
Conflicting documentation on difficulty of finding Tails-compatible printers

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1149]
I noticed that the [Tails printing guide](https://github.com/freedomofpress/securedrop/blob/develop/docs/tails_printing_guide.md) states

> Normally, any printer should work with Tails "out of the box",

while the [printer section](https://github.com/freedomofpress/securedrop/blob/develop/docs/hardware.md#printers) of the hardware guide states

> Unfortunately, it is difficult to find printers that work with Tails, and it is increasingly difficult to find non-wireless printers at all.

The latter section was written later, and, at least in my experience attempting to set up various printers with GNU/Linux, it's much closer to the truth. You might want to link to or port some of the info from the hardware doc to the Tails printing doc.

Another thing you may wish to add to either of these pages is that http://www.openprinting.org/printers provides a database of Linux-compatible printers and you may wish to link to it.Tails does not necessarily ship with all the drivers necessary to run the printers in the database, but for older printers it would be a good indicator.

**Comment by garrettr** [comment]
The Tails docs are tragicomically optimistic. In our experience, it is very difficult to get many common models of printers working with Tails.

It would be good to contribute upstream to the Tails docs, but I'd rather just continue testing printers on Tails and documenting specific known-good models in our own documentation. I say this because our requirements for printers to use with the Secure Viewing Station are more specific and stringent (no wireless functionality, etc.) than the Tails docs would require.

**Comment by justintroutman** [comment]
Currently testing an HP Deskjet F4280 (non-wireless) with Tails 3.0.

**Comment by justintroutman** [comment]
Success with printer setup and testing via both GUI and `lp` in terminal. No troubleshooting necessary; working in seconds. Will add model to documentation.

**Comment by redshiftzero** [comment]
Closing, fixed by #1952.
