### ISSUE TITLE
Source interface styling issue on TBB for Linux

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#1163]
I still get this weird spacing issue on the Source Interface (overlapping text and buttons) with the latest Tor Browser on Debian jessie. Months and months ago, I made a fix that was [merged](https://github.com/freedomofpress/securedrop/commit/e9739b225764b0fded4014bfb3a8ce183819f9e2) and later [reverted](https://github.com/freedomofpress/securedrop/commit/5b90782d93913f27171da2b24b515f8f8d47e861) because it messed something else up. The issue doesn't appear on the OSX version of Tor Browser AFAIK.

![css_error](https://cloud.githubusercontent.com/assets/1161532/10814495/9c60f9e8-7de3-11e5-94da-9a096da9e270.png)

**Comment by patrickod** [comment]
I don't see this on Tor Browser on Arch, though they do come close. Unsure what the cause is 
![1446939642](https://cloud.githubusercontent.com/assets/84262/11017943/467322ec-8566-11e5-8188-ba066e341cfb.png)

**Comment by semente** [comment]
This issue also happens in iceweasel 42.0-1~bpo80+1 from http://mozilla.debian.net/. Just saying that because it is not a issue regarding to Tor Browser.

@patrickod it also looks ugly on Arch, The button is too close to the text. Looks like your fonts are rendered differently, that is why the difference between our browsers.

The issue is caused by the pull-bottom CSS class[1] that sets the button position to absolute, so the the margin-bottom[2] move the button up 20px ignoring the other elements.

[1] https://github.com/freedomofpress/securedrop/blob/develop/securedrop/static/css/source.css#L329
[2]https://github.com/freedomofpress/securedrop/blob/develop/securedrop/static/css/source.css#L203
