### ISSUE TITLE
Send OSSEC alerts using SMTP over Tor

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1213]
As we will be using OSSEC in the near, foreseeable future (see #1123), it would be good if we continued our efforts to keep hidden services hidden (as in #1204) by sending OSSEC alert emails using SMTP over Tor.

This suggestion is following from https://github.com/freedomofpress/securedrop/pull/1211#issuecomment-160693100.

I disagree with the idea to use Pond because:

* Pond is very experimental software.
* Use of Pond itself in combination with certain other activity can be indicative of a SecureDrop instance. Issues of unaudited code aside, anonymity systems work best when huge numbers of people use them regularly.
* If admins have to boot into Tails to check Pond, they may as well SSH into the monitor server and check OSSEC manually. Otherwise, they have to have to install Pond on their workstations--not too bad on Linux, PITA on OS X, "impossible" on Windows.
* Requires significant modification to OSSEC alerts system.

OTOH, I agree with the idea to use SMTP over Tor because:

* It hides the nature of the data leaving the monitor server (i.e., that we're sending email).
* It requires little modification of existing system.
* Allows use of hidden service IMAP and SMTP servers for added security--authentication and encryption layers.
* If both the OSSEC alert email and the Admin email are created anonymously over Tor (and always used over Tor), the identity of both the monitor server and the SD instance administrator can be protected.

**Comment by mark-in** [comment]
Is it a bad idea to run IMAP-only HS on Monitor Server and get push notifications from it directly?
For me the problem is that we have some third party in the clearnet.

**Comment by garrettr** [comment]
Just a reminder: we are going to be re-working _all_ of this in the near future, so please do not restrict your thinking to just email as a notification mechanism. See #1124 for some other options that have been requested.

**Comment by garrettr** [comment]
In general, the requirements for Admin Notifications are (as I see them):

*Goal:* Detect if compromise is attempted or in-progress on the SecureDrop application server, notify the admin that action may be needed in a timely manner, and support investigation of potential suspicious activity after the fact.

So, admin notifications should:

1. Be always-on and rapidly accessible. Again, since time may be of the essence in handling an incident, I think we should prioritize availability over confidentiality here. This means the notifications should be available on their day-to-day computer (not the dedicated *Admin Workstation*), and probably also on their phone/smart watch/whatever they prefer to use to get notified of system events as well.
2. Not leak metadata about source activity on the Application Server.
3. Not be accessible to anyone other than the intended admin.

The current design (PGP-encrypted email sent to their work email) is a compromise that achieves all of these goals, but not as well as we would like. Since email is a common notification technique, it is always-on and fairly timely (although the PGP encryption means a notification on their phone won't be immediately useful, for example, and generally the usability is a barrier).

Any other design needs to explain how it meets (and ideally, improves upon the current solution) these design goals.

**Comment by mark-in** [comment]
@garrettr, sure. The general idea is to fetch these notifications from MS directly (Tor HS). It can be XMPP, email, HTTP, whatever. By the way it should be something widespread to hide the evidence of SecureDrop communication.

**Comment by garrettr** [comment]
>  I agree with the idea to use SMTP over Tor

@fowlslegs Have you ever tried to use SMTP over Tor? IIRC, it is extremely problematic (bordering on impossible) - many email servers refuse to relay traffic exiting from Tor because it is so commonly used for spam and abuse.

**Comment by mark-in** [comment]
> Be always-on and rapidly accessible. Again, since time may be of the essence in handling an incident, I think we should prioritize availability over confidentiality here. 

Agree. Then Pond is not an option (not rapidly accessible).
> This means the notifications should be available on their day-to-day computer (not the dedicated Admin Workstation), and probably also on their phone/smart watch/whatever they prefer to use to get notified of system events as well.

Maybe just serve alerts by authenticated (maybe OTP) HTTP over HS hosted on the MS? In this case it's simple to rapidly access it via TBB from anywhere. Even API for smart watch can be on the same HTTP.

**Comment by garrettr** [comment]
@mark-in The difficulty is that receiving push notifications (especially on a variety of platforms and/or via a variety of techniques) over Tor is non-trivial. Since we want this to be immediately available to admins, it should be available on a wide range of platforms (e.g. Windows, Mac, Linux, Android, iOS, etc.). Setting up Tor on all of these platforms, proxying a variety of applications through it, typically ranges from medium-hard to impossible, at least in the short term (e.g. iOS).

Also, this is something that we want to be highly available. If an admin gets a new laptop and setting up the notifications from SecureDrop is non-trivial, there is a strong chance they will never do it (massive security design failure). We really need to keep availability at the forefront of this design process.

**Comment by fowlslegs** [comment]
@garrettr I use SMTP over Tor for my college, Riseup, and FPF email accounts with no problems. I had a Gmail address years back before I had heard of Tor, so I can't say if it works with major providers like Google.

**Comment by conorsch** [comment]
@fowlslegs Support for Gmail's relays is extremely important, since small orgs without their own mail servers often use Gmail. We'll need to text extensively to make sure we're not breaking anything by routing over Tor. 

When creating new accounts, Google triggers step-up verification if you try to create over Tor. My hunch is they won't take kindly to accepting mail from Tor, at least not without routinely triggering step-up verification—which will break the sending of notifications until the admin reauths in a web browser if true.

**Comment by fowlslegs** [comment]
@conorsch True. I didn't think about this point because my email providers are all quite Tor friendly. Riseup even runs a hidden IMAP and SMTP servers.

I think what you bring up alone should be enough to close this issue. If we're going to make a change that requires a lot of our instances to do reconfiguration--which here may include the creation of a new email address with a Tor-friendly provider--, we may as well switch to a better solution than PGP email. For this reason I believe we're better off brainstorming on #1123 and #1124.
