### ISSUE TITLE
0.3.6 still showing 0.3.5 in footer

### ISSUE THREAD

**Issue by neo-luddite** [freedomofpress/securedrop#1218]
I did a fresh install of securedrop a few days ago and the admin and source 
interfaces still show "securedrop 0.3.5" instead of 0.3.6. the freedom of   
press gpg key shown with apt-key list on my app machine expires in october  
2016. so I guess I'm actually on 0.3.6. plz correct the footers to avoid
confusion. tnx!

**Comment by conorsch** [comment]
@neo-luddite What you describe is actually expected behavior at present, although it's certainly confusing. The 0.3.6 release did not include any changes to the Application Code, but rather only exists to mark the need to update the GPG signing key. You've apparently already done so, so your instance is able to receive automatic security updates. 

In the near future, we will release empty Debian packages via the automatic upgrade channel, which will take care of bumping the version up to 0.3.6 on your Source Interface.

**Comment by neo-luddite** [comment]
tnx
