### ISSUE TITLE
more explicit note in ubuntu install guide in FDE section about automatic reboots every (!) night

### ISSUE THREAD

**Issue by neo-luddite** [freedomofpress/securedrop#1222]
A more explicit note (maybe red & <blink>) about the automatic reboots in the ubuntu install guide would be really helpfull in the "Partition the disks"-section. It took me a while to figure out why my system was going down every (!) night, also if there were no updates. 

Maybe like this:

"The server and the monitoring machines do an automatic reboot every night. Using FDE therefore requires manual intervention every day (at 4 am)! Therefore we strongly discourage the usage of FDE."

you get the point ;) tnx!

**Comment by conorsch** [comment]
Documenting the automatic reboots is a good idea. I see two spots in the docs where it would be topical:

* Ubuntu Install Guide, likely in a *Note*
* In the OSSEC Guide, since the daily OSSEC alerts will show a healthy message about the servers coming back up.

For context on the nightly reboots, see #805.

**Comment by garrettr** [comment]
Closed by #1223.

**Comment by garrettr** [comment]
Side note: `<blink>` is deprecated and should not be used by anyone, anywhere (although that was really the case even before it was deprecated).

**Comment by neo-luddite** [comment]
I liked it ;) 
you took me serious with <blink> - that was just to emphasize *g*

thanks for the updated guide!
