### ISSUE TITLE
Whitelist Tor exit nodes for docs.securedrop.org/securedrop.org

### ISSUE THREAD

**Issue by mark-in** [freedomofpress/securedrop#1227]
Unfortunately `securedrop.org` uses CloudFlare.
CloudFlare is known for asking Tor users to solve captcha. This is most annoying when reading docs on Tails/TBB.
There is a solution that I know to work - [cloudflare-tor-whitelister](https://github.com/DonnchaC/cloudflare-tor-whitelister).

P.S. There would be nice to redirect Tor users to .onion somehow.

**Comment by garrettr** [comment]
@mark-in We have tried whitelisting Tor exit IP's using cloudflare-tor-whitelister on both securedrop.org and freedom.press in the past. Unfortunately, we accept credit cards for donations on both sites, and whitelisting Tor exits increases the number of credit card fraud that we experience (people who have stolen card #'s test them by making donations to us). Unfortunately, we end up being on the hook for the chargebacks, so this wastes our financial resources.

We have some ideas for allowing Tor while minimizing the credit card fraud, but they have not been implemented yet.

We maintain Tor Hidden Services for both securedrop.org and freedom.press, in part to provide a CAPTCHA-free option for Tor users. Auto-redirecting to the THS is an interesting idea, but I'm pretty sure it wouldn't work without major modifications because Cloudflare gets the request (and shows the CAPTCHA) before we get it (and have a chance to redirect it).

**Comment by mark-in** [comment]
> We have tried whitelisting Tor exit IP's using cloudflare-tor-whitelister on both securedrop.org and freedom.press in the past. Unfortunately, we accept credit cards for donations on both sites, and whitelisting Tor exits increases the number of credit card fraud that we experience (people who have stolen card #'s test them by making donations to us). Unfortunately, we end up being on the hook for the chargebacks, so this wastes our financial resources.

Hmm, strange way to steal money.
One is still able to do exactly the same at http://secrdrop5wyphb5x.onion/donate and http://freepress3xxs3hk.onion/donate.

> We have some ideas for allowing Tor while minimizing the credit card fraud, but they have not been implemented yet.

Maybe just separate donations from the main site (e.g. `donate.freedom.press`) and make it accessible only over the clearnet/CloudFlare?

> We maintain Tor Hidden Services for both securedrop.org and freedom.press, in part to provide a CAPTCHA-free option for Tor users.

The Docs are not working for THS. `http://docs.secrdrop5wyphb5x.onion/` redirects to `https://analytics.freedom.press/` with `302 Found`. Using `docs.securedrop.org` with CAPTCHA each page is really, really annoying (and it's unsolvable most of the time).

> Auto-redirecting to the THS is an interesting idea, but I'm pretty sure it wouldn't work without major modifications because Cloudflare gets the request (and shows the CAPTCHA) before we get it (and have a chance to redirect it).

There are some ideas about it but of course it's all unimplemented.
For now it would be perfect to make links to the THSes at the top of each page for Tor users. And to make them clickable.

**Comment by garrettr** [comment]
> Hmm, strange way to steal money.

Well, try running a website with a form that accepts credit cards and maybe you won't think it's so strange. This is a widespread and well-known problem on the web, and is one of the reasons so many websites block Tor exits.

> One is still able to do exactly the same at http://secrdrop5wyphb5x.onion/donate and http://freepress3xxs3hk.onion/donate.

All I can say is that when we whitelisted Tor exits, we saw a spike in the amount of fraud cases that we ended up having to pay for, and it went away when we blocked them again.

> Maybe just separate donations from the main site (e.g. donate.freedom.press) and make it accessible only over the clearnet/CloudFlare?

That's a good idea.

Our other idea is to stop returning the correct signal for small donations (since most of these fraud testers make donations in the range of $10-$20). We'll say just "payment accepted" no matter whether it was or not. Shouldn't inconvenience real donators too much, but will make the site useless for fraudsters.

> The Docs are not working for THS.

Those are legit problems you raised, thanks for pointing them out. I'm filing a separate issue to track fixing that.

> There are some ideas about it but of course it's all unimplemented.

You're not going to be able to work around that problem, you just need to get rid of CloudFlare if you want to auto-redirect people to THS.

Note that auto-redirecting people to THS could be considered a reduction in the security provided to them. THS are more vulnerable to [recent website fingerprinting attacks](https://people.csail.mit.edu/devadas/pubs/circuit_finger.pdf) than normal web sites, and in the current design are a downgrade to RSA-1024 (vs. the RSA-4096 we use for our TLS certificate) and other weak crypto. If we did that for our TLS configuration people would freak out, but of course Tor zealots don't seem to think it matters for reasons I can't quite fathom.

> For now it would be perfect to make links to the THSes at the top of each page for Tor users. And to make them clickable.

I assume you are now referring to the THS links to SecureDrop links in the directory. They are intentionally not made clickable because if you accessed the directory in a non-Tor browser and clicked the link, it would leak your intention to visit a specific .onion in a DNS request.

Before you say it - yes, we could make the links clickable in Tor Browser and not clickable in every other browser. I really think we have more important things to do but that certainly is possible, in fact it's a nice idea.

**Comment by garrettr** [comment]
We've improved the logging on our donations platform, which allows us to track potentially increased fraud caused by whitelisting Tor exit nodes, as well as the effectiveness of our planned potential mitigations for it.

As a result, we have re-enabled the whitelisting of Tor exit nodes on securedrop.org and freedom.press via cloudflare-tor-whitelister. Note that due to a limitation of Cloudflare's API, the whitelisting tool can only whitelist ~200 IP's. This means that _some_ Tor exit nodes maybe still get captcha'ed, because they cannot be included in the limited whitelist. Fortunately, you can fit ~95% of Tor's exit capacity into the ~200 IP's that can be whitelisted, so the probability of a user getting captcha'ed goes way, way down.

We will continue to whitelist Tor exits unless severely increased fraud or other issues caused by Tor users force us to reverse the decision again.
