### ISSUE TITLE
ERROR: apache2_module is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by Debakel** [freedomofpress/securedrop#1232]
I'm trying to install SecureDrop and followed the guideline until "Run the Ansible playbook". When i'm trying to run 

    ansible-playbook -i inventory -u <username> -K --sudo securedrop-prod.yml

this error shows up:

    ERROR: apache2_module is not a legal parameter in an Ansible task or handler

On the admin workstation runs elementary OS 0.3.1 Freya.

**Comment by conorsch** [comment]
You're running an outdated version of Ansible. The `apache2_module` task type [was added in v1.6](http://docs.ansible.com/ansible/apache2_module_module.html), which was [released a year and a half ago](https://github.com/ansible/ansible/blob/devel/CHANGELOG.md#16-and-the-cradle-will-rock---may-5-2014). The version included in Tails will work rather well with SecureDrop out of the box, and there are ways to install an even more recent version—see #1146.

We don't support Elementary OS for any component of SecureDrop. The compartmentalization provided by Tails is a significant security advantage, so that the machine with admin-level access does not have always-on network presence, greatly reducing its attack surface. All instance-specific information is encrypted at rest when the Tails USB is not running. See the docs starting here: https://docs.securedrop.org/en/latest/before_you_begin.html

**Comment by Debakel** [comment]
To use Ubuntu, install the latest version of Ansible (available in their PPA):

    $ sudo apt-get install software-properties-common
    $ sudo apt-add-repository ppa:ansible/ansible
    $ sudo apt-get update
    $ sudo apt-get install ansible

For security reasons, it's not recommended to do this in an productive setup (see comment above).
