### ISSUE TITLE
Apparmor denials for fontawesome-webfont.eot trigger OSSEC alerts

### ISSUE THREAD

**Issue by dbgdngit** [freedomofpress/securedrop#1240]
Dont think these are of great concern and have only occurred once but wanted to flag

Securedrop v0.3.6

OSSEC HIDS Notification.
2016 Jan 20 22:32:50

Received From: (app) xxxxxxxxxxxxx->/var/log/syslog
Rule: 100012 fired (level 7) -> "Apparmor denied event"
Portion of the log(s):

Jan 20 22:32:49 app kernel: [63168.028025] audit: type=1400 audit(1453347169.599:39): apparmor="DENIED" operation="open" profile="/usr/sbin/apache2" name="/var/www/securedrop/static/fonts/fontawesome-webfont.eot" pid=1230 comm="apache2" requested_mask="r" denied_mask="r" fsuid=33 ouid=33

--END OF NOTIFICATION

OSSEC HIDS Notification.
2016 Jan 20 22:32:50

Received From: (app) xxxxxxxxxxxxxx->/var/log/apache2/source-error.log
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

[Wed Jan 20 22:32:49.602465 2016] [core:error] [pid 1221:tid 3585599670016] (13)Permission denied: [client 127.0.0.1:47729] AH00132: file permissions deny server access: /var/www/securedrop/static/fonts/fontawesome-webfont.eot, referer: http://xxxxxxxxxxxxxx.onion

**Comment by fowlslegs** [comment]
Thanks for the report @dbgdngit. Our Apparmor profiles by default deny all access to all resources and define a whitelist of operations (read, write, and execute) that may be performed on particular files. Since we provide and use `/var/www/securedrop/static/fonts/fontawesome-webfont.eot`, a perfectly safe embeddable open-type font, Apache should in fact have read access to this file.

**Comment by fowlslegs** [comment]
I just made a quick fix slated for next release. Thanks for helping us catch/fix this issue.

**Comment by fowlslegs** [comment]
Fixed by #1373.
