### ISSUE TITLE
Next kernel update could fail due to lack of GRUB PaX flags

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#1245]
GRUB has been updated since the last time we shipped a kernel: https://www.debian.org/security/2015/dsa-3421 — So `/usr/sbin/grub-probe` etc. have probably lost their PaX flags, since we are not including a way to apply these persistently (yet). 

There is a strong chance that our next kernel update could fail, since the post-install hooks in the kernel package need to run this command.

**Comment by ageis** [comment]
For the next kernel update, it might have been sufficient to ship some paxctl commands in the preinst hooks of the `securedrop-grsec` metapackage, however, unfortunately the linux kernel installs before the metapackage since apt works in alphabetical order.

**Comment by garrettr** [comment]
> For the next kernel update, it might have been sufficient to ship some paxctl commands in the preinst hooks of the securedrop-grsec metapackage, however, unfortunately the Linux kernel installs before the metapackage since apt works in alphabetical order.

I don't think this is actually a problem. First of all, you could always ship the paxctl commands in the preinst instead of the postinst. Even then, it shouldn't matter because the lack of correct pax flags on grub will only be an issue upon reboot, which only happens after every package (including the metapackage) has finished upgrading.

We should be ok if we re-run paxctl in the metapackage post-inst; of course, the upgrade path must be tested to be sure.

**Comment by garrettr** [comment]
> There is a strong chance that our next kernel update could fail, since the post-install hooks in the kernel package need to run this command.

Ah, nvm, I misunderstood the original issue. This is still a problem. I'm reading through https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html to understand whether or not this is an issue.

**Comment by garrettr** [comment]
Have confirmed that upgrading grub wipes out the PaX flags. To test, I:

1. Checked out 0.3.8
2. Commented out the `perform safe upgrade to ensure all the packages are updated` task in `common/tasks/cron_apt.yml`. This means all of the packages will remain at the versions included in the base image. Since we are now using a bento box, these are identical to those installed by a stock Ubuntu 14.04.4 .iso.
3. Ran the playbooks.
4. Log in, check the PaX flags on the binaries in question, run an upgrade, then re-check the PaX flags to see if they were wiped out by the upgrade:

```
vagrant@app-staging:~$ paxctl -vQ $(which grub-probe)
PaX control v0.7
Copyright 2004,2005,2006,2007,2009,2010,2011,2012 PaX Team <pageexec@freemail.hu>

- PaX flags: -p---m-x-e-- [/usr/sbin/grub-probe]
vagrant@app-staging:~$ sudo aptitude safe-upgrade
The following packages will be upgraded:
  apt apt-transport-https apt-utils dosfstools dpkg grub-common grub-pc grub-pc-bin grub2-common libapt-inst1.5 libapt-pkg4.12 libc-bin libc-dev-bin
  libc6 libc6-dev libexpat1 libxml2 linux-libc-dev multiarch-support wget
The following packages are RECOMMENDED but will NOT be installed:
  manpages-dev
20 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 16.7 MB of archives. After unpacking 6,144 B will be used.
Do you want to continue? [Y/n/?] Y
<snip aptitude output>
vagrant@app-staging:~$ paxctl -vQ $(which grub-probe)
PaX control v0.7
Copyright 2004,2005,2006,2007,2009,2010,2011,2012 PaX Team <pageexec@freemail.hu>

file /usr/sbin/grub-probe does not have a PT_PAX_FLAGS program header, try conversion
```

**Comment by garrettr** [comment]
After some discussion, this is how to reproduce the issue:

1. Be running a grsec kernel
2. Upgrade grub, wiping out its PaX flags
3. Upgrade to a new grsec kernel

Since the new kernel package's maintainer scripts call the affected binaries while running on a grsec kernel, an error will be triggered unless those binaries have the correct PaX flags set when the upgrade is run.

**Comment by conorsch** [comment]
This was resolved by https://github.com/freedomofpress/ansible-role-grsecurity/issues/90, which now sets PaX flags on the GRUB binaries upon installation of a new FPF-maintained grsecurity-patched kernel. We've used this method to push kernel updates to prod systems without issue.
