### ISSUE TITLE
Unable to install SecureDrop because of errors with https://apt.freedom.press

### ISSUE THREAD

**Issue by ehartsuyker** [freedomofpress/securedrop#1247]
Full `ansible` output. I'll be email this to y'all too since this might be a security problem.

```
amnesia@amnesia:~/Persistent/securedrop/install_files/ansible-base$ ansible-playbook -i inventory -u berlinleaks -K --sudo securedrop-prod.yml
sudo password:

PLAY [mon;app;mon-prod;app-prod] **********************************************

GATHERING FACTS ***************************************************************
ok: [mon]
ok: [app]

TASK: [install_fpf_repo | install fpf apt signing gpg key] ********************
changed: [mon]
changed: [app]

TASK: [install_fpf_repo | setup fpf apt repo] *********************************
failed: [mon] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 2207, in <module>
  File "<stdin>", line 430, in main
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch https://apt.freedom.press/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
, E:Some index files failed to download. They have been ignored, or old ones used instead.

failed: [app] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 2207, in <module>
  File "<stdin>", line 430, in main
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch https://apt.freedom.press/dists/trusty/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
, E:Some index files failed to download. They have been ignored, or old ones used instead.


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/amnesia/securedrop-prod.retry

app                        : ok=2    changed=1    unreachable=0    failed=1
mon                        : ok=2    changed=1    unreachable=0    failed=1
```

This was verified on the server with `curl`.

**Comment by garrettr** [comment]
Looking into this now, thanks for the report.

**Comment by ehartsuyker** [comment]
Damn. Quick response. (thumbs up emoji)

**Comment by ehartsuyker** [comment]
More info (if it helps):

  - `curl` also fails on Tails 2.0.1 with a connection refused
  - `curl` succeeds on OSX 10.11.3

**Comment by garrettr** [comment]
@ehartsuyker Thanks for the additional info. I cannot reproduce this problem with a local development environment (`vagrant up /prod$/`). The `install_fpf_repo` task completed successfully. I can also access https://apt.freedom.press/dists/trusty/main/binary-amd64/Packages in both a normal browser and in Tor Browser.

I have verified that we do not use Cloudflare's Web Application Firewall for `apt.freedom.press`, so it's not due to Cloudflare captcha'ing Tor IP's (an initial theory, since you said it fails on Tails but not on OS X).

Continuing to investigate.

**Comment by ehartsuyker** [comment]
This is what I've found so far: http://delta.affinix.com/2007/09/17/startcom-and-debian-ubuntu/

Might just be an Ubuntu issue, but that doesn't explain why Tails can't connect at all.

**Comment by garrettr** [comment]
@ehartsuyker I am able to reproduce the issue with curl on Tails. Continuing to investigate.

**Comment by garrettr** [comment]
Interesting that I can access https://apt.freedom.press in Tor Browser on Tails, but not via curl. This suggests it might be a certificate issue, because I _think_ Tor Browser uses the Mozilla root store as opposed to the roots provided by Debian in ca-certificates.

**Comment by ehartsuyker** [comment]
Yeah, I thought I was something like that, and I tried adding the startssl
cert manually a few places, but that didn't help.

I'm AFK for now (it's late in Berlin), but I'll try to answer anything I
can before I go to work tomorrow.

**Comment by garrettr** [comment]
The curl issue is a red herring. It'll work if you `torify curl`. I don't fully understand why that is required, but it has something to do with how Tails uses iptables to block non-Tor traffic.

**Comment by conorsch** [comment]
The crux of the problem is:

> server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

The `apt_key` module gets executed on the target host (the Ubuntu servers), _not_ on the Ansible controller (Tails Admin Workstation), so we can safely set aside on Tails-specific Tor/curl madness for now.

Looks like something changed in the certs repo packages for Ubuntu. @ehartsuyker, please provide:

* version of Ubuntu (expecting 14.04.x LTS)
* version of Ansible (probably 1.7.2, stock in the Jessie repos)

We'll keep looking and see if we can identify a recent breaking change for how Ubuntu is managing certs.

**Comment by conorsch** [comment]
@ehartsuyker Check the time on the servers; too much drift could cause a cert verification failure. Since the failure is happening during initial setup, `ntp` hasn't even been installed yet.

**Comment by garrettr** [comment]
Although Ubuntu should run `ntpdate` on boot, so it *should* have nearly the correct time. If the time is off, then there are a few possible causes. One of the most likely is that your network firewall is misconfigured and is blocking NTP traffic - you can check for this by logging in to the pfSense WebGUI and looking at the logs.

**Comment by garrettr** [comment]
A final bit of debugging output that could be helpful would be to double check that you're getting the correct cert and chain for https://apt.freedom.press. To verify this, log in to one of the servers and run 

```
openssl s_client -connect apt.freedom.press:443
```

Paste the output in a comment on this issue so we can take a look.

**Comment by ehartsuyker** [comment]
@conorsch Yep, `ntp` wasn't installed. After installation, curling `https://apt.freedom.press/dists/trusty/main/binary-amd64/Packages` works on both servers. I'll re-run `ansible` tonight and see if everything is happy, but I'm going to tentatively say this is resolved.

**Comment by garrettr** [comment]
@ehartsuyker Makes sense. Ubuntu doesn't install `ntp` by default. It _does_ have `ntpdate`, which updates the time from NTP, but only on boot, and not consistently over time. The SecureDrop Ansible playbooks install ntp, so normally you don't have to do it before you install SecureDrop since the installation handles it for you; however, in this case, it seems that your system's clock was so messed up that it was required. A reboot, or manually running `ntpdate`, would also probably have been enough to bring your clock close enough to reality to successfully run the playbooks.

Agree that this appears to be resolved. Thanks for reporting the bug and providing helpful details for us as we investigated!

**Comment by ehartsuyker** [comment]
@garrettr The playbooks install `ntp`, but they do so after install the `install_fpf_repo | setup fpf apt repo` task. Perhaps this task (and others that may require time based crypto) have a dependency on the `ntp` package. So yes, this is resolved, but a minor fix to `ansible` could prevent other people with system clocks as out of sync as mine from seeing this error.

**Comment by ehartsuyker** [comment]
And thanks for looking into this :D

**Comment by conorsch** [comment]
@ehartsuyker Thanks, it does sound reasonable to install `ntp` before attempting `https` calls via apt. Your reports were highly detailed, for which we thank you heartily! Let us know if you have any other trouble.
