### ISSUE TITLE
Docs as described may lead to DNS lookup failures

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1249]
A fresh Ubuntu install is defaulting to have the network gateway as the only DNS server in `resolv.conf`. Adding the Google DNS servers `8.8.8.8` and `8.8.4.4` as `nameserver`s to `/etc/resolvconf/resolv.conf.d/tail` should be added to the docs. Currently the firewall rules listed in the docs only allow DNS lookups to the external DNS servers.

**Comment by ehartsuyker** [comment]
Ah, it seems the docs do say this in the "Ubuntu Installation Guide." However, since this doesn't seem like a place some one would necessarily look when reading the "Set up the Servers" part of the guide (since I'm guessing most people who are doing this could install Ubuntu in their sleep), I'm going to merge those two since several things like FDE and the lack of correct DNS entries will **definitely** break the SD setup. Expect a PR later.

**Comment by conorsch** [comment]
As mentioned in #1254, the Ansible playbooks do handle the DNS configuration on the hosts—see `roles/common/tasks/harden_dns.yml`. Provided the hardware firewall is configured correctly, the DNS config should be settled early enough in the Ansible run to ensure resolution during lookups for new packages and whatnot.

**Comment by conorsch** [comment]
The playbooks should be updated to ensure that the ntp package installation occurs before adding the FPF repo. If the FPF repo was added, the `apt_repository` module will automatically trigger an `apt-get update`, which could fail if the system time is wrong.

**Comment by conorsch** [comment]
The changes in #2714 added assert statements to validate that DNS is working, removing the need for Admins to run the verification commands manually as a debugging step. As written, those new checks would resolve this issue entirely. 

However, in #2741, we prioritized a fail-fast-on-grsec strategy, which prevents the checks from usefully validating DNS early in the install process, since the `common` role now runs _after_ the FPF repo install logic again. So further action still required here. We could:

1. Break out the sanity checks into a tiny role and place that at the top of the first play, to balance "fail fast with no DNS" against "fail fast on incompatible kernels.
2. Reorder the roles to run "common" first. Common's a big role, so doing so would essentially revert the changes presented in #2741. 

Slight preference for 1.

**Comment by eloquence** [comment]
Sounds good! If I don't hear otherwise by tomorrow, will break #1 into a new task we can take on in the next sprint.

**Comment by eloquence** [comment]
Per above, closing this issue and focusing on the tightly scoped #3203.
