### ISSUE TITLE
Backup role - support for large zip files

### ISSUE THREAD

**Issue by dbgdngit** [freedomofpress/securedrop#1263]
SecureDrop v0.3.6

I'm starting to use the backup role of securedrop-prod.yml for regular backup of key files.
It currently fails as the zip file is nearly 3GB in size
I can get it working by adding the allow64ZIP=True flag in the script 0.3_collect.py script
My understanding is that is the default in python 3.4 and above?

**Comment by conorsch** [comment]
We're testing a rewrite of the backup strategy in #1273. Thanks for reporting this!

**Comment by garrettr** [comment]
This will be fixed in #1273 because it switches to using tar instead of zip for the backup archive. The [default format](https://docs.python.org/2/library/tarfile.html#tarfile.DEFAULT_FORMAT) used by `tarfile` in Python 2.7 is `GNU_FORMAT`, for which the maximum archive size is [effectively unlimited](http://answers.google.com/answers/threadview?id=25116).

Note, however, that the backup archive is transferred over Tor, and that will be a significant bottleneck if your backup archive is more than a couple of GB in size. Another bottleneck to keep in mind is the amount of free space in the persistent volume on the Admin Workstation, which is where the backup archive is stored.

**Comment by fowlslegs** [comment]
>the backup archive is transferred over Tor, and that will be a significant bottleneck if your backup archive is more than a couple of GB in size

Another place pylzma would be useful. Just noting this to x-ref https://github.com/freedomofpress/securedrop/issues/1282

**Comment by conorsch** [comment]
Resolved by #1273, pending release of 0.3.7. Tracking backporting these changes into develop in #1313.
