### ISSUE TITLE
Documentation: Reorganize network firewall

### ISSUE THREAD

**Issue by freddymartinez9** [freedomofpress/securedrop#1269]
Since the [pfSense-2440](https://store.pfsense.org/SG-2440/) is the recommended firewall and that is a 4NIC, it would make more sense to move the 4NIC configuration *before* the 3NIC. This will make it the documentation more useable, as it prevent groups from making the simple mistake of starting the 3NIC setup then realizing they actually need the 4NIC rules.

**Comment by freddymartinez9** [comment]
I have a PR for this.

**Comment by conorsch** [comment]
@freddymartinez9 This makes sense, thanks. In case it's not clear, we originally added the 4-port config below the 3-port config to maintain backwards-compatibility for existing installs. Enough time has passed now that it's reasonable to swap, and in fact the docs are most likely to the newest admins anyway. Would be happy to review a PR.

**Comment by freddymartinez9** [comment]
I created PR #1270 for the fix. I will apologize for the 4 erroneous commits, I had to back out a change and am still learning how to develop using branches.

**Comment by fowlslegs** [comment]
While we're talking about this, the network firewall section could still use a number more fixes. Here's from my notes on the install process. Will try to make some commits to address these in the next week, but any help doing so or feedback is appreciated.

- network_firewall
  - We use a lot of acronyms here. I guess it’s really out-of-scope to explain them all, but at the same time it may be confusing. Thoughts?
  -  Specify subnet mask for the gateway.
  -  We say to generate a password with KeePassX, but we don’t give any instructions on doing so. A “topic guide” walkthrough with photos for KeePassX might be nice.
  - Click disconnect and then reconnect from the NetworkManager GNOME menu instead of unplugging and plugging in ethernet for whatever reason the latter did not assign me to a new network address.
  - We should specify clicking “continue on to the pfSense webConfigurator” will time out in that same paragraph. The follow sentence can be something like “If all goes well this request should time out” and then the following paragraph can explain why.
  -  “Do the same dance as before” except w/ the new username and password you generated (i.e., not with admin/ pfSense)
  -  Click save *and then* click apply changes in the “assign a static IP” section
  - Modifying the XML file worked for me, however, I remember it being a bit messy due to Tails weird separation of space. The redacted lines have all been created by the point you mention the XML file in the document. This process would be a really nice thing to script.
  - You should put the NIC labels on same line w/ IPs for better reference (near the top) where the IPs/ gateways already are.

**Comment by freddymartinez9** [comment]
I'm wondering if some of these (the KeyPassX in particular) should be their own issue, it might be cleaner. Thanks for the feedback @fowlslegs I'll continue working on it.

**Comment by freddymartinez9** [comment]
I updated the PR to address some of these. Let's discuss the rest because I have a few questions for you too @fowlslegs 
~~“Do the same dance as before” except w/ the new username and password you generated (i.e., not with admin/ pfSense)~~
~~Click save and then click apply changes in the “assign a static IP” section~~
~~You should put the NIC labels on same line w/ IPs for better reference (near the top) where the IPs/ gateways already are.~~

**Comment by freddymartinez9** [comment]
@conorsch @fowlslegs is there anything further you'd like this PR to address? I saw @ageis made some notes to the PR but I resolved those.

**Comment by conorsch** [comment]
@freddymartinez9 Thanks for the nudge, I'll rebuild the docs based on #1270 and review.

**Comment by conorsch** [comment]
Resolved via #1270.

**Comment by garrettr** [comment]
@fowlslegs You should open a new issue for these: https://github.com/freedomofpress/securedrop/issues/1269#issuecomment-202998068.
