### ISSUE TITLE
Audit for shell injection vectors in python-gnupg

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#128]
We need to audit the web application (especially the source interface) for shell injection attacks. This is especially concerning given our current use of the python-gnupg library, which is known to have shell injection vulnerabilities.

**Comment by heartsucker** [comment]
Marking as pending close because this ticket will always apply to all versions of the app. Since it can never be "done," the ticket can never be closed. Also, it's not specific enough to give a definition of done if we tried to just do it right now.

**Comment by redshiftzero** [comment]
Researched the history of this: there were [shell injection issues](http://seclists.org/oss-sec/2014/q1/262) in [`python-gnupg`](https://code.google.com/archive/p/python-gnupg/), but since we're using pip's [gnupg](https://pypi.python.org/pypi/gnupg/2.3.1) which is a [rewrite](https://github.com/isislovecruft/python-gnupg) with these shell injection issues fixed, I'm closing this.
