### ISSUE TITLE
SecureDrop release notifications

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#1300]
There is currently no straightforward way for SecureDrop users to be informed when we release an update of SecureDrop.

In the past, we have blogged about releases that get audited on the Freedom of the Press Foundation blog, but those posts are focused on the results of the audit, and we do not write them for point/maintenance releases.

Our current policy is to privately inform all of the SecureDrop administrators that we are in contact with when a new release comes out. It tells them what to expect and provides instructions if any manual steps are required on the part of the administrator. There are two problems with this approach:

1. It does not help the administrators of instances that we are unaware of.
 * This is a shame because an important goal of making SecureDrop open source, and working as hard as we have been on the installation process and documentation recently, is to encourage people to install and maintain their own systems without our involvement.
2. It creates a repetitive support burden for Freedom of the Press Foundation (writing and sending emails to dozens of administrators, dealing with associated PGP issues, replying to their queries, etc.)

As a result, I propose that we create a dedicated channel for publishing notifications of SecureDrop releases, along with any additional helpful information (e.g. manual upgrade instructions, if they are necessary).

Proposed requirements:

* It should probably be a blog.
* It should be hosted on https://securedrop.org.
* It should have an RSS/Atom feed to people can easily integrate into their notification tool of choice.
* It should be easy for us to update and edit.

**Comment by ageis** [comment]
I've been working on a blogging setup at https://securedrop.org/news, with RSS/Atom available at https://securedrop.org/news/feed. Still in progress: some styling/design aspects, adding the RSS link to the main page.

**Comment by ageis** [comment]
The news portal and RSS feed is live and ready to go. I still need to run others through the publication process.

The "Read more link was originally a button. @garrettr suggested a different style of link that doesn't take up vertical space, so that instead the link is at the end of the preceding line of the summary. I agreed that would look cleaner, so I set about trying to make it happen. When I couldn't do it, I consulted some CSS wizards on IRC. They confirmed my suspicion, that the current HTML markup of these elements will not allow that to happen. Drupal generates the markup, and there's nothing we can do to change it. To be specific, there's a <p> element encapsulating the article summary, and a paragraph defines a block.... Without being able to get the "Read more" link to appear inside of the <p>, then it is not possible to get the layout to flow as if the link were inside of that block. We are stuck with what we have.

**Comment by garrettr** [comment]
> We are stuck with what we have.

It's good enough for now. Once we've run through the publication process and ironed out any potential kinks that might arise, this issue can be closed.

**Comment by garrettr** [comment]
There were indeed some kinks in the publication process, but they have been ironed out and the new site is working smoothly now. We have used it to publish public announcements of the last two releases (0.3.6 and 0.3.7). Therefore, this issue is resolved. Thanks @ageis!
