### ISSUE TITLE
Python bug in 0.3_collect.py backup script

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#1323]
Ran into a failure on this task on a 0.3.6 staging environment.

```
TASK: [backup | run the collect script to backup all the needed files to perform a restore] *** 
failed: [app-staging] => {"ansible_job_id": "662533596198.11638", "changed": true, "cmd": "/tmp/0.3_collect.py", "delta": "0:00:00.108048", "end": "2016-06-09 22:18:55.167031", "finished": 1, "rc": 1, "start": "2016-06-09 22:18:55.058983", "warnings": []}
stderr: Traceback (most recent call last):
  File "/tmp/0.3_collect.py", line 81, in <module>
    main()
  File "/tmp/0.3_collect.py", line 77, in main
    encrypt_zip_file(zf_fn)
  File "/tmp/0.3_collect.py", line 65, in encrypt_zip_file
    gpg.encrypt_file(stream, config.JOURNALIST_KEY, always_trust='True', output=e_fn)
AttributeError: 'GPG' object has no attribute 'encrypt_file'

FATAL: all hosts have already failed -- aborting
```

Is this because something in python-gnupg has changed?

**Comment by fowlslegs** [comment]
Yes, `gpg.encrypt_file()` has been deprecated and `gpg.encrypt()` should be used in its place.

**Comment by garrettr** [comment]
A couple of things to note.

1. As of 0.3.7, backups made by the backup role are no longer encrypted (see #1273 for context). So this issue is moot in the latest stable release.
2. @fowlslegs is correct, this problem is caused by the SecureDrop 0.3.7 packages using the latest stable python-gnupg library (see #1306 and #946), which replaced `encrypt_file` with `encrypt`.

The **core problem** here is that no matter what version tag you check out in Git for an install, it will always install the _latest_ SecureDrop packages from the apt server. In this case, the conflict is caused by an incompatibility between the 0.3.6 backup script and the Python dependencies installed by the 0.3.7 .deb packages.

If you really want to install 0.3.6 (or any specific SecureDrop version), I have a custom patch that I've been using for testing, and can attach it to this issue. Such functionality is not available in any current version of SecureDrop (and, due to its nature, could only be available retroactively - you can't retcon a feature like that). Perhaps it should be?

**Comment by ageis** [comment]
@garrettr Hmm. Sounds reasonable. Well, once we get everyone upgraded, then hopefully we'll never have to go back in time again. The only reason I was spinning this up anyway is to attempt to repro an error in an instance upgrade, related to internal Redmine issue 328.

**Comment by garrettr** [comment]
Here's the [patch](https://github.com/freedomofpress/securedrop/files/308138/initial_install_version.txt) I've been using for testing. You need to set the `initial_install_version` var to specify which version of the Debian packages to install, so you'll want to make sure the var matches the tag you have checked out before running the playbook.

Note that your "initial install version" will only last until the next automatic upgrade (so, 24h or less), at which point your server will, well, automatically upgrade (unless you make additional modifications to disable automatic upgrades as well).

**Comment by garrettr** [comment]
This is not a bug in SecureDrop, since new installations should always install the latest stable version (0.3.7).

If that patch that I attached in https://github.com/freedomofpress/securedrop/issues/1323#issuecomment-225067188 seems worth merging into the main codebase, a new issue should be filed.

One scenario to consider: if there are instances that *still* have not yet upgraded to 0.3.6, will this create problems for them? There would be a problem if a 0.3.5 instance's packages auto-upgraded to 0.3.7, and then an admin tried to run the 0.3.6 playbook per our documentation. That's exactly what happened here, although for a different reason (testing). However, this is not actually an issue because 0.3.6 updates the expired signing key, so a 0.3.5 instance's package *cannot* auto-upgrade to 0.3.7 until the 0.3.6 playbook is run. It's an ugly situation, but at least it's not going to bite anyone.

**Comment by rajevenkat** [comment]
> Yes, `gpg.encrypt_file()` has been deprecated and `gpg.encrypt()` should be used in its place.

Hi ,How can we encrypt the file with gpg then ? i am trying to encypt a file and save it to my local
with .pgp extension (ex; from Test_file.txt to Test_file.pgp after encyption)
