### ISSUE TITLE
Update SecureDrop deployment and configuration process for admins

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1340]
As mentioned in a few places (at least once [here](https://github.com/freedomofpress/securedrop/pull/1334#issuecomment-226544917)), the current deployment of Ansible is rather delicate.

Some goals of this should be to:
- Reduce the likelihood that an admin overwrites their `config.py` (or values for that wherever they are loaded)
- Have all files be kept in the git repo with a config be read from somewhere else on disk
- Have some sort of configuration validation (to avoid things like #1257)

One solution would be a simple CLI tool that is both scriptable and interactive that reads a config from elsewhere and validates it, or generates one.
### For example

```
anmnesia@amnesia:~/Persistent/securedrop/$ ./config-tool load-config ../securedrop-configs/config.yml
Loading old config from /home/amnesia/Persistent/securedrop-configs/config.yml
Validating...
WARN - config has extraneous key 'foo' with value 'bar'
ERROR - config has an invalid GPG key for key 'admin-key-fpr' with value '0x123abc'
```

```
anmnesia@amnesia:~/Persistent/securedrop/$ ./config-tool new-config --output ../securedrop-configs/config.yml --foo bar --baz quux
Validating...
ERROR - Missing key 'wat'
```

This `.yml` would still be used the way the current `.yml`: to power ansible deploys where all the moving around of details is still done within ansible as is some validation. This would just provide a nice user interface to help admins get things right on the first try.

**Comment by heartsucker** [comment]
Just leaving this as a note while looking for an unrelated issue:

This also affects issues #749 and #924.

**Comment by conorsch** [comment]
There are a couple of viable approaches here. There's already a small amount of variable validation performed in the `validate` role, which runs automatically as part of the prod playbook (but not staging, since it checks for staging/dev vars and fails if found), so I'm inclined to continue work in that direction.

Currently, the validate role uses `fail` tasks with conditional logic via `when` statements to bail out on a bad config. It'd be more intuitive to switch to using Ansible's [assert module](http://docs.ansible.com/ansible/assert_module.html). Should we need more sophisticated analysis of variable values than what's provided by Ansible's Jinja2 filters, we can add custom filter_plugins to the validate role, which gives us the power of raw Python.

**Comment by conorsch** [comment]
I also see this as related to #1129. Any work done to aid in bootstrapping the initial config should consider implications on general configurability for the deployment.

**Comment by redshiftzero** [comment]
This now exists and is `securedrop-admin`. Closing!  Feel free to make followup tickets for improvements to `securedrop-admin`.
