### ISSUE TITLE
Consider installing some debug/ development tools in development VMs

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1369]
As long as we make sure that the tools we choose to install (and their dependencies) won't affect the code that SD executes at any time, it should be safe (and useful) to install, e.g., `ipython` in the development VMs by default. Of course, these tools should stay out of prod just in case. We'd probably want Ansible to install them w/ `pip` instead of using the out-of-date apt packages in trusty.

**Comment by fowlslegs** [comment]
`tmux` would be good too.

**Comment by heartsucker** [comment]
Being linked from another issue, we should add at least `vim`, `emacs`, and `nano` as permanent requirements to our dev VM since we can assume that devs will always want those.

**Comment by garrettr** [comment]
I'm inclined to include `vim` and `tmux` since those are the tools that I find myself reaching for the most often when I'm working inside of the development VM.

Note that in general, it is expected that most text editing will occur on the host machine using your preferred text editor, thanks to synced folders. However, it is occasionally useful to edit text inside the VM, and it would be good to provide a better editor than `nano` (which comes by default with the Bento boxes) for this purpose.

I am less inclined to include `emacs` by default (even though I am an emacs user) because it requires downloading 36MB of archives, which will significantly increase the time required to provision the development VM. Compare to vim, which requires only 5MB of archives, and tmux, which requires only 247kb.

**Comment by heartsucker** [comment]
>  it requires downloading 36MB

Good god. Yeah, please leave it out. I suggested both to avoid the `vim` vs. `emacs` flame ware. :)
