### ISSUE TITLE
Proposal: Change git process to include manual test about breaking the dev env

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1386]
I think somewhere in the docs should be a note about how to ensure changes don't break the dev environment for other people.
1. Clone into another directory from your branch (to ensure no generated files are present), boot dev VM, run test suite
2. Clone into another directory from your branch, do `git reset HEAD^ hard` provision, run test suite, `git pull`, provision again (on same VM), run test suite

This ensures that someone cloning your new commit won't have a borked env, and someone else pulling won't also have a borked env.

**Comment by conorsch** [comment]
Great idea, but I'd prefer to go even further and have the testing be automated. We can accomplish a lot with automated tested in terms of the application code, and also the configuration of the development machine, but provider-specific issues such as the VirtualBox woes you describe in #1381 may need to remain manual for the time being.

The recommendations you describe would be a fine fit the developer docs, so that contributors aren't stepping on each other, particularly as we make changes to the development environment itself. In particular, I'm looking askance at the switch to the Bento boxes, which have introduced a lot of pain points.

**Comment by heartsucker** [comment]
> askance

Learned a new word today. :D

As for the Bento boxes, I'm a bit in agreement on the grounds of "it it ain't broke, don't fix it."

**Comment by garrettr** [comment]
> I think somewhere in the docs should be a note about how to ensure changes don't break the dev environment for other people.

This is already basically handled by Travis CI. The Travis environment is nearly identical to the dev environment (compare `securedrop-travis.yml` to `securedrop-development.yml`). Generally, changes that break the development environment cause the test run to fail on Travis, and we do not merge pull requests unless they pass the tests on Travis.

Can you give a specific example of a recent change that broke the dev environment but did not fail the Travis tests?

**Comment by conorsch** [comment]
> Can you give a specific example of a recent change that broke the dev environment but did not fail the Travis tests?

Switching to Bento boxes. Even manual testing of the Bento boxes wouldn't have caught #1381, however, since the failure was dependent on the host OS (i.e. Jessie vs. Stretch). More explicit documentation of versions for software such as VirtualBox would go a long way in clarifying the requirements to hack on SecureDrop.

**Comment by garrettr** [comment]
> Switching to Bento boxes.

Ah, good point - Travis handles the underlying base operating system differently than Vagrant. I agree that it would be good to normalize/consolidate these environments as much as possible, and apply automated testing them as part of our CI process.

**Comment by heartsucker** [comment]
Closing this issue I opened a long time ago. I remember my dev env getting ruined a number of times and being cranky when I opened this. We've gotten a lot better about the dev environment, and the solution I proposed is far too much overhead.
