### ISSUE TITLE
Ensure that files never touch an actual disk unencrypted

### ISSUE THREAD

**Issue by ioerror** [freedomofpress/securedrop#14]
It appears that in https://github.com/deaddrop/deaddrop/blob/master/crypto.py#L97 the data is unencrypted on the disk. Even if the disk is encrypted, I think this is sub-optimal. I would suggest either a tmpfs (not so solid for various forensics reasons), encrypting the files on the client as they're uploading, or encrypting them in chunks once they're in the server's memory.

**Comment by garrettr** [comment]
Resolved in #862.

**Comment by evilaliv3** [comment]
@garrettr @redshiftzero : was the analysis of Apache2 completed in relation to this topic?

i think that by default the same issue may exist in the multipart implementation of it and this could cause to write plaintext data for both POST and file uploads: https://github.com/apache/httpd/blob/5f32ea94af5f1e7ea68d6fca58f0ac2478cc18c5/server/apreq_parser_multipart.c

Probably while this is analyzed it would be better to enlarge the buffer size and limit the requests size to the size of the buffer?

@jimjag @wrowe: would you please point us to the right person inside apache can could support identifying the best configuration possibilities and if necessary design a patch for this?

**Comment by evilaliv3** [comment]
@redshiftzero: i'm actually not sure because i'm still trying to understand if apache is currently working in streaming passing the stream directly to flask (where #862 is effective) or if it may be doing some multipart parsing as well. 

In this condition i doubt that when the stream is bigger thant the ```brigade_limit``` (https://github.com/apache/httpd/blob/5f32ea94af5f1e7ea68d6fca58f0ac2478cc18c5/server/apreq_parser_multipart.c#L272) the file could be parsed using the filesystem as temporary storage.

**Comment by GrahamDumpleton** [comment]
Nothing in mod_wsgi should be trying to parse the content of a request. It gets passed through straight to the WSGI application as is. Whether the WSGI framework will send it to disk is a different matter.

**Comment by evilaliv3** [comment]
Thank you @GrahamDumpleton for checking this already! this is a relief.

The implementation of the WSGI Framework (Flask) was fixed in #862

We should be fine so @redshiftzero !

**Comment by GrahamDumpleton** [comment]
If not already done, what you perhaps want to look at is any input filters for Apache that may sensibly be applied when using mod_wsgi.

One that comes to mind is mod_deflate, when request content is compressed. That said, that is actually hard to use with WSGI applications because you need extensions in the WSGI framework to step around WSGI spec and ignore `CONTENT_LENGTH` on input and read to end of input. Flask does support that though.
