### ISSUE TITLE
Rewrite bash scripts in Python

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1409]
Rewrite `pip_update.sh` and `upgrade_version.sh` in Python such that they are cleaner and easier to test

**Comment by fowlslegs** [comment]
```
% find . -not -path '*/\.*' -type f -name '*.sh'
./install_files/ansible-base/roles/app-test/files/xvfb_display.sh
./install_files/ansible-base/roles/ossec-server/templates/send_encrypted_alarm.sh
./install_files/securedrop-ossec-server/var/ossec/setup_gmail_test.sh
./migration_scripts/0.3pre/upgrade.sh
./pip_update.sh
./securedrop/test.sh
./tails_files/install.sh
./tails_files/65-configure-tor-for-securedrop.sh
./update_version.sh
./build/build_generic_package.sh
./snap_ci/development_clean.sh
./snap_ci/prod_clean.sh
./snap_ci/staging_clean.sh
./snap_ci/pinned.sh
```

Some of these will have to remain as bash scripts, some of these are low-priority for conversion, and others are basically irrelevant altogether this point. Besides the two you've mentioned, I'd say `tails_files/install.sh` is the top candidate for conversion to Python.

**Comment by cowlicks** [comment]
Here is an alternative to `pip_update.sh` in python

```python
#!/usr/bin/env python

import os
import sys
import subprocess

def which(program):
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK)

    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            path = path.strip('"')
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                return exe_file

    return None

dir_ = os.path.dirname(os.path.realpath(__file__))
requirements_dir = os.path.join(dir_, 'securedrop/requirements')
venv='review_env'

if 'VIRTUAL_ENV' in os.environ:
    print('Please deactivate your virtualenv before running this script.')
    sys.exit(1)

install='sudo apt-get install -y'.split()

install_pip = install + 'python-pip'.split()
install_venv = install + 'python-virtualenv'.split()
mkvirtualenv = 'virtualenv -p python2.7'.split() + [venv]

big_command = """
virtualenv -p python2.7 {venv}
source "{venv}/bin/activate"

pip install --upgrade pip
pip install pip-tools

# Compile new requirements (.txt) files from our top-level dependency (.in)
# files. See http://nvie.com/posts/better-package-management/
# Maybe pip-tools will get its act together and standardize their cert-pinning
# syntax and this line will break. One can only hope.
pip-compile -U -o "securedrop-requirements.txt" "securedrop-requirements.in"
pip-compile -U -o "test-requirements.txt" "test-requirements.in"
""".format(venv=venv)
if not which('pip'):
    subprocess.check_call(install_pip)

if not which('virtualenv'):
    subprocess.check_call(install_venv)

try:
    os.chdir(requirements_dir)
    subprocess.check_call(mkvirtualenv)
    subprocess.check_call(big_command)
finally:
    shutil.rmtree(venv)
```

Having written this, I have to say this should just be done in bash. Not python.

**Comment by fowlslegs** [comment]
@cowlicks and I talked about this in-person, and I suggested to first install pip-tools, then import that to write this script. After looking into pip-tools however, I would say it's not really a library one should be working with, and that this script should stay bash. This is because [`pip-compile` itself is a Python script](https://github.com/nvie/pip-tools/blob/master/piptools/scripts/compile.py), and it doesn't make sense to re-implement it with a more narrow focus. That would just create more maintenance work for us in the future.

**Comment by fowlslegs** [comment]
For reference, the most important and viable rewrite candidates exist under `tails_files` and `install_files`. The `build` and `snap_ci` scripts could be rewritten as well, but this work is not as important. Avoid rewriting `securedrop/test.sh` because I will be making a PR that removes this next week.

**Comment by conorsch** [comment]
Great input, @cowlicks. I agree that it's logical to retain bash for scripts that are largely just shelling out to other programs. 

>  The `build` and `snap_ci` scripts could be rewritten as well, but this work is not as important. 

Also agreed. The `build` scripts for deb packages were converted to templates in Ansible roles in #1214, but the ship has sailed on merging that due to churn on `develop`. (I'll be submitting a leaner rewrite of the changes in #1214 shortly.) As for the `snap_ci` scripts, don't bother, since those aren't actively running in the CI pipeline yet, and may change substantially before they do. In particular, I'd like to use external pip libs where possible to minimize the testing code within the repo (see #1067).

**Comment by conorsch** [comment]
The most important target IMO is `tails_files/install.sh`, since that's nearly 500 lines of Bash that's largely untested. What testing there is, is mostly manual pre-release QA. Given the push for Ansible v2 described in #1146, and related Python/playbook-based helper scripts in #1762 and #1779, we're in a good position to minimize the clunky bash and do proper exception handling some combination of Python helper scripts and Ansible playbooks.

**Comment by redshiftzero** [comment]
We've removed the particularly gnarly and unnecessary bash scripts - `securedrop/test.sh`, `tails_files/install.sh`, and all the `snap_ci` scripts. I'm fine leaving the others as is, so I'm closing this. If you feel that there are other bash scripts that should be rewritten as Python, comment here and we can reopen.
