### ISSUE TITLE
security implications of running SecureDrop on rented servers

### ISSUE THREAD

**Issue by alexandervlpl** [freedomofpress/securedrop#1423]
I'm planning to setup SecureDrop for a small news organization that currently does not have a secure location for servers of its own.

Rented dedicated servers from a large, reliable provider seem like an acceptable option, since data from submissions is encrypted at rest. I see multiple warnings against this in the docs, but no rationale. **What are the actual security risks of having both SecureDrop servers hosted outside the organization?**

Might be good to elaborate on this topic in the docs, since many organizations are likely to consider the rented server option.

**Comment by redshiftzero** [comment]
So we consider it **necessary** to have dedicated physical machines hosted within the organization for both technical and legal reasons:

* While the documents are stored encrypted at rest (via PGP) on the SecureDrop application server, the documents hit server memory unencrypted (unless the source used the GPG key provided to encrypt the documents first before submitting), and are then encrypted in server memory before being written to disk. If the machines are compromised then the security of source material from that point on cannot be assured. The machines are hardened to prevent compromise for this reason. However, if an attacker has physical access to the servers either because the dedicated servers are located in a datacenter operated by a 3rd party or because the servers are not dedicated and may have a virtual machine co-located on the same server operated by a 3rd party, then the attacker may be able to compromise the machines.
* In addition, attackers with legal authority such as law enforcement may (depending on the jurisdiction) be able to compel physical access, potentially with a gag order attached, meaning that the 3rd party hosting your servers may be legally unable to tell you that law enforcement has been given access to your SecureDrop servers. 

In order to mitigate these threats, we require the dedicated servers be hosted in a physically secure location in the organization itself with controlled physical access.

You’re totally right that the project documentation does not adequately justify the hardware requirement. There's a little bit [here](https://docs.securedrop.org/en/stable/hardware.html) but we will definitely update the docs to add a more detailed explanation of our rationale. Thanks for calling attention to this!!

**Comment by alexandervlpl** [comment]
Thanks for making that clear, and for improving the docs so quickly!
