### ISSUE TITLE
Consider merging the ossec repo into this one

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1468]
I'm just going to quote a comment I made in a relevant PR that more or less explains the proposal I'm making and the reasoning behind it:

> @conorsch and I just talked for a minute, and I expressed concerns about the process of building the OSSEC packages via a separate repo being cumbersome. It also seems possible if not likely that a developer could forget to pull, rebuild, and re-copy-over new OSSEC packages as work happens in that repo. I proposed the possibility of merging that repo into this one. By merging the OSSEC repository into the SD repository, I see us gaining two things:

> 1. We could more fully realize the aspiration of this PR, which I see as being to automate the (re-)building and (re-)installation of local deb packages from the latest version of the source for use in the staging test VMs.

> 2. The OSSEC packages might get more love, since they'll be more visible.

---https://github.com/freedomofpress/securedrop/pull/1464#issuecomment-259299390

**Comment by conorsch** [comment]
During recent testing sprints, we discovered that the modes on files and directories within `/var/ossec/` are not consistently declared. This is because the `postinst` scripts in the FPF-maintained Debian packages clobber permissions on every install. Worse, the permissions set via `postinst` are not well structured, e.g. `chmod -R 550 ${OSSEC_HOME}` needlessly setting executable bits on all files.

We don't have a tight testing loop on these settings now, since they're maintained in a [separate repository](https://github.com/freedomofpress/ossec), so I'm in favor of merging those files in here and writing config tests to validate the setup.

**Comment by conorsch** [comment]
Turns out this is necessary for the new CI pipeline described in #1067, so adding to the 0.4 milestone.
