### ISSUE TITLE
Replace Redis workers with Python threads

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/securedrop#1469]
**Edit:** title changed to reflect change of plans via https://github.com/freedomofpress/securedrop/issues/1469#issuecomment-259883310.

@redshiftzero and I were talking about how we currently start Redis workers and never check on them. We should have a mechanism in place in the application to check job results, log errors, and retry jobs as necessary. I haven't put much thought into how this should be implemented, but wanted to raise the issue, and open the discussion. https://github.com/freedomofpress/securedrop/pull/1440/commits/c589c2d0f02ed7106c43c12d551cb68270579ea4 is a baby step towards making this happen.

**Comment by fowlslegs** [comment]
Thinking about this more, I'm not sure there's a convincing reason to use Redis, just for Redis workers. For one, the `py-redis` API is really limited. For example, there's no sort of callback or co-routine functionality. For two, it's a big dependency to add, for a problem I think I could solve better with some code using just standard Python libraries (I wish `asyncio` was an option, but that came in Python 3.4--I'll probably try `threading` instead). Maybe, I'm missing some good reason to choose Redis workers over this approach? Would love to hear more input.

**Comment by ajvb** [comment]
> I'm not sure there's a convincing reason to use Redis just for Redis workers. For one, the py-redis API is really limited. For example, there's no sort of callback or co-routine functionality. For two, it's a big dependency to add, for a problem I think I could solve better with some code using just standard Python libraries

Personally, I feel like Redis is overkill for this purpose alone. Though, this is very common for Python and Ruby, as concurrency in these languages is weak, frail, and complicated (in comparison to other languages).

For the simple use-cases in which it is used in SecureDrop (could only find two calls to `worker.enqueue`) using `threading` could be a great way to remove a big dependency that doesn't offer too much value in exchange for a little bit more code.

> Maybe, I'm missing some good reason to choose Redis workers over this approach?

Only two I have are:
1. It is easier than using `threading`
2. It is easier to interact with jobs (for example monitoring them) if they are in Redis. 

¯\_(ツ)_/¯ hope this is helpful

**Comment by NSkelsey** [comment]
Here is an external perspective FWIW. I am not sure what the status of this discussion is, but with GlobaLeaks we are thinking about adding external processes/tools to handle this.

GL relies on twisted schedulers to provide workers for notifications, anomaly monitors, and cleaners that do smart things like make sure tokens are expiring. IMO doing everything in a single process works well enough for small apps, but we have just about hit the limit with putting everything in a single python process. What bothers me the most is that one heap contains deferred callbacks to expire sessions, interact with the filesystem, and talk over SMTP.

Due to the GIL and our expert skills with python, the performance of our REST API is occasionally degraded by jobs that spin up lots of work / do not handle timeouts well.

Hence sticking with Redis or using a tiny __external__ scheduler/notifier seems like the way to go.

**Comment by redshiftzero** [comment]
I think we should probably just stick with Redis - using workers to run jobs from a queue provides a much more predictable environment than spawning threads whenever some background job needs executing. So I'm going to close this issue for now, but comment if you think there is a compelling reason why we should modify this.

**Comment by fowlslegs** [comment]
My compelling reason is explained in the initial issue commit. I'm definitely considering what others have said in this thread, but until I've done some further research and experimentation, I want to keep this one open.

**Comment by dachary** [comment]
For the record see https://github.com/freedomofpress/securedrop/pull/2256 for a proposed implementation. Motivated by the need to fix a bug that demonstrates, IMHO, rq/redis is not only overkill, it also is error prone.

**Comment by rmol** [comment]
We've started actually using Redis for caching since this issue was filed, so we're not going to be able to remove that as a dependency.

`rq`, on the other hand, as pointed out above, is both overkill for our purposes, and [error prone](https://github.com/freedomofpress/securedrop/issues/4711#issuecomment-517813231). We've accumulated a fair [amount](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/worker.py) of [code](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/scripts/rqrequeue) for dealing with it, and I think the only thing we're using it for at this point is the asynchronous hashing of submissions. 

That task would be a good candidate for another process run under `systemd`, like those for deletion of sources and submissions. That approach is both simpler than threaded code, and doesn't run the risk of interfering with the application server process.

I'm closing this in favor of #5485.
