### ISSUE TITLE
Per journalist starring of sources and system-wide source pinning

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1488]
When a person uses an application like Slack, when they star a message, it is a per-user star. However on SecureDrop on the journalist interface when we star a message it stars for every user on the interface. Ideally we would split this into two features: one feature that a journalist can use to star for herself the sources of interest, and one that a journalist or admin could use to pin certain source of interest to all users of the interface (given the potential metadata issues, this is tagged as a 1.0 issue such that this metadata can be encrypted to the SVS key).

**Comment by ninavizz** [comment]
The way the current staring is done (it sounds like) is very wacky. Slack follows the standard best-practice pattern—which is in part standard, because stars are so vague in meaning. I've worked on enterprise projects where this is debated hotly among the product team, and in either testing or stakeholder interviews, it's almost always revealed that there's never a consistent understanding of what exactly a star means. They're a great device for single-user visibility, but not for teams.

With the creation of multiple journalist accounts in 0.4, will the existing pattern carry-over?

It's standard for Tags to be global—so, every user can create new tags or delete their own created tags, and all tags are visible to all users—but not starred items.

**Comment by eloquence** [comment]
Since this issue was filed, we've talked a lot about the shared inbox vs. per-user state, esp. in the context of seen/unseen, read/unread. For now we're keeping the "shared inbox" behavior; to the extent that we make a change here, we'll want to consider this holistically for multiple features (starring, deletion, seen/unseen), which we'll track separately. Closing this issue for now.
