### ISSUE TITLE
Add alarming section to documentation for SD admins

### ISSUE THREAD

**Issue by freddymartinez9** [freedomofpress/securedrop#1496]
New SD admins are currently getting OSSEC alarms with no context (if they have never used OSSEC before). Our documentation should include basic details about the type of emails an admin will receive, approximately when, and sample "this is normal/this is not normal" OSSEC samples.

**Comment by conorsch** [comment]
@freddymartinez9 This would be great! We typically receive a flurry of "is this OK?"-type inquiries from first-time SD Admins who aren't familiar with OSSEC. Additionally, some of the OSSEC filters could use a bit of tweaking, and at the very least we should be documenting those common alert messages for review by Admins.

One that comes immediately to mind is checksums changing on files due to nightly updates run by cron-apt. The solution there should be to check the dpkg and apt logs and confirm that the packages were indeed upgraded last night. 

An overview of the severity levels would be quite beneficial, as well. We should link out to the official OSSEC docs where appropriate, but I don't mind maintaining SecureDrop-specific alerting documentation, since it's vital that Admins be equipped to interpret the alerts they receive for their instance.

**Comment by freddymartinez9** [comment]
@conorsch feel free to assign this to me. I also should mention we can add a section for `apt-get updates` usually send a bunch of alarms in OSSEC which we can tell admins it looks normal (but they should also read the logs for suspicious looking binaries being installed just in case)

**Comment by conorsch** [comment]
All yours! Remember to use the live-reload feature when editing the docs: https://docs.securedrop.org/en/latest/development/documentation_guidelines.html Since switching to RTD, making changes to documentation is actually rather pleasant. :smile:

**Comment by freddymartinez9** [comment]
Created #1497 thanks @conorsch !
