### ISSUE TITLE
More granular persistence for Tails volumes

### ISSUE THREAD

**Issue by nvesely** [freedomofpress/securedrop#1518]
When setting up Tails USBs, we can make it harder for malware to persist by more granularly setting persistence options in the Tails GUI. Some examples:

* None of the Tails volumes--SVS, JW, AW--should require generic dotfiles persistence. 
* Only the AW needs SSH persistence.
* The SVS only needs GPG key persistence in addition to the `~/Persistent` folder.

I know there have been some changes to the persistence options, and I haven't looked at the GUI for setting persistence in a while; precisely listing the persistence options for each type of Tails volume would require a careful comparison of what we want to keep on each volume, and what options Tails exposes.

This was originally brought up in https://github.com/freedomofpress/securedrop/pull/1505#issuecomment-268979203.

**Comment by conorsch** [comment]
The reason we make the blanket recommendation to enable _all_ Persistence types in the setup docs is simply to prevent user error by new Admins during configuration of an admittedly rather complex medley of Tails devices. As discussed in #1505, that recommendation is quite general, but I'm not sure that making the requirements more granular would actually help Admins get it right the first time.

As far as malware mitigation goes, the airgap is our strongest defense in the Tails environment, and while removing dotfiles persistence is theoretically superior to leaving it enabled, moving to a different architecture that focuses more on containment for untrusted document viewing would be the right approach long-term.

**Comment by fowlslegs** [comment]
> The reason we make the blanket recommendation to enable _all_ Persistence types in the setup docs is simply to prevent user error by new Admins during configuration of an admittedly rather complex medley of Tails devices. As discussed in #1505, that recommendation is quite general, but I'm not sure that making the requirements more granular would actually help Admins get it right the first time.

Making the requirements more granular would in fact very slightly increase the chance admins might screw up the install. However, (i) we already expect admins to carry out much more difficult and error-prone tasks, and (ii) disabling dotfiles persistence in particular eliminates probably the lowest hanging fruit in terms of how an adversary might persistently compromise Tails.

> As far as malware mitigation goes, the airgap is our strongest defense in the Tails environment, and while removing dotfiles persistence is theoretically superior to leaving it enabled, moving to a different architecture that focuses more on containment for untrusted document viewing would be the right approach long-term.

Can you be a bit more specific? The airgap does basically nothing in terms of anti-exploitation (probably not what you meant by mitigation), and in fact is a nightmare situation IMO because we don't instruct admins to update the software on it; attackers don't need a 0-day when they can just look to months or years worth of CVEs for PDF readers and kernel privilege escalations alike. On this note, the "airgap" doesn't do a particularly great of mitigating the spread of malware (probably what you meant by mitigation). Again, the vulnerable state of the SVS means root compromise comes easy to attackers, which means USB (which most orgs choose instead of WORM for efficiency) malware can be easily deployed. Though both malware and sensitive information can be spread/exfiltrated from other ways I've gotten into elsewhere...

To not get further off-topic, I'll just conclude by saying I believe this presents a good trade-off in terms of system setup burden vs. security benefit (think I made this point mostly in the first paragraph).

**Comment by msheiny** [comment]
Without delving into this debate on the security-front -- I will chime in from an administrative/install experience perspective and agree with @conorsch's assertion. This is an ample opportunity for an admin to mess up and not select the right item and then have a frustrating experience further in the documentaiton.

However, I do feel like this is one more item that could be automated. I've seen a Tails persistent config file floating while I was poking at the file system. I think if we wrap the creation of the persistent drive and the configuration as part of a larger `setup` script we could alleviate both concerns (ie @conorsch's concerns about admins manually hitting the wrong option and @fowlslegs 's concern about scoping down persistence options).

**Comment by conorsch** [comment]
@msheiny That's a fine compromise. We have a long way to go in providing a more streamlined first-run experience for setting up the initial install, but that's seriously worth investing in, to minimize user error and thereby close potential security holes early on. 

#1176 suggests templatizing the Tails creation of Journalist volumes, which sounds smart to me, but we'll need a workable plan to automate it. I think even more explicit documentation without much scripting would be a big win there.

**Comment by conorsch** [comment]
Good call, @edenemmanuel, I think we've largely moved based this strategy as a meaningful security control for real-world instances. Much more useful, based on Admin feedback, would be a tool to create new Journalist Workstations, as described in #1177 and #2751.
