### ISSUE TITLE
Consider use of Github integration(s) to help us keep up on dependency management

### ISSUE THREAD

**Issue by nvesely** [freedomofpress/securedrop#1519]
Presently, we intermittently check on our Python dependencies to see if new versions are available. If so, we do our best to review the changes, and if we discover there are any vulnerabilities in package versions shipped in our latest app code deb, release a hot-fix. Ideally, we should be notified about updates to dependencies, and vulnerabilities in libraries we use ASAP. There exist several Github integrations, all with free plans for open-source projects that can do this for us. Foremost among them, in my opinion, from my limited research, is [SRC:CLR](https://github.com/integrations/src-clr), though [VersionEye](https://github.com/integrations/versioneye) and [WhiteSource](https://github.com/integrations/whitesource) are also considerations.

These integrations should not serve as a replacement for manual review of dependency updates, but, in my opinion, as a necessary supplement.

**Comment by fowlslegs** [comment]
Resurrecting this issue because SourceClear changed policy such that you now are only allowed 10 free scans monthly. This obviously doesn't suffice if we want to run it in Travis as opposed to manually, so we're backing it out (see #1818 and #1819).

Time to look further into the other options, because I do believe this is a valuable type of tool.

**Comment by redshiftzero** [comment]
Resolved via #2462
