### ISSUE TITLE
Make message for flagged sources more user friendly

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1524]
This is a UX suggestion by @ninavizz to improve the notification displayed to flagged sources (click on image below to see her suggestion for this issue in greater detail):

![screen shot 2017-01-17 at 5 08 10 pm](https://cloud.githubusercontent.com/assets/7832803/22050053/7152eb3a-dcec-11e6-8bcc-98bcd7f0b38a.png)

**Comment by ninavizz** [comment]
Hey folks! I'm not a developer, otherwise I'd do this myself... but to those who are and would like to code this, I offer the below (with a hearty "thank you!"). (Thx @redshiftzero for posting!)

#405F6F Title: Whew, it’s you! Now, the embarrassing part…
#555 Text: Our servers experienced an unusual surge of new activity, when you last visited. This could have been human activity, an automated attack, or just some random blip. To err on the side of caution, we put a hold on sending all documents from that day, through to our journalists.

Now that we know you’re really a human, though, we’ll get your previous submission into the hands of a journalist, straight away. We’re sorry for the delay. Please do check-back again in a week or so.

SVG icon:
`<svg xmlns="http://www.w3.org/2000/svg" width="135" height="99" viewBox="0 0 135.3 98.8"><style>.a{fill:#006E94;}</style><path d="M68.6 29.8c10.9 0 19.8 8.9 19.8 19.8s-8.9 19.8-19.8 19.8c-10.9 0-19.8-8.9-19.8-19.8S57.7 29.8 68.6 29.8M68.6 24.9c-13.6 0-24.6 11-24.6 24.6S55 74.2 68.6 74.2c13.6 0 24.6-11 24.6-24.6S82.2 24.9 68.6 24.9" class="a"/><path d="M80.1 56.1c-1 4.6-5.8 8.2-11.6 8.2 -5.8 0-10.6-3.5-11.6-8.2" class="a"/><path d="M62.9 42.8c1.7 0 3.1 1.4 3.1 3.1 0 1.7-1.4 3.1-3.1 3.1 -1.7 0-3.1-1.4-3.1-3.1C59.8 44.3 61.2 42.8 62.9 42.8" class="a"/><path d="M74.3 42.8c1.7 0 3.1 1.4 3.1 3.1s-1.4 3.1-3.1 3.1 -3.1-1.4-3.1-3.1S72.5 42.8 74.3 42.8" class="a"/><path d="M64.5 37c-0.4-1-1.5-1.4-2.4-1l-4.5 2c-0.9 0.4-1.3 1.5-0.9 2.5s1.5 1.4 2.4 1l4.5-2C64.5 39 64.9 37.9 64.5 37" class="a"/><path d="M79.4 38.1l-4.5-2c-0.9-0.4-2 0-2.4 1 -0.4 1 0 2.1 0.9 2.5l4.5 2c0.9 0.4 2 0 2.4-1C80.7 39.6 80.3 38.5 79.4 38.1" class="a"/></svg>`

**Comment by jcmcreate** [comment]
I'm happy to work on this issue as part of the overhaul of the flash messages, see also #1526

**Comment by redshiftzero** [comment]
Implemented in PR #1558 so closing
