### ISSUE TITLE
Improve flashed message when source successfully submits a document or message

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1525]
This is a UX suggestion by @ninavizz to improve the notification displayed to sources upon submission of a document or message (click on image below to see her suggestion for this issue in greater detail):

![screen shot 2017-01-17 at 5 08 23 pm](https://cloud.githubusercontent.com/assets/7832803/22050173/6f121980-dced-11e6-9f3c-0676a37a413b.png)

**Comment by ninavizz** [comment]
Thanks for posting, @redshiftzero! 

Implementation notes:

1. Mentioning the media organization's name (for my wires, I use "The Daily Bugle"). It's important to remind users who they submitted info to. Remember: many are doing something that will put their livelihoods on the line if they're caught, so that anxiety can impact retention of basic info. Is this possible to somehow dynamically populate w/ the installed org's name?

2. A link to remind users of their codename. Ideally upon clicking that link, the hyperlink would reveal a new <p> below the message text, describing where on the screen they can find it. Something simple and friendly, such as: "Click on the thumbprint above," or "Scroll down and you'll find it mid-screen. Remember, write it down somewhere safe!" The prior suggestion of course, dependent on that separate functionality being added.

Ok!
`#079A54` Title: Success!
`#555555 `Message: Thank you for sourcing this information to <%org-name-here%>. Please check-back later for replies. Forgot your Codename?
Icon SVG: `<svg xmlns="http://www.w3.org/2000/svg" width="135" height="99" viewBox="0 0 135.3 98.8"><path d="M86.8 50c0 12.9-10.5 23.4-23.4 23.4 -12.9 0-23.4-10.5-23.4-23.4s10.5-23.4 23.4-23.4C76.4 26.6 86.8 37.1 86.8 50M79.5 43.4l-5.5-4.9L60.8 53.4l-6.6-6.8 -5.3 5.1L61 64.2 79.5 43.4z" fill="#079A54"/></svg>`

**Comment by jcmcreate** [comment]
@ninavizz I don't think I can get the organisation name to insert into this flash message, as it's not currently declared by the organisation anywhere (that I could find at least!). Is there alternate text that would work here instead?

**Comment by ninavizz** [comment]
@jcmcreate The alternative would be "Thank you for sharing this information with us!"

@fowlslegs @justintroutman @redshiftzero This ain't urgent, but generally speaking SD needs to be able to message users with the name of the newsroom in the messaging. Could it be prioritized to include the org name as a declaration upon installation (did I word that correctly?)?

**Comment by heartsucker** [comment]
@jcmcreate There are steps in the `ansible` provisioning that allow different variables to be added to the generated `config.py`. This should be updated to include something where an `organization_name` variable can be added. Then, in the code, there is something like:

```python
if config.org_name:
    flash('Thanks for submitting to {}!'.format(config.org_name), 'notification')
else:
    flash('Thanks for submitting to us!', 'notification')
```

And yes, I think it makes sense to make the split into two distinct messages to future proof it from strange grammar errors.

**Comment by freddymartinez9** [comment]
Another UX/ UI thing to consider is the `Thanks! We received your document` message never clears. So a source who wants to upload multiple documents would see their first document sent and then go to see upload their second one and still see `Thanks! We received your document` _before_ the second document uploads ![flashnevercleared](https://user-images.githubusercontent.com/3100220/31730966-6fdc836e-b3e8-11e7-9289-4e62b0b2602b.png)

**Comment by ninavizz** [comment]
^ re: Freddy's observation... any chance this has since been fixed?

**Comment by ninavizz** [comment]
Nobody responded to my prior question, so I'll try another poke... anyone know if this issue is still an accurate reflection of a Source's multi-file upload experience, today?

**Comment by ninavizz** [comment]
Take on to close issue in #4967. Macro issue however, remains around single-file-upload as confusing user problem.

**Comment by eloquence** [comment]
As noted above, this original design suggestion was implemented; closing.
