### ISSUE TITLE
DOS detection

### ISSUE THREAD

**Issue by david415** [freedomofpress/securedrop#153]
We should use Eric's DOS detection algorithm...
The idea we discussed so far:

A standalone daemon tails a log for events which contain a timestamp and an ID.
The daemon writes to a different output log when it detects a DOS attack.
OSEC monitors that log and performs a mitigation action.

Perhaps we should rename to dos_detection.py instead of dos_mitigation.py

**Comment by heartsucker** [comment]
Marking as "Pending close" because DOS detection is likely covered by Nagios. Plus, if the onion services are being DOS'd, it's not like an admin can call CloudFlare and say "plz make it stop."

**Comment by redshiftzero** [comment]
Nagios will indicate if a particular SecureDrop is unavailable, which could be due to a DOS attack or many other issues. It's not clear to me from this ticket what the mitigation action would be here. If there's a specific suggestion for what mitigation action could be put in place to justify attempting to detect DOS attacks then let's file a followup.
