### ISSUE TITLE
Instructions for HTTPS on the source interface

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1553]
Add documentation (or ideally automation) to help organizations rollout HTTPS on their source interface - as done by [The Intercept](https://y6xjgkgwj47us5ca.onion/) and the [New York Times](https://nytimes2tsqtnxek.onion/).

**Comment by conorsch** [comment]
We'll need both docs and first-class vars for this. The documentation should cover the steps necessary to procure the cert, and include an explanation that only EV certs are currently supported. The automation would be fairly trivial in comparison, particularly because a few orgs are already doing it and we've shaken out most of the kinks.

Since we'll need to require Admin intervention during the 0.4 release, perhaps we should target 0.4 for this feature as well.

**Comment by redshiftzero** [comment]
Closing this one as it is a duplicate of the more detailed follow up issue #1605
