### ISSUE TITLE
Reconcile develop and master

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1559]
HEAD on master points to SecureDrop 0.3.4 (in git-flow HEAD should point to the latest release) and is 1407 commits behinds develop - release/0.3.10 is 1310 commits behind develop.

**Comment by conorsch** [comment]
The real goal here is to get `develop` into a releaseable state. We've made good strides on testing lately, but there's still more ground to cover.

That said, catching up canonical `master` to point to the latest release (0.3.11 as of #1563) is a good starting point, and should indeed be done.

**Comment by fowlslegs** [comment]
I made the suggestion that we should delete `master` and rename `develop` -> `master` the other day. Then we can try to bring changes from `0.3.11` into the new `master` (reconciliation). Then with each release branch we should then work on getting more of the new `master` into that release branch.

Another thing we could do is delete `master` and create a new master based on `0.3.11` (or do a fast-forward which should be possible). Then bring things from `develop` into `master`, which for an interim time (the reconciliation process), we can allow to break, while still having our nice `0.3.11` branch and our nice `develop` branch. After this is done we can delete `develop`. The next release will involve moving work from this new `master` into the next release branch.

We are trying to ditch git-flow, so `master`'s HEAD should no longer point to the latest release.

**Comment by ninavizz** [comment]
So this was a bad week to try and learn Git with the SD repo?

**Comment by fowlslegs** [comment]
Not really. We haven't started the crazy migration work yet. `develop` has almost all of the latest work as you aware. `master` is basically irrelevant in it's current state. `release/0.3.11` has a little bit of stuff `develop` doesn't that's accumulated over the last half-dozen releases or so. Since `develop` is not just purely ahead of the release branches, which have to a small degree gone their own way, we'll need to reconcile these differences in order to get our branching scheme into a better state where we can just pull things down from `develop` into our release branches and it will generally work.

After each new release, we may have to push a few things back up into our development branch (which will be named `master` in the future), but the closer we can keep our development and release branches, the less work that will be. To briefly explain why this may be necessary, take the example of us having to fix the icons on the `release/0.3.11` branch that have been removed in `develop`. We have to scope releases because we can't always put a whole bunch of new work into what's supposed to be a hotfix or point release branch (see http://semver.org/ for how we do versioning if you're not already familiar). Minor releases require a whole lot of testing, and if we're doing something like a source interface UX overhaul it makes sense to wait until we've completed that overhaul and things are in a state everyone is happy with before shipping it. In the meantime, TBB 6.5 introduced a new security feature that forced us to make UX modifications. But now our development changes won't cleanly apply to the release branches because of this fix we had to make. Minor stuff like this happens all the time, requiring reconciliation. As I mentioned above, the goal is to keep the development and release branches as close as possible by reconciling changes between them after every release. This ensures our workflow is as fast, modular, and painless as possible and helps us bring more changes to users faster.

**Comment by fowlslegs** [comment]
Feel free to follow up via email with more questions @ninavizz and I'll happily try to explain, but we should probably keep this issue thread on track.

**Comment by ninavizz** [comment]
Sorry, was just trying to make a joke... no real questions. Thanks for the info tho. :D

**Comment by fowlslegs** [comment]
That was so funny I forgot not to write two lengthy paragraphs (this is also a joke, happy to help you understand wtf is going on).

**Comment by fowlslegs** [comment]
Do we want to delete `master` now and rename `develop` to `master`? Or wait until the `0.4` release?

**Comment by conorsch** [comment]
Hold off on branch destruction and renaming for now. We can handle that as part of release, but we still have tons of triage to slog through before we decide that develop is fit for shipping. Above I said: 

> catching up canonical `master` to point to the latest release (0.3.11 as of #1563) is a good starting point, and should indeed be done.

and that seems like a decent way to get a handle on the scope of changes we're dealing with. Ideally we'll be able to _merge_ develop into master (once master is the same as 0.3.11), but given the magnitude of the drift, resolving may be more complicated than that.

**Comment by fowlslegs** [comment]
We could also delete `master`, create a new master branched off `release/0.3.11`, and then proceed to merge `develop` into `master`. I don't see a point in merging `release/0.3.11` into `master`, when it could essentially just become `master`. I do, however, see your point in wanting to merge the changes from `develop` back into a branch based off our latest release to (a) give us a sense of exactly what `0.3.11` -> `0.4` looks like, and (b) have a more continuous and linear git history.

**Comment by redshiftzero** [comment]
In the `release/0.4` branch, we've merged `develop` into `master`, resolving conflicts in the following files manually:

```
docs/set_up_admin_tails.rst
install_files/ansible-base/roles/common/defaults/main.yml
install_files/securedrop-app-code/DEBIAN/preinst
securedrop/manage.py
```

We'll continue with our current branch strategy for now. Once this large backlog of changes is shipped in the upcoming release and we move to a more frequent release schedule, this should alleviate many of the problems arising from the large diff between `develop` and `master`. However, if necessary we can re-evaluate the branch strategy in a few months once the dust has settled. Until then, I'm closing this.
