### ISSUE TITLE
Add injectable organization name to source/journalist interface

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1575]
As suggested by @ninavizz here https://github.com/freedomofpress/securedrop/issues/1524, source templates could be improved by including the organization name as string in various copy and flashed messages.

**Comment by fowlslegs** [comment]
I'm not sure where she actually suggested including the org names in the messaging. Could you clarify @ninavizz @heartsucker?

**Comment by ninavizz** [comment]
It's very problematic right now, that the name of the newsroom for each SD instance is absent in the Source UI. That's why B2B2C apps co-brand: to cognitively anchor the user with where they're creating/uploading things on/to, not so much to show off logos & attribution.

Right now "SecureDrop" appears to users as a service, that newsroom landing pages send them to. That's just a common pattern in the world that today's UI reflects. That matters. My longer-term UI sketch shows a cobranding schema, which wd obvs be much more involved. 

Short-term, the most obvious/easy area to present the org name to a user in, is the confirmation message—which is also confusing (tho less-urgently) bcuz it follows the "info bubble" UI pattern for color/icon use.

All of this is in the latest version of the Source UI stuff that you guys have from me. The GDoc links all point to the most recent versions of everything.

"Thank you for submitting your documents" is an incomplete message. "Thank you for submitting your documents to The New York Times" more clearly states that the user's stuff just went to servers owned by the NYT, and reminds users where to follow-up, on the chance they submitted to multiple orgs.

**Comment by heartsucker** [comment]
As a side note, this is going to be a **massive** pain in the ass if we decide to do internationalization because English basically ignores "cases." We use the same "the" or adjective for naming an object directly, indirectly, etc. If this gets added in extensively, simply injecting "The Local Newspaper" into the templates will lead to significant grammatical incorrectness.

[Click here](http://german.about.com/od/grammar/fl/The-Four-German-Noun-Cases.htm) and search for the tables under the phrase "Definite Articles".

Also, this [wiki page](https://en.wikipedia.org/wiki/German_adjectives) on adjectives.

Yeah. Sadness.

**Comment by ninavizz** [comment]
I kinda tried to address that concern, with how I asked newsrooms input their names on the admin-pane I sketched-out—and by wording the confirmation bubble *exactly* as I did. I worked on the localization team at Yahoo!, and this issue was an epic PITA. Within my admin pane sketch, it gives newsrooms the oppty to input whatever they want for their name (eg: "The Intercept" or simply "Intercept"), and as they type the character inputs are automatically plugged-in to the confirmation message's sentence, shown below. Should the app get localized, then hopefully that'd take care of it?

**Comment by heartsucker** [comment]
True, but even in this case, if we had, for exampe, Der Speigel setting up SecureDrop, there' is no way to write that sentence because when you say "to" something, Der Speigel would become "Dem Speigel," and in this case you'd smash the "to" and "the" together and get "zum Spiegel". And if even if you wanted to say "the SecureDrop of Der Speigel," it would have to "der SecureDrop Des Speigels." And possessive like "Der Speigel's SecureDrop" would be "Der Speigels SecureDrop" (no apostrophe). I mean. It seems like translation isn't going to happen any time soon, but again, just making note of what an absolute nightmare this would be.

Which is also a bummer because I still think having things in English only is going to hurt adoption outside the US.

**Comment by heartsucker** [comment]
Also, @fowlslegs the original note about org name is here: https://github.com/freedomofpress/securedrop/issues/1526

**Comment by ninavizz** [comment]
@heartsucker Agreed—but that's a bridge yet to cross, that can be elegantly crossed for those users, once the time comes. In the interim, the feature should still be included, for US users. Especially as more and more ppl in big places, are using SD, more often (thank heaven).

Localization isn't always pretty, and some times does require complete text-string rewrites. That's just the nature of different languages having different structures... but most localization peeps will all agree, that English does in fact meet the Gold WTF Standard for linguistics. We can only do so much. :)
