### ISSUE TITLE
freedom and no third parties?

### ISSUE THREAD

**Issue by stopANALytics** [freedomofpress/securedrop#1585]
analytics not much unlike third party ads are ANTITHETICAL to privacy and subsequently to freedom

https://securedrop.org/

loads

https://analytics.freedom.press/piwik.js

**Comment by conorsch** [comment]
We run that analytics server ourselves, so it doesn't qualify as a third-party. We've worked hard to avoid use of more polished analytics frameworks in order to provide better privacy for our visitors, and the configuration we have in place respects the "Do Not Track" header, should users choose to set it. For those interested in a similar setup, check out the [Piwik project](https://piwik.org/). It's [also open source](https://github.com/piwik/piwik), just like SecureDrop.
