### ISSUE TITLE
Discuss implications of including journalist username in replies

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/securedrop#1592]
In https://github.com/freedomofpress/securedrop/pull/1534 I merged https://github.com/freedomofpress/securedrop/pull/1534/commits/413e8874c9dbe665a2de28bdcc4211ea7185a05c, which includes the username of the journalist that sends each reply for the source to see in the `/lookup` view. I regret not thinking more carefully about it at the time, but I want to discuss the implications of this change.

Our use of passwords (potentially Diceware-enforced if we merge https://github.com/freedomofpress/securedrop/pull/1509), 2FA, and ATHS ensure that leaking usernames is not a security risk in the sense it does not really aid in access to the JI. Rather, this change might take journalists by surprise who do not expect their usernames to be public. Maybe they want to remain anonymous, but their usernames will de-anonymize them. Maybe they've just chosen an un-professional username.

If we want to include a "From:" field, which is not inherently a bad idea, I think we should do it more carefully. Journalists and admins should be aware this is public-facing, and should be able to choose a "display name," or hide under a cloak of anonymity. Whatever they choose, they should at least have awareness of how their responses will appear to their sources.

**Comment by redshiftzero** [comment]
OK, in order to prevent surprises in the 0.4 release for journalists, I'm going to submit a PR to remove the display of the journalist username from the source interface in `develop`. 

I'm also going to make a tracking issue for changes from 0.4 that we remove that we probably want to bring back in later (punting on the debate on which reverted changes to bring in and when). 

To be clear, I think the general direction here letting the sources know who they are talking to is a very sensible one (snippets from @ninavizz's mockup in #1560):

![screen shot 2017-04-21 at 11 36 04 am](https://cloud.githubusercontent.com/assets/7832803/25291911/d146ee84-2688-11e7-93d5-aa1bd7e2d607.png)

But I do think it makes sense to wait until a future release where we can allow the journalists to specify their display name (this is implemented already in PR #1523).

**Comment by fowlslegs** [comment]
:+1: Looks like we're on the same page here. Review coming up!

**Comment by heartsucker** [comment]
Reopening after discussion in #1658

**Comment by eloquence** [comment]
Still relevant (thanks @psivesely), refactored for readability into #5572.
