### ISSUE TITLE
Sass 3.5 will require Ruby>=2.0.0

### ISSUE THREAD

**Issue by nvesely** [freedomofpress/securedrop#1594]
Currently Ubuntu Trusty has 1.9.3 in it's repos. We'll need to pin Sass<3.5 if Ubuntu doesn't upgrade Ruby by the time Sass 3.5 is released. Sass is currently on version 3.4.23.

**Comment by garrettr** [comment]
Does SASS need to be installed on the servers? Wouldn't it be better to generate the final CSS from the SASS as part of the build process, and only ship the CSS in `securedrop-app-code.deb`?

**Comment by heartsucker** [comment]
Sass is not needed for the servers. Only for the build. The 'build' role
does the compilation during the Debian packaging. However, we could nail
the version down in the 'gem install' step to give us longer until we have
to deal with this.

Am 01.03.2017 10:01 nachm. schrieb "Garrett Robinson" <
notifications@github.com>:

Does SASS need to be installed on the servers? Wouldn't it be better to
generate the final CSS from the SASS as part of the build process, and only
ship the CSS in securedrop-app-code.deb?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/freedomofpress/securedrop/issues/1594#issuecomment-283468647>,
or mute the thread

**Comment by fowlslegs** [comment]
Not a direct concern for production systems, but needed by the development and build Vagrant machines (the latter of which generates the final CSS for the app code package w/ `sass`).

**Comment by eloquence** [comment]
This gem has reached end-of-life; closing in favor of #4452.
