### ISSUE TITLE
Make "Back to submission page" link a secondary style button to the left of "Exit" in the `/why-journalist-key` view

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/securedrop#1599]
I think this would look more stylistically consistent, and it would help to ensure the source does not confuse the "Exit" button for one that would take them back to the submission page.

**Comment by ninavizz** [comment]
All Back/Next buttons should be on the bottom of a page. The "Exit" button is at the top, as that placement speaks to user mental models of account/sesstion management.

Separately—this shouldn't be necessary, at all. Don't all pages have the submission functionality on them? If this is an FAQ kind of page, the message itself about the crypto-key should include all text the Source may need (as previously submitted wireframes proposed). Flow problem, not UI problem.

**Comment by fowlslegs** [comment]
> All Back/Next buttons should be on the bottom of a page.

That makes sense to keep a consistent look. I think would be nice to turn the link into a button or at least change the styling/ spacing of it to make it more clearly discoverable.

An alternative idea is to get rid of this view and maybe include the text in an [accordian](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_collapsible_accordion&stacked=h). I think this may be a better solution to the flow problem. This text should also be reworked to include GPG Tools instructions for Mac users.

> The "Exit" button is at the top, as that placement speaks to user mental models of account/sesstion management.

On that note "Exit" is confusing to me. Didn't it used to be "Logout"? I think that's way more immediately clear. Putting myself in the shoes of someone who didn't know where all the links in SD went, I wanted to click on "Exit" on the `/why-journalist-key` view in order to take me back to the submission page.

> Don't all pages have the submission functionality on them?

No, only the submission page.

> If this is an FAQ kind of page, the message itself about the crypto-key should include all text the Source may need (as previously submitted wireframes proposed).

I'm not understanding what you're saying here.

**Comment by eloquence** [comment]
It is a navigational link, so IMO should not really be a button. We can reconsider if others disagree. Closing, tentatively.
