### ISSUE TITLE
Resolve UI inconsistencies for the 0.4 release

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1604]
In order to start working from `develop` we had to merge a lot of changes back in from `release/0.3.11`. This has created an inconsistent style within and across the JI and SI. One area this is notable is the buttons:

> This introduces (further?) inconsistency in the between the new and old style buttons. Some buttons contain camel-case text with narrow spacing and icons (old style). Others are all caps with wide letter spacing and no icons (new style). We should have a consistent button style (or set of styles). In the JI especially (e.g., in the `/col/<sid>` view), there is the problem that some of the different style buttons are right next to each other and much different in size and style.

-- https://github.com/freedomofpress/securedrop/pull/1581#pullrequestreview-24619661

We may need to resolve some other inconsistencies as well.

X-link: https://github.com/freedomofpress/securedrop/issues/1603.

**Comment by redshiftzero** [comment]
OK just compared `release/0.3.12` and `develop` from the perspective of the UI. What follows is a step by step view of the major screens so the major changes can be seen. A checklist of items that I will fix for the unified 0.4 UI in a subsequent PR is at the end. Please comment if you disagree with my assessment.

# Source Interface

## Frontpage

### Master

![screen shot 2017-04-24 at 2 01 02 pm](https://cloud.githubusercontent.com/assets/7832803/25358726/6087f21c-28f7-11e7-825b-032dbebc0262.png)

### Develop

![588203dc-28f7-11e7-9005-16a94548a240](https://cloud.githubusercontent.com/assets/7832803/25358761/7c4404e6-28f7-11e7-9193-8f096cbbf1b2.png)

## Generate codename

### Master

![screen shot 2017-04-24 at 2 01 10 pm](https://cloud.githubusercontent.com/assets/7832803/25358980/3d9afc26-28f8-11e7-93cb-8d712d20b421.png)

### Develop

![screen shot 2017-04-24 at 12 19 38 pm](https://cloud.githubusercontent.com/assets/7832803/25359081/9f8ecb1a-28f8-11e7-80df-9110f60795cc.png)

## Submit

### Master

![screen shot 2017-04-24 at 2 01 14 pm](https://cloud.githubusercontent.com/assets/7832803/25359176/ff12deaa-28f8-11e7-8a89-229f7c405946.png)

### Develop

![screen shot 2017-04-24 at 12 19 43 pm](https://cloud.githubusercontent.com/assets/7832803/25359067/8f2e42aa-28f8-11e7-96c3-24ee01d7d667.png)

# Journalist Interface

## Login

### Master

![screen shot 2017-04-24 at 1 57 43 pm](https://cloud.githubusercontent.com/assets/7832803/25358779/86153ca6-28f7-11e7-97c3-0aebb78ab74e.png)

### Develop

![screen shot 2017-04-24 at 12 23 50 pm](https://cloud.githubusercontent.com/assets/7832803/25358811/94c1d502-28f7-11e7-8202-ee5a249830b1.png)

## Sources

### Master

![screen shot 2017-04-24 at 2 01 30 pm](https://cloud.githubusercontent.com/assets/7832803/25359227/3433b0aa-28f9-11e7-8f88-d820fb1122ea.png)

### Develop

![screen shot 2017-04-24 at 12 23 13 pm](https://cloud.githubusercontent.com/assets/7832803/25359232/3b85b95c-28f9-11e7-893d-d591a9df9079.png)

## Submissions for a given Source

### Master

![screen shot 2017-04-24 at 2 01 36 pm](https://cloud.githubusercontent.com/assets/7832803/25359369/cadc90b2-28f9-11e7-9e8b-9e50d5390e35.png)

### Develop

![screen shot 2017-04-24 at 12 23 24 pm](https://cloud.githubusercontent.com/assets/7832803/25359364/c2ae1bea-28f9-11e7-8a81-b4ab4be5defb.png)

## Admin Interface

### Master

![screen shot 2017-04-24 at 2 01 43 pm](https://cloud.githubusercontent.com/assets/7832803/25359193/16cf8638-28f9-11e7-9794-9ad75e8bcf38.png)

### Develop

![screen shot 2017-04-24 at 12 23 30 pm](https://cloud.githubusercontent.com/assets/7832803/25359203/21037740-28f9-11e7-8c8f-fe478a3ccb1c.png)

## Add/Edit User

### Master

![screen shot 2017-04-24 at 2 01 48 pm](https://cloud.githubusercontent.com/assets/7832803/25359294/77a0362e-28f9-11e7-9e0f-b3ba8a6d26cc.png)

### Develop

![screen shot 2017-04-24 at 12 23 36 pm](https://cloud.githubusercontent.com/assets/7832803/25359281/6d69feba-28f9-11e7-9481-ccfafd2c89ef.png)

# Action Items

Here's what I propose doing:

- [ ] Put the journalist interface buttons on the top of the table for "Submissions for a given Source" back to the style used on top of the table on the previous "Sources" page for unity. I think it's fine to keep the "Submit" and "Delete collection" button in the new style. 
- [ ] Modify the CSS on the buttons on the source interface frontpage in the "Submit documents for the first time" and "Already submitted something" panels to have the same distance between the side and bottom of the box. 

Note there are some more extensive UI changes that can be made in a future release (see nice mockups in #1560 and #1540). Clearly, as you can see in these screens there are changes between `release/0.3.12` and `0.4` (I mean... it's 1000+ commits), but they are subtle and are overall going in a softer and more user friendly direction, so unless there are actual problems with them I don't think we should back them out just because.

**Comment by fowlslegs** [comment]
> Modify the CSS on the buttons on the source interface frontpage in the "Submit documents for the first time" and "Already submitted something" panels to have the same distance between the side and bottom of the box.

I don't understand what you're saying here :confused:.

> Put the journalist interface buttons on the top of the table for "Submissions for a given Source" back to the style used on top of the table on the previous "Sources" page for unity.

You mean add back the icons? If so, I agree. It also looks better how all the buttons on the top are of uniform size in the "Sources" view, so we should fix that too.

> I think it's fine to keep the "Submit" and "Delete collection" button in the new style.

Your screenshot misses the original "Delete collection" button, but for reference we just removed the trashcan icon.

Overall, I think these minor changes should be sufficient for 0.4. Thoughts on #1603?

**Comment by redshiftzero** [comment]
> You mean add back the icons? If so, I agree. It also looks better how all the buttons on the top are of uniform size in the "Sources" view, so we should fix that too.

Yep definitely make the buttons on the top uniform size as in the "Sources" view. In terms of the icons, I could go either way, but I will put them back in for 0.4 for consistency. 

> I don't understand what you're saying here

Sorry, my bad. Here's a pic of the area I'm talking about:

![screen shot 2017-04-24 at 3 15 53 pm](https://cloud.githubusercontent.com/assets/7832803/25361062/f9938f12-2900-11e7-8e72-f44a701ef251.png)

The distance between the button and the bottom of the enclosing box and the button and the side of the enclosing box seems like it should be the same. 

> Thoughts on #1603?

No major feelings on #1603, I would need to see it implemented I think. But either way I don't think it's something we should resolve for 0.4.

**Comment by fowlslegs** [comment]
Okay, I'm all on-board as far as this goes being the complete "inconsistencies to resolve for 0.4" list then. Unless something else important comes up, which is unlikely as we both seem to have done a fairly careful review already.
