### ISSUE TITLE
PyCrypto is no longer being actively maintained

### ISSUE THREAD

**Issue by nvesely** [freedomofpress/securedrop#1609]
As first noted in https://github.com/freedomofpress/securedrop/issues/204#issuecomment-272338348:

> So it's come to our attention that we need to replace PyCrypto, the progress of which is pretty much stalled (e.g., [this year-old vulnerability](https://github.com/dlitz/pycrypto/issues/173) has still not been fixed in a release, even though it's patched in master--note this one does not effect SD).... Ideally, we'd use https://github.com/pyca/pynacl, which bundles `libsodium`, as a replacement...

While as noted there are no known PyCrypto vulnerabilities that affect SD, we still should still have it in our timeline for the coming months to look into replacements.

**Comment by KwadroNaut** [comment]
We might want to add https://github.com/pyca/cryptography as well, depending on the functionality that's being replaced.

**Comment by fowlslegs** [comment]
Both would work, but libsodium offers a lot more functionality that we might not use at first, but will be available should we choose to use it later.

**Comment by redshiftzero** [comment]
Hmm, `pycryptodome` is an actively maintained drop-in replacement for the aging `PyCrypto` library, this is probably the best candidate for a quick replacement: https://github.com/Legrandin/pycryptodome

**Comment by redshiftzero** [comment]
PyCrypto has at least one vulnerability in it - [CVE-2013-7459](https://security-tracker.debian.org/tracker/CVE-2013-7459) - for posterity, the reason CVE-2013-7459 does not impact us directly is that we:

1. Do not make an attempt to use IVs in ECB mode (that wouldn't make sense and we generally don't use ECB mode).
2. Do not pass IVs directly to CTR mode (we use the IV to [generate a counter](https://github.com/dlitz/pycrypto/blob/v2.7a1/lib/Crypto/Util/Counter.py#L68)).

So we don't hit the CVE-2013-7459 overflow [on this line](https://github.com/dlitz/pycrypto/blob/v2.7a1/src/block_template.c#L226). PyCryptodome has this fixed in https://github.com/Legrandin/pycryptodome/commit/8dbe0dc3eea5c689d4f76b37b93fe216cf1f00d4.

Note that the place we are currently using this library in SecureDrop is for the implementation of the secure tempfile which encrypts submissions to a symmetric key as they stream in.

**Comment by redshiftzero** [comment]
After discussion in sprint prep, we should get #2903 in for 0.5.2, and a migration in the future to `cryptography`. The advantage of `cryptography` is that it is more commonly used than `PyCryptodome`, though it would require some refactoring of the secure tempfile implementation to use e.g. [Fernet](https://cryptography.io/en/latest/fernet/) or to directly use their implementations of the [primitives](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.modes.CTR) we use.
