### ISSUE TITLE
Harden Python package download process

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/securedrop#1617]
`pip` does not encourage use of or check Python package signatures. That doesn't mean we can't do better than just running `pip wheel` in the `build_securedrop_app_code_deb` role. Here are a few things we could do to harden the package download process:

- [ ] Check signatures on the packages that provide them (last time I checked a while back 4/19 upstream projects signed their packages).
- [x] Pin SHA256sums of packages. This is something `pip` supports enforcing via the `requirements.txt` file.
- [ ] Pin PyPi's cert. It hasn't changed in years.
- [ ] Use Tor.
- [ ] Try to reduce the number of dependencies SD uses. There are numerous packages we use that have barely if at all changed in years, and that we only use tiny snippets from.
- [ ] File issues with upstream package developers encouraging them to sign their packages.

**Comment by legoktm** [comment]
I'll bring this up as an agenda item in the next server development hangout (if we have time), my current feeling is that there's nothing actionable here besides the work being done for reproducible wheels (https://github.com/freedomofpress/securedrop/issues/5901).

Going through the list:
* Check signatures on the packages that provide them - instead of checking signatures, we're auditing the code itself through diff reviews
* Pin SHA256sums of packages - done.
* Pin PyPi's cert - dubious value IMO, SHA256sums prevent us from getting compromised packages. And we're moving in the direction of cutting pypi out of the build process by hosting our own wheels.
* Use Tor - doesn't help with hardening the package download process?
* Try to reduce the number of dependencies SD uses - a very good goal that we're slowly making progress on, but is better handled in a separate or more scoped ticket.
* File issues with upstream package developers encouraging them to sign their packages - see above, we're not using package signatures anymore.

**Comment by legoktm** [comment]
No objections in today's hangout, so closing.
