### ISSUE TITLE
Add reminder about starting the build machine

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1706]
If a person forgets to start the build VM and tries to provision the staging VMs, they get the following error:

```
failed: [app-staging] (item=securedrop-ossec-agent-2.8.2+0.3.12-amd64.deb) => {"failed": true, "item": "securedrop-ossec-agent-2.8.2+0.3.12-amd64.deb", "msg": "Unable to find '../../build/securedrop-ossec-agent-2.8.2+0.3.12-amd64.deb' in expected paths."}
failed: [mon-staging] (item=securedrop-ossec-server-2.8.2+0.3.12-amd64.deb) => {"failed": true, "item": "securedrop-ossec-server-2.8.2+0.3.12-amd64.deb", "msg": "Unable to find '../../build/securedrop-ossec-server-2.8.2+0.3.12-amd64.deb' in expected paths."}
failed: [app-staging] (item=securedrop-app-code-0.3.12-amd64.deb) => {"failed": true, "item": "securedrop-app-code-0.3.12-amd64.deb", "msg": "Unable to find '../../build/securedrop-app-code-0.3.12-amd64.deb' in expected paths."}
failed: [mon-staging] (item=ossec-server-2.8.2-amd64.deb) => {"failed": true, "item": "ossec-server-2.8.2-amd64.deb", "msg": "Unable to find '../../build/ossec-server-2.8.2-amd64.deb' in expected paths."}
failed: [app-staging] (item=ossec-agent-2.8.2-amd64.deb) => {"failed": true, "item": "ossec-agent-2.8.2-amd64.deb", "msg": "Unable to find '../../build/ossec-agent-2.8.2-amd64.deb' in expected paths."}
failed: [mon-staging] (item=securedrop-keyring-0.1.0+0.3.12-amd64.deb) => {"failed": true, "item": "securedrop-keyring-0.1.0+0.3.12-amd64.deb", "msg": "Unable to find '../../build/securedrop-keyring-0.1.0+0.3.12-amd64.deb' in expected paths."}
failed: [app-staging] (item=securedrop-keyring-0.1.0+0.3.12-amd64.deb) => {"failed": true, "item": "securedrop-keyring-0.1.0+0.3.12-amd64.deb", "msg": "Unable to find '../../build/securedrop-keyring-0.1.0+0.3.12-amd64.deb' in expected paths."}
```

An addition to the msg like "Did you forget to start the build VM? Please run `vagrant up --no-provision build` and try again" would be :100:

**Comment by conorsch** [comment]
We _did_ have this, but it broke during the switch to Ansible v2. Under Ansible v1, running the staging playbook without the build VM present shows:

>TASK: [Check for "build" machine in inventory.] ******************************* 
failed: [localhost] => {"failed": true}
msg: The "build" VM is not reachable, but is required for building the app code Debian packages on the staging machines. Run `vagrant up build`, then `vagrant provision /staging/`. Thereafter you can run `ANSIBLE_ARGS="--tags rebuild" vagrant provision /staging/` to rebuild and reinstall the application code.  

Which is indeed what we want. (Note that I had to revise the `find` module references when testing under Ansible v1, since Ansible v1 doesn't have the `find` module.)
