### ISSUE TITLE
Empty replies can be sent to a source

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1715]
# Steps to reproduce

1. Provision development VM
2. Submit some documents through the source interface.
3. Create a journalist account.
4. Click on a source.
5. Attempt to send an empty reply.

# What should happen

A flashed message should appear indicating that text must be entered in the reply field.

# What actually happens

The empty reply is uploaded.

# Comment

Whoever fixes this ideally should definitely write a functional or unit test to guard against future regressions.

**Comment by fowlslegs** [comment]
So despite my noting in https://github.com/freedomofpress/securedrop/issues/1714#issuecomment-302796470 that `textarea` supports the `minlength` attribute (well I said `maxlength`, but `minlength` is supposed to work too), the documentation I cite is the "living HTML standard." OTOH, we have TBB 6.5.2, most of the relevant code for which was likely last changed quite some time ago. Using `minlength` _did not work_ when testing in TBB stable. So since we can get near instant feedback by implementing this in the Flask app code, and can also easily create a specific warning message to flash, this is the way I'm going to do it.

**Comment by redshiftzero** [comment]
Fixed by fowlslegs in #1765
