### ISSUE TITLE
Send admin alert when multiple Sources share a filesystem ID

### ISSUE THREAD

**Issue by fowlslegs** [freedomofpress/securedrop#1760]
In `db.get_one_or_else()` we're already logging when this happens. We could parse that log and alert when the line "found multiple while..." is encountered in order to let the admin know there's a serious problem with their database they should address or have us help them address via the support portal.

```py
def get_one_or_else(query, logger, failure_method):
    try:
        return query.one()
    except MultipleResultsFound as e:
        logger.error(
            "Found multiple while executing %s when one was expected: %s" %
            (query, e, ))
        failure_method(500)
    except NoResultFound as e:
        logger.error("Found none when one was expected: %s" % (e,))
        failure_method(404)
```

**Comment by garrettr** [comment]
> when multiple sources share a filesystem ID

This is not a concern thanks to `generate_unique_codename`. Even if we didn't have `generate_unique_codename`, the probability of this event occurring is miniscule.

`get_one_or_else` is just an attempt to DRY a common pattern in our database access and error handling patterns. I think it's fine if there are some usages of `get_one_or_else` where only a subset of the exceptions that it catches are relevant. If you have strong feelings or a bright idea for how to refactor this to make it even better, go for it. Otherwise, I think this issue should be closed because it is invalid.

**Comment by fowlslegs** [comment]
I'm aware of everything you explained in your comment. I was just a little deep in https://github.com/freedomofpress/securedrop/pull/1720, and was only thinking about `get_on_or_else()` in the context of Source queries. I could expand on said past thoughts to shed more light on my reasoning for opening this one, but I'm just going to save myself the time and close it.
