### ISSUE TITLE
Submission on source interface does not produce flashed message

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1763]
# Description

A first time submission to the source interface does not produce a flashed message in the staging environment using Tor Browser.

# Steps to reproduce

1. Provision staging VMs
2. Load the source interface in Tor Browser.
3. Generate a new codename.
4. Submit a test message "blah".

# What should happen

A flashed message like this one should appear:

![screen shot 2017-05-30 at 7 17 17 pm](https://cloud.githubusercontent.com/assets/7832803/26612926/d486ed26-456c-11e7-98c0-8347600e3bb9.png)

# What actually happens

No flashed message is shown. If you refresh the page, the flashed message will then appear. Subsequent submissions will produce the flashed message. Also note that this problem does not appear in Chrome.

**Comment by garrettr** [comment]
I think this is being caused by recent-ish changes to the cache headers (e.g. #1185). If you look at the Network panel while reproducing the issue, notice how the POST gets a 302 to `/lookup`, which then uses a cached copy.

<img width="997" alt="screen shot 2017-06-02 at 2 10 03 pm" src="https://cloud.githubusercontent.com/assets/407302/26745097/e0cfe74e-479d-11e7-9d79-7f1438e8efb6.png">

**Comment by garrettr** [comment]
HTTP caching is a somewhat complex topic. Here's a good [reference](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching).

To fix this bug, we need to stop telling the browser to cache HTML responses for logged-in users; however, we should continue to cache images/stylesheets/scripts to maintain the improved user experience from #1185 (see also #1152 for background on the motivation for adding HTTP caching to the Source Interface). We may be able to do this entirely in the Apache configuration, or it may make more sense to move the cache header logic into Flask (similar to this Stack Overflow user's [approach](https://stackoverflow.com/a/37331139)).

**Comment by garrettr** [comment]
Discussed this in a meeting today. We all agreed that the Apache configuration needs to be reviewed and annotated, because:

* Some if its directives may be redundant/pointless
* There are few comments, which makes the configuration hard to audit.

A full rework should probably wait until after 0.4, since we're trying to keep changes minimal for 0.4 to minimize potential regressions. I'll file a new issue for reviewing and annotating the Apache configuration.
