### ISSUE TITLE
Bug during app install

### ISSUE THREAD

**Issue by twilliamsH** [freedomofpress/securedrop#1839]
TASK [common : make the required grub paxctl changes] **************************
failed: [app] (item=grub_pax) => {"changed": true, "cmd": ["paxctl", "-Cpm", "grub_pax"], "delta": "0:00:00.002228", "end": "2017-06-16 15:28:26.610440", "failed": true, "item": "grub_pax", "rc": 1, "start": "2017-06-16 15:28:26.608212", "stderr": "grub_pax: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [mon] (item=grub_pax) => {"changed": true, "cmd": ["paxctl", "-Cpm", "grub_pax"], "delta": "0:00:00.002452", "end": "2017-06-16 15:28:26.613128", "failed": true, "item": "grub_pax", "rc": 1, "start": "2017-06-16 15:28:26.610676", "stderr": "grub_pax: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/home/amnesia/Persistent/securedrop/install_files/ansible-base/securedrop-prod.retry

PLAY RECAP *********************************************************************
app                        : ok=14   changed=0    unreachable=0    failed=1   
mon                        : ok=14   changed=0    unreachable=0    failed=1   

Following the instructions on https://docs.securedrop.org/en/stable/install.html I run into this error. I have the newest version of tails and I am following the guide exactly. Saw a post about perhaps being wrong version of Ansible but I have yet to find how to install the correct one. Tried apt-get install -t testing ansible with no luck. If I do need to install a specific version of ansible can you please list the instructions? I attempted everything I found in this thread with no success https://github.com/freedomofpress/securedrop/issues/1146

**Comment by conorsch** [comment]
@twilliamsH The current stable release of SecureDrop is 0.3.12, and requires Tails 2. Ansible should be installed from the apt repos (`sudo apt install ansible`). The upcoming 0.4 release of SecureDrop will mandate use of Tails 3, and include tooling to make a persistent virtualenv for storing Ansible and other helpers, as described in #1146 .

**Comment by twilliamsH** [comment]
@conorsch so I need to downgrade back to Tails 2 and follow the directions again?

**Comment by conorsch** [comment]
@twilliamsH You're in a difficult position regarding versions and release dates. As of today, Tails 2 in combination with SecureDrop 0.3.12 is the correct approach. If you can delay installation a few weeks until we release SecureDrop 0.4 (shooting for mid-July), you'd save a lot of time during the upgrade, since you won't have to upgrade all your Tails sticks 2 -> 3, which is a manual process.

**Comment by twilliamsH** [comment]
@conorsch unfortunately I cannot wait. I have downgraded and continued the process and found a new problem that I did not have in Tails 3 When I run sudo ./install.sh instead of opening the prompt to enter HidServAuth info, I get mkdir: cannot create directory '/live/persistence/TailsData_unlocked/dotfiles': Permission denied. Any thoughts on what to do here? As I said, that worked when I attempted it in Tails 3

**Comment by conorsch** [comment]
@twilliamsH Check the persistence options in the "Configure Tails Persistence Volume" and confirm that you have enabled dotfiles persistence. As [stated in the docs](https://docs.securedrop.org/en/stable/set_up_tails.html#enable-persistent-storage):

> We recommend that you enable **all** features.

That recommendation is simply to ease the burden on the Admin with micromanaging types of persistence per Tails device. By enabling all of them, you can be sure you've got the necessary ones checked, as well. Make sure you reboot after editing the persistence settings, otherwise they won't have taken effect yet.

I'm going to close this issue since the original problem has been resolved. Feel free to open future issues if you run into problems, @twilliamsH.
