### ISSUE TITLE
rework, cleanup and merge i18n past efforts

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1851]
i18n has seen good work from various people (see https://github.com/freedomofpress/securedrop/pull/753 for instance). It has also been a source of disconnect between the community and the SecureDrop team. I believe the past PRs should be cleaned up and merged. It is worth setting this as a goal for 0.4.1 and make it a priority. Resolving this tension would not only add a frequently requested feature to SecureDrop. It would also show a positive sign to developers willing to contribute to SecureDrop. The current state of the i18n pull requests has the opposite effect.

It seems the only argument against adding i18n support to SecureDrop is that it cannot be officially supported by the FPF. This is ok: the FPF does not need to support every features of SecureDrop. It is common for an organisation offering services for a given Free Software to only support a subset of its functionalities.

**Comment by heartsucker** [comment]
Sup, y'all. Coming out of hiding to say that if this is something that FPF says they're definitely going to do, I'd like to help. Probably start over and not even bother trying to rebase that old stuff I did. I know a few people over here that have offered translations in various languages.

**Comment by dachary** [comment]
I'm also willing to work with you to make that happen.

**Comment by fowlslegs** [comment]
We're going to have to wait until next week to discuss this. We have put some more consideration into making this a more near-term priority. I definitely can't speak on behalf of the team though, so you'll have to just wait. I can say that chances it will happen in 0.4.1 are very slim, but as far as something we start on before end-of-year, maybe.

**Comment by dachary** [comment]
I realize the original description suggests that the SecureDrop team does all the work, but I'm actually proposing something that is less of a burden. The commitment from the SecureDrop team would be to

* set i18n as a goal for 0.4.1
* diligently review pull requests implementing i18n

This is significantly less work than actually implementing the changes but it still requires some commitment.

**Comment by dachary** [comment]
@redshiftzero do you have an opinion on this issue ?

**Comment by redshiftzero** [comment]
Thanks for making this issue @dachary - I largely agree with what’s been stated here. Internationalization is an oft requested feature that we really do need to add to SecureDrop. It’s also true that it’s been a point of disconnect between the wider community and the SecureDrop engineering team. 

If (ideally separate) PRs come in implementing some of the steps toward internationalization of the source interface, *after the release of 0.4*, we will review and merge them. Specifically:

* the source interface will need to render well with both right-to-left and left-to-right text (#1884)
* #1357 will also need to be implemented due to our use of fixed pixel size elements
* finally Flask-Babel will need to be integrated (reusing commits from the recently closed PRs where possible)
* a glossary for translators will need to be written and added to the docs

Note that we are won’t be directly merging translations as we are going to try to have all the translations come in through Transifex, and then bundle them from there into SecureDrop releases. 

Our current thinking is that there are some pressing cleanup issues that will need to take priority from the internal team for the 0.4.1 release. We’re advocating a conservative goal such that we can hit our goals and keep a frequent release schedule for the health of the project. The upcoming release of 0.4 (largely a cleanup release) is establishing the groundwork for us to do that.

**Comment by dachary** [comment]
I like the idea of paving the way to translation, using small pull requests for easier review. We can start a branch including a series of independent commits right now so they can be submitted as individual pull requests, one at a time, right after 0.4 is released.

I'm however opposed to using transifex because it is a service based on proprietary software. Alternatives such as https://weblate.org/ seem good enough and are Free Software based.

**Comment by heartsucker** [comment]
@redshiftzero I think one thin we could do would be to integrate Flask-Bable _without translations_ in one PR to ensure that everything else still works. SD/FPF could set up a target language to roll the change out to, preferably with a real org who wants some language implemented. Also, a policy about copy changes would have to be established so that translations could be kept up to date. I also think that the codebase has drifted enough to not try to cherry pick but maybe just copy/paste bits and pieces.

**Comment by redshiftzero** [comment]
Thanks for sharing Weblate @dachary, I just played around with it and it does look quite nice. I'm certainly open to other platforms than Transifex, and I would like to support FOSS where possible. One of the main concerns we had is how to get peer review of translations, but it looks like [Weblate supports this](https://docs.weblate.org/en/latest/faq.html#how-do-i-review-others-translations). 

>  integrate Flask-Bable without translations in one PR to ensure that everything else still works

:100:, this would make this easiest for us to review and integrate. Once Flask-Babel is integrated we can start testing out translation platforms. Also, given the amount of German speakers we have (:eyes:) that are interested in SecureDrop, German seems like a good first choice - and the long words will also be a good test for our CSS.

**Comment by dachary** [comment]
Someone also mentionned http://pootle.translatehouse.org/

**Comment by dachary** [comment]
I'll be working on preparing the ground for i18n this week-end. A forum topic was open for this at https://forum.securedrop.club/c/translations

**Comment by dachary** [comment]
The [rework & cleanup part is complete](https://github.com/dachary/securedrop/commits/wip-i18n-base) and it is going to be merged, [one commit after the other](https://github.com/freedomofpress/securedrop/pull/1924). In the meantime french translation is complete, german translation is half way done and more will come. This is [happening in parallel](http://weblate.securedrop.club/) and is mostly independent from the i18n of the code/templates.

I am closing this issue since it is more about discussing the issue than actually scheduling the work or reporting problems. Discussions now happen in the [translation category](https://forum.securedrop.club/t/about-the-translations-category) of the SecureDrop forum.
