### ISSUE TITLE
journalist: can login with the current token despite error message saying otherwise

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1887]
# Bug

## Description

When the journalist makes a mistake entering the password and no token, the message asks that they wait for the next token. However, if they try again and use the correct password and the right token immediately after, it works.

When the journalist makes a mistake entering the password and uses the right token, the message asks that they wait for the next token. And if they try with the right password and the right token it will issue exactly the same message because, not because of the wrong password but because the right token was used twice.

## Steps to Reproduce

* Connect to the journalist login page
* Using an existing journalist account name
* Enter the wrong password and no token
* Try to login and see the error message asking to wait for the next token
* Do not wait for the next token
* Enter the right password and the current token

## Expected Behavior

* Unable to login because the token is not the next token

## Actual Behavior

* Login is successful 

## Comments

This is inconsistent and slightly confusing but I'm not sure this can be fixed. And it's probably not a significant user experience problem.

**Comment by fowlslegs** [comment]
It can definitely be fixed!

Basically, what should happen is the current TOTP time code [1]  should be saved each time there's an attempted login for a particular user account. Right now the token is saved, not the time code, and it's only saved if the password is correct, which explains this bug.

When a user logs in (unless it's their first login ever) the token they submit should be compared against the three tokens that correspond to the time codes of the one saved from the most recent login attempt as well as the preceding and proceeding time codes. If any of the comparisons match, login should fail with a flashed message that more accurately informs them about waiting to login again (e.g.,"Wait approximately 44 seconds until your TOTP token rolls over..."). And of course in this implementation it will actually be true they can't login for whatever amount of time. This strategy is adapted from https://github.com/google/google-authenticator-libpam.

The reason for rejecting login attempts when the token matches one corresponding to the preceding and proceeding time codes of the time code saved from the last login attempt is that these are the three tokens a malicious actor is most likely to have observed if they were shoulder-surfing/CCTVing/etc. a journalist when they opened up FreeOTP/ Google Authenticator. It provides a slight inconvenience if a journalist makes a typo, but we believe this to be a necessary evil in order to maintain the strictest reasonable security posture we can for the application.

[1] The current time code is not the token nor is it dependent on a particular secret; it is a integer measurement of time equal to the number of 30 second intervals since the unix epoch. I should be precise and note that while 30 second intervals are most standard, one could choose to use a different amount for token rollover.

**Comment by fowlslegs** [comment]
@redshiftzero Thoughts on the above and if/ when this solution or another one should be implemented (in terms of release schedule)?

**Comment by dachary** [comment]
I was not able to repeat the above, presumably because session expiration code was reworked. Happily closing !
