### ISSUE TITLE
Lint HTML

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1897]
To catch issues like the [missing](https://github.com/freedomofpress/securedrop/pull/1829/commits/05e5ddb05d96f2a107410d1c6e5fa63dcf286d72#r122849978) `</a>` tag found in #1829, we should find a good linter for HTML (e.g. [html-linter](https://pypi.python.org/pypi/html-linter/)), and add it to CI.

**Comment by fowlslegs** [comment]
I wonder how difficult this will be to work out considering our heavy use of Jinja2 templates. Linters certainly won't work on the templates themselves, but maybe we can render some by passing in some different values to them, and then lint the resulting HTML? I couldn't really find any resources on this, but I also have not spent too much time looking into it.

**Comment by dachary** [comment]
We could have tests that save the HTML page for every possible page state. For instance test_journalist.py test test_admin_resets_user_hotp would save resp instead of discarding it. The linter could then run through all these static HTML pages. A human being could also browse them from time to time to catch visual problems such as https://github.com/freedomofpress/securedrop/issues/1895. And they could also be captured via http://browsershots.org/ or something similar for cross-browser compatibility.

**Comment by dachary** [comment]
For the record a [series of commit take screenshots](https://github.com/dachary/securedrop/commit/96dc6140e681184222d92a50abc91ce51cfba8b6) of every page state (source / journalist) so translators can verify how they look without complicated and error prone navigation of the interfaces. The same code can be used to store the HTML of each page which can then be linted trivially with tidy or something equivalent.

**Comment by redshiftzero** [comment]
Reopening: #2081 did _some_ HTML cleanup but as @dachary [points out in a comment on #2081](https://github.com/freedomofpress/securedrop/pull/2081#issuecomment-320502936), the changes in that PR do not catch missing `</a>` tags and as such we should add an HTML validator to CI. [html5validator](https://github.com/svenkreiss/html5validator) may be a good one (needs further testing)...

**Comment by prateekj117** [comment]
@eloquence I can take a look into this.

**Comment by cfm** [comment]
@prateekj117, just wanted to let you know that I have some time at the moment to pick up this task in connection with other CI-related work.  :-)
