### ISSUE TITLE
Python dependency versions differ on development between local VMs and Travis

### ISSUE THREAD

**Issue by nvesely** [freedomofpress/securedrop#1918]
# Bug

## Description

In both environments, `pip` is invoked sequentially on multiple requirements files. When a particular dependency is present in more than one requirements file, the version installed will be from whichever requirements file `pip` is is first invoked on. In the local VM context, `pip` is invoked via Ansible in the `development` Ansible role first on `securedrop-requirements.txt` and then on `test-requirements.txt`. In Travis `pip` is first invoked on `testinfra/requirements.txt`, and then the `development` Ansible role is run [1].

In #1829 I added the version of `requests` in `test-requirements.txt` to the `test_development_pip_dependencies()` testinfra test, which caused Travis to fail because an older version is present in `testinfra/requirements.txt` (which, again, `pip` is invoked on first in the Travis context). I'm not sure why this and a number of the other `test-requirements.txt` dependencies are missing from the `test_development_pip_dependencies()` testinfra test, but I believe there may be even more conflicts.

I have not taken the time to check whether or not there is overlap between `testinfra/requirements.txt` and `securedrop-requirements.txt`, but if that is the case, or were to become the case in the future (it's certainly possible with how things now work) that would arguably be an even worse situation.

[1] In Travis `develop-requirements.txt` is also installed, but after the app code and testinfra tests are run, so we can mostly ignore this for the purpose of this discussion.

## Comments

I'm still brainstorming ideas on how to solve this problem in a way that is maintainable, verifiable (i.e., our tests should conclusive prove things are as they should be), easy to follow, and would keep the diff as small as possible. Please chime in if you have ideas to this extent; I intend to follow up myself in the near-term.

**Comment by conorsch** [comment]
The sane approach here is to stop reusing the Travis environment as representing multiple incompatible machine roles:

* development VM
* Ansible controller
* app-test machine
* docs-lint machine

Those are separate use cases, and shoving the conflicting dependencies into the same box is bound to create problems. Near-term we could resort to virtualenvs, which should help, but seems overwrought as a temporary solution. 

Medium-term we should focus on creating isolated containers for the various testing and linting suites we want to run, so that we do not pollute the "development VM" or "Ansible controller" machine roles with logic specifically for e.g. docs-linting.

**Comment by redshiftzero** [comment]
Resolved during requirements file cleanup (`testinfra/requirements.txt` is deprecated).
