### ISSUE TITLE
Update HTTPS config on source interface

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1929]
In #1605 we recently added optional HTTPS configuration on the source interface :tada:. However, the ciphersuites allowed (e.g. [3DES](https://blog.cryptographyengineering.com/2016/08/24/attack-of-week-64-bit-ciphers-in-tls/) is allowed), should be updated:

```
SSLProtocol all -SSLv2 -SSLv3
SSLHonorCipherOrder on
SSLCompression off
SSLCipherSuite EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5
```

We strongly recommend all sources use only the latest version of Tor Browser and thus we don't need to preserve backwards compatibility for a range of different old browsers, so we can use [these modern settings](https://wiki.mozilla.org/Security/Server_Side_TLS).

**Comment by conorsch** [comment]
Thanks for opening, @redshiftzero. I agree, we should definitely update the cipher suite as much as possible. Given all the manual QA with Tor Browser required for the 0.4 release, I'm open to adding these fixes immediately. One of the shortcomings of the current Ansible config process is that we can't update the SSL config via unattended upgrades—an Admin must run the Ansible scripts to change these settings.

**Comment by redshiftzero** [comment]
I think it makes sense to get this into 0.4 in that case.

**Comment by fowlslegs** [comment]
Just wanted to add that we do not want to support OCSP stapling because it requires the client browser to contact the CA the certificate was issued from to confirm validity. While done over Tor, there are still obviously reasons to avoid this, foremost that it lets a CA know exactly when an instance is visited.

HSTS, on the other hand, we may wish to support, especially with intention of getting as many instances as possible on the HSTS preload list (the only way to really take advantage of HSTS given the amnesiac nature of the Tor Browser Bundle).

**Comment by garrettr** [comment]
> Just wanted to add that we do not want to support OCSP stapling because it requires the client browser to contact the CA the certificate was issued from to confirm validity. While done over Tor, there are still obviously reasons to avoid this, foremost that it lets a CA know exactly when an instance is visited.

@fowlslegs You are confusing OCSP and OCSP stapling. The entire point of OCSP stapling is to avoid leaking user's browsing history to CA's.

**Comment by fowlslegs** [comment]
My bad--thanks for the correction. OCSP stapling does in fact address the privacy issue described above introduced in the original OCSP implementation.
