### ISSUE TITLE
Apt install output from `securedrop-admin setup` is poorly formatted

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1947]
# Bug

## Description

Running `securedrop-admin setup` outputs some hard-to-read formatting during apt package installation. Here's a screenshot:

![tails3-securedrop-admin-bad-formatting](https://user-images.githubusercontent.com/657862/27975632-f0ad61b0-6317-11e7-8f3b-25c7efdb993b.png)

## Steps to Reproduce

1. Boot into Tails 3 environment.
2. Run `./securedrop-admin setup` from the root of the securedrop repo.
3. Observe hard-to-read output

## Expected Behavior
Apt installation info is output in a readable fashion, consistent with the output from `apt install <package>` run interactively in a terminal window.

## Actual Behavior
Apt installation tasks include extra whitespace that makes the output hard to read, and creates a sense of unease that the script may not be working correctly.

## Comments
The extra whitespace was likely introduced in #1885. See @dachary's suggestion in https://github.com/freedomofpress/securedrop/pull/1885#issuecomment-311491090 about an alternative run-command wrapper that may resolve the formatting woes.

**Comment by garrettr** [comment]
The "hard-to-read output" is caused by `apt-get` calling out to `dpkg`, which mistakenly believes it is writing to a TTY and attempts to render a progress indicator that uses `\r` to repeatedly rewrite a status line. Since dpkg's stdout is not actually a TTY, but rather is being intercepted and re-printed by the `run_command` wrapper, the desired effect is not achieved and the resulting output appears garbled and difficult to read.

**Comment by conorsch** [comment]
Resolved by #1958.
