### ISSUE TITLE
docs: 0.4 flag for reply screenshot is incorrect

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1955]
Please use the appropriate part of the template: "Bug" or "Feature Request"

# Bug

## Description

The screenshot at https://securedrop.readthedocs.io/en/latest/journalist.html#flag-for-reply is incorrect

## Steps to Reproduce

Visit https://securedrop.readthedocs.io/en/latest/journalist.html#flag-for-reply and look at the screenshot

## Expected Behavior

![no_key](https://user-images.githubusercontent.com/433594/28023368-0cc12454-658e-11e7-8aad-aef5aed321b5.png)

## Actual Behavior

![document4](https://user-images.githubusercontent.com/433594/28023298-c91f9956-658d-11e7-8caa-f2882210ab90.png)

## Comments

Re-do the screenshot with shadows and a Mac so it looks like the others.

**Comment by conorsch** [comment]
> Re-do the screenshot with shadows and a Mac so it looks like the others.

Actually we _don't_ want the screenshots to use macOS—see #1544, which includes bullet points for updating the screenshots to use Tails. We've been waiting to regenerate screenshots until the UI for 0.4 stabilizes, and we're approaching that point now.

**Comment by conorsch** [comment]
This is a major discrepancy in the docs, so I'm marking as QA for 0.4 and trying to resolve as part of the docs refresh described in #1544.

**Comment by conorsch** [comment]
Looks like the confusion here is the conditional language: 

> If the server experiences a large number of new sources signing up at once and is overloaded with submissions, you will need to flag sources for reply before you can communicate with them.

If-and-only-if the server has decided to start flagging sources, _then_ the special "flag for reply" div will be displayed:

![document-flag-source-for-reply-button](https://user-images.githubusercontent.com/657862/28440313-8d70e85e-6d5a-11e7-9f43-37e34ec13e5e.png)

However I don't see the flag-for-reply button in the stable or latest journalist interface guide write now—which seems to be what this issue is pointing out. Will update with explicit (and Tails-based) screenshots during work toward #1544.

**Comment by conorsch** [comment]
Resolved via #2011.
