### ISSUE TITLE
Mitigate confusion on source interface "screen-saver"

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#1975]
# Feature request

## Description

Part of a commit that went in to address feature request #447 introduced a fade-out to the source interface after a minute of elapsed idle time. It's definitely a cool feature that I think we should keep, but it's a little confusing to users without any type of messaging. There should be some minimal text on-top of the white screen explaining succinctly to the user that everything is okay.

💡 Bonus "semi-serious but joking if I'm pressed about why we need it" feature --- it would be cool to have a [boss-key](https://en.wikipedia.org/wiki/Boss_key) to bring up a fake spreadsheet page if someone is in a public location and wants to suddenly hide what they are doing.

## User Stories

As a user, when I step away from the source interface after a minute of idle time - I'd like to not freak out and think I lost any work in progress when I return to a blank page :)

Example:

![selection_027](https://user-images.githubusercontent.com/1727935/28180848-6f6403a4-67d4-11e7-9d78-c12be94ed111.png)

**Comment by redshiftzero** [comment]
More confusion about this feature was reported. Users think that because the screen went blank that someone how their session is gone or lost. I'm curious what you think about this @ei8fdb @belenbarrospena.

**Comment by belenbarrospena** [comment]
I don't have much context, so please take my comments with a pinch of salt. 

I think users' confusion is understandable: SecureDrop is not giving them enough feedback as to what's happening. As the description very well observes: we need some explanation somewhere :)

I quite like the idea of displaying something fake or funny. I remember Basecamp used to show Maru videos in their empty pages. They always made me laugh. We could also provide a set of "obfuscation content" options users could choose from. Making the setting configurable might mean users recognise the content and know what's happening. 

We might also consider hiding the page title. From the screenshot, although you cannot see what users are doing, you do know they are using SecureDrop.

One more question: what does the source needs to do in order to see the screen content again?

**Comment by dachary** [comment]
> what does the source needs to do in order to see the screen content again?

Hovering or typing in the page will show the content again.

**Comment by belenbarrospena** [comment]
great. That means we might get away with not even providing instructions as to how to bring back the content :)

I guess next step is providing a mock up / prototype of how we think the page could look like. 

Before building it, it would be good to test it with users though, since I've never designed a feature like this before. Remote, unmoderated user testing might do for something like this.
