### ISSUE TITLE
Automate generation of screenshots for user guides

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2016]
Currently every time we change the SecureDrop interface, we need to generate a round of screenshots pre-release to update our Source, Journalist, and Administrator guides. This is a time consuming and manual process. Fortunately, a contributor at a hackathon recently wrote a nice PR to take automated screenshots for the functional tests: #1954. We _could_ adapt this to automate the taking of screenshots pre-release to auto-update the documentation. Our functional tests mostly correspond to the steps written out in the user guides anyway, so this should not be too challenging.

**Comment by dachary** [comment]
A commit in the i18n uses functional test functions for the purpose of [generating screenshots for every state of the journalist / state interface](https://github.com/freedomofpress/securedrop/pull/1983/commits/00fec107522a939d7012a0c338cd4870ef0629e6). It is useful for:

* uploading screenshots and associate them to strings to be translated ( see http://weblate.securedrop.club/translate/securedrop/securedrop/da/?type=all for instance )
* generating screenshots to verify how the translated strings actually look in a given language

Unless there are specific needs for the screenshots included in the user guides, they could be used.

This commit is going to be proposed as part of the i18n work scheduled for 0.4.1, but it will happen late because it depends on a dozen other commits.

**Comment by redshiftzero** [comment]
Merge of #2141 will get us 90% of the way there on this. We will just need to: 

* Slightly modify the size of the window:

![source-index_javascript](https://user-images.githubusercontent.com/7832803/29543496-6ba99806-8696-11e7-94f0-f3b1b202a6d7.png)

* Change the name of the files in the guides in the documentation to be consistent with the names of the screenshots in #2141 

* Optionally, create a makefile target (`make update-guides`) to run the `page-layout` tests and copy over the screenshots into the guides
