### ISSUE TITLE
Add backup and restore options to securedrop-admin

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2023]
## Description

Instead of admins directly running Ansible playbooks for backup and restore, which can be a bit confusing for the uninitiated, add command line options to the `securedrop-admin` script to perform the backup and restore to make this task a bit more user friendly, e.g. `securedrop-admin backup` and `securedrop-admin restore <restore_file>`

## User Stories

As an administrator, I want to have a straightforward tool for backups so I will frequently backup my SecureDrop instance. 

As an administrator, I want to have a straightforward tool for restoring backups so I can easily restore my SecureDrop instance in case of failure.

**Comment by conorsch** [comment]
I'm going to take a stab at this quickly, since having a solid wrapper around the backup and restore functionality would vastly simplify testing of #2026. Right now we're instructing Admins to manually activate the virtualenv and run a complicated list of command-line flags that invite mistakes. Will timebox the effort—OK if it doesn't make it into 0.4, but will try.

**Comment by conorsch** [comment]
Functionality is good, for both backup and restore. Updating docs, then will toss up a PR.

**Comment by redshiftzero** [comment]
Fixed by #2027
