### ISSUE TITLE
Be clear on the source interface that SecureDrop accepts files of any type

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2089]
UX feedback from https://forum.securedrop.club/t/documents-or-files/67:

> Both in the Source interface and in the Journalist interface the platform seem to mix the terms documents and files.
>
> In the welcome screen for new sources with "Submit documents for the first time". That might be OK as SecureDrop is a platform for submitting documents and tips to organizations hosting such a system. Though it might also be confusing if the source does not have actual documents and have not read info on a landing page about the possibility of only submitting a message.
>
> Further on in the "Submit Materials" page of the Source interface the term files are used. Though not with any clarification that the source could submit any file they want (regardless of format).
>
> In the Journalist interface the term document(s) are used. So the count of submitted info from sources are x messages and x documents. Though the counter for documents is really a counter of submitted files – both files of typical document format (pdf, docx etc) and any other file.
>
> It would be good to inform potential sources that the platform is for submitting documents and relevant info for the journalistic organization, and then letting them know we can accept almost any format. Not much need to change here.
>
> For the Journalist interface the term file is the most correct one, as the system does not know what kind of files have been submitted.

**Comment by edenemmanuel** [comment]
Some ideas to consider:

- On the first page of the Source Interface, where it says "Submit documents for the first time", how about "Submit documents _or messages_ for the first time". Otherwise "Submit for the first time" (omitting the word "documents")
- On the "Submit Materials" screen, we could title it "Submit Materials or Messages"
- On the "Submit Materials" screen, replace sentence "You can send a file, a message, or both." with "You can submit any kind of file (up to 500 MB), a message, or both."

**Comment by dachary** [comment]
> Submit for the first time

👍 My vote is on this one.
