### ISSUE TITLE
SD post-install - journalist workstation docs elaborate need for setup

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2093]
# Feature request

## Description

After installing secure-drop, the documentation for the [journalist work-station section](https://docs.securedrop.org/en/stable/onboarding.html#set-up-automatic-access-to-the-journalist-interface) is missing the `./securedrop-admin setup` step. This is required because the `tailsconfig` task is fairly new and requires ansible.

I actually see two possible (non exclusive) solutions here:
* Update the documentation
* Add a command - something like `journo_tails_helper` - which will `rsync` off the appropriate files to the a second mounted journalist tails stick.

## User Stories

As an admin, I would like documentation and tools to assist in the manual process of creation of journalist workstation sticks.

**Comment by conorsch** [comment]
We definitely need to improve the workflow for creating Journalist Workstations, and the docs along with. Related issues:

* #1176
* #1177 
* #1699
* #1742 

A subcommand to the securedrop-admin script is definitely the way to go here. Jotted down notes on the workflow in this gist: https://gist.github.com/conorsch/19681765f2e64b916db7473df062e963 which provides a decent baseline for scripting the creation tasks. We should be able to go a step further, however, and place all of the necessary persistence settings into `/media/amnesia/TailsData/` so that on next boot, the Journalist Workstation has desktop icons and ATHS credentials added to its torrc. 

Doing this well will require extensive QA, so we should prioritize getting Tails into CI for full testing. That's semi-related to #1767, but perhaps warrants a separate issue.

**Comment by eloquence** [comment]
The docs issue has long since been fixed; closing in favor of #5297 (and potential transition to the SecureDrop Workstation).
