### ISSUE TITLE
Retry SMTP relay and SASL domain verification tasks

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2099]
## Description

The "Validate SASL domain" and "Validate SMTP relay" tasks (in `validate_ossec_info.yml` in the `validate` role) timeout pretty often, so let's either increase the timeout or retry them.

**Comment by conorsch** [comment]
Working on this now. Two quick thoughts on implementation:

* We'll need to stop using `assert` on the lookups because then we can't use `retries` effectively. If we use `command`, then we're OK.
* Consider using `nslookup` rather than `host`, which itself has a `retry=<n>` flag.

@redshiftzero Can you run `nslookup -version` for me and share the results?

**Comment by redshiftzero** [comment]
FYI I don't have a version argument on my `nslookup`:

```
$ nslookup -version
*** Invalid option: version
```

but the `retry=number` option is present.
