### ISSUE TITLE
./securedrop-admin tailsconfig fails if parent not named "securedrop" 

### ISSUE THREAD

**Issue by ryantate** [freedomofpress/securedrop#2114]
# Bug

## Description

Running `tailsconfig` on a workstation Tails fails unless the directory has a particular name. This doesn't seem to be documented.

## Steps to Reproduce

Place copy of securedrop repo in `~/Persistent` of a properly-configured (dotfiles etc) Tails 3.1 instance running with an admin password enabled. Ensure repo is in dir named `securedrop-develop`, as it is named by default if you downloaded a zip file of the repo from github and unzipped it (not the recommended approach, more below). Copy your working `app-journalist-aths` and `app-source-ths` into `securedrop-develop/install_files/ansible-base`. `cd` into the repo dir and run `./securedrop-admin setup` and then `./securedrop-admin tailsconfig`. Enter admin password as prompted.

## Expected Behavior

Install works, just as it would if the dir were named "securedrop".

## Actual Behavior

 Install fails, see 
[securedrop-install-error.txt](https://github.com/freedomofpress/securedrop/files/1226552/securedrop-install-error.txt). I tried this twice with each directory name and the exact same config files and steps to ensure I wasn't borking things with anything other than the dir name. Always worked in `~/Persistent/securedrop` and failed in `~/Persistent/securedrop-develop`.

The use of a hardwired dir name seems to emerge in the session like so
```
TASK [tails-config : Migrate site-specific configuration to new location.] *****
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["cp", "/home/amnesia/Persistent/securedrop/install_files/ansible-base/prod-specific.yml", "/home/amnesia/Persistent/securedrop/install_files/ansible-base/group_vars/all/site-specific"], "delta": "0:00:00.002211", "end": "2017-08-15 21:20:57.049969", "failed": true, "rc": 1, "start": "2017-08-15 21:20:57.047758", "stderr": "cp: cannot stat '/home/amnesia/Persistent/securedrop/install_files/ansible-base/prod-specific.yml': No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
```

## Comments

People shouldn't be downloading the zip file, they should be using the git install, so they can use the inbuilt gpg verification and check out a particular tag.  If they do that, and don't rename anything, this won't be an issue. I ultimately did this.

That said, it's never explicitly documented that the dir must be named `securedrop`. That should probably be stated explicitly here:

https://docs.securedrop.org/en/stable/set_up_admin_tails.html#download-the-securedrop-repository

And/or here:

https://docs.securedrop.org/en/stable/onboarding.html

OR the code should be fixed to not depend on a particular dir name. IMO.

**Comment by conorsch** [comment]
Completely agree on the documentation updates, we should indeed state the requirement explicitly. The new (as of 0.4) validation logic built in to the `securedrop-admin` script is intended to standardize the Admin Workstation environment to what's established in the documentation.

Doing so allows us to point to specific paths on disk with explicit full paths, rather than falling back to more ambiguous statements such as "Now `cd` into the git repo that you chose to save SecureDrop too...". Most commonly these types of questions are asked in support requests, but they're also clearly applicable to the project documentation.

> People shouldn't be downloading the zip file, they should be using the git install, so they can use the inbuilt gpg verification and check out a particular tag. 

Well put. Given the threat model guiding development and deployment of SecureDrop, skipping the GPG verification task for the git repo is simply not an option.
