### ISSUE TITLE
A bug in unattended upgrades can potentially break all SecureDrop instances simultaneously

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop#2146]
# Bug

## Description

When a bug is introduced by an unattended upgrade, the SecureDrop app may shutdown and become unavailable. Since all SecureDrop instance upgrade the same day, they all go down at the same time.

## Steps to Reproduce

* Add foobar at the beginning of source.py
* vagrant provision build
* update apt.freedom.press with the bugous packages
* see all SecureDrop instance go down the next day

## Expected Behavior

* A few instance go down and report downtime on https://support.freedom.press
* The packages are rebuilt and re-uploaded within 24h
* The other SecureDrop instances skip the bugous upgrade and do not suffer a downtime
* The broken SecureDrop instances come back up after upgrading to the packages containing the fix

## Actual Behavior

* All instances go down and report downtime on https://support.freedom.press
* The packages are rebuilt and re-uploaded within 24h
* The broken SecureDrop instances come back up after upgrading to the packages containing the fix

**Comment by dachary** [comment]
If it is acceptable that an unattended upgrade happens X days after the upgrade is planned, it can be scheduled every X days instead of daily. The first day of the cycle can be picked with hash(securedropurl) % X

**Comment by legoktm** [comment]
This is definitely a risk with using unattended upgrades, as a bad upgrade can take stuff down. Most (all?) SDs are very homogeneous so it's likely that all will go down at the same time.

Since this was filed we've taken steps to mitigate the risk of this, specifically with moving Tor to a manual update cycle after we've manually tested it. We're also working on moving the kernel to its own update cycle (#6328), which will reduce the need for unnecessary SecureDrop release hotfixes.

The remaining risk of a bad package upgrade has to be balanced with the speed of how fast we want security updates to be applied. I think our current risk posture is a good balance between getting updates out quickly.
