### ISSUE TITLE
Pip requirements - clarify docs and centralize txt locations

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2175]
# Bug

## Description
There is confusion between the team, what our docs indicate, and what the scripts run in production on what ansible version we are pegging to. This is easy to understand because we currently have 5 requirements files:

* ./testinfra/requirements.txt
* ./securedrop/requirements/test-requirements.txt
* ./securedrop/requirements/securedrop-requirements.txt
* ./securedrop/requirements/develop-requirements.txt
* ./install_files/ansible-base/requirements.txt

## Steps to Reproduce

* Go through the documentation to set up a local environment, `https://docs.securedrop.org/en/stable/development/getting_started.html` - you'll install ansible `2.2.1`
* Go through CI -- runs on ansible `2.2.3.0`
* Run a prod installs -- ansible `2.2.3.0`

## Expected Behavior

we should have a max of three requirements files:
* one for usage INSIDE the dev box, 
* one for usage to perform deployments + testing 
* one for usage in prod 

With script breakage if your ansible version doesnt match (see #2166 ) and guard-rails to help developer set up their virtualenv (thinking a make command).

**Comment by conorsch** [comment]
I'm going to take a crack at this. The recent changes in #2462 didn't work for me locally, since I install the `develop-requirements.txt` for local development, not the confusingly duplicated `testinfra/requirements.txt`. We should pass multiple `.in` files to `pip-compile` and have it output separate files for the different environments.

**Comment by conorsch** [comment]
Shucks, we can't use the `--generate-hashes` on all our requirements files, because the version of pip installed on the dev VM is very old: 1.5.4, versus 1.8 required for understanding the checksum pinning. 

To date we've only used the pinning on the Admin Workstation requirements files to pull in Ansible and its dependencies, since we don't have GPG signature validation via the git repo tag, nor via apt updates (since we install Ansible via pip in Tails).
