### ISSUE TITLE
Remove /usr/games and /usr/local/games

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2177]
# Feature request

## Description

`/usr/games` and `/usr/local/games` should not be on the path, and the files should not be on the app/mon servers. These is absolutely nothing good that can come of this.

Note: These are present in Ubuntu 14.04 by default, and there is nothing in ansbile that explicitly removes them.

**Comment by conorsch** [comment]
The directory paths `/usr/games` and `/usr/local/games` are added via the `base-files` package in Ubuntu Trusty, and that's a package we definitely _don't_ want to remove, since it configures critical system paths (see `dpkg -L base-files | sort` for details). Furthermore, the directories are empty:

```
$ find /usr/games /usr/local/games -mindepth 1 | wc -l
0
```

The postinst scripts for `base-files` ensure that `/usr/local/games` exists, and the package contents include `/usr/games`. As such, any upgrade to the package will recreate these directories even if we remove them. Therefore I'm against any special customization here, since it would be rendered moot by the unattended-upgrades strategy. 

The goal for reducing unnecessary dependences is a good one! At present, I suspect we'd do better to investigate containerization more heavily in order to achieve a smaller application footprint for all services in the SecureDrop architecture.

**Comment by redshiftzero** [comment]
Good thought @heartsucker, but given that these directories are empty, I think we can close this. Thanks for investigating @conorsch.
