### ISSUE TITLE
Tails/SecureDrop is unpacking excel (xlsx) files 

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2188]
# Bug

## Description

When a journalist attempts to decrypt a modern excel format (`.xlsx`) under Tails (`3.0.1`+) from a SecureDrop (`0.4.2`) instance the file unpacks in a way that is unreadable. More specifically, it appears that Tails is unpacking the xlsx file into a new directory - which is a confusing experience for a journalist trying to read a source.

## Steps to Reproduce

* Generate an xlsx file (you can do this from libreoffice, just make sure you save-as and select `xlsx` )
![image](https://user-images.githubusercontent.com/1727935/29677142-335bba22-88c8-11e7-894d-5c378063b58a.png)
* Upload to a securedrop 0.4.2 instance
* Download and transfer the file to the SVS machine (needs to be running tails `3.0.1`+)
* Open nautlius (`files` app) and unpack the file by double clicking continually. The excel file will eventually unpack to a directory which contains files  looks like the file contents of a typice:

```
$ unzip -l excel.xlsx 
Archive:  excel.xlsx
  Length      Date    Time    Name
---------  ---------- -----   ----
      571  2017-08-24 16:17   _rels/.rels
      380  2017-08-24 16:17   docProps/app.xml
      731  2017-08-24 16:17   docProps/core.xml
      549  2017-08-24 16:17   xl/_rels/workbook.xml.rels
      878  2017-08-24 16:17   xl/workbook.xml
     4583  2017-08-24 16:17   xl/styles.xml
     2501  2017-08-24 16:17   xl/worksheets/sheet1.xml
      318  2017-08-24 16:17   xl/sharedStrings.xml
     1111  2017-08-24 16:17   [Content_Types].xml
---------                     -------
    11622                     9 files
```

## Expected Behavior
File should should maintain extension and open up in libreoffice. Note that I have verified the gnome `/usr/bin/dconf` bashrc setting was in place on the SVS.

## Suggestions to fix, any other relevant information.

I realize there are previous tickets relating to this -- https://github.com/freedomofpress/securedrop/issues/1862 not sure it is completely resolved though.

**Comment by harlo** [comment]
can confirm with .xlsx, .docx, .odt files. i presume this occurs with any file that is essentially a glorified zip file.

**Comment by harlo** [comment]
Did a bit of a test: I made an .xlsx file, used gzip on it to compress. Then extracted it, and observed the same behavior. Please double-check!

`
amnesia@amnesia:~/Desktop$ file test.xlsx.gz 
test.xlsx.gz: gzip compressed data, was "test.xlsx", last modified: Thu Aug 24 21:54:04 2017, from Unix
`
Then, used "Extract Here" from the GUI, and finally
`
amnesia@amnesia:~/Desktop$ ls -la test.xlsx
total 0
drwx------ 5 amnesia amnesia 120 Aug 24 21:54 .
drwx------ 3 amnesia amnesia 140 Aug 24 21:54 ..
-rw-rw-r-- 1 amnesia amnesia   0 Aug 24 21:54 [Content_Types].xml
drwx------ 2 amnesia amnesia  80 Aug 24 21:54 docProps
drwx------ 2 amnesia amnesia  60 Aug 24 21:54 _rels
drwx------ 4 amnesia amnesia 140 Aug 24 21:54 xl
amnesia@amnesia:~/Desktop$ 
`

**Comment by redshiftzero** [comment]
I see the same behavior (thanks for the bug report @msheiny and reproducing @harlo!) on a test SVS which had dotfiles persistence enabled and `/usr/bin/dconf write /org/gnome/nautilus/preferences/automatic-decompression false` appended to its `.bashrc`. 

## Problem

This issue is arising because the `/org/gnome/nautilus/preferences/automatic-decompression` option is set in `.bashrc` (which persists due to dotfiles persistence). The problem is that this means that the Nautilus preference is only getting applied when a Terminal is opened. This slipped in QA because during testing we likely opened a Terminal to read the nautilus option and check it was set. 

One can verify this is the problem by:

1. Booting to a Tails 3+ SVS with dotfiles persistence enabled and `/usr/bin/dconf write /org/gnome/nautilus/preferences/automatic-decompression false` appended to its `bashrc`.
2. Try to open SecureDrop submissions of filetypes including png, odt, docx, etc. by clicking continuously - the resulted decrypted and uncompressed file will either have the name `data` (png) or will show up as a directory (xlsx, odt, docx, etc.). This reproduces the bug described in this ticket and #1862.
3. Open a Terminal. 
4. Try to open the SecureDrop submissions of filetypes including png, pdf, odt, docx, etc. by clicking continuously - a window will spawn asking you where you'd like to extract the file to. Each file will now be extracted with its filename preserved and it will not appear as a folder.

## Fix

One should apply this option in [`.xsessionrc`](https://wiki.debian.org/Xsession) instead of `.bashrc`. `.xsessionrc` also will persist if dotfiles persistence is enabled on the SVS.
