### ISSUE TITLE
Remove securedrop version info from public facing pages

### ISSUE THREAD

**Issue by mrphs** [freedomofpress/securedrop#2192]
[I did a couple of quick searches but haven't looked too deeply to see if a similar ticket has been opened in the past so I apologize in advance if this is a dup]

The version of SecureDrop is publicized in footer of every page. Is this necessary for some reason? Should it not be only visible to admins? I can't think of a particular attack that would take advantage of the version number right now, but intuitively, I think it shouldn't be publicized unless it's absolutely needed for some reason.

**Comment by conorsch** [comment]
We definitely want the version number present: it's the only means we have to verify that updates are being installed. Since FPF does not have direct access to SecureDrop instances, the best we can do to confirm that updates are being installed correctly is scan the Source Interfaces for known instances—which is exactly what we do. This enables us to reach out to select instances that failed to upgrade and solicit more debugging information. (Selective failed upgrades are actually quite rare, but we'd rather know about them than now.)

It's also intended as transparency for sources: a source has a right to know if an organization is running an unpatched version of software intended to protect their anonymity.

**Comment by heartsucker** [comment]
IMO each version `0.4.1 -> 0.4.2` will have enough noticeable changes that an adversary will be able to look at the CSS, HTML, SVGs, or translations and determine the version. There's also a `/metadata` endpoint that offers this as well for automated checking of instances to ensure they upgraded.

Related: #972

**Comment by conorsch** [comment]
Agreed with @heartsucker that removing the version number from the footer is _not_ sufficient defense to prevent an adversary from identifying the version running on the server. Now that #972 has been appropriately referenced (:tophat: @heartsucker), I'm closing this issue, since discussion about publishing version info is better placed in #972.
