### ISSUE TITLE
Docs: Consider suggesting use of "Get Tor" service

### ISSUE THREAD

**Issue by mrphs** [freedomofpress/securedrop#2193]
[Development Practices page](https://docs.securedrop.org/en/stable/deployment_practices.html) suggest running a local mirror of Tor and Tails. While this might be a good idea to avoid raising flags by downloading Tor Browser, it might not be practical as running these mirrors are costly and require a lot of space. A good alternative could be suggesting use of [Get Tor](https://gettor.torproject.org/). Get Tor allows censored users to download Tor Browser from Google Drive, Dropbox or a random mirror. Get Tor accepts request via email, XMPP, Twitter DM or API calls.

**Comment by mrphs** [comment]
That being said, even if they download Tor discreetly, once they run Tor Browser it would be obvious they are connecting to the Tor network. Unless we want to advice people to use meek. meek is a Pluggable Transport that takes advantage of domain fronting to make it seem like you're connecting to either Amazon or Microsoft while you're actually connecting to Tor network.

**Comment by redshiftzero** [comment]
Thanks for filing this @mrphs. The suggestion of Get Tor is a good idea: this could prevent sources from being trivially discovered by a passive eavesdropper. Otherwise, an adversary can monitor the network for connections to news organizations using SecureDrop and then subsequent connections to torproject.org. 

However, I would be cautious about implementing this as a broad requirement for all SecureDrop sources, as doing so would funnel all sources into the Get Tor channels, which are likely less used. Are there statistics on the usage of Get Tor? My concern is specifically making the third parties hosting the channel (e.g. the Twitter account used for Get Tor) an especially juicy target. 

That said, I'm looking favorably upon this suggestion nevertheless as it leads to a net improvement:
 * For a nation state adversary with XKEYSCORE-like capabilities, they would then need to introspect into the servers of 3rd parties (which would be possible for some (e.g. PRISM partners) but not all nation state adversaries - there are nation states that have access to internet metadata but can't send a court order to Twitter). 
 * For any local passive eavesdropper, they could no longer trivially discover sources.

Ported the suggestion of meek to another ticket (#2201) for further discussion.

**Comment by mrphs** [comment]
That's a really good point @redshiftzero. I don't think at any point we should require people to use these methods and should rather let them know they exist. Although I don't know what would be the best way to simply explain these options without making them confused.

Pinging @ilv for GetTor stats.

**Comment by dachary** [comment]
@redshiftzero

> this could prevent sources from being trivially discovered by a passive eavesdropper. Otherwise, an adversary can monitor the network for connections to news organizations using SecureDrop and then subsequent connections to torproject.org.

If the passive eavesdropper is able to see a download from https://www.torproject.org/projects/torbrowser.html.en, can it also see mails/xmpp messages being sent to gettor@torproject.org or twitter messages ?

@mrphs I understand how Get Tor helps when tor download URLs/IPs are blocked. I don't understand how it avoid raising flags ? This is not a trick question ! I'm fairly new to surveillance self defense :-)

**Comment by mrphs** [comment]
@dachary They can't see what page on torproject website you've visited but they can see you've visited Tor and how much traffic did you exchange with them. So if you spent 5mins on the site and downloaded ~40-50MB, it's obvious what you did there. When you use a third party as a proxy, the eavesdropper can see you've connected to whatever email/xmpp service you use or Twitter. They can't see who you talk to on there. Using GetTor, all they can see is that for example you connected to gdocs or dropbox and downloaded 40-50MB of data. They cant tell what that is. It could be anything. ...Well, assuming the service provider isn't actively providing info to them. If your adversary involves anyone who might have access to the service provider's servers (in one way or another) this is not going to necessarily save you and I think that was @redshiftzero's point.
