### ISSUE TITLE
Migrate all provisioning scripts to utilize molecule v2

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2198]
# Feature request

## Description

[Molecule](https://molecule.readthedocs.io/en/latest/) `v2` is currently in release candidate form but is looking to be in a solid workable state for inclusion into our project. We should migrate all local provisioning scripts (including dev and CI) to molecule and wrap entry points in `make` commands.

In my mind this will replace:
* local developer provisioning ( all three environments - dev, staging, prod )
* CI provisioning (same as above, all three environments )
* deb package building and testing

Currently I have a PR going through the motions that uses molecule in #2160 .

## User Stories

As a SecureDrop project maintainer, I want to remove the burden of maintaining a set of complex scripts for provisioning and offload maintenance as much as possible by utilizing (actively maintained) third-party tooling.

**Comment by msheiny** [comment]
hey @dachary ! we can battle over molecule here (instead of in #2160 )

 ⚔️ 🔥

**Comment by dachary** [comment]
@msheiny thanks for the invite :-) 

I'm opposed to using molecule for something that is completely different from its primary goal which is integration testing. The fact that it is possible to do so is not a good reason. Molecule is certainly not the only option to leverage the provisioning capabilities that ansible has to offer. 

If an ansible based alternative to the current set of scripts is implemented (not with molecule but maybe by leveraging some of its modules ?) it can be tested with molecule. But diverting molecule from its primary purpose and have it produce artificats instead of testing something that produces artificats is not good because it cannot be tested.

I insist primarily because there already is a another instance of such a creative use of a tool for a purpose which is a little baroque: using ansible to create debian packages instead of the tools designed to create packages. I do understand the reasons why this happened (debian packaging is exceptionally difficult). But we now have to live with it and is is a burden.

**Comment by conorsch** [comment]
The work described in the OP is now accomplished: both dev and CI environments make heavy use of Molecule to manage the VM/container provisioning, as well as running tests against the hosts.
