### ISSUE TITLE
Docs: Additional docs of prod VM developer spin up

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2203]
## Description

Developer docs on prod VMs need a description of how to fill out `site-specific` with prod-like secrets. 

## User Stories

As a SecureDrop developer, I want clear instructions on how to provision the production-like environment for testing.

**Comment by conorsch** [comment]
I propose removing the Ansible provisioning blocks for the prod VMs from the Vagrantfile, essentially mandating use of Tails for Admin Workstation in order to test prod VMs. Staging has improved vastly over the past six months or so, and should be sufficient for testing developer code and config changes locally.

**Comment by redshiftzero** [comment]
Good idea - I'm fine with making this change once we've documented (in an ideal world we would script, but documentation is a must) the spinup for the virtualized Admin Workstation on macOS + Linux.
