### ISSUE TITLE
Investigate flaky functional tests

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2205]
## Description

We're noticing some occasional flaky Selenium tests, let's post builds here so we can fix them:

* https://travis-ci.org/freedomofpress/securedrop/builds/268366914 in `_journalist_delete_all_javascript()`
* Same function in https://travis-ci.org/freedomofpress/securedrop/builds/268561511

## User Stories

As a SecureDrop developer, I want test flakes reduced to a minimum so that I trust the test suite.

**Comment by conorsch** [comment]
Hypothesis: heavy load creates races in the functional tests (cc @dachary). We might be able to gather more data by placing `uptime` calls before and after the app tests run. 

Another thing to watch for is are the tests failing only on Travis, or Circle CI, or both?

**Comment by dachary** [comment]
>Another thing to watch for is are the tests failing only on Travis, or Circle CI, or both?

IIRC flaky selenium tests are found on Travis, not Circle CI.

**Comment by dachary** [comment]
@redshiftzero  https://travis-ci.org/freedomofpress/securedrop/builds/268561511 mentionned in the issue message actually passed. Was it another maybe ?

**Comment by dachary** [comment]
Very interesting read http://www.obeythetestinggoat.com/how-to-get-selenium-to-wait-for-page-load-after-a-click.html

**Comment by dachary** [comment]
For the record I tried using phantomjs and ran into troubles. My primary incentive was to get something more stable but I get the opposite impression because there seems to be less user of the selenium webdriver than firefox. My secondary incentive was performances since it's supposed to be lighter than firefox, but I observer around 50% speedup which is not that much. 

<pre>
diff --git a/securedrop/tests/functional/functional_test.py b/securedrop/tests/functional/functional_test.py
index 1e4aba70..e020953b 100644
--- a/securedrop/tests/functional/functional_test.py
+++ b/securedrop/tests/functional/functional_test.py
@@ -137,7 +137,7 @@ class FunctionalTest():
         self.source_process.terminate()
         self.journalist_process.terminate()
 
-    def wait_for(self, function_with_assertion, timeout=5):
+    def wait_for(self, function_with_assertion, timeout=20):
         """Polling wait for an arbitrary assertion."""
         # Thanks to
         # http://chimera.labs.oreilly.com/books/1234000000754/ch20.html#_a_common_selenium_problem_race_conditions
diff --git a/securedrop/tests/functional/journalist_navigation_steps.py b/securedrop/tests/functional/journalist_navigation_steps.py
index 79dad848..73a725fd 100644
--- a/securedrop/tests/functional/journalist_navigation_steps.py
+++ b/securedrop/tests/functional/journalist_navigation_steps.py
@@ -473,9 +473,32 @@ class JournalistNavigationSteps():
         assert ('/account/reset-2fa-hotp' in
                 hotp_reset_button.get_attribute('action'))
 
+        # class wait_for_page_load(object):
+
+        #     def __init__(oself, browser):
+        #         oself.browser = browser
+
+        #     def __enter__(oself):
+        #         oself.old_page = oself.browser.find_element_by_tag_name('html')
+
+        #     def page_has_loaded(oself):
+        #         new_page = oself.browser.find_element_by_tag_name('html')
+        #         print(str(new_page.id) + " != " + str(oself.old_page.id))
+        #         assert new_page.id != oself.old_page.id
+
+        #     def __exit__(oself, *_):
+        #         self.wait_for(oself.page_has_loaded)
+
+        # with wait_for_page_load(self.driver):
         hotp_reset_button.click()
 
     def _set_hotp_secret(self):
+        def some():
+            assert self.driver.find_elements_by_css_selector(
+                'input[name="otp_secret"]')
+        self.wait_for(some)
+        print(str(self.driver.find_elements_by_css_selector(
+                'input[name="otp_secret"]')))
         hotp_secret_field = self.driver.find_elements_by_css_selector(
             'input[name="otp_secret"]')[0]
         hotp_secret_field.send_keys('123456')
diff --git a/securedrop/tests/pages-layout/functional_test.py b/securedrop/tests/pages-layout/functional_test.py
index ccb8ecc1..09be9290 100644
--- a/securedrop/tests/pages-layout/functional_test.py
+++ b/securedrop/tests/pages-layout/functional_test.py
@@ -24,7 +24,8 @@ from selenium.webdriver.common.action_chains import ActionChains
 from selenium.webdriver.common.keys import Keys
 
 from selenium import webdriver
-from selenium.webdriver.firefox import firefox_binary
+# https://github.com/detro/ghostdriver
+from selenium.webdriver import PhantomJS
 
 from tests.functional import functional_test
 
@@ -47,39 +48,33 @@ class FunctionalTest(functional_test.FunctionalTest):
             os.path.join(dirname(realpath(__file__)),
                          'screenshots', self.accept_languages))
         os.system("mkdir -p " + self.log_dir)
-        log_file = open(os.path.join(self.log_dir, 'firefox.log'), 'a')
+        log_path = os.path.join(self.log_dir, 'phantomjs.log')
+        log_file = open(log_path, 'a')
         log_file.write(
             '\n\n[%s] Running Functional Tests\n' % str(
                 datetime.now()))
+        # https://seleniumhq.github.io/selenium/docs/api/py/webdriver_phantomjs/selenium.webdriver.phantomjs.webdriver.html
         log_file.flush()
-        firefox = firefox_binary.FirefoxBinary(log_file=log_file)
-        profile = webdriver.FirefoxProfile()
-        profile.set_preference("intl.accept_languages", self.accept_languages)
+        webdriver.DesiredCapabilities.PHANTOMJS['Accept-Language'] = self.accept_languages
         self.override_driver = True
-        self.driver = webdriver.Firefox(firefox_binary=firefox,
-                                        firefox_profile=profile)
+        self.driver = PhantomJS(service_log_path=log_path, executable_path='phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs', service_args=['--ignore-ssl-errors=true', '--ssl-protocol=any', '--debug=true'])
+#        self.driver.implicitly_wait(50)
+        self.javascript = True
         self._javascript_toggle()
 
         yield None
 
+#        self.driver.save_screenshot(os.path.join(self.log_dir, 'last.png'))
+#        open(os.path.join(self.log_dir, 'last.txt'), 'w').write(self.driver.page_source)
         self.driver.quit()
 
     def _screenshot(self, filename):
+        self.driver.execute_script('document.body.style.background = "white"')
         self.driver.save_screenshot(os.path.join(self.log_dir, filename))
 
     def _javascript_toggle(self):
-        # the following is a noop for some reason, workaround it
-        # profile.set_preference("javascript.enabled", False)
-        # https://stackoverflow.com/a/36782979/837471
-        self.driver.get("about:config")
-        actions = ActionChains(self.driver)
-        actions.send_keys(Keys.RETURN)
-        actions.send_keys("javascript.enabled")
-        actions.perform()
-        actions.send_keys(Keys.TAB)
-        actions.send_keys(Keys.RETURN)
-        actions.send_keys(Keys.F5)
-        actions.perform()
+        self.javascript = not self.javascript
+        webdriver.DesiredCapabilities.PHANTOMJS['phantomjs.page.settings.javascriptEnabled'] = self.javascript
 
     def _save_alert(self, filename):
         fd = open(os.path.join(self.log_dir, filename), 'wb')
</pre>
test script with various pointers
<pre>
from selenium import webdriver
 
headers = { 'Accept':'*/*',
            'Accept-Language':'fr-FR,en-US,en;q=0.8',
    'Cache-Control':'max-age=0',
    'User-Agent': 'Mozilla/6.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'
}

# requires phantomjs > 1.9 https://github.com/detro/ghostdriver/commit/43a8fbcb6cbe55c459b659e44a61858ef1169a71
# wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
for key, value in headers.iteritems():
    capability_key = 'phantomjs.page.customHeaders.{}'.format(key)
    print(key + " = " + value)
    webdriver.DesiredCapabilities.PHANTOMJS[capability_key] = value

webdriver.DesiredCapabilities.PHANTOMJS['phantomjs.page.settings.javascriptEnabled'] = False

driver = webdriver.PhantomJS(service_log_path='/tmp/a.log', executable_path='phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs', service_args=['--ignore-ssl-errors=true', '--ssl-protocol=any', '--debug=true'])
driver.get('https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending')
#driver.get('http://dachary.org')
 
html = driver.page_source
print(html)
</pre>

**Comment by dachary** [comment]
I think it may be as simple as increasing the timeout for functional tests. And adding a timeout to --page-layout: there was none and they were much more likely to fail as a result.

https://github.com/freedomofpress/securedrop/pull/2211
