### ISSUE TITLE
[docs] Make Tails upgrade documentation more generic

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#2244]
We currently have some excellent documentation for specific scenarios where we expect SecureDrop users will need to manually upgrade their Tails USBs:

* [Upgrade Tails from 1.x to 2.x](https://docs.securedrop.org/en/stable/upgrade_to_tails_2x.html)
* [Upgrade Tails from 2.x to 3.x](https://docs.securedrop.org/en/stable/upgrade_to_tails_3x.html)

However, we lack a _generic_ guide for manually upgrading Tails. Manual upgrades are also necessary in the following scenarios:

* Admins who upgraded their internet-connected Tails USBs (Admin/Journalist Workstation) from Tails 3.0 to Tails 3.0.1, which had a [bug](https://labs.riseup.net/code/issues/13426) that broke subsequent automatic upgrades. The official [fix](https://tails.boum.org/news/rescue_3.0.1/index.en.html) required a manual upgrade.
* In every case, the Secure Viewing Station (SVS) Tails must be manually upgraded, because the SVS is airgapped and unable to receive automatic upgrades over the network.
    * Clearly documenting this upgrade flow is especially important in the context of #2238. The initial RCE exploit was in the Nautilus file manager, and while it has been fixed upstream, it still [needs to be backported to Tails](https://labs.riseup.net/code/issues/14584). Once the backport is done, we expect a new version of Tails will be released, at which point SecureDrop administrators/journalists will need to manually upgrade their SVS' Tails to patch it against this specific vulnerability.

**Comment by redshiftzero** [comment]
A contributor that wants to pick this documentation ticket up can start from branch `generic-tails-manual-upgrade-docs` as there is lots of work to build from in there.

**Comment by eloquence** [comment]
Since this issue was written, we've formalized the habit of providing Tails upgrade instructions with each release of SecureDrop ([example](https://docs.securedrop.org/en/release-0.14.0/upgrade/0.13.1_to_0.14.0.html#updating-the-tails-workstations)). Where an upgrade has to be performed manually, we state so explicitly.

This enables admins to perform many SecureDrop-related maintenance tasks in one batch, in regular intervals. However, it still makes sense to add a general "Keeping all Tails workstations up-to-date" guide, especially for the air-gapped SVS. If we had a generic manual upgrade guide, we could regularly remind people to update their SVS in our release-to-release upgrade docs.

The `generic-tails-manual-upgrade-docs` branch above is dated but the gist of its recommendation seems still solid to me, minus the historic issues with very old Tails releases that we no longer have to explicitly reference. Essentially, for a manual upgrade, it suggests:

1. Make a backup
2. Do an in-place upgrade from another Tails

I do think we should be able to reduce this to a single new section in the docs. If we feel the "[Manually upgrade from another Tails](https://tails.boum.org/upgrade/clone/index.en.html)" instructions are adequate, I would prefer to use them instead of duplicating them.
