### ISSUE TITLE
Extra level in zip folders for single sources

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2262]
## Description

There is an extra unnecessary folder for zipfiles downloaded from the journalist interface for single sources. 

## Steps to Reproduce

0. Submit some files to SecureDrop
1. Load the home page of the journalist interface
2. Select one source using the checkbox
3. Select "Download"
4. Unzip the resulting file

## Expected Behavior

File structure would ideally be: 

`source-name/number_date`

e.g.:

`ecstatic-potato/1_03-20-20`

## Actual Behavior

Instead there is an additional layer:

`ecstatic-potato/ecstatic-potato/1_03-20-20`

## Comment

This additional folder is confusing to users and should be removed.

Note: if you download unread or download all for multiple sources - the outer folder will not be named after the source and will be e.g. `all`:

`all/ecstatic-potato/1_03-20-20`

**Comment by redshiftzero** [comment]
(this was not discovered doing 0.4.3 release QA, this is in production)

**Comment by kushaldas** [comment]
i can verify with the following details.

## Steps to Reproduce

0. Submit some files to SecureDrop
1. Load the home page of the journalist interface
2. Click on one source
3. Select one document from source using the checkbox
4. Select "Download"
5. Unzip the resulting file




## Expected Behavior
File structure would ideally be:
```
source_name/number_date
```
e.g.:

```
ecstatic_potato/1_03-20-20
```
## Actual Behavior

Instead there is an additional layer:

```
ecstatic_potato/ecstatic potato/1_03-20-20
```
