### ISSUE TITLE
sdconfig fingerprint should allow white space separated form

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2266]
# Feature request

## Description

The `securedrop-admin sdconfig` input for the `securedrop_app_gpg_fingerprint` and `ossec_gpg_fpr` should ignore whitespace. 

## User Stories

When installing securedrop I want to copy/paste the output of `gpg --list-key` without manually removing the white space when answering the `securedrop-admin sdconfig` prompt for `securedrop_app_gpg_fingerprint` and `ossec_gpg_fpr`

**Comment by conorsch** [comment]
Hmm, not a bad idea. We do already check for whitespace and fail if it's found: https://github.com/freedomofpress/securedrop/blob/afa97acb49f2d0f95208ff6f1c456718ae5e681d/install_files/ansible-base/roles/validate/tasks/validate_gpg_info.yml#L10-L11 but I see what you're saying, we could just strip it. Not opposed.

**Comment by conorsch** [comment]
#2267 was solid progress here, but was inadequately QA'd in Tails, and doesn't work as advertised. For one, the inner quotes should be single quotes, not double quotes, otherwise Ansible throws an error:

![tails-quotes-in-fingerprint-whitespace-stripping](https://user-images.githubusercontent.com/657862/30355670-a4ce9726-97e9-11e7-9999-4f191434ef56.png)

Notably `yamllint` catches that error:

```
yamllint install_files/ansible-base/securedrop-configure.yml -d relaxed
install_files/ansible-base/securedrop-configure.yml
  60:81     warning  line too long (84 > 80 characters)  (line-length)
  65:81     warning  line too long (84 > 80 characters)  (line-length)
  159:67    error    syntax error: expected <block end>, but found '<scalar>'
```

so I'll get a PR up for #2255 pronto. Even with the quoting fixed, however, the associated validation tasks still fail if whitespace is provided in the fingerprint. Looks like we'll need to import the vars if writing to the local site-specific vars file reported changes, to make sure we have the var value _after_ the whitespace has been stripped. (Loosely related: #2095.)

**Comment by kushaldas** [comment]
This one is fixed in https://github.com/freedomofpress/securedrop/commit/b7b6ca2e77d6ff8ae82ac87abaadc12896940ee8#diff-a3b5e93ae26d81aad5d29a02b86500deR201 Closing the ticket.

**Comment by dachary** [comment]
@kushaldas thanks !
