### ISSUE TITLE
Textboxes for admin and journalist logins should be longer

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#2288]
# Feature request
Textboxes for admin and journalist logins should be longer.

## Description
In login pages where long diceware passphrases are expected to be typed in, the textbox for the passphrase should be long enough to fit a diceware passphrases of the word size recommended.

## User Stories
As a journalist or admin, I want to be able to enter my very long diceware passphrase and make sure I didn't miss or misspell any words before logging in and realizing I done goofed, which would make me have to type a very long passphrase in another time.

**Comment by redshiftzero** [comment]
Noting that in the SecureDrop web applications the codename will not be visible since the form input type is `password` - however I think your point still stands, for example if a user is typing a long password it is useful to see the feedback of the number of obfuscated characters increasing. [This blog](https://baymard.com/blog/form-field-usability-matching-user-expectations) echoes @huertanix's advice here and has some other good background on good UX on forms.
