### ISSUE TITLE
Create a better session expiry page

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#2290]
# Feature request
Create a better session expiry page. 

## Description
Currently, when a journalist session expires, they run into a blank "CSRF token expired" page. Ideally, should instead be given a more context-specific, rather than tech-specific error message e.g. "Your SecureDrop session has expired, please log back in to continue." and redirected or given a link to go back to a login page so that they're not stuck/worried not knowing what happened or what to do next.

## User Stories
As a journalist I'd like to be notified when my session expires and what to do when it does. Also I'd like to not worry about weird messages that sounds scary but aren't actually anything to worry about.

**Comment by redshiftzero** [comment]
Closed by #1494, users will as of 0.4.4 get a friendlier message as suggested here

**Comment by heartsucker** [comment]
Reopening because this is *not* actually closed. We just *happened* to work around it. Flask-WTF sets the CSRF protection tokens to have a time limit of 60 minutes by default (set with `WTF_CSRF_TIME_LIMIT`). We set the session timeout to be 30 minutes by default. This means we never see the error page unless an admin adjusts the timeout.

This can be verified with:

```python
app.config['WTF_CSRF_TIME_LIMIT'] = 10 # seconds
```

In `journalist.py`. Run the app, load the login page, wait over 10 seconds, then attempt to log in (either good or bad credentials). This will display the ugly 400 Bad Request page.

![screenshot_2017-10-07_15-27-01](https://user-images.githubusercontent.com/3998464/31308268-043a1b0c-ab74-11e7-96cf-62b2b6cf093d.png)

A possible solution would be to set the CSRF timeout to be equal to the session timeout. I also know the CSRF value is set to 24 hours for sources, but I suspect that setting it lower won't break the uploads because it would be very strange for Flask-WTF to set a callback that breaks the connection at the instant the token expires. This would need to be investigated.

Or, we could just use a custom error handler [as described in the Flask-WTF docs](https://flask-wtf.readthedocs.io/en/stable/csrf.html#customize-the-error-response).

**Comment by heartsucker** [comment]
It would also be good to clear the session in the aforementioned handler since the CSRF token expiring should indicate that the session is unattended as well.
