### ISSUE TITLE
Add a Support Section to Docs

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop#2297]
Please use the appropriate part of the template: "Bug" or "Feature Request"

# Feature request

## Description

Currently the Support for SecureDrop (Redmine system) isn't in the documentation. We should add it as a full topic guide for new admins.

## User Stories

As a person who is installing or maintaining a SecureDrop, I would like to easily know where I can get support in the documentation.

**Comment by eloquence** [comment]
Prominently explaining support options and issue reporting makes sense to me. @edenemmanuel, I will take a stab at this and ask for your sign-off on the PR.

**Comment by eloquence** [comment]
We have since created https://securedrop.org/priority-support/ as a prominent landing page for this, and of course we also have http://securedrop-support.readthedocs.io/ . So I think the main task here is to make sure that this information is prominently linked from https://docs.securedrop.org/ , rather than repeating it.

**Comment by edenemmanuel** [comment]
That seems more than reasonable to me @eloquence. It will significantly reduce risk of outdated and conflicting docs if we implement your suggestion.
