### ISSUE TITLE
Demo login error

### ISSUE THREAD

**Issue by trajce9** [freedomofpress/securedrop#2314]
# Bug

## Description

I am not able to login on the demo at https://document.securedrop.org/login
With the credentials: 
**username:** journalist
**password:** WEjwn8ZyczDhQSK24YKM8C9a
**Two Factor Code:**  6 digit number returned back from the Google Authenticator app

## Steps to Reproduce

Try to enter the credentials to https://document.securedrop.org/login

## Actual Behavior

<img width="1047" alt="screen shot 2017-09-15 at 4 42 07 pm" src="https://user-images.githubusercontent.com/17157714/30487822-dcd815e6-9a34-11e7-873c-d593f1e132c7.png">

**Comment by dachary** [comment]
Hi ! The demo is indeed broken and should not be linked anymore.
@msheiny would it be possible to do something about that ?. 

You will find a working demo at http://demo.securedrop.club/ . It's a demo and you have the admin credentials, therefore it's entirely possible to break it. If you do please let us know so we can reset it. Otherwise it is going to be reset on a daily basis anyway.

Cheers

**Comment by dachary** [comment]
@trajce9 feel free to close this issue once you've used the demo successfully.

**Comment by trajce9** [comment]
Thank you dachary providing me with option to review the functionalities offered by securedrop 

closing this issue
