### ISSUE TITLE
Improve consistency of multi-factor auth terminology

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2331]
# Feature request

## Description

There are several place in the docs and apps where "two factor {code,token,credentials}" are used seemingly interchangeably.

We should use

- two factor secret: for the shared secret
- two factor code: the actual OTP

Google uses the phrase "authentication code" and we should at least stick to the phrase "code" in our docs / app.

This should also be included with variable names in the app. Using `totp_token` to parse what the docs call a "two factor code" is unnecessarily confusing.

## User Stories

As a translator, I want to have a smaller number of glossary terms to maintain.

As a (non-technical) user, I want to be able to simply follow directions without having to know if a two factor token is the same as a two factor code.

**Comment by heartsucker** [comment]
This include the 2FA verification screen on the journalist app that says "Verification code."

**Comment by rmol** [comment]
Our terminology for everything related to multi-factor authentication is internally inconsistent, doesn't match some popular web services that users might have experience with, and is wasting a lot of translator effort. 

I'd like to add to this ticket normalization of the terms for devices used in two-factor authentication. A  quick survey suggests that "security key" is the most common term for them:
- [Facebook](https://www.facebook.com/help/401566786855239)
- [GitHub](https://help.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-security-key)
- [Google](https://support.google.com/accounts/answer/7539956)
- [Microsoft](https://support.microsoft.com/en-us/help/4463210/windows-10-sign-in-microsoft-account-windows-hello-security-key)

We should settle on that in code and docs.

**Comment by ninavizz** [comment]
WRT "Security Key," I feel Duo does it very well on this page. Which, I realize, is only one part of the problem... https://guide.duo.com/u2f

**Comment by eloquence** [comment]
Nina and I discussed this today, to ensure that we're agreeing on consistent terminology we can use for the SecureDrop Workstation as well. The proposal here makes sense to us:

- Two-Factor Code - (with "two" always spelled out) for the numeric codes the user enters
- Two-Factor Secret - for the seed used to manually configure a two-factor authentication device, in lieu of scanning a QR code
- Security Key - for dedicated physical security devices like YubiKeys that can be used to generate two-factor code;

A couple of notes on usage:

- "Two-Factor Secret" is a very unusual term (under 3,500 Google hits); most applications just present you with the QR code. If the seed is given, it is often just called a "code", or a "plain-text code". We appreciate that "Two-Factor Secret" is a more precise term, but we suggest using it in connection with other language, like "Pair your device manually by entering the following two-factor secret in your authenticator app" (where the term "pair your device" is a familiar concept from other contexts).

- "Security Key" could be confused with other terms often used in a SecureDrop context, like "Submission Key" or the colloquial term "USB key" for USB flash drives. We suggest using it in connection with explanatory language, e.g., "Security Key (e.g., a YubiKey)" where possible, to avoid this kind of confusion.

We would like to suggest one other change in the scope of a PR to resolve this issue:

- Change the glossary term "Two-Factor Authenticator" to "Two-Factor Device". "Two-Factor Authenticator" is a confusing term in that it doesn't speak for itself. Does it refer to a person, an app, a device? Fortunately, we only use this term rarely, so it should be easy to update.

Nina will also invite comments from other security UX practitioners. We both appreciate that we are aiming to get a PR in by the end of the week, so I'll get that ready ASAP and we can amend as needed during review.

**Comment by rmol** [comment]
That all sounds good to me, but "Two-Factor Authenticator" sounds like it was supposed to be ambiguous, to cover either an app or a device. Maybe instead of picking only device, it would be better to drop it as a term from the glossary and just always spell it out, like "security key or authentication application"?

**Comment by eloquence** [comment]
> That all sounds good to me, but "Two-Factor Authenticator" sounds like it was supposed to be ambiguous, to cover either an app or a device.

Yes, that was our read as well. The intention here would be to consider a phone+app *or* a YubiKey a "two-factor device". In common usage on the web, "two-factor device" is also used to be inclusive of both phones and tablets.

The term "authenticator" only appears twice in the docs, so I do like the alternative of avoiding the use of a confusing or ambiguous umbrella term entirely.

**Comment by ninavizz** [comment]
Twitter is expanding it's 2FA, and I also found its use of language interesting. Only including here as a reference point. Too tired to read through all the awesome convo since I tersely ended my convo with Erik to rush off to crossfit, earlier this eve. 

﻿﻿
![image](https://user-images.githubusercontent.com/8262612/69317273-70749800-0bef-11ea-9436-ef91e0d83df3.png)

**Comment by ninavizz** [comment]
Twitter is expanding it's 2FA, and I also found its use of language interesting. Only including here as a reference point. Too tired to read through all the awesome convo since I tersely ended my convo with Erik to rush off to crossfit, earlier this eve. 

﻿﻿
![image](https://user-images.githubusercontent.com/8262612/69317273-70749800-0bef-11ea-9436-ef91e0d83df3.png)

**Comment by seamustuohy** [comment]
Hear me out here before you mute me for linking to NIST.  Their [Digital Identity Guidelines](https://pages.nist.gov/800-63-3/sp800-63b.html) not only has specific terms for each type, they also have illustrative iconography for each type. (I believe that the art is all non-copy-writable and therefore reusable under [17 U.S.C. §105](https://www.govinfo.gov/content/pkg/USCODE-2014-title17/pdf/USCODE-2014-title17-chap1-sec105.pdf) )

**Comment by eloquence** [comment]
Good find @seamustuohy!  We may be able to create custom icons more in line with the SecureDrop styles if we decide that we want to add visuals in certain locations, but it's great to know that these public domain icons are available. In terms of the terminology, we likely want to use a smaller set of terms that allows us to be a bit less precise (e.g., we don't need to distinguish between a single-factor authentication device and a multi-factor authentication device, because we only use single-factor devices, and in combination with "two-factor", introducing that distinction has a lot of potential for confusion).

**Comment by seamustuohy** [comment]
I agree! The highly specific terminology used in the NIST standard is far too precise and jargon filled for even an reasonably tech-savvy user to get value from. That said, there is always a risk of erring on the side of overly broad when trying to get terminology more easy to understand. This can make it hard for a user to distinguish exactly what each option means. Using the very specific definitions in NIST as a guide would allow you to help users understand that you are asking them to use "Two Factors of Authentication." Their password, and a choice of [Option], [Option], and [Option. as the Second Factor. 

I'm currently of the opinion that building off the roots of precise language is a more sustainable approach than working back from the most commonly used parlance or developing ones own classification based on the current supported technology. Primarily because the latter two approaches have a tendency to make a glossary somewhat fragile. They force "breaking changes" to a users conceptual model when new authentication technology is added/changed and therefore requires re-educating an entire user-base which can be a big lift. The former allows a user (or their non-security technical advisers) to more easily search external resources to verify which specific implementation of the available security features is appropriate for the threats they are facing. This helps reduce the burden on the internal documentation, community support, and training teams. 

In my mind a language based on the standard definitions which was both understandable and concise would look to something like the following.

"You can choose one or more of the following for your Second Factor:"

- Use a **Software Authenticator** - Use a piece of installed software to authenticate your login attempts.
- Use a **Device Authenticator** - Use a physical electronic device to authenticate your login attempts.
- Use a **Look-Up Secret** - Use codes from a previously downloaded list to authenticate your login attempts.
- Receive an **Out of band secret** over [SMS | Voice Call | Email | WhatsApp | Signal ] - Use a code sent to you over [SMS | Voice Call | Email | WhatsApp | Signal ] to authenticate your login attempts. You will need access to your [ phone | email | account ] to login.
- Use a **One Time Password (OTP) Device** - Use a device linked to your account to generate a one time use code to authenticate your login attempt.
- Use a **One Time Password (OTP) App** - Use an app linked to your account to generate a one time use code to authenticate your login attempt.

As folks have identified earlier in this thread, one of the big challenges with using the existing standardized definitions is their inconstant broad use of "password/secret/code" in the titles of technologies. I think the confusion here can be addressed by sticking to a consistent term (i.e. "code") in the description and defining that separately. This allows a search for a title to return accurate results about the technology while still making the functionality of an authentication type understandable and consistent internally.

**Comment by eloquence** [comment]
We addressed most of this in #5014. There are likely still some potentially confusing uses of terms like `token` in the codebase; however, this should be tracked separately. Closing this issue.
