### ISSUE TITLE
Meta: concensus on officially supported languages for i18n

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2351]
# Feature request

## Description

As a team, we should determine which languages will have top level support. This means that a requirement for a release is that they have 100% translated strings (0 need review, 0 fuzzy). This should also mean that we support word lists in those languages.

I propose we pilot this with French as we have @dachary working on it with the optional addition of German (me) and Norwegian (@comradekingu). Dutch could be another option as it appears there's someone diligently working on that, but I'm not sure how reliable they may be or how connected to the project they are (and if you're reading this, no offense, I just honestly don't know).

These supported languages will need to be documented in the `docs/` directory (possibly in the `README` too) and included in the out-of-repo SecureDrop release checklist.

Last, this number should remain low for a number of releases until we are comfortable managing i18n. We'll need to see how the community responds to this and how quickly we can get translations for new strings as they appear.

## User Stories

As an SD user, I want to know if they language I'm using will receive continuous support or if I may end up with broken strings.

**Comment by redshiftzero** [comment]
Great issue, thanks @heartsucker - I think certainly French and Norwegian should be in the first merge of translations since they are 100% translated and we have reviewers for them as [noted here](https://forum.securedrop.club/t/workflow-for-supported-languages/149). We should document these two supported languages and add the names of the reviewers (if they are comfortable with that) to the documentation. 

If there is sufficient interest from the community, i.e. if there is both a committed reviewer in the targeted language able to review the work of translators _and_ the translations are complete, then we can add whichever languages are requested by users of SecureDrop. 

I'm not sure however that we want to block on having the full EFF or diceware wordlist in the target language before adding new languages to the interfaces? Ideally yes the full wordlist would be translated, but I would argue that a translated SecureDrop UI with the English wordlist is better than only an English SecureDrop UI. Happy to be convinced otherwise on this point.

**Comment by dachary** [comment]
This was resolved at 3569f705df125bd63add9bb35810f7f887491aa3 when we merged in **ar de_DE fr_FR nb_NO nl**
