### ISSUE TITLE
Consider moving SUPPORTED_LOCALES from config.py to i18n.py

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2378]
# Feature request

## Description

The current design is to allow an admin to set the available locales that a user may select in the UI (both source and journalist) via `config.SUPPORTED_LOCALES`. I think we should move this to `i18n` as a hard coded value (or better yet, derive it from the locales in the `translations` dir).

I think the most pressing case for this is the case where an org whose native language / national language is X sets `SUPPORTED_LOCALES = ['X']`, but there is a source who speaks X poorly and wants to submit anyway. The UI being in a "foreign" language may inhibit this.

## User Stories

As an admin, I want to not break SD by setting a bad local string like `en-US` instead of `en_US`.

As an admin, I want all the latest languages available.

As a source, I don't want to be restricted my ability to submit based on the languages an org assumes I speak.

As a journalist in an international org, I want to be able to work in my native language even if it's not one of the official languages spoken by the org.

**Comment by dachary** [comment]
I'd add the following user story:

As a journalist I want to be able to choose in which language SecureDrop can be used. I would not be able to communicate in all the languages proposed.

To be clear I see your point. But I also see why a journalist would not want to display all available languages. Imagine a source submits a chinese document. And the journalist has absolutely no way to read this. He or she would have to ask a translator just to figure out if that's a spam or a valuable document. Of course that can also happen if chinese is not proposed in the menu. But then the journalist would disregard the document and since the interface is not in chinese, the source cannot be mislead into thinking the document in chinese can be read by the journalist.

**Comment by heartsucker** [comment]
I think that's a fair point. A possible compromise could be to have admins set something like `JOURNALIST_LOCALES` and display a flash warning that says "Warning: there are no journalists who speak the language you have selected!" This would allow someone to use the interface to submit a doc on the off chance that a journalist can translate it or it's in the journalist's native tongue, but the source can't read it.

*and this is why we need a UX person*

**Comment by eloquence** [comment]
Discussed in backlog review today w/ @conorsch @rmol -- this is something we still want to leave up to news organizations to configure as they see fit. Since this issue was filed, there is now input validation for these locale strings in `securedrop-admin sdconfig`, so if admins are using that to configure their instance, they cannot accidentally break their configuration by specifying an invalid locale. Closing.
