### ISSUE TITLE
Text is aligned to the wrong side in rtl languages 

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2381]
## Description

Much of the text on the Arabic version of SecureDrop is aligned to the wrong side (left aligned, when it should be right aligned). Needs fixing pre-release:

![screen shot 2017-09-28 at 5 14 14 pm](https://user-images.githubusercontent.com/7832803/30995762-0fa57ac2-a471-11e7-95d4-47d4fb9f12cb.png)

![screen shot 2017-09-28 at 5 15 30 pm](https://user-images.githubusercontent.com/7832803/30995813-51257f60-a471-11e7-84c3-13702d16409d.png)

**Comment by heartsucker** [comment]
@redshiftzero found [this post](http://matanich.com/2013/09/06/rtl-css-with-sass) which should let us write the CSS we need, however, it would still require us to have both RTL and LTR versions of the CSS and it would have to be set up so that jinja knows to select the right one. Because this is a big change and not quickly reversible, I think we still need to talk to a front end dev about how to do this. However, I'm working on something right now that uses he `dir($dir)` pesudo selector that might do the trick. However, it is only supported on FF [according to this](https://css-tricks.com/almanac/selectors/d/dir/). That's fine because we only target TB, but it's something to consider.
