### ISSUE TITLE
Add expiration dates to SecureDrop apt repository

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2436]
# Feature request

## Description

Add expiration dates (`Valid-Until`) on the SecureDrop apt repos. This will prevent attacks from an adversary caching and serving up an older mirror of the apt repo with known vulnerabilities.

See - https://wiki.debian.org/DebianRepository/Format#Date.2C_Valid-Until

**Comment by emkll** [comment]
This is a great idea @msheiny. It seems like the practice varies: `stretch-updates` for example, uses 1 week, [tor](https://deb.torproject.org/torproject.org/dists/stretch/Release) uses 40 days, and others simply don't have a `Valid-Until` date ([xenial](http://archive.ubuntu.com/ubuntu/dists/xenial/Release), [xenial-updates](http://archive.ubuntu.com/ubuntu/dists/xenial-updates/Release), [xenial-security](http://archive.ubuntu.com/ubuntu/dists/xenial-security/Release)). 

- For the SecureDrop repo, I think that using a Valid-Until value of approximately (and perhaps slightly greater) one release cycle (6 weeks), since we update the Release file at every release.

- For the mirrored `tor-apt` repo, it appears tor releases ~3 weeks, so once again using ~6+ weeks `Valid-Until` seems reasonable.

**Comment by conorsch** [comment]
Done, active since Feb 2020. See https://github.com/freedomofpress/securedrop/issues/3086#issuecomment-710258486
