### ISSUE TITLE
Add `safety check` for all python dependencies to CI

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2451]
# Feature request

As noted in #2450, we have a vulnerable dependency. We should automate checks for this.

## Description

In our travis build:

```bash
pip install safety
find . -name '*requirements.txt' -print0 | xargs -0 -n 1 safety check --full-report -r
```

## User Stories

As a dev, I don't want to manually check for vulns in my dependencies.

As an admin, I don't want to get hacked via my dependencies.

As a server, I don't want to get hacked at all kthx.

**Comment by emkll** [comment]
Great idea. GitHub also launched a [dependency graph](https://github.com/freedomofpress/securedrop/network/dependencies) tool a couple of days ago which that alerts on vulnerable package.

**Comment by conorsch** [comment]
Yes! Let's wire up a makefile target to run the command. Optional whether it's in a container—although we'll need to add `safety` to `develop-requirements.txt` if not.

Note that the use of `xargs` here is required since otherwise we can't force `find` to report errors reliably via `-exec`—at least not in a cross-platform way.
