### ISSUE TITLE
Testinfra tests failing for app-staging and mon-staging

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2489]
# Bug

## Description

Testinfra test fails in current `develop` branch.

## Steps to Reproduce
```
./testinfra/test.py app-staging
./testinfra/test.py mon-staging
```

## Expected Behavior
All tests should pass.

## Actual Behavior
2 tests fail: 
* `test_ip6tables_drop_everything`
* `test_app_iptables_rules`

**Comment by dachary** [comment]
in freedomofpress/securedrop@3da5605 @msheiny changed, October 20th, the two tests because he expects them to always fail. And they indeed always fail in the CircleCI context. Otherwise CircleCI would complain on every pull request. However, on our local machines it does not fail as expected and this is the reason why we're having this problem.

I think we can safely ignore this error. My guess is that ip6tables tests fail on CircleCI because the ipv6 configuration is incomplete or missing. But on our laptops it works fine. It's difficult to know for sure though because the output of testinfra in CircleCI is not output. See https://circleci.com/gh/freedomofpress/securedrop/3095?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link for instance.
