### ISSUE TITLE
2FA reset page only talks about Google Authenticator

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#2499]
# Bug

## Description

The 2FA reset page only talks about Google Authenticator, we should suggest either Google Authenticator or FreeOTP or their favorite 2FA application there.

## Steps to Reproduce

Go to `/account/2fa`

## Expected Behavior

It should say to use Google Authenticator or FreeOTP or people's favorite 2FA application.

## Actual Behavior

Only tells me about Google Authenticator.

**Comment by heartsucker** [comment]
The problem with multiple recommendations (apart from support requests for others, possibly) is that when we localize strings, we shouldn't translate the English steps (e.g., "Tap 'scan code', then tap 'confirm'") because the localized strings in the app may be different. I'm all for using FOSS where possible, and if we want to recommend FreeOTP, we should *only* recommend that. Otherwise I think we should *only* recommend Google Authenticator.

**Comment by redshiftzero** [comment]
Good point @heartsucker - when this documentation is translated, the translators will need to ensure they are using the correct terminology in the Google Authenticator application. 

For the purposes of this page in our documentation, I think it's sufficient to simply make clear "the following steps are for Google Authenticator. The steps will vary if you choose to use FreeOTP or another application.".

**Comment by huertanix** [comment]
Generally, we've trained with Google Authenticator and only mention others in passing; There may be some way to indicate that there are other alternatives without having to go into the weeds on how to use them. e.g. "There's many options for 2FA apps but we use Google Authenticator for this example."

**Comment by kushaldas** [comment]
Closing this ticket as the document is already updated, problem solved.
