### ISSUE TITLE
Create a demo instance 

### ISSUE THREAD

**Issue by Hainish** [freedomofpress/securedrop#253]
It would be good to have an instance of SecureDrop just for demonstration purposes (either available on the public internet, as a Tor hidden service, or both) .  It could delete all the source directories and the database at a regular interval or upon request.  This would require some kind of external way to provide a GPG public key for the system.

**Comment by msjoinder** [comment]
@ageis sorry, I'm just seeing this now. Are you still interested in transferring SecureDropDemo.org ? Please contact me msjoinder@gmail.com with how I can help.

**Comment by garrettr** [comment]
@ageis Has posted a public demo of the current release (0.3.1) [here](https://securedrop.org/demo).

@ageis Do we still want securedropdemo.org? Or would it be better to shut it down?

**Comment by ageis** [comment]
Given that securedropdemo.org expires in October and we now have a demo at our main website, I don't think we need it. However, I e-mailed @msjoinder yesterday nonetheless to see if domain ownership could be transferred. If we do get control then we could just forward it to the new one, until the domain expires. Either way I think it would be good to shut down that old demo since it's running 0.2.

As I've set up the [demo page](https://securedrop.org/demo) with the instructions for logging in as a journalist, and added custom warnings to the [source interface](https://source.securedrop.org) not to submit real leaks. I've added it to the main menu of the SecureDrop website.

So this issue could be considered completed.
