### ISSUE TITLE
Determine FPF's container signing/validation story

### ISSUE THREAD

**Issue by msheiny** [freedomofpress/securedrop#2545]
# Feature request

## Description

As we start hosting and pushing user's to utilize more FPF built containers - we need to figure out the signing and verification story.

`Docker` currently utilizes [notary](https://github.com/theupdateframework/notary) which is based off [TUF](https://www.theupdateframework.com/). Our current docker repository host (quay.io) does not support [docker content trust](https://support.coreos.com/hc/en-us/articles/115000289114-Docker-Content-Trust-support) so we'd either have to move to docker hub and/or spin-up our own notary/repository server. As far as I can tell as well, it's annoying to do full off-line signing with notary though we could take advantage of a yubi key.

As far as I can tell, `Rkt` has [signing and verification via gpg](https://coreos.com/rkt/docs/latest/signing-and-verification-guide.html) though I've found bits and pieces alluding to adoption/evaluation of `notary` - it's telling that `notary` just got adopted by the Cloud Native Computing Foundation. I'm concerned that plain GPG verification lacks the additional benefits of using a TUF based solution - particularly protections against replay attacks, and support for delegation of specific keys. 

## User Stories

As a securedrop maintainer, I want to be able to push out containers that can be properly verified by end-users.

As a securedrop maintainer, I want to protect users against an attacker serving a securedrop instance out of date container dependencies.

As a securedrop admin, I want to ensure I am getting the latest securedrop updates with cryptographic verification.

**Comment by heartsucker** [comment]
Side note: notary does not support multiple signatures / thresholds at the moment. There's been some definite interest in adding support for that, but nothing concrete at the moment. Maybe @endophage can comment on that as it would be nice to have multiple FPFers have to sign off on things.

**Comment by heartsucker** [comment]
Also, last I looked, running a DTR of your own isn't free. We could host elsewhere, but I feel like that runs afoul of the "be responsible for your uptime" mantra.

**Comment by heartsucker** [comment]
*(I'm basically spamming comments now, sorry)*

Also, one of the big advantages of TUF is the existence of the snapshot metadata which pins other metadata as being current / compatible. Since we'd only have a few containers, and they'd all move in lockstep, aaaaand FPF controls all the containers and there's no outside contributors, it would be sufficient for us to use something other than TUF so long as it requires multiple signatures and supports expirations / rollback preventions.

**Comment by endophage** [comment]
Hey, the notifications for this thread got buried in my personal email. Thresholds have been delayed in notary solely due to any UX we've discussed being appallingly bad. It's a terribly complex experience for users.

As far as offline signing, I really want to see this happen via configurable local management of the TUF files rather than management via a remote notary server. There's a relatively short path to implementing that but I can't commit any time from my team to making it happen right now. If there's need and resources on your end, I'm happy to discuss what needs to happen there and commit to reviewing the PR :-)

**Comment by conorsch** [comment]
Right now we only use containers for development, testing, and package-building, not for running SecureDrop in production. In order to ensure integrity, we pin the image hash in the builder image, as seen in https://github.com/freedomofpress/securedrop/pull/5411/files 

We'll continue to follow what the ecosystem provides in terms of signing solutions for containers, but don't plan to migrate to any of the existing solutions at present.
