### ISSUE TITLE
Use monitoring server to check integrity of site pages

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#256]
We should run a script on the monitoring server (or a separate server) that periodically downloads SecureDrop pages over fresh tor circuits and check whether they've been tampered with. It's been suggested that this server terminate the power supply of the App Server immediately when it detects an attack.

This would allow us to more safely deploy host-served Javascript if we decide to do so, which is something that is being considered in #92.

**Comment by conorsch** [comment]
The information in this ticket is outdated. Since the last comment four years ago, we've implemented a third-party SecureDrop directory at https://securedrop.org/directory (http://secrdrop5wyphb5x.onion/directory). The directory is a static list of "verified" instances—meaning the news organization contacted FPF to request inclusion, and further asserted a list of truths enumerated in the [Instance Verification page](https://securedrop.org/instance-verification-form)—and the list is signed with a GPG key controlled by FPF staff. 

In #258, a more robust scanning solution is proposed that is already underway. As such, I'm closing this issue, since we do not plan to leverage the Monitor Server for scanning SecureDrop pages in the near future.
