### ISSUE TITLE
Compile a list of SD 'Success Stories'

### ISSUE THREAD

**Issue by Hainish** [freedomofpress/securedrop#257]
It would be great to have a list of success stories, where SD has been instrumental to getting a leak out.

**Comment by redshiftzero** [comment]
There have been a few recent public admissions of the use of SecureDrop for important stories - [here](https://twitter.com/Fahrenthold/status/785195210347163648) and [here](https://theintercept.com/2016/10/23/endace-mass-surveillance-gchq-governments/) - so this seems like it can be tackled now.

**Comment by fowlslegs** [comment]
https://www.wired.com/2015/11/securedrop-leak-tool-produces-a-massive-trove-of-prison-docs/

**Comment by redshiftzero** [comment]
This list of public stories that have come through securedrop seems like something that would best go on `securedrop.org` as at least another FAQ, added it to the FPF-internal TODO for that website revamp (SD-4). Feel free to add more here as they are announced

**Comment by conorsch** [comment]
Since this issue was opened, we've launched the SecureDrop Directory: https://securedrop.org/directory More recently, we've seen a ton of coverage on the project, including:

* [Nieman Labs report with ProPublica on using SecureDrop](http://www.niemanlab.org/2017/01/how-easy-is-it-to-securely-leak-information-to-some-of-americas-top-news-organizations-this-easy/)
* [Tow Center report on SecureDrop](https://towcenter.gitbooks.io/guide-to-securedrop/), which includes several explicit case studies of orgs using SD.

Honestly, I'm not sure that there's still an extent need to "Compile SD success stores"—I feel that's largely been done already, both by the community and by FPF. If anyone agrees (cc @redshiftzero @fowlslegs), go ahead and close this.

**Comment by redshiftzero** [comment]
Sure, makes sense. Closing!
