### ISSUE TITLE
Create a SD Directory Server to Audit and Enumerate instances

### ISSUE THREAD

**Issue by Hainish** [freedomofpress/securedrop#258]
This has been discussed in https://github.com/freedomofpress/securedrop/issues/92#issuecomment-26857005 - create a third party directory server to periodically scrape the SD instances out there, checking all active resources for malicious code injection using a standardized hashing mechanism.  If an instance is modified, alert the SD instance owner of the change.

The entire SD application can live in a JS browser application, but the one component that would still have to be provided by the server is the GPG key of the instance.  Thus the directory server should have a copy of the keys and check that the public key of the system is the same as well.

**Comment by dachary** [comment]
@conorsch is this resolved in the upcoming securedrop.org version ?

**Comment by conorsch** [comment]
@dachary Thanks for the ping!

Yes, the forthcoming overhaul of securedrop.org will implement an _automated_ scanner for both the Source Interface and the Landing Page for each known SecureDrop instance, similar in style to [Secure The News](https://securethe.news/). The development effort on the new scanner is ongoing, and we optimistically hope to ship in Q2 2018. 

As such, I'm closing this issue, as the final pieces are close to completion, and no code changes will be required to this repository in order to finalize implementation.
