### ISSUE TITLE
Virtualized Admin Workstation broken in Tails 3.3

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2598]
## Description

Tried to install a fresh Tails 3.3 Admin Workstation VM for SecureDrop QA and was unable to boot after install. This was on VirtualBox 5.2.0.

*Note:* I'm filing here instead of Tails repo because it's a virtualized-Tails-only issue and not something I was able to reproduce on hardware (I upgraded a hardware Tails device and created a fresh Tails device without issue). 

## Steps to Reproduce

0. Boot VM to a live Tails 3.3 iso. 
1. Apply changes to installer as described [here](https://docs.securedrop.org/en/latest/development/virtualizing_tails.html#install-tails). 
2. `sudo /usr/bin/tails-installer -u -n --clone -P -m -x` 
3. After install, reboot.

## Expected Behavior

You boot to Tails. 

## Actual Behavior

<img width="717" alt="screen shot 2017-11-21 at 12 19 25 pm" src="https://user-images.githubusercontent.com/7832803/33104183-a605e832-cedb-11e7-9f30-8297194a0e1f.png">

## Comments

Hey @kushaldas is this the same issue you saw?

**Comment by kushaldas** [comment]
This is exactly same error I am seeing on KVM.

**Comment by redshiftzero** [comment]
Err, oops, I have this working now. After install, open `/media/amnesia/Tails/syslinux/live*.cfg` and remove `live-media=removable` everywhere and that will resolve this. Marking as pending close until you confirm this resolves for you @kushaldas

**Comment by conorsch** [comment]
Had some trouble reproducing this under KVM—looks like a simple checkbox toggle resolved it for me.

Tails 3.3 boots fine from the ISO. After attaching a virtualized USB storage device and installing Tails 3.3 to, as [described in the Tails docs](https://tails.boum.org/doc/advanced_topics/virtualization/virt-manager/index.en.html#index5h1), the system didn't come up after a reboot. All I had to do was check a box to enable booting from the removable USB:

![tails-libvirt-boot-options](https://user-images.githubusercontent.com/657862/33155321-88ec906a-cfa4-11e7-963a-451086ee0c16.png)

Thereafter it worked fine:

![tails-libvirt-persistence-working-3 3](https://user-images.githubusercontent.com/657862/33155605-ae821c3a-cfa6-11e7-8875-4e96337b1ad9.png)

Cross-linking to #2204 since we'll need to document the boot option toggle.

**Comment by kushaldas** [comment]
I had the same option marked, now a final fresh install worked. But, all the updates failed to find the initramfs.

**Comment by redshiftzero** [comment]
We've got this resolved now :smile:
