### ISSUE TITLE
Language menu of source journalist lack spacing.

### ISSUE THREAD

**Issue by fpoulain** [freedomofpress/securedrop#2734]
Language menu of source journalist lack spacing.

Seen on http://source.demo.securedrop.club/ deployed from commit e4fded239f8b7358fc20db57f299a1c22ac5d249.

![capture d ecran de 2017-12-13 14 54 54](https://user-images.githubusercontent.com/32539071/33942534-8dab8c3c-e016-11e7-8fc2-520a8270ef2b.png)

Adding something like `margin-left: 1em;` in css makes it better:

![capture d ecran de 2017-12-13 14 56 44](https://user-images.githubusercontent.com/32539071/33942543-939c6bb6-e016-11e7-9d22-5c1ad694cddb.png)

**Comment by dachary** [comment]
We're going to remove the flags it seems https://github.com/freedomofpress/securedrop/issues/2734 . This is another way to get rid of this specific problem ;)

**Comment by dachary** [comment]
And also the source / journalist interface only is supported for the tor browser which is based on firefox. The problem you're seeing is chrome/ium only.

**Comment by fpoulain** [comment]
> The problem you're seeing is chrome/ium only.

No I use firefox. :)

**Comment by dachary** [comment]
Which version is it ?

**Comment by fpoulain** [comment]
Firefox ESR 45.8.0

**Comment by dachary** [comment]
I guess that's why: the version of Firefox is too old. Note that the actual user of SecureDrop will use the tor browser which updates automaticaly to the latest Firefox. Reason why no effort is made for browser compatibility. I'm not saying it's a good thing but it's definitely low in the list of priorities because it is a very marginal use case.
