### ISSUE TITLE
Modify testinfra to run against containerized dev env

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2736]
## Description

In #2523 @tmc contributed a containerized development environment :tada:. Currently this is not advertised due to some remaining issues that we need to fix. We should modify our [`testinfra`](https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html) development environment tests to run against the docker container. See `testinfra/test.py` - we should modify the `conn_type` to `docker` for the `development` target host. 

## User Stories

As a SecureDrop developer, I want all test suites to pass on the `develop` branch in my development environment.

**Comment by conorsch** [comment]
Totally willing to update the `testinfra/test.py` wrapper script to support the newer container logic. However, I must point out that since we've started using Molecule, we don't need the wrapper logic at all anymore—Molecule abstracts away the connection info used for targeted different backends, e.g. VMs and containers. But we can handle that further down the road.

**Comment by msheiny** [comment]
yeahh @conorsch brings up an excellent point here... in all of our www repos - we use molecule scenarios for the developer environments as well as CI. It's been working really great there.

**Comment by zenmonkeykstop** [comment]
Dev is very different from staging/prod envs, so testinfra results are not going to be too meaningful. Closing, but will reopen if/when the dev env is more aligned with production.
