### ISSUE TITLE
contributing: consider suggesting or enforcing the use of yapf for python code

### ISSUE THREAD

**Issue by tmc** [freedomofpress/securedrop#2785]
embracing a tool that encode code formatting rules would make the contribution experience nicer. yapf appears to be the best option for this category of tool.

**Comment by redshiftzero** [comment]
So we rarely if ever debate code style since we added flake8 linting in CI - would we want `yapf` do something beyond that? That said, it seems like if developers want a `go fmt`-like experience to automate fixing their code formatting they could use `yapf` themselves - it could make sense to add some documentation in the developer guide to that effect

**Comment by eloquence** [comment]
Superseded by #5551.
