### ISSUE TITLE
securedrop-admin sdconfig erases additional values in site-specific

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2955]
# Bug

## Description

securedrop-admin sdconfig erases values in site-specific when they are not prompted for. `securedrop-admin sdconfig` should not erase entries in site-specific, which would help testing (e.g.: releases that are in development or perhaps alpha/beta features).

## Steps to Reproduce

* edit `/install_files/ansible-base/group-vars/all/site-specific` and add another value
* run ./securedrop-admin sdconfig
* open `/install_files/ansible-base/group-vars/all/site-specific` and observe your value has disappeared

## Expected Behavior

`securedrop-admin sdconfig` should not erase entries in `/install_files/ansible-base/group-vars/all/site-specific`.

## Actual Behavior
`ecuredrop-admin sdconfig` erases entries in `/install_files/ansible-base/group-vars/all/site-specific`.

**Comment by dachary** [comment]
@emkll additional values that Ansible would use can be set in a (for instance) `install_files/ansible-base/group-vars/all/myvars` file and it will be loaded. This is indeed convenient for testing.

I think it is good that `site-config` is owned by `securedrop-admin sdconfig` (in the sense that there is no other way to edit it), but it is entirely possible that I missed a use case.

Is there a specific reason that I'm missing for such variables to be in the `site-specific` file ?

**Comment by emkll** [comment]
@dachary This came up when I was testing https://github.com/freedomofpress/securedrop/pull/2803, which required some journalist email specific variables in `site-specific`. This behavior may also come up during development of new features, and perhaps in production, where admins use extra variables to store potentially useful information (e.g. `smtp_relay_old`). I opened this issue because I think it's a regression compared to the behavior of the old `securedrop-admin sdconfig` , but I understand this is more of an edge-case scenario.

**Comment by dachary** [comment]
@emkll thanks a lot for filling this, it would have been problematic if discovered after the release. The regression is as follows:

* An admin stored extra variables in `site-config` (they should not and it is best served in another file but it is entirely possible that they did)
* The admin key is updated to 0.6
* The admin runs `securedrop-admin sdconfig` (for whatever motive)
* The extra variables in `site-specific` are silentely removed
* The admin runs `securedrop-admin install` and unexpectedly modifies the production instances because the variable is no longer in `site-specific`, leading to unknown regressions

I propose that it is fixed as follows:

* `securedrop-admin sdconfig` loads `site-specific`
* for each top level YAML variable it does not know a message is displayed (**WARNING: custom variables must not be stored in `site-config`, it should be stored in another file and will have the same effect***)
* when `securedrop-admin sdconfig` it keeps the unknown variables instead of removing them

An alternative would be to write all unknown variables into another file `custom-variables`. But I'm not a fan of this option as it would likely confuse the admin expecting the variables to be in `site-specific`.

**Comment by emkll** [comment]
That approach makes sense to me @dachary. The alternative `custom-variables` option is not only confusing but may lead to more issues (`.gitignore`?).

Perhaps the error message could also be worded to suggest the user entered a valid (non-custom) but misspelled variable name in`site-specific`.
