### ISSUE TITLE
Application integration tests fail in local staging environment

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2980]
# Bug

## Description

Application integration tests fail in local staging environment.

## Steps to Reproduce

* `make build-debs`
* `vagrant up staging`
* `sudo su www-data -s /bin/bash`
* `cd /var/www/securedrop`
* `pytest -v tests/`

## Expected Behavior

All tests should pass.

## Actual Behavior

Integration tests fail due to selenium/Firefox WebDriver exception:

```
E               WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpJDEyXO If you specified a log_file in the FirefoxBinary constructor, check it for details.

/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py:108: WebDriverException
```
Full trace here: https://gist.github.com/emkll/e3767437a0aee4c3c40765789d267545

**Comment by dachary** [comment]
The tests pass when run as root. A faster reproducer is:
<pre>
pytest -v  tests/functional/test_admin_interface.py::TestAdminInterface::test_admin_interface
</pre>
Looking at /var/log/syslog while the test run does not show any apparmor messages. The tests/logs/firefox.log does not contain any error message. It is likely a permission problem silentely ignored by selenium.

**Comment by dachary** [comment]
`/usr/bin/firefox -foreground` is run by selenium but does not connect to the Xvfb server, presumably because `install_files/ansible-base/roles/restrict-direct-access/templates/rules_v4` strictly restricts what the `www-data` is allowed to do. Connecting via TCP to port 6001 is not allowed. And if we added an exception, we would have to add another one so the selenium drive can connect to the port open by firefox to allow remote control.

Maintaining these exceptions to carefully tailored iptable rules and possibly apparmor rules as well does not seem to be the right way to approach this. Maybe running as root is ok.

When we run as root, the successful run of the tests does not say anything about errors related to permissions. But it is a valuable confirmation that the installed files are sane and that there is nothing obvious missing.

@emkll what about changing the instructions to run as root ? If this is not a good idea for some reason, we should list the pros and cons of running as www-data.

**Comment by redshiftzero** [comment]
The application tests ran as root will change the permissions of files that the `www-data` user needs to access - you can see this occurring in issue #2634 (which produced follow up #2636). Since the root user running the full unit and functional test suite will get passing tests, but will render those staging VMs unusable for interactive manual testing via Tor Browser, what about we suggest to run as root but we include a note indicating that currently you can either:

* Preserve interactive manual testing by running the test suite as the `www-user` (and note there will be failures of the functional tests), or

* Run automated test suite as root in the staging environment, noting that it will render the VMs unusable for interactive manual testing.

This is a bit convoluted, but I believe this is the best path forward as it enables us to run the full test suite in the staging environment, provides clear guidance to the developer, and doesn't introduce any further deviation between staging and production (i.e. via customizing iptables rules).

**Comment by dachary** [comment]
@redshiftzero good point ! What about adding a `chown -R www-data /var/lib/securedrop /var/www/securedrop` in the instructions, with a note explaining why this is necessary ?

**Comment by redshiftzero** [comment]
Ah nice - that's a better solution :+1:
