### ISSUE TITLE
Prevent automated submissions (CAPTCHA)

### ISSUE THREAD

**Issue by klpwired** [freedomofpress/securedrop#3]
Changed name due to debate over whether CAPTCHA is right method to use. Consensus is on developing a responsive approach that combines several methods, including CAPTCHAs.

**Comment by heartsucker** [comment]
Marking as "Pending close" as this either requires as 3rd party (unacceptable) or adding a lib (something we try to avoid to keep the app lean in the name of security / auditability).

If we look at the current state of captchas using Google and CloudFlare as the prime examples, they a complex system of identifying images that are unlikely to be repeated for a given user. This is not something SD could support. The other "I'm not a robot" mouse-tracking-click-thing is also not an option because 1) JavaScript, and 2) requires all the fancy ML stuff to match it to known human patterns. Also not easy to support. That leaves us with some Python libs that general messy text for humans to decipher. Getting the complexity high enough that a computer can't beat it makes it too hard for humans too these days. This was realistic option for SD in 2013, but I think it's not anymore.

Last, if someone really wants to overload SD, Tor is likely to be the bottle neck. Someone could script the submission and still have a human solve the captcha and be able to overload the network and/or fill the disk in a day or two.

**Comment by conorsch** [comment]
Great summary, @heartsucker. I'll add that to date we have not received any support requests from organizations running SecureDrop in production to add a CAPTCHA. So far, all the discussion toward this feature has assumed that organizations demand it—but we haven't heard that yet.

@ioerror's point from years ago:

> I suggest that rather than making is harder to upload, find a way to make it easier to sort out lots of irrelevant stuff on the back end.

Still rings true to my ear, and jives well with the workstation refresh we're looking at.

**Comment by redshiftzero** [comment]
I agree with @heartsucker in that it is challenging to devise a CAPTCHA that both:
* uses no third parties _and_ 
* wouldn't be trivial to defeat for an attacker capable of using e.g. Selenium to automate submissions to SecureDrop

The better solution is indeed to enable journalists to quickly sort through submissions (either manually via a smoother journalist workflow on the [Qubes workstation](https://github.com/freedomofpress/securedrop-workstation) - or in the future potentially by learning characteristics of spam submissions). Since a CAPTCHA isn't the right approach here I'm closing.
