### ISSUE TITLE
`make test` fails because of cached/compiled python files

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3024]
# Bug

## Description

`make test` outputs:

```
__________________________________________________________ ERROR collecting test_secure_tempfile.py __________________________________________________________
import file mismatch:
imported module 'tests.test_secure_tempfile' has this __file__ attribute:
  /vagrant/securedrop/tests/test_secure_tempfile.py
which is not the same as the test file we want to collect:
  /home/heartsucker/code/freedomofpress/securedrop/securedrop/tests/test_secure_tempfile.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

## Steps to Reproduce

Run `make test` when there are compiled/cached python resources.

## Expected Behavior

There should be no resources in the container that reference the host.

## Actual Behavior

Cached resources with references to the host contaminate the container.

## Comments

`make test` should clean up resources before building the docker image.

**Comment by dachary** [comment]
So, this actually is the same problem with vagrant and it happens because the .pyc were created with /vagrant/securedrop as the root of the repository although they reside in the directory in which the checkout was made. If you run tests locally on the host and then try to run them in vagrant, you will experience the same failure.

The one time workaround is to **find . -name '*.pyc' | xargs rm**

**Comment by dachary** [comment]
Note that the files are not copied into the docker image and ignoring pyc while building the image won't solve that.
