### ISSUE TITLE
Improve input validation in `manage.py`

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#3071]
# Feature request

## Description

* The [sh](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/manage.py:L35) function as well as the translate function it [helps](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/manage.py:L35) could benefit from further validation of the [messages.pot](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/translations/messages.pot) file before invoking `sh`.

* Two commands appear to be invoked with an unneeded shell
https://github.com/freedomofpress/securedrop/blob/develop/securedrop/manage.py:L315
https://github.com/freedomofpress/securedrop/blob/develop/securedrop/manage.py:L362
However, removing the `shell=True` causes  `tests/test_i18n.py::TestI18N::test_i18n` to fail with `OSError: [Errno 2] No such file or directory.` 

While these features are only used by translation maintainers,  they require maintainers to be diligent in handling translation files while merging them into the codebase (see https://github.com/freedomofpress/securedrop/pull/3042).

## User Stories

As a translations maintainer, I was to ensure that malicious code within a translations file does not not execute unwanted code.

**Comment by heartsucker** [comment]
Marking this as `easy` since this is relatively contained to a single part of the code even though solving it might be a bit of a challenge.

**Comment by usmanmuhd98** [comment]
I would like to work on this issue.

**Comment by dachary** [comment]
@usmanmuhd98 consider yourself assigned!

**Comment by usmanmuhd98** [comment]
I was going through the code. It is that the shell is invoked for the git operations which do not run when shell=False. To avoid that problem, I think the git library in python may help.
If not, how else should I validate the input?

**Comment by heartsucker** [comment]
I would personally reject a PR that pulled in the whole git lib for this because that's too much for this simple thing. I think we can do some manual validation ourselves and (ideally) yank the `shell=True` line from the subprocess call.

**Comment by Anonymous26** [comment]
@usmanmuhd98 what is the status of this issue? Let me know If you are not working then i would like to give it a shot.

**Comment by dachary** [comment]
@Anonymous26 I think you can give it a shot since there has not been activity in the past two weeks. @usmanmuhd98 if you're also working on it, please speak up now :-)

**Comment by usmanmuhd98** [comment]
@Anonymous26 You can go ahead.
@dachary I am caught up with quite a lot of college work. Maybe I can take up a different issue once I am free.

**Comment by octaflop** [comment]
Presently working on this during PyCon 2018 Sprints!

**Comment by octaflop** [comment]
End of day update on this issue:

Basically, the `sh()` method is referenced in a number of places (including the tests), so swapping to `shell=False` isn't nearly as easy as it would seem on the surface. I've started re-writing a few commands at a time to some success (eg, the `pybabel` call in `translate_messages()`), but a better approach may be to refactor the commands to use `os` python functions for file manipulation and only call `subprocess.Popen` in specific instances.

An even more robust approach would involve directly calling the [`babel.messages` low-level extraction interface](http://babel.pocoo.org/en/latest/api/messages/extract.html) instead of the command-line interface for babel. The API to directly call babel's `extract` isn't as nice as the command-line interface, so it's not as big of a deal. 

I also noted that babel has some explicit documentation for adding it to a distutils setup: http://babel.pocoo.org/en/latest/setup.html#extract-messages which may be an alternative approach to importing translations.

I've only started looking at securedrop's code today, so I may be missing out on some important historic reasons for adding a separate util for handling translations.

One last note: In my humble opinion I don't think this should be labeled as `easy`. There are a few hidden moving parts which complicate this issue.

I'll take another crack at this tomorrow (EDT) and see what I can come up with, but I figured I'd get these observations down in case someone else starts down this issue.

**Comment by dachary** [comment]
@octaflop I agree this is not easy. The i18n_tool.py helper is meant to abstract the gory details of i18n for scripting. Back when @emkll created this issue, this script was part of manage.py which is a script deployed with SecureDrop and used in production. It deserves a lot of attention and my guess is that it is the primary reason why avoiding using shell snippets was suggested.

However i18n_tool.py was later extracted from manage.py and is never used in production, only for development. It may be worth reconsidering the benefits of removing the shell snippets in favor of more complicated and possibly more secure python equivalents.
