### ISSUE TITLE
Attempting to change a password right after logging in errors out

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3173]
# Bug

## Description

Part of the login hardening on SD is preventing OTP token reuse. This means if you login and within the 30 second window attempt to change your password (or take another action that requires token authentication), then you will receive an error message that may not be helpful.

## Steps to Reproduce

1. Login
2. Immediately attempt to change your password

Or

Run `test_user_edits_password_success_response` without login hardening disabled.

## Expected Behavior

Login hardening only affects the actual login.

## Actual Behavior

Login hardening affects the entire app.

**Comment by heartsucker** [comment]
Attempting to fix this breaks a lot of tests, and we might have to wait until we have finished moving everything over to pytest. The reason this has worked for so long is we've been mocking the token verification to always return true (which imo has always felt a little dangerous).

**Comment by redshiftzero** [comment]
Thanks for filing this @heartsucker. In the case you describe, the error message produced is indeed not helpful. This is what happens when I use a valid password and 2FA token (reused from login less than 30 seconds ago):

<img width="787" alt="screen shot 2018-03-16 at 10 34 48 am" src="https://user-images.githubusercontent.com/7832803/37535670-ad07f77c-2905-11e8-9a51-5ed4e59bde5c.png">

Due to our 2FA reuse prevention (independent of the setting of `LOGIN_HARDENING`), the login fails. As a user, I might be confused by this if I was certain I used the correct password and 2FA code.

Since the intention behind requiring the password and 2FA token for a password change is to ensure the user is in control of valid login credentials (i.e. not an attacker in control of a stolen session) prior to changing their password (covering the scenario described in section "Test Password Change" [here](https://www.owasp.org/index.php/Testing_for_weak_password_change_or_reset_functionalities_(OTG-AUTHN-009))), this behavior seems reasonable. However the error message could be phrased similarly to what is done on login when a user attempts to use a previously used token:

<img width="791" alt="screen shot 2018-03-16 at 11 01 18 am" src="https://user-images.githubusercontent.com/7832803/37537105-c9e59d28-2909-11e8-9a3c-fb12afa66a0b.png">

Perhaps "User validation failed. Please wait for a new code from your two-factor token or application before trying again."? What do you think?

**Comment by heartsucker** [comment]
I think that would be a simple fix, but I think it would be possible to split `Journalist.login` to `Journalist.validate_credentials` where the former does hardening (token reuse, rate limiting) plus what the latter does (pw & token correct). I think this would solve it, but that's also more code. I was going to hold off on this until I got more of the tests sorted out since I think we might hit more related bugs/oddities as we enable OTP protection in more of the tests.

**Comment by eloquence** [comment]
Wording tweaks may still be helpful, but as pointed out in https://github.com/freedomofpress/securedrop/issues/3173#issuecomment-373800636 the original error message does warn about token re-use. PRs welcome to tweak wording, but closing this issue since this is an edge case that seems already reasonably well-handled.
