### ISSUE TITLE
Link GitHub accounts and stuff to Liberapay

### ISSUE THREAD

**Issue by rugk** [freedomofpress/securedrop#3217]
It is very hard to verify that [your Liberapay profile](https://liberapay.com/SecureDrop/) is really legitimate and actually belongs to securedrop. That only one user (and community) is a member of the team is already irritating.
Secondly it does not link to the wmain website (https://securedrop.org/) nor does the main website link to the Liberapay profile. 

Also the GitHub repo or at least Twitter account or so is not linked to Liberapay. As such, there is no easy way to verify this belongs to Securedrop and not someone impersonates you. Please at least link these official accounts.

**Comment by dachary** [comment]
@rugk thanks for this bug report, there is a need for clarification, deeply sorry for the frustrating experience. I hopefully improved things and [opened a thread in the forum to discuss further changes](https://forum.securedrop.club/t/clarification-of-the-liberapay-endorsement/570). Since this is not a technical bug I'm closing this issue and invite you to continue the dicussion in the forum.

**Comment by dachary** [comment]
Not closing as it may be perceived as dismissive. @rugk please let me know if closing this issue is ok with you ;-)

**Comment by rugk** [comment]
Ah, yes, sure. :smiley:

**Comment by dachary** [comment]
Cool, thanks!
