### ISSUE TITLE
[journalist-api] Rebase journalist-api branch to develop

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3236]
In preparation for working on the journalist-api for 0.9.0 (which we'll need for Qubes OS workstation features), we need to rebase the current branch, since it predates some major refactoring. 

This is part of the #1761 epic.

**Comment by redshiftzero** [comment]
done in [`journalist-api-0.9.0`](https://github.com/freedomofpress/securedrop/compare/journalist-api-0.9.0), I converted the unit tests to pytest, used the same slug on the journalist interface for sources (`filesystem_id`) instead of the primary key, and modified the reply endpoint to expect pre-encrypted replies (since we can have the clients encrypt to the sources public key). After we release 0.8.0 (i.e. in the next sprint) I'll add developer docs and make a PR
