### ISSUE TITLE
Set a more secure gpg.conf

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3266]
# Feature request

## Description

The default GPG configurations are somewhat reasonable, but we should force specify exactly the hash algorithms and ciphers we want. For example:

```
personal-cipher-preferences AES256 AES192 AES
personal-digest-preferences SHA512 SHA384 SHA256 SHA224
cert-digest-algo SHA512
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES Uncompressed
```

## User Stories

As a cypherpunk, I don't want all of SecureDrop's goodness undone by crappy GPG configurations.

**Comment by ThinkingMonkeyv2** [comment]
As NOT a cypherpunk (that's something you get labeled, not appoint yourself as BTW) but as a person that has common sense and can read I'd like to ask what part of that gpg.conf do you think is "crappy"? 

The personal cipher list is set as strong as possible, the same for digest and cert digest. The preference list is listed "strongest" to "not quite the strongest" with no other settings for the config file listed here. There may be some really crappy, unsafe settings, but who knows what's included in the rest of the file. It appears this is everything.

As far as SecureDrop, it has some extremely bad press. And you didn't mention it costs money. Linus Torvalds has publicly called the "clowns" and their code "garbage", a pretty damning statement from the man who controls the kernel that the SecureCode guys are trying to patch. He's asked them repeatedly to submit updates properly and they refuse.

He's asked them to break the updates into manageable chunks instead of massive, impossible-to-work-with messes and they publicly refuse.

They want to operate under the GPL license because they have to then publicly accuse developers of copyright infringement (huh?) when they try to make SecureCode fit their needs. Admittedly, at least one developer stripped the copyright notice from the code, which wasn't very nice, but still.

So out of the two things here, a solid gpg.conf and a claim that SecureCode has "goodness", the evidence shows that SecureCode is missing any "goodness" that may be present on this page.

**Comment by heartsucker** [comment]
That gpg conf I provided was the suggestion for what we should use. We manually set many of the configurations ourselves, and the suggestion was that it might be wise for us to control the GPG configs ourselves.

As for your other concerns, the forum is a better place to address those instead of this ticket: https://forum.securedrop.club/

**Comment by redshiftzero** [comment]
the ciphersuites/compression options we have set are the following (this is from `CryptoUtil.gpg._prefs`):

```
'SHA512 SHA384 SHA256 AES256 CAMELLIA256 TWOFISH AES192 ZLIB ZIP Uncompressed'
```

These are all reasonable and secure ciphersuite choices as of Feb 2019, so I'm going to close this. Please re-open if there's a more specific action here!
