### ISSUE TITLE
Investigate broadening CircleCI build access

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3288]
*Originally filed in our infrastructure repository on 2017-10-16, migrating here for visibility/discussion.*

SecureDrop maintainers should have the ability to restart/kill CI builds. Currently they do not.

# User Story

As a maintainer, I want to be able restart or kill builds in case of problems, so I'm not bottlenecked on others doing so.

**Comment by eloquence** [comment]
We touched base at the engineering meeting on 4/19 about this. @msheiny will investigate what our options are. @harrislapiroff reported that he _is_ able to restart builds on another repo without being the owner.

**Comment by msheiny** [comment]
After some investigation with faux accounts, this seems to be accessible (as @harrislapiroff noted) but any user with write access to the repository. @dachary / @kushaldas - in order to do this you have to sign into circleci when you go to the build page using the OAuth Github link. You should then be able to drill into the workflow and re-run jobs.

Here is an example of where to find that... (Note the link below that says `Workflow: securedrop_ci`
![image](https://user-images.githubusercontent.com/1727935/39016484-204210fe-4410-11e8-939a-d555c1121e65.png)

If you follow the workflow , you'll get to the following page where you can either rerun everything or `rerun failed jobs`. Whenever @kushaldas  or @dachary ping me for re-running i typically run that task so it only runs the tasks that failed again.

![image](https://user-images.githubusercontent.com/1727935/39016530-3cee21ca-4410-11e8-904e-d3a76afa9a51.png)

**Comment by dachary** [comment]
I confirm I have access. Awesome !

**Comment by eloquence** [comment]
Excellent. Let's wait for @heartsucker or @kushaldas to confirm and then we can close this.

**Comment by heartsucker** [comment]
Confirmed access :D

**Comment by eloquence** [comment]
Hooray! Closing this issue. @kushaldas please speak up if this explanation doesn't work for you. :)
