### ISSUE TITLE
Debian package securedrop-app-code is not getting upgraded

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#3316]
# Bug

## Description

In my prod vm `securedrop-app-code` package is not getting upgraded.

## Steps to Reproduce

Follow the QA steps to fetch the latest packages from apt-test repo.

## Expected Behavior

We should get the 0.7~RC1 packages.

## Actual Behavior

```
$ dpkg -al | grep secure
ii  openssh-client                       1:6.6p1-2ubuntu2.10                        amd64        secure shell (SSH) client, for secure access to remote machines
ii  openssh-server                       1:6.6p1-2ubuntu2.10                        amd64        secure shell (SSH) server, for secure access from remote machines
ii  openssh-sftp-server                  1:6.6p1-2ubuntu2.10                        amd64        secure shell (SSH) sftp server module, for SFTP access from remote machines
ii  secure-delete                        3.1-6                                      amd64        tools to wipe files, free disk space, swap and memory
ii  securedrop-app-code                  0.6                                        amd64        Packages the SecureDrop application code pip dependencies and apparmor profiles. This package will put the apparmor profiles in enforce mode. This package does use pip to install the pip wheelhouse
ii  securedrop-config                    0.1.1+0.7.0~rc1                            all          Establishes baseline system state for running SecureDrop.
ii  securedrop-grsec                     4.4.115+r1                                 amd64        Metapackage providing a grsecurity-patched Linux kernel for use
ii  securedrop-keyring                   0.1.1+0.7.0~rc1                            amd64        Provides an apt keyring for SecureDrop-related packages, so the master signing key used for SecureDrop packages can be updated via apt.
ii  securedrop-ossec-agent               2.8.2+0.7.0~rc1                            amd64        Installs the securedrop pre-configured OSSEC agent
ii  ssh-import-id                        3.21-0ubuntu1                              all          securely retrieve an SSH public key and install it locally
```

```
$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  securedrop-app-code
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

```

**Comment by kushaldas** [comment]
It seems if I manually do a `sudo apt-get update` and then `sudo apt upgrade`, it pulls in the right dependencies and the upgraded package.

**Comment by kushaldas** [comment]
In my latest testing I could not reproduce this error. I am closing this issue.

**Comment by redshiftzero** [comment]
Do you understand why this only happens in some situations? `cron-apt -s -i` always does an `apt-get update` first, no?

**Comment by kushaldas** [comment]
>Do you understand why this only happens in some situations? cron-apt -s -i always does an apt-get update first, no?

Yes (about doing that `apt-get update` by `cron-apt -s -i`), but, for some reason it failed for me once, I am guessing the same happened to you too.

**Comment by msheiny** [comment]
yeah im able to also reproduce this on my instance... digging

**Comment by msheiny** [comment]
Sooo I think this might be by design on debian's side ... I'm having trouble finding links explaining this behavior but as an analogy it seems to be similar to how permissions work on Android apps:

* You have an app `Foo` that you previously installed
* New updates to `Foo` come in without new permission changes and can be automatically updated
* Say one day `Foo` updates but is now requiring access to your `Camera` ... Android wants you to manually approve that change in underlying app dependency.

[This article](https://debian-administration.org/article/69/Some_upgrades_show_packages_being_kept_back) had a really good quote summing this up:

>  If I may try to rephrase: 'Apt-get dist-upgrade'ing also installs new packages brought in the chain of dependencies, whereas 'apt-get upgrade'ing only install newer versions of packages already installed. After a couple of years working with Debian, I never managed to exactly understand that difference. Would you believe I never found documentation who states this as simple?


Still diggin into solutions here

**Comment by redshiftzero** [comment]
Hmm interesting - but then how did we add dependencies before? For example, when we added the [`securedrop-keyring`](https://github.com/freedomofpress/securedrop/commit/75961546e0078ed0c3ad47e8d67bb4a94c78bc2a#diff-8f4b8b485ba54d091bf0bd9e34f6b86b) package as a dependency of the `securedrop-app-code`?

**Comment by dachary** [comment]
Back when [-o Dir::Etc::SourceList=/etc/apt/security.list](https://github.com/freedomofpress/securedrop/commit/dd9137cf1a5aeb8f6186b326f0f519b4efe42b03) in 2014, it does not look like it was for a specific reason. At least it was not explained in the commit history and there was not other discussions archived.

Unless someone has an issue with using Ubuntu repositories other than security repositories during upgrades, could we remove this option?

**Comment by conorsch** [comment]
@dachary I'm in favor of permitting upgrades for all installed packages. See #3376 for that discussion.

**Comment by conorsch** [comment]
Since we're excavating old commits, @dachary, I'll take this opportunity to point out that the decision to use `cron-apt` over the more typical `unattended-upgades` seems to have been motivated by the lack of a properly configured "Origin" field in the Release file: https://apt.freedom.press/dists/trusty/Release. That's a backend config setting, one which we can easily correct and therefore switch to using unattended-upgrades, if desired. The migration effort may not be worthwhile, but the problems reported here may have been more easily discoverable if we had been using unattended-upgrades, which enjoys much more robust documentation.

**Comment by redshiftzero** [comment]
Continued discussion over in #3376 (as this will get closed soon)
