### ISSUE TITLE
Update threat model in docs & enumerate mitigation strategies

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3349]
We have a threat model doc based on SecureDrop 0.3, here:

https://docs.securedrop.org/en/stable/threat_model/threat_model.html

We should update this document in two ways:
- [ ] Ensure that current information is still relevant and prune/update as appropriate
- [ ] Include enumeration of current mitigation against specific threats (why does SecureDrop implement feature/characteristic X: to mitigate against threat Y)

@emkll has done extensive internal threat modeling which is at a level of detail not appropriate for the docs, but should serve as a source. This will be less granular than what's described in #2335, but will be a good starting point for further improvements.

# User Stories

As a SecureDrop administrator, I would like to be able to receive up-to-date information about SecureDrop's threat model, so that I better understand why it works the way it does and what it protects against.

As developers and maintainers of SecureDrop, we want to provide up-to-date threat model information, so that we can increase the likelihood that news organizations follow best security practices (it's harder to follow practices if you don't understand the motivation behind them).

**Comment by eloquence** [comment]
Hey @olivemartini, just checking in -- is this still something you'd like to work on?

**Comment by olivemartini** [comment]
^Whoops hello!
I have the following restructure of the threat model outlined in a Google Doc, which has been reviewed in part by @emkll and @redshiftzero.

When speaking with colleagues about the best way to distill a larger threat model document for our public documentation, we conferred and decided that the best way forward was to organize the attacks and countermeasures by attack area, (attack area>attacks on said area>countermeasures leveled on said area) in a table format.

I'm happy to lodge a PR with what I have once I format it (halfway done and totally neglected on my machine) so that it is prepped for other folks to take during an upcoming sprint.
