### ISSUE TITLE
[0.7.0] Journalist and admin notifications can group and cause "SecureDrop Submissions Error"

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3368]
## Description

While trying to reproduce #3367, I discovered a related issue, where a "SecureDrop Submissions Error" is sent to the administrator.

## Steps to Reproduce

1. Enable journalist notifications.
2. Reboot the app server (I just powered off the VM)

## Expected Behavior

No journalist notification is sent

## Actual Behavior

A notification entitled "SecureDrop Submissions Error" is sent to the administrator, clipped:

```
OSSEC HIDS Notification.
2018 May 04 06:35:13

Received From: (app) 10.0.1.4->netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort
Rule: 533 fired (level 7) -> "Listened ports status (netstat) changed (new port opened or closed)."
Portion of the log(s):

ossec: output: 'netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort':
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:54579           0.0.0.0:*               LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::34144                :::*                    LISTEN     
Previous output:
ossec: output: 'netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort':
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:35431           0.0.0.0:*               LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::34203                :::*                    LISTEN     



 --END OF NOTIFICATION



OSSEC HIDS Notification.
2018 May 04 06:35:13

Received From: (app) 10.0.1.4->head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'
Rule: 400600 fired (level 1) -> "Boolean value indicating if there were submissions in the past 24h."
Portion of the log(s):

ossec: output: 'head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'':
1
```

## Comments

I found a similar issue during [review](https://github.com/freedomofpress/securedrop/pull/2803#discussion_r170430840), that should be the first thing to investigate

**Comment by redshiftzero** [comment]
Ah, so we assumed [here](https://github.com/freedomofpress/securedrop/pull/2803#discussion_r170454765) that the "level 1" and "level 7" are sent separately, but this is not accurate, so we need another method to prevent alert grouping.

**Comment by dachary** [comment]
Shoot. I'll work on that first thing in the morning tomorrow.

**Comment by kushaldas** [comment]
I rebooted (forced reboot) my prod vm a couple of times, but, could not reproduce this. No emails.

**Comment by redshiftzero** [comment]
So this bug results from two underlying issues: 

1. The journalist emails are sent on boot. This is bug #3367. 
2. The journalist notifications can group with admin alerts under some previously not understood situations. 

Digging more into the second issue, OSSEC notifications are grouped by default. This is set by `maild.groupping=1` in [internal_options.conf](https://github.com/ossec/ossec-hids/blob/v2.8.2/etc/internal_options.conf#L57). It looks like this what this option does is when there is an event that will trigger a notification, OSSEC will [wait and group together alerts](https://github.com/ossec/ossec-hids/blob/v2.8.2/src/os_maild/maild.c#L404) if they are close together in time (within 5 seconds).

However, if you toggle `maild.groupping=0` in `internal_options.conf`, then we should not get the "SecureDrop Submissions Error" as we don't go into the [if statement seen here](https://github.com/ossec/ossec-hids/blob/v2.8.2/src/os_maild/maild.c#L404) and instead just send the mail [seen here](https://github.com/ossec/ossec-hids/blob/v2.8.2/src/os_maild/maild.c#L427). 

To test this, I set this option (`maild.groupping=0`) and I did _not_ hit the "SecureDrop Submissions Error" as seen previously. 

The downside is that this might generate more OSSEC alerts in the situation where we get a storm of alerts at once and they are all grouped into a single email.

**Comment by dachary** [comment]
For the record I'm looking at [email-alerts-config.c](https://github.com/ossec/ossec-hids/blob/v2.8.2/src/config/email-alerts-config.c) and more generally trying to get an understanding of how [do_not_group](http://ossec-docs.readthedocs.io/en/latest/syntax/head_ossec_config.email_alerts.html?highlight=grouping#element-do_not_group) works.

**Comment by dachary** [comment]
The [do_not_group](http://ossec-docs.readthedocs.io/en/latest/syntax/head_ossec_config.email_alerts.html#element-do_not_group) element is used in [ossec.conf server side](https://github.com/freedomofpress/securedrop/blob/develop/install_files/securedrop-ossec-server/var/ossec/etc/ossec.conf#L138)

<pre>
  &lt;email_alerts>
    &lt;email_to>root@localhost&lt;/email_to>
    &lt;rule_id>400600&lt;/rule_id>
    &lt;do_not_delay />
    &lt;do_not_group />
  &lt;/email_alerts>
</pre>
so the [mail triggered by the daily notification rule](https://github.com/freedomofpress/securedrop/blob/develop/install_files/securedrop-ossec-server/var/ossec/rules/local_rules.xml#L194) is not grouped with another email alert:
<pre>
&lt;group name="Ossec daily notifications">
  &lt;rule id="400600" level="1" >
    &lt;if_sid>530&lt;/if_sid>
    &lt;options>alert_by_email&lt;/options> &lt;!-- force email to be sent -->
    &lt;match>ossec: output: 'head -1 /var/lib/securedrop/submissions_today.txt&lt;/match>
    &lt;description>Boolean value indicating if there were submissions in the past 24h.&lt;/description>
  &lt;/rule>
&lt;/group>
</pre>
However...  this is apparently ignored or ineffective for some reason.

**Comment by dachary** [comment]
The [sendmail.c](https://github.com/ossec/ossec-hids/blob/v2.8.2/src/os_maild/sendmail.c#L55) debug flag is set at compile time and [maild.c](https://github.com/ossec/ossec-hids/blob/v2.8.2/src/os_maild/maild.c) does not implement debug messages.

**Comment by dachary** [comment]
After running
<pre>
./testinfra/test.py app-staging
</pre>
the file ``/var/ossec/logs/alerts/alerts.log`` contains:
<pre>
** Alert 1525519439.229786: mail  - Ossec daily notifications
2018 May 05 11:23:59 (app-staging) 10.0.1.2->head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'
Rule: 400600 (level 1) -> 'Boolean value indicating if there were submissions in the past 24h.'
ossec: output: 'head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'':
0
</pre>

**Comment by dachary** [comment]
On the mon server it is possible to verify the **do_not_group** option is indeed taken into account by doing the following:

Tmux window 0

<pre>
$ sudo service postfix start
$ sudo service ossec stop
$ sudo postsuper -d ALL
$ sudo strace /var/ossec/bin/ossec-maild -f -dddd
</pre>

Tmux window 1

<pre>
$ sudo cat >> /var/ossec/logs/alerts/2018/May/ossec-alerts-05.log <<EOF

** Alert 1525529439.229786: mail  - Ossec daily notifications
2018 May 05 13:23:59 (app-staging) 10.0.1.2->head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'
Rule: 400600 (level 1) -> 'Boolean value indicating if there were submissions in the past 24h.'
ossec: output: 'head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'':
0

** Alert 1525529439.229786: mail  - Ossec daily notifications
2018 May 05 13:23:59 (app-staging) 10.0.1.2->head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'
Rule: 400600 (level 1) -> 'Boolean value indicating if there were submissions in the past 24h.'
ossec: output: 'head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'':
0
EOF
$ sudo mailq
# see two mails to journalist@ossec.test
</pre>

Repeat the above after commenting out the **do_not_group** in ``/var/ossec/etc/ossec.conf``
<pre>
  &lt;!-- Ossec daily notifications -->
  &lt;email_alerts>
    &lt;email_to>root@localhost&lt;/email_to>
    &lt;rule_id>400600&lt;/rule_id>
&lt;!--
    &lt;do_not_delay />
    &lt;do_not_group />
-->
  &lt;/email_alerts>
</pre>
and verify that
* no mail is sent immediately
* after a minute one mail is sent instead of two (the other is silently ignored)

**Comment by dachary** [comment]
@redshiftzero if you are able to repeat the problem, could you please also provide the content of the most recent ``/var/ossec/logs/alerts/*/*/ossec-alerts-*.log`` file? After testing a few combinations and reading the [maild.c](https://github.com/ossec/ossec-hids/blob/v2.8.2/src/os_maild/maild.c) code, I'm unable to reproduce the problem. The code is contorted but does seem to cover all corner cases and I'm puzzled by the aggregation of the two alerts into a single mail.

Thanks!

**Comment by redshiftzero** [comment]
Thanks for looking into this issue @dachary, I have confirmed that `do_not_group` is indeed set in the following stanza:

```
  <!-- Ossec daily notifications -->
  <email_alerts>
    <email_to>root@localhost</email_to>
    <rule_id>400600</rule_id>
    <do_not_delay />
    <do_not_group />
  </email_alerts>
```

is in `/var/ossec/etc/ossec.conf` but I'm looking at this again in prod VMs and I'm continuing to see the "SecureDrop Submissions Error" due to grouped alerts on some reboots. Here's the tail of `/var/ossec/logs/alerts/alerts.log`:

```
** Alert 1525637904.10667: - Ossec start notifications
2018 May 06 20:18:24 (app) 10.0.1.4->ossec
Rule: 400503 (level 1) -> 'This alert overrides 503 to suppress daily email alerts to admins.'
ossec: Agent started: 'app->10.0.1.4'.

** Alert 1525637904.10900: mail  - ossec,
2018 May 06 20:18:24 (app) 10.0.1.4->netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort
Rule: 533 (level 7) -> 'Listened ports status (netstat) changed (new port opened or closed).'
ossec: output: 'netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort':
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:37294           0.0.0.0:*               LISTEN
tcp6       0      0 :::111                  :::*                    LISTEN
tcp6       0      0 :::44352                :::*                    LISTEN
Previous output:
ossec: output: 'netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort':
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:48638           0.0.0.0:*               LISTEN
tcp6       0      0 :::111                  :::*                    LISTEN
tcp6       0      0 :::37312                :::*                    LISTEN

** Alert 1525637904.11923: mail  - Ossec daily notifications
2018 May 06 20:18:24 (app) 10.0.1.4->head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'
Rule: 400600 (level 1) -> 'Boolean value indicating if there were submissions in the past 24h.'
ossec: output: 'head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'':
0
```

which produces this (decrypted) "SecureDrop Submissions Error" email:

```
gpg: encrypted with 4096-bit RSA key, ID 0x[...], created [...]
      "[...] <[...]>"

/var/ossec/process_submissions_today.sh failed to find 0/1 submissions boolean in the following OSSEC alert

>From ossec@freedom.press  Sun May  6 20:18:28 2018
Return-Path: <ossec@freedom.press>
X-Original-To: root@localhost
Delivered-To: root@localhost
Received: from notify.ossec.net (mon-prod [127.0.0.1])
	by ossec.server (Postfix) with SMTP id D12D41211ED;
	Sun,  6 May 2018 20:18:28 +0000 (UTC)
To: <root@localhost>
From: OSSEC HIDS <ossec@freedom.press>
To: <root@localhost>
Date: Sun, 06 May 2018 20:18:28 +0000
Subject: OSSEC Notification - (app) 10.0.1.4 - Alert level 7
Message-Id: <20180506201828.D12D41211ED@ossec.server>


OSSEC HIDS Notification.
2018 May 06 20:18:24

Received From: (app) 10.0.1.4->netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort
Rule: 533 fired (level 7) -> "Listened ports status (netstat) changed (new port opened or closed)."
Portion of the log(s):

ossec: output: 'netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort':
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:37294           0.0.0.0:*               LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::44352                :::*                    LISTEN     
Previous output:
ossec: output: 'netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort':
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:48638           0.0.0.0:*               LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::37312                :::*                    LISTEN     



 --END OF NOTIFICATION



OSSEC HIDS Notification.
2018 May 06 20:18:24

Received From: (app) 10.0.1.4->head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'
Rule: 400600 fired (level 1) -> "Boolean value indicating if there were submissions in the past 24h."
Portion of the log(s):

ossec: output: 'head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'':
0



 --END OF NOTIFICATION
```

**Comment by dachary** [comment]
I'm able to reproduce the problem with the provided content, every time. Cool :-)

**Comment by dachary** [comment]
**Note** in the following the timestamp following **Alert** is set in the distant future so alerts are always parsed and acted upon.

The following does **not** trigger an error, it sends one mail per alert as expected.

<pre>
cat >> logs/alerts/2018/May/ossec-alerts-07.log <<'EOF'
** Alert 1625693173.315226: mail  - ossec,syscheck,
2018 May 07 11:39:33 mon-prod->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
Integrity checksum changed for: '/var/ossec/etc/ossec.conf'
Size changed from '6442' to '6455'
Old md5sum was: '7c1f892fce8df29d304356e13b721748'
New md5sum is : '685ce9610b46c1c5581b35157539d426'
Old sha1sum was: '6b75ff00c135101d474bad5e151dcea6500edc8a'
New sha1sum is : '3cd01be22a8ed70de92aaead01d2ad11d3fe1d6a'

** Alert 1625637904.11923: mail  - Ossec daily notifications
2018 May 06 20:18:24 (app) 10.0.1.4->head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'
Rule: 400600 (level 1) -> 'Boolean value indicating if there were submissions in the past 24h.'
ossec: output: 'head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'':
0

EOF
</pre>
The following produces a single mail that contains **both** alerts instead of just one
<pre>
cat >> logs/alerts/2018/May/ossec-alerts-07.log <<'EOF'
** Alert 1625637904.10900: mail  - ossec,
2018 May 06 20:18:24 (app) 10.0.1.4->netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort
Rule: 552 (level 7) -> 'Listened ports status (netstat) changed (new port opened or closed).'
ossec: output: 'netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort':
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:37294           0.0.0.0:*               LISTEN
tcp6       0      0 :::111                  :::*                    LISTEN
tcp6       0      0 :::44352                :::*                    LISTEN
Previous output:
ossec: output: 'netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort':
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:48638           0.0.0.0:*               LISTEN
tcp6       0      0 :::111                  :::*                    LISTEN
tcp6       0      0 :::37312                :::*                    LISTEN

** Alert 1625637904.11923: mail  - Ossec daily notifications
2018 May 06 20:18:24 (app) 10.0.1.4->head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'
Rule: 400600 (level 1) -> 'Boolean value indicating if there were submissions in the past 24h.'
ossec: output: 'head -1 /var/lib/securedrop/submissions_today.txt | grep '^[0-9]*$'':
0

EOF
</pre>

**Comment by dachary** [comment]
Filed a bug report against OSSEC https://github.com/ossec/ossec-hids/issues/1416

**Comment by dachary** [comment]
I can't reproduce the problem, I was testing against prod on the development branch which does the following:

* install 0.6 packages # because I did not tell it to take the apt-test packages
* install the process_submissions_today.sh script in /var/ossec/ which fooled me into thinking 0.7.0 packages were installed

The alerts are grouped into a single mail because the [required ossec.conf + rules](https://github.com/freedomofpress/securedrop/issues/3368#issuecomment-386787302) are not in the 0.6 packages. Back to square one.

**Comment by dachary** [comment]
For the record, @kushaldas & @redshiftzero managed to reproduce it as follows:

On the app server

*   edit var/ossec/etc/ossec.conf for email to journalists in every 3 minutes (so that I can see them).
*   echo 1 > /var/lib/securedrop/submissions_today.txt
*  rebooted the app server
* and one case I also rebooted the mon again

@redshiftzero sent me the content of the ossec.log containing the alerts and despite injecting them in a mon I was not able to reproduce the problem.

**Comment by dachary** [comment]
it could be a race condition when writing the log file while reading is going on
which would explain why I'm not seeing it when writing wiht cat : too fast
and why it only happens at boot time: because the two alerts come in sequence
and why it does not always show: because the race has to be lost which is by definition not always
and [src/shared/file-queue.c](https://github.com/ossec/ossec-hids/blob/v2.8.2/src/shared/file-queue.c) has no lock

**Comment by dachary** [comment]
Hum, reading read-alert.c I don't see how that theory would work. The file is append only.

**Comment by redshiftzero** [comment]
Note that myself and @kushaldas were only able to reproduce this (and only intermittently even then) when the journalist notification time was dramatically increased. We _could not_ reproduce this issue with the notification time at 24 hours. 

A commit was added in #3384 by @dachary to mitigate this issue - as such I'm closing this for now.
