### ISSUE TITLE
Consider replacing chroot jails with Xen

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#338]
I've been using the [Qubes](http://qubes-os.org/trac/wiki) operating systems recently, and I've been very impressed with it. It uses the Xen hypervisor to let you easily run different programs in their own VMs, and it includes some cool tricks like sharing the same read-only root filesystem between VMs, so that if one of them gets compromised and system files get modified, they don't persist a VM reboot.

It appears that Xen does a better job of isolation than chroot jails do. If we replaced the source/document chroot jails on the app server with Xen VMs instead, we wouldn't have to be concerned with things like not listening on the same network port, and the root user inside each VM wouldn't have direct access to hardware ([on systems that support VT-d](http://qubes-os.org/trac/wiki/UserFaq#CanIinstallQubesonasystemwithoutVT-d)). Attackers would need to break out of the Xen VM before they could leave a persistent rootkit, which isn't true with the current chroot setup.

If we assumed that Xen didn't contain any vulns that could be exploited to break out of a VM, I think it would also be safe to make the monitor server just a third VM, making it so SecureDrop could be installed on a single physical server. But we can't assume that, so we should keep two physical servers.

Thoughts?

**Comment by garrettr** [comment]
We got rid of the chroots in 0.3 because they were no longer necessary. Therefore, this issue is no longer valid and can be closed.

The discussion in this issue is semi-relevant in the context of potential future efforts to compartmentalize the Application Server to reduce attack surface, which was one of the recommended "long term solutions" proposed by iSec in their recent [audit](https://freedom.press/securedrop-files/iSEC_OTF_FPF_SecureDrop_Deliverable_v1.2.pdf) of SecureDrop.
