### ISSUE TITLE
Admin interface

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#344]
It would be useful if there were an admin web interface, in addition to source and document interfaces, that let organizations customize their SecureDrop instance.

It could let them:
- Set an organization name (so the HTML title isn't always SecureDrop, but rather something like "The Intercept - SecureDrop")
- Upload a logo/header image
- Add custom submission instructions/other blocks of text
- Add a custom footer

This would also be a good place to let admins manage journalist users as well:
- Add new users (creates new authenticated hidden services and Google Auth tokens), and also set their public key for #98 
- Regenerate credentials for a user
- Revoke user privileges
- Maybe import/export all user data, to facilitate a fresh install

This could simplify the installation process too. Rather than specifying journalist users ahead of time during installation, it could just give the admin access to this interface.

**Comment by redshiftzero** [comment]
Of the features here, most of them have now been implemented, and we have filed more specific followups for the issues that are still to be completed:

> Set an organization name (so the HTML title isn't always SecureDrop, but rather something like "The Intercept - SecureDrop")

Tracked in #1575

> Upload a logo/header image

Added in #2769

> Add custom submission instructions/other blocks of text

Tracked in #3044

> Add a custom footer

Tracked in #1967

> Maybe import/export all user data, to facilitate a fresh install

Tracked in #606 

All of the admin interface features regarding adding/removing new users and regenerating credentials was added in #522.

In terms of the OSSEC data, since the application server cannot modify contents of the monitor server, we cannot easily add these features to the Admin Interface. If there is a specific suggestion for doing so, it should be suggested in a followup issue.

Closing in favor of these scoped issues.
