### ISSUE TITLE
[0.7.1] QA the release candidate(s)

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3445]
Part of epic #3443. From approx. May 21 to June 1, we should test the release candidate(s) for 0.7.1, including with hardware instances running in likely kernel downgrade configurations to ensure a downgraded kernel is not incorrectly upgraded. Depending on QA results, we should create new RCs as appropriate. 

If by May 28 we are not confident in the release, we should postpone it, since the pre-release announcement is otherwise scheduled to go out on May 29.

**Comment by emkll** [comment]
The following test suite should be run in various scenarios:
* paxtest blackhat
* spectre/meltdown test
* Run an end-to-end submission test
* Check syslog
* reboot
* check syslog
* keep online for 24+h
* check syslog + ossec alerts

The following scenarios should be tested to over as many real-world situations as possible:
[ ] Install on VMs
[ ] Install on Mac Mini
[ ] Install on NUC
[ ] Test upgrade scenario on MacMini or NUC
[ ] Test on hardware (MacMini, Nuc or other) w/ rolled back (3.14) kernels (ensure the 3.14 kernel boots)

**Comment by emkll** [comment]
Two (significant) issues have come up so far with 4.4.132 kernels so far, that do not appear to be config-related (through several attempts, including using the current config w/ 4.4.132)

* Clean install: `securedrop-app-code` install failed during the postinst phase. `service apache2 stop` did not properly stop the apache processes. `apache2ctl stop` however, was able to stop the process. Currently investigating. 

* Upgrade install on rolled-back (3.14 kernels using [this](https://docs.securedrop.org/en/stable/upgrade/0.5.x_to_0.6.html)): Since 4.4.115 kernels are not uninstalled, Rolled back instances will boot in 4.4.115 after the upgrade to 0.7.1. Perhaps changing the package relationship between metapackage and kernel package

**Comment by conorsch** [comment]
Reporting successful upgrade testing from 0.7.0 prod VMs to 0.7.0~rc1 running 4.4.132-grsec. Have not yet attempt a "clean install" as @emkll reports, will try that next. Early results, however, show that the postinst changes @emkll wrote for inclusion in 0.7.0~rc1 seem to resolve the issue.

**Comment by dachary** [comment]
> 0.7.0~rc1

Did you mean **0.7.1~rc1** ?

**Comment by eloquence** [comment]
Due to issues with 4.4.132, we've decided to wait for at least 4.4.133 and defer this to 0.8.0.

**Comment by dachary** [comment]
> Due to issues with 4.4.132

Are these issues documented?

**Comment by redshiftzero** [comment]
@dachary the issues so far are in a comment by @emkll [here](https://github.com/freedomofpress/securedrop/issues/3445#issuecomment-390754380) - @emkll I believe this is up to date, if not please comment here!
