### ISSUE TITLE
[ci upgrade testing] Investigate use of Google Cloud for nested virtualization

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3451]
As part of #1689, we are interested in using Google Cloud for automated upgrade testing. We have to verify that we can use the required nested virtualization with libvirt within Google Cloud VMs. This ticket is intended to capture the findings related to this investigation.

**Comment by msheiny** [comment]
This task has been completed. It was super easy to do. Under estimated the hours a bit... but I did do a little more than a standard test. Big thanks to @redshiftzero for carrying the torch over with `tor` testing. 

Guide was closely followed from [here](https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances) and [here](http://www.brianlinkletter.com/enable-nested-virtualization-on-google-cloud/) 

* First off, I had to make a new image with a special license attached. Note that there is no additional charge for this. I started off with a stretch image:
```bash
gcloud compute images create nested-vm-image2 \
  --source-image-project debian-cloud --source-image-family debian-9  \
    --licenses
    "https://www.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx"
```

and then i created an instance in a zone that supported haswell processors (i looked this up beforehand)

```bash
gcloud compute instances create nesttest --zone us-east1-d --machine-type
n1-standard-1 --min-cpu-platform "Intel Haswell" --image nested-vm-image2
--boot-disk-size 60 --boot-disk-type "pd-ssd" --boot-disk-device-name "nest-1"
```

and then i ssh'd to that machine andddddd installed the following apt packages:
```
$apt-get install -y build-essential libssl-dev libffi-dev python-dev     dpkg-dev git linux-headers-$(uname -r) libvirt0 vagrant-libvirt vagrant-mutate qemu-kvm libvirt-clients libvirt-daemon-system libvirt-daemon virtualenvwrapper
```

and then added my user to the libvirt groups
```bash
$ sudo usermod -a -G libvirt mike
$ sudo usermod -a -G libvirt-qemu mike
```

restarted libvirtd
```bash
$ sudo service libvirtd restart
```

and then cloned in securedrop, created a virtualenv, blah blah.. vagrant up /staging/.

The only issue encountered was that it was a little slow... i think i was hitting the memory limit on my 3.5 GB ram machine... and we initially hit a tor issue which @redshiftzero apparently fixed by sshin' into the machine and enabling tor debug mode... So yeah that was weird. I suspect it was a transient `tor` issue. But i'm marking this missions successful and pressing forward.
