### ISSUE TITLE
[ci upgrade testing] Create a no-op Google Cloud spin-up and tear-down CI task

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3452]
To scaffold local automated upgrade testing within CI (epic #1689), we want to create a no-op CI Google Cloud image spin-up and tear-down task that can run in CI. This will not yet pull any SecureDrop related code, but just a base image with the required dependencies for nested virtualization. 

This task includes coming up with a caching strategy.

Blocked on findings from #3451.

**Comment by msheiny** [comment]
This is becoming an increasingly annoying ticket.... I think I'm going to switch scope here.

* gce ansible module requires `libcloud` which requires `pycrypto` (see #1609 )
* molecule gce driver doesnt support random gce instance names ... which i find problematic because it blocks us from using multiple CI runners in the future.
* it just came to me... if we aren't using this in circleci ... why do we need spin up logic coded here? why not just handle this in [jenkins](https://plugins.jenkins.io/google-compute-engine) similar to how it spins up AWS instances for us as builders ? This would allow us to not use up two builder slots... one for the kick off the job which starts up a GCE instance to run the job and instead ... just start running assuming we are already on a GCE host.

**Comment by msheiny** [comment]
For my research next week... i did a manual test with jenkins and getting gce nodes spin-up was a piece of cake with the google compute engine plugin. Now I have to automate that config by closely matching the logic I have for AWS nodes. Looks like both plugins utilize the jenkins concept of `clouds` and the original groovy script should match very closely. Heres some research items for next week that i need to follow up on:

* Reference groovy script for ec2 --> https://github.com/freedomofpress/ansible-role-jenkins-config/blob/master/templates/ec2_cloud.groovy
* Reference for `InstanceConfig` -> https://github.com/jenkinsci/google-compute-engine-plugin/blob/master/src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java#L42
* Reference for `GoogleEngineCloud` --> https://github.com/jenkinsci/google-compute-engine-plugin/blob/master/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineCloud.java#L70

**Comment by msheiny** [comment]
I got a pending PR ready for review at https://github.com/freedomofpress/ansible-role-jenkins-config/pull/10 . I'm moving onto other issues unless something new comes up here during review.
