### ISSUE TITLE
Submission Key

### ISSUE THREAD

**Issue by this-is-ian** [freedomofpress/securedrop#3493]
# Bug

## Submission Key Password

The password that we have configured on our submission key does not appear to be valid when attempting to decrypt messages on the Viewing Station. 

## Steps to Reproduce

Receive a message through our SecureDrop instance. Journalist station downloads the message and copies to the transfer device. Transfer device is then connected to the the Viewing Station.

## Expected Behavior
Decryption of messages and files.

## Actual Behavior
We will either receive an incorrect password when prompted to enter or some appear to be unzipped and write files. Some messages do appear to automatically unzip however, those files open to a blank document when double-clicked.

## Comments
Is there a way to reset this key password?

**Comment by conorsch** [comment]
We received private contact from the user above, regarding this same issue, and responded via our [support portal](https://securedrop-support.readthedocs.io/en/latest/index.html). As such, I'm closing this issue.

For anyone else who finds this issue seeking to troubleshoot, note that the [project documentation](https://docs.securedrop.org/en/release-0.7/generate_securedrop_application_key.html) does not recommend setting a passphrase on the submission key. If you wish to rotate the key (for example, to a key without a passphrase), follow the docs on generating a submission key, then:

1. Copy the public key to the Admin Workstation, replacing the old key.
2. Note the fingerprint for the new pubkey.
3. Run `./securedrop-admin sdconfig` and update the fingerprint when prompted.
4. Run `./securedrop-admin install` command in order to place the key on the server.

You can verify that the new key is in place by confirming display of the fingerprint on the Source Interface. Then, make sure to send a test submission, and verify you can decrypt it on the SVS.
