### ISSUE TITLE
[reply refactor] Allow journalists to download replies from journalist interface

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3674]
After #3673 is implemented, we should allow journalists to download replies from the journalist interface UI. Note that for long-running SecureDrop instances, there will be old replies encrypted only to the source key that should be unavailable for download.

Epic: #3097

**Comment by emkll** [comment]
Since we now want to indicate that the replies can be downloaded, I suggest we make the style similar to source messages and mark journalist replies as `read` by default and changed the icon to the right of the checkbox on the left side as the reply icon as such:

### Current (journalist replied can't be downloaded)
![current](https://user-images.githubusercontent.com/15223328/43596156-773c10d8-964c-11e8-8815-8337ec069d65.png)
### Proposed (journalist replies can be downloaded)
![proposed](https://user-images.githubusercontent.com/15223328/43595569-023053cc-964b-11e8-87ab-4a9fb023e5e0.png)

Happy to change/rollback the design to whatever seems most user-friendly.

Now that we will be preserving journalist replies, we cannot rely on deletion for the read receipt (https://github.com/freedomofpress/securedrop/issues/3675). Perhaps we should consider adding an icon to the right side of the document (perhaps something like :heavy_check_mark: ) to indicate the source has marked the reply as read?

**Comment by redshiftzero** [comment]
proposed design looks great! i also like the UX suggestion for #3675. another idea: we could re-use the opened/closed envelope icons
