### ISSUE TITLE
[reply refactor] Preserve conversation history between sources and journalists

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3675]
In order for journalists to view the conversation history between sources and journalists, when a source deletes the journalist reply from the _source inbox_, it should not delete the reply from the _journalist's_ inbox. This is a major UX win for journalists while preserving the current behavior of minimizing data available if a source codename is compromised. 

We could do this by adding a column to the replies table that `allow_source_read` (`default=True`) or something similar that we can filter by when showing replies to sources. When the source deletes the reply from their inbox, we set this to `False`. 

Epic: #3097

**Comment by eloquence** [comment]
In #3097 it was noted that the message in the source interface ("[Deleting replies] also lets us know that you are aware of our reply") is inaccurate. If we have the `allow_source_read` column, we could potentially also use this to indicate to the journalist that a reply has been read and acknowledged by the source.

At the risk of complicating things, I think there's a case to do so, since a savvy journalist who paid attention to the deletion status of replies to infer source activity would no longer be able to do so after this change.

I suggest we add a follow-up issue for that, where we could discuss the best way to address the UX (both for the web interface and the graphical client). If we don't get to that before 0.9.0, we can remove the inaccurate sentence from the source interface for now.
