### ISSUE TITLE
Include `fingerprint` in the `key` object in a `Source` response

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3911]
## Description

To easily manipulate and reference PGP keys using GPG or GPG-wrappers, we need to know the key's fingerprint. It may make sense for the server to calculate this for us and send it as part of the response.

**Comment by redshiftzero** [comment]
we should implement this as part of resolving https://github.com/freedomofpress/securedrop-client/issues/363. The reason why is because the existing logic on the client side parsing stdout to get the key fingerprint needs modification when we use the qubes RPC service for importing keys. This is a symptom of the fact that parsing stdout to get key fingerprints is pretty brittle. We should just expose the fingerprint via the API.
