### ISSUE TITLE
Expiration date on PGP key leaks date of source's first contact

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3912]
## Description

When we autogen PGP keys, the expiration is set to 1 year. This can be used to infer the date a source first used SD. We may want to remove this expiration field altogether to get around this issue.

**Comment by garrettr** [comment]
Mind if I take this one? :)

**Comment by garrettr** [comment]
Note that GPG keys also embed a [Creation Date](https://www.gnupg.org/documentation/manuals/gnupg-devel/Unattended-GPG-key-generation.html), which defaults to the current system time at the moment the key is generated; however, like the expiration date, it is also customizable.

**Comment by garrettr** [comment]
Additional thought: should we be specifying an expiration date on SecureDrop's internal reply GPG keys at all? The keys are managed by the server and never made accessible to anybody else. Allowing them to expire seems like it would create problems (e.g. a long-term user returns and can no longer receive replies because their reply key has expired) without any benefit (keys are managed by the server anyway). What do you think, @heartsucker?

**Comment by garrettr** [comment]
One more thought: should we add some code to randomize the creation and expiration dates for reply keys that have already been created on existing deployments?

**Comment by redshiftzero** [comment]
> Additional thought: should we be specifying an expiration date on SecureDrop's internal reply GPG keys at all? 

Good point, we should just have keys not expire

> should we add some code to randomize the creation and expiration dates for reply keys that have already been created on existing deployments?

Hmm so I think one needs the passphrase of the private key to modify the expiration date / created on fields (worth double checking). If that's true, then we could add a method to `crypto_util.py` to check and update the expiration date / created on fields and run it after login (when `g.codename` is available). This won't handle the case if a user doesn't log in for a year, but there's not much we can do about that. What do you think @garrettr? Let me know if you think of a better place for this logic. 

The nice thing about this migration being in the app code (otherwise I would wonder whether it's worth the trouble) is that writing unit tests to cover this scenario is pretty straightforward.

**Comment by garrettr** [comment]
> This won't handle the case if a user doesn't log in for a year, but there's not much we can do about that. 

Yup, I think that's the best/only option available to us given the other design constraints. Would you prefer I implement in the PR I'm about to submit for this issue, or would it be better to do it in a follow-up?

**Comment by redshiftzero** [comment]
I think it's worth getting the fix to remove the expiration date / created on fields in first (since it can cause a bug) and then we can tackle the removal of those fields after login for existing sources in a followup

Smaller PRs are best PRs :)

**Comment by redshiftzero** [comment]
Hmm, I suspect the diff between 1 and 2 is pretty small? Along those lines, I slightly worry about randomizing the times, e.g. for creation time it seems safest to just set the creation time to a certain date in the past (e.g. Jan 1 2010 or something equally arbitrary before the creation of SecureDrop). 

Agreed on a separate PR/issue for 3
