### ISSUE TITLE
have /journalists API endpoint

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3925]
## Description

We need to be able to list all current journalists if we want to be able to have clients show the sender of a message in the situation where multiple journalists are involved in a conversation with a single source.

(Related ticket: https://github.com/freedomofpress/securedrop-client/issues/76)

## User Stories

As a user of the SecureDrop client, I want to know which of my colleagues have already messaged a particular source.

**Comment by heartsucker** [comment]
Additionally, we should probably include a `/journalist/<uuid:id>` endpoint just for consistency.

**Comment by redshiftzero** [comment]
we worked around this by exposing the journalist UUID and username on each reply so that the conversation flow can be constructed client-side, I'm going to close this for now until we decide we need to expose this information (right now only admins can see all other onboarded users to SecureDrop, so if we were to do this we'd probably want to do it under an admin API endpoint, which we currently have none of)
