### ISSUE TITLE
Prevent automated submissions (CSRF)

### ISSUE THREAD

**Issue by klpwired** [freedomofpress/securedrop#4]
EDIT: Renamed title to reflect current discussion.

**Comment by garrettr** [comment]
There are a lot of interesting ideas and discussion in this issue; however, it is unfocused and the goal is unclear. Here's an update on how things stand in the current version of SecureDrop (0.3.1):

1. We use cookies for session management, because it makes development much simpler. The cookies are signed, and are used in conjunction with hidden form fields to implement CSRF protection (via [flask-wtf](http://flask-wtf.readthedocs.org/en/latest/csrf.html)).
2. DoS/automated submissions are not really related topics. We will continue to track DoS mitigation strategies in other issues.

Therefore, this issue is no longer relevant and it can be safely closed.
