### ISSUE TITLE
Unclear as to whether admin workstation has to be dedicated computer

### ISSUE THREAD

**Issue by iqlinuxadmin** [freedomofpress/securedrop#4307]
I'm setting up a new SecureDrop installation, which I'll be administering.  The journalist will be someone other than me.  I'm trying to understand whether I can use my "every-day laptop" booted into tails to administer SecureDrop, or whether I should use a separate dedicated workstation.  
This page https://docs.securedrop.org/en/release-0.11.1/overview.html says "Journalist Workstation: The every-day laptop that the journalist uses for their work."

This page 
https://docs.securedrop.org/en/release-0.11.1/hardware.html says "Dedicated physical computers for the Admin, Journalist, and Secure Viewing Station that can boot to Tails. At minimum this is 2 computers."
And it says ""At least 1 physical computer that is used as a workstation for SecureDrop admins and/or journalists."

What is confusing to me is this:
The journalist can use their every day laptop
The journalist and admin workstation can be the same computer.
That might imply that the admin workstation can be an everyday computer.  Bottom line is I'd love to be able to do admin from my everyday laptop, BUT I want to adhere to best practices, which I suspect that is not.

**Comment by iqlinuxadmin** [comment]
This https://docs.securedrop.org/en/release-0.11.1/set_up_admin_tails.html also implies the admin workstation doesn't have to be a dedicated machine: "After you boot the Admin Workstation Tails USB on your normal workstation."

**Comment by conorsch** [comment]
@iqlinuxadmin Thanks for calling this to our attention! You're right that we could be clearer in the docs about what's appropriate in terms of hardware selection. To answer your question, yes, it's fine to use an "everyday laptop" for the Admin Workstation. 

In practice, the primary concerns to consider in hardware choice for the Workstations are:

1. **Compatibility with Tails.** Not every "everyday laptop" will work well with Tails, so make sure to test. Recent Apple laptops in particular can be tricky, due to lack of full-size USB ports, high-DPI screens, or trackpad sensitivity.
2. **Interruptions to daily workflows unrelated to SecureDrop maintenance.** It may _appear_ convenient to be able to reuse the Admin's primary laptop for managing SecureDrop, but having to reboot into Tails and lose access to workplace communication channels such as email may result in unacceptable gaps in coverage for other (non-SecureDrop) admin duties. 

Depending on your environment, it may be appropriate to provision hardware and confine its use to a secure room, with limited access only to trusted SecureDrop Journalists and Administrators. That way, the same physical hardware can be reused for Journalist or Admin Workstation duties. Such a setup may not be appropriate, however, if some of the Admins are remote, lacking regular on-site access to the same secure room where the Journalist Workstation and SVS are stored. 

Hope that explanation is helpful, @iqlinuxadmin. Don't hesitate to ask for further clarifications. We'll aim to have a small docs update in soon to improve the docs for others in the process of setting up.

**Comment by zenmonkeykstop** [comment]
Hi @iqlinuxadmin, thanks again for flagging this - I've submitted a small PR that will hopefully make things a bit clearer.
