### ISSUE TITLE
remove unneeded  email headers from ossec alerts

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#442]
Postfix is currently sending the mail agent, user id and hostname of the as part of the ossec alert smtp headers which should be removed. Reported by @iSec

**Comment by garrettr** [comment]
@dolanjs Followed @ageis's recommendation from the previous comment to strip these headers. An Ansible task was added to place `/etc/postfix/header_checks` in 5fd464ada46de2b3eeafffaef750638354985c11 and `/etc/postfix/main.cf` was updated in 339bd72d0ed33a4775ca2dc35f256e370e65228d. I am not sure why this issue was not updated when those changes were made, but it is resolved now.
