### ISSUE TITLE
Message to flagged sources without keys can still be improved

### ISSUE THREAD

**Issue by rmol** [freedomofpress/securedrop#4453]
## Description

We can still improve the explanation a source sees when the system was too busy to generate a GPG key for them.

In translation work for 0.13.0, it was [suggested](https://weblate.securedrop.org/translate/securedrop/securedrop/nb_NO/?checksum=1e543c0620e21f71#comments) that this:

`Our SecureDrop recently experienced a surge of activity. For security reasons, the creation of a two-way communication channel was delayed until you checked in again.` 

is confusing because of the tense, the vagueness of "security reasons", and using "check in" instead of "log in".

[Also](https://weblate.securedrop.org/translate/securedrop/securedrop/nb_NO/?checksum=97cf88f29dc1f8f2#comments):

`Please rest assured that we were able to download your submission, and check back again later for a reply.`

could more clearly confirm that we received the submission.

Here's my suggestion, to kick off the festivities:

`When you created your account, our SecureDrop was very busy and had to defer the creation of the encryption key we need to securely reply to you. That key is now being created. Your submission was securely received, so please log in again soon to check for our reply.`

References:
- [previous work](https://github.com/freedomofpress/securedrop/issues/4420)

**Comment by ninavizz** [comment]
Thanks for this ticket John, lots to unpack! Ultimately, this flow needs to go into user testing to refine the message. Much of the content in the Source Experience is problematic—for exactly that reason. 

I'm not worried about "Log In" vs "Check In" and separately want to change login it to "Check In" anyway, since the spoken-to interaction does not match common mental models of a login/signin. But, again—that needs user testing. 

We're also intentionally vague around "security reasons" because it's important to not get all techno-specific with users... because we expect many to not know what a security or encryption key is. 

Anywho—this is a great example of the importance of testing stuff for comprehension before it gets deployed. Really looking forward to improving this, and all the other messaging in SD... but it's not a quick nor easy process.

**Comment by eloquence** [comment]
Deferring further work on this for now until we've had a chance to investigate if we can get rid of entropy checks entirely (#1584), which would enable us to remove this feature.

**Comment by ninavizz** [comment]
Let's tackle this in #4967, or better yet—kill the entropyfail schtick altogether via #1584 !!

**Comment by eloquence** [comment]
Closing in favor of #1584, which we may be able to address as part of the Focal transition.
