### ISSUE TITLE
Duplicate Source Interface session triggers server error

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4458]
## Description

Initiating more than one SecureDrop session in the Source Interface at a time causes a Server Error for the second session, and causes the first session to be invalidated.

## Steps to Reproduce

1. Launch the Docker-based SecureDrop development environment;
2. Visit http://localhost:8080/generate twice, in two separate private browser tabs.
3. Click "Submit" in the first tab
4. Click "Submit" in the second tab

## Expected Behavior
I can submit messages or documents.

## Actual Behavior

In the second tab, the following error message appears:

> Server error
> Sorry, the website encountered an error and was unable to complete your request.

In the first tab, subsequent page loads take me to the login screen: http://localhost:8080/login

**Comment by eloquence** [comment]
It's not entirely clear to me what the correct behavior in this case _should_ be. Intuitively, I think it should invalidate the older session, in the unlikely even that it was initiated by a different user, and start a new session.

**Comment by DrGFreeman** [comment]
I've started investigating this issue.

My understanding so far is that, despite using two private browser windows or tabs, both share the same session and the [`session['codename']`](https://github.com/freedomofpress/securedrop/blob/62f7d224217add9959ef0708b00ab2b3ccd810f4/securedrop/source_app/main.py#L40) variable gets the value of the last codename generated (whether through opening a new window or tab, or by clicking the button to generate a new codename in any of the open windows or tabs).

For example, if I perform the following steps in order:
1. Click "Get Started" in *window_1*,
1. Click "Get Started" in *window_2*,
1. Click "Submit Documents" in *window_1*,
1. Click "Show" (codename) in *window_1*

*window_1* shows the codemane that is displayed in *window_2*.

I can then proceed with submitting a document in *window_1* however if I noted the codename shown in *window_1* at step 1 above, I will not be able to log back-in using that codename since the actual codename that was in the `session['codename']` variable when the new Source entry was generated is the one generated in *window_2* (generated after the one in *window_1*).

The error (satus code 500) that occurs following the steps in "Steps to Reproduce" above is because the codename from *window_2* already exists when the [`/create`](https://github.com/freedomofpress/securedrop/blob/62f7d224217add9959ef0708b00ab2b3ccd810f4/securedrop/source_app/main.py#L52) route is executed from *window_2* and we try to add a new Source with a codename that already exists (was added with "Submit Documents" was clicked in *window_1*).

Having the possibility of generating multiple codenames in multiple windows before the source logs-in presents a significant risk that the source keeps note of a different codename than the one actually used to create the Source database entry.

I think the safest way to prevent this is to only allow one `/generate` window until the user has logged-in by clicking the "Submit Documents" button.

To achieve this, the `/generate` route could check for the case where `session['codename']` exists but the user is not logged-in. In this case, the user would be redirected to the index with an appropriate flash message.

Any comments / issues with this proposal?

**Comment by redshiftzero** [comment]
nice investigation

> presents a significant risk that the source keeps note of a different codename than the one actually used to create the Source database entry.

indeed, unless they pay special attention to the part of the `/lookup` page that has their codename for reference (available on the first login only and they might not look at it) they might find themselves unable to login again.

> the `/generate` route could check for the case where `session['codename']` exists but the user is not logged-in. In this case, the user would be redirected to the index with an appropriate flash message.

this sounds like a reasonable approach!

**Comment by eloquence** [comment]
@emkll notes that we should investigate other aspects of the application, to determine whether they would exhibit similar issues, and/or whether #5075 would have any side effects on it.
