### ISSUE TITLE
Update icons placed on Submit/Cancel buttons in Source Interface

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#4501]
## Design Epic 
Design updates to the Source UI (w/in the existing experience) are being explored in [UX-repo issue #42](https://github.com/freedomofpress/securedrop-ux/issues/42). Within these updates, a new color palette is being used. The goal of the color updates are make the product reflect the SecureDrop brand, as it's presented on the website. They also make the product snazzier.

**This issue has been drafted to implement the below in a PR after #4500 has been completed**
 
## This Issue
See mockup:  [static](https://scene.zeplin.io/project/5cb7d4d1f93bd116d7b25561)
- [x] Update "x" icon to `sd-blue` artwork w/o circle in static mode, and `grimace-blue` artwork for hover. Both icons as PNGs are [here](https://drive.google.com/open?id=1ycflbtla_9ZU0ErKBv-pqEUThfCcKl4w).
- [x] Eliminate checkmark icon on `Submit`
   - This is very confusing, as it indicates an action has already happened; when a file has been selected to be uploaded but not yet submitted, it's more confusing. :(

**Comment by eloquence** [comment]
The mockup link points to a folder, I am guessing you meant to link to this specific mockup?

https://scene.zeplin.io/project/5cb7d4d1f93bd116d7b25561/screen/5cf5cd50a10cff716e3db87b

If so, I agree with these changes: the current icon choices look confusingly like a state indicator or a button-within-a-button. The simpler "X" and removal of the icon on the "Submit" button make a lot of sense to me. :)

Since this issue is not just about colors, I've updated the issue title for clarity.

**Comment by eloquence** [comment]
Could you upload a larger version of the "x" PNG button in both colors so it zooms cleanly on HiDPI monitors? Right now it's 9x9, 36x36 would be good.

**Comment by ninavizz** [comment]
Between this and the upload-arrow bit, I feel we're establishing good precedent for creating a rule that all PNG art shd be generated at 3x the 100% size, and with PNG-24. That'll be a nice one to include in an eventual styleguide. Yep, creating 36x36, now! :)

**Comment by eloquence** [comment]
I need a version of the "x" icon in the new "button blue" (`#045fb4`).

**Comment by ninavizz** [comment]
New colors/usage + PNG artifacts documented: https://github.com/freedomofpress/securedrop-ux/issues/65
