### ISSUE TITLE
Use random superhero name as source nickname in journalist interface

### ISSUE THREAD

**Issue by dtauerbach** [freedomofpress/securedrop#451]
This was an email thread (see below). At a Sunday SecureDrop hackday now, and wanted to get this down as an issue.

From the email thread:

I kind of agree, that the superhero names including things like Mister
Winky and normal names like James Sanders are more memorable than, say,
"idealogical Teller", "East Indian Piperales", and "fossilized Umbrian",
which are 3 that were just randomly created for me.

On 05/26/14 14:47, Trevor Timm wrote:
> I still think those weird names are more memorable than random
> adjectives, random nouns. And going through the whole dictionary
> taking out the bad ones may be more trouble than it's worth.
>
> But I'm cool with either ultimately.
>
> Sent from my iPhone
>
>> On May 26, 2014, at 3:05 PM, Garrett Robinson
>> <garrett@pressfreedomfoundation.org> wrote:
>>
>> Just took a look at the list, I'm not sure if I think this is a
>> good idea anymore. It's weird that some of the names are
>> obviously superheros (Wundarr the Aquarian) while others look
>> like normal people's names (William Baker) and some are just kind
>> of creepy (Winky Man?)
>>
>> I think we could probably get a lot more mileage out of the
>> "adjective-noun" convention if we cleaned up our wordlists to get
>> rid of excessively long or unfamiliar words. Heroku's machine
>> provisioning, which inspired this convention, had small, focused
>> word lists, so stuff was always called "iced-rain" or
>> "massive-robot" which were short and memorable IMO.
>>
>>> On 05/23/2014 06:34 PM, Trevor Timm wrote: It's for the
>>> journalist side, so entropy is not a factor. Source passphrases
>>> are staying the same
>>>
>>>> On 5/23/14, 6:33 PM, Kevin M. Gallagher wrote: think it adds
>>>> a nice psychological/moral boost to the act of
>>>> whistleblowing. but possibly not enough entropy
>>>>
>>>>> On 05/23/2014 08:48 PM, Trevor Timm wrote: Turns out there
>>>>> are 2826, so I was off by a few thousand. What do we
>>> think?
>>> https://github.com/elasticsearch/elasticsearch/blob/master/src/main/resources/config/names.txt
>>>
>>>
>>>
- --

**Comment by aliclark** [comment]
There may be some value in having boring code words that are less likely to become anecdotes (but obviously boringness may have a trade-off against memorability).

Normal names generated from a corpus like this http://www.behindthename.com/ might not be a terrible option especially if there's something else to disambiguate from real names in case of collision.

Perhaps there could also be some value in very commonly used words like first names, city names, etc. which could give journalists more flexibility to talk about the source without uniquely identifiying the code-word "william" to mean "green william eight" instead of a uniquely identifying and very interesting "spiderman".

Using that scheme "$color $name $number" could give lots of reasonably memorable yet absolutely dull code names.

**Comment by garrettr** [comment]
We've pruned the word lists for journalist designations significantly for 0.3, honing them to mostly short and familiar words. As a result, I think the usability of those designations has improved considerably. I still think the superhero names are not a good idea for the reasons I mentioned in the email thread quoted in the issue description.

Ultimately, I think the "right solution" is to allow journalists to pick these names, but they will have to be encrypted with the journalist's key and handled carefully to allow that. I think this would be a logical part of the "ultimate viewing station interface" proposed in #415.
