### ISSUE TITLE
Formatting errors in landing page docs

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4542]
https://docs.securedrop.org/en/release-0.13.1/deployment/landing_page.html has a couple of formatting errors:

`Don’t log access to the *Landing Page* in the webserver`
`Change detection monitoring for the web application configuration and *Landing Page* content`

(Asterisks instead of italics.)

**Comment by nickcannariato** [comment]
@eloquence I can knock this out quickly to remove the asterisks, but the ultimate limitation here is that reStructuredText doesn't support nesting italicized text inside of bold text (and vice versa), even though Markdown does. 

Would we just like those asterisks removed so that "Landing Page" is bold like the rest of the line? Or is there another way you'd ultimately like this formatted?

**Comment by eloquence** [comment]
Thanks @nickcannariato, please use your best judgment -- if it makes sense to use headlines, call-out boxes or other formatting choices to side-step the issue, that might work; if we lose the italics it's not the end of the world. :)
