### ISSUE TITLE
Update screenshot taking code such that manual editing is unnecessary

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4561]
@eloquence recently re-ran our [automated screenshot taking code](https://docs.securedrop.org/en/latest/development/documentation_guidelines.html?#updating-screenshots) and found the following deficiencies (see [#4559 (comment)](https://github.com/freedomofpress/securedrop/pull/4559#issuecomment-506535733)):

> the following currently require manual editing or re-taking:
> 
> Bad cropping:
> 
> `journalist-composes_reply.png` cut off just above the submit button
> `source-flagged.png` cut off just above the submit button
> `source-lookup.png` has bits of the "Read Replies" text cut off
> `source-checks_for_reply.png` does not show the reply
> `source-flagged.png` has the "Submit" button cut off
> `journalist-admin_changes_logo_image.png` - the essential message we want to show ("Image updated") is not visible
> `journalist-admin_new_user_two_factor_totp.png` - verification code is cut off
>
> Too much whitespace below the footer:
> 
> basically all screenshots of short pages
>
> Bad content:
> 
> `source-index.png` has JavaScript warning, but JS should be disabled for this screenshot in the docs
> `source-logout_flashed_message.png` has JavaScript warning, and does not in fact show a flashed message (guessing because it's FF not Tor in this case? it's styled to render in Tor only)

For the bad cropping issues, a single PR that:
* enables the customization of the size of the window for the tests that generate those screenshots and,
* updates the sizes for the above PNGs 

would be a nice solution. 

Otherwise for the bad content issues, individual PRs fixing the described issue one PNG at a time is appreciated.

*Edited by @eloquence on 2019-06-28 to add one more bad cropping example.*

**Comment by DrGFreeman** [comment]
> For the bad cropping issues, a single PR that:
>    * enables the customization of the size of the window for the tests that generate those screenshots and,
>    * updates the sizes for the above PNGs

Hi, I'd like to work on this if it is still relevant.

**Comment by DrGFreeman** [comment]
I propose the following approach:
1. Increase the window [height of the selenium driver window](https://github.com/freedomofpress/securedrop/blob/abdebc1ac33d8c8d99a572dee9997ce12e446c77/securedrop/tests/functional/functional_test.py#L130) used to capture the screenshots to ensure that all the page content is captured.
1. Automatically crop the bottom of the image to the actual content size (+ some padding).

I have tested the above steps separately and have a solution that gets perfectly cropped screenshots automatically (including the screenshots with modal dialogs that have a darker background).

I am asking because this is not *customization* as proposed by @redshiftzero in the issue description but rather *automatic croping* and I want to make sure I understand the intent properly before implementing a solution in the codebase and creating a PR.

Thx.

**Comment by redshiftzero** [comment]
@DrGFreeman that solution sounds like it would be perfect!
