### ISSUE TITLE
Weblate source string links are broken

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4562]
## Description

@comradekingu [noticed](https://github.com/freedomofpress/securedrop-i18n/pull/1) that the links to our source strings are 404ing. This is useful for translators who might want to make PRs with source string changes, or who might want to see the context in the template for that string. 

The links are missing a `securedrop/` folder, we should investigate why this is broken and resolve.

**Comment by redshiftzero** [comment]
As localization managers for 0.14.0, @rmol @kushaldas can y'all investigate this one? We might not get this resolved for this release, but at a minimum would be good to understand for the next cycle.

**Comment by rmol** [comment]
I've fixed it by updating the repository browser URL template for the SecureDrop component in the Weblate admin. The last change to that was in November 2018 ... I guess it's possible no one's actually tried these links since then (if that was even when they were broken; the changes themselves are not available in the admin). Seems unlikely, but I don't see what else could affect them.

**Comment by redshiftzero** [comment]
Just checked out weblate and confirmed the fix, thanks @rmol!
