### ISSUE TITLE
[docs] Docs dev environment setup docs missing key steps

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/securedrop#4573]
## Description

Following the instructions for setting up a development environment for documentation editing here: https://docs.securedrop.org/en/latest/development/documentation_guidelines.html does not result in a working development environment in macOS Mojave.

## Steps to Reproduce

Follow these steps on a fresh clone of the SecureDrop repository: https://docs.securedrop.org/en/latest/development/documentation_guidelines.html

## Expected Behavior

`make docs` spins up a dev environment for editing docs.

## Actual Behavior

Depending on a number of factors, including whether or not one is using a system Python or using a virtualenv which contains it's own Python, any number of what boils down to "where is python" errors appear.

## Comments

Following the separate steps for setting up a dev environment (https://docs.securedrop.org/en/latest/development/setup_development.html) basically work, it's just `make docs` that causes issues.

**Comment by eloquence** [comment]
This issue is a bit stale since the migration to the standalone docs repo. @huertanix, at your convenience, I would appreciate it if you could step through the updated docs setup instructions:
https://docs.securedrop.org/en/latest/development/documentation_guidelines.html#updating-documentation

Thanks to Python 3's `venv` module, there should be no requirement to follow OS-specific steps to install the dependencies. Closing for now, please file a new issue in `securedrop-docs` if you experience difficulties with the revised setup guide.
