### ISSUE TITLE
[v3 onion migration] If v2 and v3 are both used, set Alt-Svc header in Apache configs

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4630]
## Description

We can transparently move user traffic over to v3 using the HTTP Alternative Service (`Alt-Svc`) header. If v2 and v3 are both used, we should set the `Alt-Svc` header to point to the v3 onion. 

References for `Alt-Svc`:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc
https://tools.ietf.org/html/rfc7838

Subticket of #2951

**Comment by conorsch** [comment]
For now, we should limit use of the `Alt-Svc` header to the Source Interface. If we also apply it to the Journalist Interface, we run the risk of breaking access for Journalists during the v2->v3 migration window: the v3 auth tokens will not be present on the Journalist Workstation until an Admin provides them, due to the need to fetch the v3 info from the server, via shell access, which Journalist Workstations lack.

**Comment by conorsch** [comment]
Took a look at potential implementations for adding the Alt-Svc header. In short, we have full flexibility to use a conditional logic and edit the Apache configs directly, via Ansible. Since Admins must run the Ansible logic in order to add v3 URLs, we'll be able to use the `v{2,3}_onion_services` values to determine whether it's appropriate to add the Alt-Svc header—as well as the value, which must be the hostname for the _new_ v3 Onion—directly to the Source Interface apache config:

https://github.com/freedomofpress/securedrop/blob/de8cbcf66e86164b7a386858d717ea3ac58d9c6d/install_files/ansible-base/roles/app/templates/sites-available/source.conf#L48-L56

We can look up the hostname for the v3 URL at that point in the Ansible run, because the Tor updates have already been applied. Then the template can insert the relevant `Alt-Svc` header if-and-only-if both v2 & v3 services are enabled.

**Comment by redshiftzero** [comment]
[removing from 1.0.0 milestone, at this point we likely won't do this at all, but it _definitely_ won't happen for 1.0.0]

**Comment by eloquence** [comment]
Tentatively closing, we're unlikely to do this at this point (it would be a heavy lift for 1.1.0 and would be unlikely to matter soon after). @redshiftzero please reopen if you disagree.
