### ISSUE TITLE
Deleting a user in the Journalist Interface should trigger a confirmation dialog, even without JavaScript

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4649]
Currently, deleting a user using the "trashcan" icon in the Journalist Interface is done immediately, without a confirmation dialog. As standard practice, destructive operations without undo should have a confirmation step.

# User Stories

As an admin, I want to be prompted before performing destructive operations, so I don't perform them accidentally when my hamster jumps onto my head.

**Comment by DrGFreeman** [comment]
There is a [confirmation dialog](https://github.com/freedomofpress/securedrop/blob/67c23e9bf266051ebac2d559553e1c753a658d68/securedrop/static/js/journalist.js#L167-L178), but it displays only with JavaScript is enabled.

![image](https://user-images.githubusercontent.com/22901938/69202010-38e1ef00-0b0e-11ea-82d6-766946ee7f23.png)

I presume this issue is to have an equivalent confirmation dialog without JavaScript?

**Comment by eloquence** [comment]
Ah, thanks; I must have been testing without JS when I reported this issue. Yes, it would be preferable to have a dialog that doesn't use JS; note we have an existing implementation for this when you delete submissions.
