### ISSUE TITLE
make Flask test server more like the live SD servers

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#467]
We should attempt to catch bugs like #453 in the future before they go live.

**Comment by garrettr** [comment]
I believe the spirit of this issue is resolved by the new staging and prod environments that we have created as part of the Ansible playbooks for 0.3. See `docs/develop.md` for details.

Note that the Flask test server is now only used in the `development` VM (and is/was never used in production systems). It is useful because it supports automatic code reloading and has some nice debugging features (when `DEBUG=True`). I plan to continue using it in the development environment.
