### ISSUE TITLE
[v3 onion migration] fail if v3 partial config is encountered

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#4681]
## Description

In `securedrop-admin install` when a user runs with `v3_onion_services=True`, we should:

* check for existing client auth files
* check for existing tor keypairs JSON file
* fail if one-but-not-both are found 

The goal is to provide a fail-fast mechanism that prevents breaking v3 services for orgs with multiple Administrators. See discussion https://github.com/freedomofpress/securedrop/pull/4652#issuecomment-522703768 for context. The "validate" role seems like the best place to run this logic, since that'll catch misconfigurations even if `securedrop-admin sdconfig` was _not_ run.

**Comment by redshiftzero** [comment]
If a playbook run bails _after_ the tor keypairs JSON fail is generated but _before_ the ths/client auth files exist, we probably shouldn't start failing subsequent attempts to run the playbook since it won't actually be due to this multiple administrator situation, it's due to a playbook failure which can happen pretty often because Tor (this happened to me while testing the other day and I thought of this ticket). 

However in the scenario where the admin _does_ have ths/client auth files but _not_ the tor keypairs JSON file, we [should](url) fail because it means they only fetched half the secrets they need from the other admin. Lmk if you disagree @conorsch @kushaldas
