### ISSUE TITLE
Finalize footer wording

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4700]
In review of #4666, @zenmonkeykstop observed

> As an aside, the footer language appears a bit stilted - "stewarded" isn't in common usage and it's more natural to refer to "the Freedom of the Press Foundation" rather than "Freedom of the Press Foundation" - the combination of the two gives the footer text a phishy vibe for me.

Let's kick this around to make sure we pick wording that works for everyone. To recap, the revised footer was spec'd in #4662, with the following language about FPF:

> SecureDrop is free and open-source software stewarded by Freedom of The Press Foundation.

Adding a bit more context in a comment, but inviting everyone to weigh in before feature freeze (EOD 8/29).

**Comment by eloquence** [comment]
We discussed this language a bit in past UX meetings. "Stewarded" was chosen as a term intended to convey leadership beyond maintenance (e.g., in community engagement, fundraising, training; pursuing long term efforts like the workstation), but it's a word that's admittedly easy to stumble over. Common meanings suggest managing something on behalf of someone else, which is a recipe for incorrect translation if we're not very careful, but also for misunderstanding in English.

"Maintained by" would be the easy and conservative choice commonly used in open source projects. I still have a soft preference for "stewardship" but I admit its negatives weigh pretty heavily, so we may want to default back to the conservative choice if we can't find something better.

As for "the FPF" vs. "FPF", I have no preference (our docs use both inconsistently), and am happy to go with "the Freedom of the Press Foundation" if nobody has any concerns about that edit.

**Comment by ninavizz** [comment]
"Maintained by" implies "keeps from breaking" to me, vs product evolution and growth. 

"Developed by" isn't exactly accurate, either, because Aaron/Kevin created it. Likewise, as a non-dev contributor I personally find references to "development" to exclude wisdom informing a product outside engineering things... which obvs bothers me a lot.

The point of the language in the footer is to speak to accountability; that someone is accountable for this product and stands by its assertions, with something to lose if they're being deceptive. Consumer-culture-centric language is what users will expect, because we're trained to trust language that alludes to concepts of "ownership." FOSS projects, of course, eschew concepts of centralized control... so we're in an odd spot. 

Non-technical user comprehension needs to identify a governing/accountable body responsible for SD, is the goal of whatever word does get used. Because FOSS is still a relatively foreign concept to mainstream society, I don't think that introducing new verbiage is really avoidable; unless it's sought to speak to SD as a project by developers, for developers.

I'll poke around to see how Mozilla speaks to Firefox as its thingy. Its the only mainstream FOSS app I can really think of. 

I personally dislike "the FPF" because it feels extraneous for UI copy (whereas in a document, I'd prefer it)... but I'm also happy to defer that one to what others may think?

**Comment by ninavizz** [comment]
In the Apple app store: 
"Firefox is the independent, people-first browser 'made by Mozilla', voted the Most Trusted Internet Company for Privacy" 

Also: `© Mozilla and its contributors 2018` 

In the footer on their page tho, they reference "...the Mozilla Corporation's not-for-profit parent The Mozilla Foundation." So maybe that's how they can do the © thing (which I personally dislike, on an aside—so am not advocating for... even though it is what most clearly/simply accomplishes the semiotic goal).

I'll poke around elsewhere, over the weekend...

**Comment by ninavizz** [comment]
Random Sunday reading that's tangentially related... http://fossmarks.org/

**Comment by ninavizz** [comment]
`SecureDrop is a project of Freedom of The Press Foundation. It is is free and open-source software, published under a GNU Affero General Public License v3. SecureDrop is made by a team of community contributors with project leadership, funding, and support from Freedom of The Press Foundation.`  <—It's a bit of a mouthfull, but I've been sitting on that for a couple of days and kind of really like it. What do you think, @zenmonkeykstop? 

Alternately, pulling from how things are summarized on the GH project page's readme: `SecureDrop is free and open source software, managed by Freedom of The Press Foundation.`

**Comment by ninavizz** [comment]
```
SecureDrop is a project of Freedom of The Press Foundation (FPF), published under a GNU Affero General Public License v3. 
Made by a team of community contributors with project leadership and support from FPF.
```
_(ok, done with being a comments-hog on this ticket! looking forward to feedback & continued discussion)_

![image](https://user-images.githubusercontent.com/8262612/63655380-34d74880-c73c-11e9-95d5-0785b8639ed2.png)

**Comment by rocodes** [comment]
I vote "SecureDrop is a project of Freedom of the Press Foundation," but if people want another verb in there, my preference is for "maintained."

**Comment by rocodes** [comment]
Zooming out a bit and going back to what the purpose of this text is: it answers the question, "who the heck made SecureDrop--surely not XYZ News Org on their own"? It creates commonality across SD instances, and accountability (the organization behind the platform).  

For someone to be reading the footer, they have to have taken some steps to get there already, and in those steps is where their own education/discovery is probably happening. IMO, the place for education/discovery (What does 'stewarded by' mean? What is GPLv3 license? Is it good that this is open-source software?) is not at the moment that they are trying to figure out the Source/Journo interface. But just stating the name of the project and of the organization means that the user, at a time that it doesn't interrupt their workflow, can choose to go investigate the nuts and bolts if they are curious. 

I guess what I'm trying to say is that using the platform could be an emotionally-charged moment for people, so I think that, without being patronising, the experience should be as unsurprising and uneventful as possible, and I feel like throwing in terms or concepts count as semi-"eventful" intrusions on the user.
