### ISSUE TITLE
Forensic analysis of Securedrop in RAM

### ISSUE THREAD

**Issue by aoighost** [freedomofpress/securedrop#486]
In-RAM forensic artifacts can become extremely valuable, for raids, cold boot attacks, and malware. It would be useful to investigate Securedrop in memory to find ways to minimize the ability of an attacker to use a memory dump against a whistleblower.

**Comment by ageis** [comment]
Two points: grsecurity will not allow you to dump /proc/kcore. Secondly, cold boot attacks are [not as effective](https://www1.cs.fau.de/filepool/projects/coldboot/fares_coldboot.pdf) with modern-day RAM chips.

**Comment by fowlslegs** [comment]
It's unclear what machine(s) your concerns are geared towards. We have already pretty extensively addressed this on the application server, for example. It should be noted the application server does not use FDE, as that presents challenges regarding automatic reboots (see https://github.com/freedomofpress/securedrop/issues/816), and the machine is nearly always-on anyway.

I'm working on a PR to address https://github.com/freedomofpress/securedrop/issues/204, that will help in the case a source or admin/journalist has logged out of SecureDrop (or just quit Tor Browser w/o explicitly clicking the logout button), but the physical memory address space the cookie was stored in has not been overwritten.

Other than that, Tor Browser has a pretty strong anti-forensics model. In Tor Browser, all cookies are saved as session cookies, but we also explicitly set our cookies as session cookies. Though there have been problems documented on Windows, this is out of our reach to address. We also encourage sources to use Tails, which has a strong anti-forensics model. The journalist and admin workstations also use Tails.

Since this issue is too vague, I'm going to close it. If you have a specific forensics concern, please feel encouraged to make a more targeted issue describing it.
