### ISSUE TITLE
ClamAV/Yara/Cuckoo Sandbox scan of sent files for malware

### ISSUE THREAD

**Issue by aoighost** [freedomofpress/securedrop#498]
It might be useful to implement functionality to have the server automatically scan dropped files with ClamAV, yara, and/or cuckoo sandbox in an attempt to test for malware attached to the dropped files. While this will have limited protection, some protection is better than none. If an infected file is found, it is flagged, zipped, and password protected to allow the document to be safely handled. Furthermore, in order to be able to drop files with known malicious code in them, it would be useful to put an option for "known malicious file attached", which would zip up and password protect the infected file to prevent accidental infection. If this were checked, it would flag the file as having malicious code and information would be able to be given on how to properly handle the file.

In implementing this functionality, it becomes easier to protect journalists from malicious sources, or compromised files from legitimate sources in the event of malware being spread whether by accident or malice.

**Comment by garrettr** [comment]
@aoighost This is an interesting idea that could have some benefit.

Unfortunately, will be even more difficult to implement due to #862.

It's also safe to assume that a reasonably sophisticated adversary will be able to bypass typical AV (especially signature-based detection).

I'm going to leave this in the issue tracker for now, but do not plan to schedule it for the upcoming release. If anybody is reading this and feels like taking this on, contributions welcome!

**Comment by fowlslegs** [comment]
Considering #862 and that these files are not decrypted until they are on an airgapped Tails machine, there appears to be no good stage at which this could happen. I also agree that

> It's also safe to assume that a reasonably sophisticated adversary will be able to bypass typical AV (especially signature-based detection).

Since there's been no interest in this issue in over 20 months, questionable effectiveness of such a mechanism, and significant challenges to implementing such a mechanism, I am going to close this issue.
