### ISSUE TITLE
Source Interface should include information from landing page

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#503]
An organization who sets up SecureDrop spends a lot of time crafting a landing page that explains how to use SecureDrop safely, what kind of documents can be submitted, what happens if the source forgets her codename, and so on. Ideally, the same information should be visible on - or at least accessible from - the Source Interface. If the source finds the landing page and reads the information there before she visits the Source Interface, she is better off than if she visits the Source Interface directly.

**Comment by garrettr** [comment]
This issue is too vague to work on without further clarification. What information should be duplicated? Why? The same information for all organizations? Where should it go? The point of the landing page to get them to the source interface safely, so isn't duplicating that information redundant?

I think a better long-term solution is to allow organizations to easily customize the content of the Source Interface, as in #774.
