### ISSUE TITLE
Split the SecureDrop installation guide into separate documents

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#504]
The current workflow for installing SecureDrop, assuming you are starting from scratch, is incredibly complex. It is hard to write an installation guide as one single document that does not feel messy and requires the reader to jump back and forth between different sections. For this reason, we should split the installation guide into separate documents. We have a few of these documents already, but here's a quick list I came up with after a solo brainstorming session:

 * Installing Ubuntu 12.04
 * Creating an air-gapped machine
 * Creating GPG keys
 * Installing Tails on a USB stick with a persistent volume
 * Creating an Ubuntu kernel with Grsecurity
 * Installing SecureDrop on the App and Monitor servers
 * The day-to-day workflow

**Comment by conorsch** [comment]
Revisiting the idea of a docs overhaul. Would be great to have a new docs platform ready by 0.4. There are a few stand-out candidates.

### Candidates
  * [GitBook](https://www.gitbook.com/) (already mentioned above)
  * [ReadTheDocs](https://readthedocs.org/)
  * [MkDocs](http://www.mkdocs.org/)

To make the comparison meaningful, let's sketch out a list of desired features.

### Desired features
  * Support Markdown format
  * Portable (exported static directory can be served up from any host)
  * Viewable offline
  * Searchable
  * Click-through navigation (e.g. via **Next** button)

Given that list of features, MkDocs is the best candidate I've seen so far. RTD is a strong project, but it's Markdown support is lacking. To use RTD effectively, we'd have to convert our Markdown files to RST.

Next steps should be standing up an instance for the docs in their current format. I'll take a look at that shortly. Once that's done, the bigger work is restructuring the installation documentation so that flows linearly, which should greatly reduce headaches during installation.

**Comment by garrettr** [comment]
Note that RTD supports [CommonMark](http://commonmark.org/), a well-specified subset of Markdown which our existing docs probably mostly or entirely conform to. Are there other things that make you say their Markdown support is lacking?

The main thing I can think of (having used Sphinx in the past) is that RST actually has a bunch of useful features that Markdown simply doesn't have. One that comes to mind are RST's "directives", which are commonly used for *admonitions* (e.g. little asides for warnings, notes, etc.). I think these would actually be really useful things to have in the SecureDrop docs, which suggests that it might be worth converting the docs from Markdown to RST in order to take advantage of the richer markup language. There is a tradeoff there in that people tend to be more familiar with Markdown than they are with RST, but it might be worth it.

Finally, remember that it's _really easy_ to translate between markup formats (e.g. from Markdown --> RST) with Pandoc.

**Comment by conorsch** [comment]
There are indeed advantages to RST, it's just that converting all the docs by hand is a pain. Using pandoc for the conversion worked fine in testing, with the exception that RTD's toctree directive lacks Markdown support. See these conversations for some context:

 * https://github.com/sphinx-doc/sphinx/issues/825#issuecomment-121514833
 * http://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rst

So I'm certainly not opposed to converting the docs to RST, but I think we can gain a lot from streamlining the docs without converting. Started a rough draft of using MkDocs here: http://conorsch.github.io/securedrop/

**Comment by conorsch** [comment]
Accomplished via transition to ReadTheDocs in #1158. We now have dedicated guides for the various user roles (Source, Journalist, Admin), as well as guided flow through the primary installation steps:

* Create Tails USBs
* Set up the Secure Viewing Station
* Set up the Data Transfer Device
* Generate the SecureDrop Application GPG Key
* Set up the Admin Workstation
* Set up the Network Firewall
* Set up the Servers
* Install SecureDrop
* Configure the Admin Workstation Post-Install
* Create an admin account on the Document Interface
* Test the Installation
* Onboard Journalists

Closing.
