### ISSUE TITLE
1.2.0 Acceptance Testing (Source Interface) large file submission does not produce expected result

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop#5044]
## Description

Running through QA testing for 1.2.0 , the following scenario (submit a large file) does not yield expected result ("connection was reset briefly then file is uploaded").

## Steps to Reproduce

Create file just larger than 500MB , attempt to submit it via Source interface.

## Expected Behavior

> - []  On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser quickly before the entire file is uploaded 

## Actual Behavior

A 525 MB file produces "The connection was reset" but stays in this state, is not uploaded, TB does not return to Source Interface view.

## Comments

Am I understanding the scenario correctly?

**Comment by emkll** [comment]
Yes @rocodes, that should be expected behavior. This is because the page is served by the Apache web server and not the Flask application itself: https://github.com/freedomofpress/securedrop/blob/70b598561bce683569d27f9885f0079e6a6f9472/install_files/ansible-base/roles/app/templates/sites-available/source.conf#L59

**Comment by rocodes** [comment]
Ok thanks - that is what I thought the behaviour was, but was confused by the instructions in the test plan (the snippet I quoted).
