### ISSUE TITLE
Docs: Replace USB-sticks with optical media?

### ISSUE THREAD

**Issue by englishm** [freedomofpress/securedrop#512]
Switching from USB sticks to optical media would add overhead (burning CD-Rs, etc.) but could shrink surface area open to attack and help reinforce strong compartmentation. 

It [sounds like](https://twitter.com/securedrop/status/494935292181110787) this may already be the best practice recommended to media orgs, but the [user manual](https://github.com/freedomofpress/securedrop/blob/develop/docs/user_manual.md) still includes many references to USB sticks.

Thoughts?

**Comment by flamsmark** [comment]
If recommending DVDs, it's probably worth including that in journalist-facing documentation, including instructions for burning disks under Tails, and for safely disposing of disks afterwards.

**Comment by fowlslegs** [comment]
If you're going to switch to CDs/DVDs, the optical bay used to read them/ launch Tails should preferably be read-only. I am not convinced that optical discs are truly WORM. Maybe to regular firmware, but malicious firmware combined with write capability might still be used to encode hidden data onto the disc.

What's to say that malware can't reprogram optical bay firmware and either cause it to write past the EOF marker or to deepen existing pits? Obviously you can flatten out pits and write whatever data you would like--that is the physical attribute of the medium by which we consider it WORM--but why can't you make some more deep, make more of them, etc.? The CRC may even be used to your advantage. 

Say you infect the SVS with malware that reprograms the optical bay firmware, then encodes the private key in errors, which are corrected by the CRC. Tails will then operate totally normally, however, if the disc is captured, you can recover the private key embedded in the errors.

Let me know if I'm way off here. I couldn't find any examples of doing anything like this, but in my admittedly shallow knowledge of optical disc technology, it seems possible.

**Comment by garrettr** [comment]
@fowlslegs I don't think you're way off, but I do think you are going down a rabbit hole. I am not an expert on optical media either (although note that only factory-made CDs and DVDs have actual physical pits that can be, as you say, "flattened" - consumer-grade writers use lasers to change the colors of dyes or re-crystallize a thin layer of alloy to change reflectivity). An error-based side channel is certainly possible (and a cool idea), but it is quite complex and requires either collusion (synchronized malware) between the online and offline machines, or physical access to retrieve the CD.

One general recommendation that I would make for orgs that want to use DVDs is that they should have 2 compartmentalized DVD burners/readers: one that is only used with the online machine, and one that is only used with the offline machine. This makes it more difficult for malware on the offline machine to collude with malware on the online machine to exfiltrate data, and avoids potentially transferring malware via the drive itself (e.g. in the drive's USB firmware).

In general, you seem to be arguing against the first comment in this issue, which posits there are security benefits to using optical media over USB devices to transfer data between online and offline hosts. I tend to agree that optical devices are more secure than USB devices for this use case, because:

1. The write-once property of CD-R's and DVD-R's is considered to be a physical limitation of their design, as far as I understand it (any experts on optical media care to chime in here?). You argue that this may not be the case; however, I have never heard of anybody successfully rewriting a CD/DVD-R. On the other hand, it is impossible to properly write-protect a USB drive without specialized and somewhat pricey hardware (forensic write blocker) - most USB drives that claim to be write-protectable rely on the host OS to enforce this, and so may easily be subverted by malware.
    * Even if you do want to use USBs with a forensic write blocker, I'm not sure/don't know if they would protect you from firmware attacks like BadUSB.
2. Unlike USB mass storage devices, CD/DVD-R's do not potentially have reprogrammable flash memory that could be used to hide malware (again, BadUSB). While it is conceivably possible that malware could modify data written to a CD/DVD to trigger an exploit in the receiving DVD reader's firmware, that seems like a much higher bar to me.

Basically, no one's arguing that write-once optical media is a perfect solution. However, it does seem to be a much more secure solution than using USB mass storage devices.

**Comment by fowlslegs** [comment]
>On the other hand, it is impossible to properly write-protect a USB drive without specialized and somewhat pricey hardware (forensic write blocker) - most USB drives that claim to be write-protectable rely on the host OS to enforce this, and so may easily be subverted by malware.

> Even if you do want to use USBs with a forensic write blocker, I'm not sure/don't know if they would protect you from firmware attacks like BadUSB.

In https://github.com/freedomofpress/securedrop/issues/827#issuecomment-148901704 I talk about this a little bit. Specifically, the USB controller is w/in the device itself, so it is not up to the host OS to enforce it, rather, it is up to the host OS not to reflash the firmware of the USB so that the USB firmware enforces the write protection. And, there are USBs that only run digitally signed firmware, which--vendor trust and lock-in issues aside--should protect against BadUSB. For large transfers we must (practically speaking) use a USB. In that case we are already trusting vendor USB firmware. It only requires one transfer via USB to infect a machine, so we may as well always use USB.

> Basically, no one's arguing that write-once optical media is a perfect solution. However, it does seem to be a much more secure solution than using USB mass storage devices.

I agree they are generally more secure. I was just questioning the conception that optical media are truly a WORM technology. If we never had to transfer 700MB+ archives, I'd agree they should be used, but for the reasons above, I think an option like the Kanguru USB is actually our best bet.

**Comment by garrettr** [comment]
> For large transfers we must (practically speaking) use a USB.

> If we never had to transfer 700MB+ archives,

This is not a limitation. We usually use DVD-R, not CD-R (as mentioned earlier in https://github.com/freedomofpress/securedrop/issues/512#issuecomment-154607538), which can hold up to either 4.7GB or 8.5GB (dual layer). For larger transfers, you can always `split` it into chunks that will fit on these devices.

**Comment by fowlslegs** [comment]
I guess if there is a way via GUI (Brasero?) to `split` and then `cat` the files, this would work. I wrote "practically speaking" because I'm not aware of an easy way to do this.

**Comment by fowlslegs** [comment]
The docs already mention the benefits of using DVDs or USBs. In the next generation of SD we'd like to move away from using a transfer device and instead combine the SVS and Journalist Workstation into a single device where they are each run in their own VM via full, hardware-assisted virtualization and isolated by a type 1 hypervisor--Qubes is looking like the best solution for this so far. With this said, I'll be closing this issue.
