### ISSUE TITLE
Google Authenticator or YubiKey for two factor authentication

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#513]
The SecureDrop installation guide talks about using the Google Authenticator app on an Android or iOS device for two factor authentication. I hear we currently recommend using a YubiKey instead. If this is the case, and it is something we will want to continue doing, we should document how to set up the YubiKey (the [official guide from Yubico](http://www.yubico.com/wp-content/uploads/2014/02/Yubico-TOTP-Setup.pdf) may possibly be good enough) and change the installation guide to match this.

**Comment by flamsmark** [comment]
Since Journalists already need to use a (physical) Tails disk with persistent recollection of the document interface onion access credentials, does a Yubikey make their life much harder? Conversely, if the Tails disk and the Yubikey are on the same keychain, does the Yubikey meaningfully represent a second factor.

The ideal configuration for Yubikeys would be U2F rather than HOTP, but that requires U2F support in Firefox and then for that to get picked up by Tor Browser.

**Comment by redshiftzero** [comment]
This documentation now exists in: https://docs.securedrop.org/en/stable/yubikey_setup.html. Closing!
