### ISSUE TITLE
Multiple security issues with the gpg --recv-key command in install.md

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#520]
`docs/install.md` instructs the admin to fetch the securedrop code signing key with the command `gpg --recv-key BD67D096`. Problems that I can see:
1. Short key IDs are insecure since generating collisions is trivial. See http://www.asheesh.org/note/debian/short-key-ids-are-bad-news.html. Easy to fix by using the full key ID `9092 EDF6 244A 1603 DCFD  C462 9A2B E67F BD67 D096`
2. However, even using long key IDs, `gpg --recv-key` has an open bug where GPG won't verify that the key ID of the received key matches the key ID that was requested (!!!). Here's the open upstream ticket (warning: self-signed cert): https://bugs.g10code.com/gnupg/issue1579.
3. On top of all this, gpg isn't fetching keys over SSL here (unless you've installed gnupg-curl or set up gpg2, and specify a SSL-only keyserver or keyserver pool - I use hkps://pgp.mit.edu ever since I convinced the person running it to support SSL). 

Impact:
At least fetching the package and signature happens over SSL. However, given this bug, code signing is useless against an active MITM with no special capabilities.

Mitigation:
Use the long key ID. Make sure the key is received over SSL, though that doesn't fix the second problem if the keyserver is malicious. Make the admin manually check that the long key ID of the received key matches the requested key ID until the upstream bug is fixed.

**Comment by fowlslegs** [comment]
Funny, agl's issue was fixed the day after this issue was closed. It's been 14 months, so I'm sure changes have propogated to the gnupg binary in Tails. It should no longer be necessary to check the fingerprint separately when GPG now implicitly does so when fetching a key using its fingerprint; I will go ahead and remove this from install.md.

Also, since Tails 1.6 (and probably older versions too) ships with the SKS hkps keyserver certificate and the hkps pool as the default keyserver in the [gpg.conf](https://labs.riseup.net/code/projects/tails/repository/entry/config/chroot_local-includes/etc/skel/.gnupg/gpg.conf?utf8=%E2%9C%93&rev=1.6), the `--keyserver pool.sks-keyservers.net` option currently present in install.md is just exposing the admin to a possible MitM attack. This would be a serious concern if (a) the agl bug hadn't been fixed and (b) instructions weren't added to verify the fingerprint separately, but as things stand today at worst this could result in a DoS or an attempt to exploit GPG by sending it a malformed key (the latter is probably very difficult though). Anyway, I'll remove that in my pull request too.
