### ISSUE TITLE
Use unattended-upgrades instead of cron-apt

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5295]
SecureDrop uses its own `cron-apt` script for nightly package updates. To reduce our code maintenance footprint, we should consider switching to [unattended-upgrades](https://help.ubuntu.com/community/AutomaticSecurityUpdates), which is the distribution-standard way to offer similar functionality. If we make this switch, we must ensure that we can match our current reboot logic (per the linked page, unattended-upgrades supports automatic reboots).

This is a candidate for inclusion in the Bionic/Focal epic (#4768).

**Comment by emkll** [comment]
Since cron-apt is separated into it's own task, we should create a new unattended-upgrades task, and conditionally use it in Focal in https://github.com/freedomofpress/securedrop/blob/9059594d6beb0d0b792006b9223e110ac7ffff08/install_files/ansible-base/roles/common/tasks/main.yml#L14 (and continue to use cron-apt in Focal). This will add a bit more complexity in the test logic, but will only be temporary.
