### ISSUE TITLE
Update user_manual.md with screenshots from 0.3

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#530]
With the 0.3 release in the works, we should remember to update user_manual.md with new screenshots and step-by-step instructions.

**Comment by conorsch** [comment]
Done and done! The documentation base has grown substantially since this issue was opened. We now have targeted guides for the various user roles in SecureDrop:

* [Source Guide](https://docs.securedrop.org/en/stable/source.html)
* [Journalist Guide](https://docs.securedrop.org/en/stable/journalist.html)
* [Admin Guide](https://docs.securedrop.org/en/stable/admin.html)

All include screenshots. It's worth noting that the existing screenshots are mostly from OS X, rather than Tails, but we're tracking that problem in #1231.
