### ISSUE TITLE
Marking grsec kernel as default in Focal staging

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5507]
## Description

Currently Focal by default has a kernel with higher version (`5.4.x`) than our grsec kernel (`4.14.x`). We have to mark our grsec kernel as the default kernel for boot.

We can use steps mentioned in 
https://github.com/freedomofpress/securedrop-debian-packaging/blob/main/securedrop-workstation-grsec/debian/postinst#L29-32 for the same.

**Comment by conorsch** [comment]
A few clarifications regarding the current state of Focal kernel support. 

The Focal VMs are already booting into grsecurity-patched kernels, and those kernels persist after the VMs are rebooted. This works because in install logic (Ansible playbooks), the grsec kernel is forced for the subsequent boot, and post reboot, we remove all non-grsec kernels from the host, so they can't be updated and take precedence in the boot menu. See for example:

https://github.com/freedomofpress/securedrop/blob/f81e41539bc5e5ae8b9a443ead719513622553c8/install_files/ansible-base/roles/grsecurity/tasks/from_fpf_repo_install_grsec.yml#L60-L61

That's not quite as elegant as the explicit version pinning via metapackage that we employ in the Workstation (https://github.com/freedomofpress/securedrop-debian-packaging/blob/05eedc6e2a5d9a1c53ebb6dda0a2188365063e05/securedrop-workstation-grsec/debian/postinst#L26-L32), and switching to that setup for the servers would make things a lot more predictable, and also enable us to delete a bunch of Ansible tasks. 

We'll likely want to split the metapackage by distro, however, so that we can evaluate newer kernels on Focal (#5479) without also forcing changes on Xenial. Additionally, we'll likely switch to paxctld (#4134), and test-driving that setup on Focal separately from Xenial will help with review. Recall that in #5518 we only updated the `paxctl` command in the Ansible tasks—in the metapackage, they're unchanged. That's fine for now, but it means that a Focal machine with the metapackage installed would fail on kernel upgrade, because the wrong header style would be used to set flags on the grub binaries, causing the package upgrade to abort.

Let's take a closer look at the "Ansible and molecule changes" section on the #4768 epic and try to map those out more explicitly.

**Comment by eloquence** [comment]
(@emkll and @conorsch will discuss next steps and update the epic.)

**Comment by conorsch** [comment]
Started working on this already. Note that the work here boils down to "create Focal-specific `securedrop-grsec` metapackage", as described in #4768, and is closely related to #4134, as well. I'm going to open a new issue that succinctly captures the goal of a new metapackage to aid in upcoming review.
