### ISSUE TITLE
Add `seen` data to `qa_loader`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5514]
#5505 will add the tables to support the seen/unseen feature in the SecureDrop Client (https://github.com/freedomofpress/securedrop-client/issues/187). To test this feature, it will be helpful to have some `seen` annotations for submissions generated through the loader.

**Comment by eloquence** [comment]
I would suggest that all replies generated by the scripts should be marked as seen by one user, because there will never be a situation under which they are not at least seen by the sender.

**Comment by eloquence** [comment]
Given the heavy focus on SecureDrop Workstation template consolidation and the SecureDrop Core release this sprint, we've agreed to defer work on this for now during the 10/1-10/15 sprint period, likely until the next sprint. Contributor help welcome before then, though, so tagging accordingly :)

**Comment by sssoleileraaa** [comment]
Whoops closed this by saying `partially resolves` this issue in the pr that was merged above. Reopening because we still need to update qa_loader to show seen data (and file submissions so we can test file-specific changes, but this can be done separately if one so chooses). I updated the title and description of this issue accordingly.
