### ISSUE TITLE
`deb-tests-focal` CI job flakes with connection failure

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5540]
Example failure: https://app.circleci.com/pipelines/github/freedomofpress/securedrop/1056/workflows/988b91e4-5748-497d-a37a-10b509c42775/jobs/45010

Example output:

```
TASK [build-ossec-deb-pkg : Download OSSEC signature.] *************************

fatal: [focal-sd-generic-ossec-agent]: FAILED! => {"changed": false, "dest": "/tmp/build/ossec-hids-3.6.0.tar.gz.asc", "elapsed": 10, "msg": "Connection failure: The read operation timed out", "url": "https://github.com/ossec/ossec-hids/releases/download/3.6.0/ossec-hids-3.6.0.tar.gz.asc"}
```

**Comment by conorsch** [comment]
Submitted a PR with an attempted quick-fix, just increasing the timeout on this and related tasks. Stepping back, it's not really necessary that we build the ossec deb packages from scratch each run. Since they change so seldom, we could just fetch them from the FPF apt server, which would decrease builds times by a few minutes, at a guess.
