### ISSUE TITLE
Weblate login account error

### ISSUE THREAD

**Issue by KwadroNaut** [freedomofpress/securedrop#5588]
## Description

When trying to use GitHub to login, but that username is already registered, you will not get a helpul error message:

`Could not complete registration. The supplied authentication, e-mail address or username is already in use for another account.
`

## Steps to Reproduce

1.  Create a user at weblate.securedrop (username+password)
2. Logout of weblate
3. Login to a github account with the same username as above (case insensitive though I think) with the same browser session
4. Try to login via github, get registration error and not login error.

Note: if you're *not* logged into github, you get thrown into the registration process and be given a github login screen.

## Expected Behavior

Get an error that you couldn't login with that github account because there it conflicts with an existing account and thus not create an account either. The wording could be better :)

## Actual Behavior

![Screenshot from 2020-10-17 00-20-31](https://user-images.githubusercontent.com/99527/96319492-1bfcb700-1010-11eb-8fb5-f1f614e18634.png)

## Comments

@eloquence suggested to open this bug here, but it might very well be better placed at weblate

**Comment by echoesactiii** [comment]
I think it's a case of bad UX from Weblate here. This is what I narrowed it down to:

- It _seems_ as though the account was original created with a username/password, and never then had the GitHub account of the same name associated to it.
- Because the GitHub account wasn't already linked to a weblate account, it tried to create a new one with that username (the default behaviour when you login with a GH account it doesn't know)
- It failed, because the username already exists - resulting in the somewhat poorly worded error above. 

You are able to _add_ an otherwise unregistered GitHub account to an already registered Weblate account, but to do that you need to login and add it in your settings page. It won't auto associate them because that would mean that anyone could login to a Weblate user's account by creating a GitHub account by the same name.

**Comment by KwadroNaut** [comment]
As I suspected, feel free to throw it over the wall at weblate and close this one. Thanks!

**Comment by eloquence** [comment]
@KwadroNaut I agree the error message could be improved. I've filed https://github.com/WeblateOrg/weblate/issues/4745 ; please don't hesitate to add ideas/context there as needed. Closing this issue.
