### ISSUE TITLE
TBB detection not working in SI for TBB 10.0.4 on MacOS

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5626]
## Description

TBB 10.0.4 on MacOS is incorrectly identified as a non-Tor browser in the Source Interface

## Steps to Reproduce

Start TBB 10.0.4 and visit an SI address.

## Expected Behavior

- message displayed indicating that user should change security setting

## Actual Behavior

- message displayed encouraging user to use Tor Browser "instead"

![Untitled 2](https://user-images.githubusercontent.com/2782952/99124627-85042a00-25d0-11eb-8181-4fd2f8723d00.png)

## Comments

(Detection also failing on securedrop.org.)

**Comment by harrislapiroff** [comment]
I'll take a look at this for SDO purposes and share the necessary updates here

**Comment by harrislapiroff** [comment]
Looks like the issue is the bit of the user agent string to match the macOS version. The current string:

https://github.com/freedomofpress/securedrop/blob/b16aa1f932ff5168536feb1d2dd13bf2a3ec0e47/securedrop/static/js/source.js#L1

An updated string that works:

```js
const TBB_UA_REGEX = /Mozilla\/5\.0 \((Windows NT 10\.0|X11; Linux x86_64|Macintosh; Intel Mac OS X 10\.[0-9]{2}|Windows NT 10\.0; Win64; x64|Android; Mobile); rv:[0-9]{2}\.0\) Gecko\/20100101 Firefox\/([0-9]{2})\.0/
```

(Note the specific bit that I changed was: `Intel Mac OS X 10\.14}` => `Intel Mac OS X 10\.[0-9]{2}`
