### ISSUE TITLE
[1.7.0-rc4 QA] Internal Server Error when selecting Simplified Chinese

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop#5740]
## Description

When you select "zh_Hans" from the language menu on the Journalist Interface, you get an internal server error. This doesn't happen on the Source Interface, though.

## Steps to Reproduce

1. `git checkout release/1.7.0`
2. make sure `apt_repo_url` is set to `https://apt-test.freedom.press` and `apt_repo_pubkey_files` is set to `apt-test-signing-key.pub` in `install_files/ansible-base/roles/install-fpf-repo/defaults/main.yml`
3. `./securedrop-admin setup`
4. `./securedrop-admin sdconfig` and type in `zh_Hans` as a language choice
5. `./securedrop-admin install` and make sure install occurs without error
6. `./securedrop-admin tailsconfig`
7. Run tails updater
8. Go to journalist interface, log in, and select zh_hans from the language menu

## Expected Behavior

To see the journalist interface switch to zh_hans, like it does for the source interface, e.g.:

![Screenshot from 2021-01-22 21-42-30](https://user-images.githubusercontent.com/4522213/105551885-0d313a80-5cb8-11eb-98ea-0c53f7001568.png)

## Actual Behavior

![Screenshot from 2021-01-22 21-21-51](https://user-images.githubusercontent.com/4522213/105551893-0f939480-5cb8-11eb-966a-32a6978bb827.png)

**Comment by rmol** [comment]
It's due to a key error triggered by an out-of-date placeholder variable in one of the source strings in the journalist interface (`{doc_num}` changed to `{num}`). It's been sorted out during the translation work for this release -- the translators have been working with the updated source string, and the simplified Chinese translation is now correct. So when we merge the updated translations just before release, it will be fixed. 

You can verify this now with the dev server, if that timing makes you nervous. I did. :slightly_smiling_face: 

- `git checkout -b zhtest origin/release/1.7.0`
- `make dev`
- log in to the JI, switch to simplified Chinese, confirm the key error
- `securedrop/bin/dev-shell ./i18n_tool.py --verbose update-from-weblate` (part of the [i18n release management instructions](https://docs.securedrop.org/en/stable/development/i18n.html#merge-translations-back-to-develop))
- it takes a while, but once it's finished, try the JI again and it should work

**Comment by rmol** [comment]
This was fixed with the new translated strings for 1.7.0.
