### ISSUE TITLE
[Focal] LTS channel allowed for upgrades

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#5782]
## Description

The release management settings for Focal permit `do-release-upgrade` to the next LTS version. There isn't one of those yet, but tests are failing because of it:

```
        def test_release_manager_upgrade_channel(host):
            """
            Ensures that the `do-release-upgrade` command will not
            suggest upgrades from Xenial to Bionic (which is untested
            and unsupported.)
            """
            expected_channels = {
                "xenial": "never",
                "focal": "never",
            }
    
            config_path = "/etc/update-manager/release-upgrades"
            assert host.file(config_path).is_file
    
            raw_output = host.check_output("grep '^Prompt' {}".format(config_path))
            _, channel = raw_output.split("=")
    
            expected_channel = expected_channels[host.system_info.codename]
    >       assert channel == expected_channel
    E       AssertionError: assert 'lts' == 'never'
    E         - never
    E         + lts
```

To see that test fail, you'll need to use hardware or Qubes VMs (installed from ISO), since the bento boxes modify the setting https://github.com/chef/bento/blob/3dd165cf422572ab4240c8f1ce9a7e40b7960457/packer_templates/ubuntu/scripts/update.sh#L5 in a similar fashion to what we implemented for Xenial in https://github.com/freedomofpress/securedrop/pull/3546/files

## Comments

This is almost certainly a duplicate of #5781, but filing separately until that's confirmed.

**Comment by emkll** [comment]
This test failure is due to changes introduced by https://github.com/freedomofpress/securedrop/pull/5684/files

The securedrop-config (focal) package no longer contains some of the historical changes we've made on long running instances via securedrop-config postinst.

The xenial postinst, containing historical changes: https://github.com/freedomofpress/securedrop/blob/develop/install_files/securedrop-config/DEBIAN/postinst
The (streamlined) focal postinst: https://github.com/freedomofpress/securedrop/blob/develop/install_files/securedrop-config-focal/DEBIAN/postinst .


We can update that string ansible (or via postinst) if strictly necessary for 1.8.0
