### ISSUE TITLE
`make build-debs` fails due python3.5 support having been removed from setuptools-scm

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5876]
## Description

`make build-debs` is failing at  `TASK [build-securedrop-app-code-deb-pkg : Install SecureDrop Python requirements in virtualenv for translation work] ***`, with the following error output:

```
...
"Collecting python-dateutil==2.7.2 (from -r /tmp/securedrop-app-code_1.9.0~rc1+xenial_amd64-prep/requirements.txt (line 187))", "  Downloading https://files.pythonhosted.org/packages/c5/39/4da7c2dbc4f023fba5fb2325febcadf0d0ce0efdc8bd12083a0f65d20653/python-dateutil-2.7.2.tar.gz (298kB)", "    Complete output from command python setup.py egg_info:", "    WARNING: The wheel package is not available.", "    Traceback (most recent call last):", "      File \"<string>\", line 1, in <module>", "      File \"/tmp/pip-build-u4k0g0te/python-dateutil/setup.py\", line 86, in <module>", "        \"test\": Unsupported", "      File \"/tmp/securedrop-app-code-i18n-ve/lib/python3.5/site-packages/setuptools/__init__.py\", line 144, in setup", "        return distutils.core.setup(**attrs)", "      File \"/usr/lib/python3.5/distutils/core.py\", line 108, in setup", "        _setup_distribution = dist = klass(attrs)", "      File \"/tmp/securedrop-app-code-i18n-ve/lib/python3.5/site-packages/setuptools/dist.py\", line 425, in __init__", "        k: v for k, v in attrs.items()", "      File \"/usr/lib/python3.5/distutils/dist.py\", line 281, in __init__", "        self.finalize_options()", "      File \"/tmp/securedrop-app-code-i18n-ve/lib/python3.5/site-packages/setuptools/dist.py\", line 706, in finalize_options", "        ep.load()(self)", "      File \"/tmp/securedrop-app-code-i18n-ve/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 2229, in load", "        return self.resolve()", "      File \"/tmp/securedrop-app-code-i18n-ve/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 2235, in resolve", "        module = __import__(self.module_name, fromlist=['__name__'], level=0)", "      File \"/tmp/pip-build-u4k0g0te/python-dateutil/.eggs/setuptools_scm-6.0.1-py3.5.egg/setuptools_scm/__init__.py\", line 15, in <module>", "        from .version import format_version, meta", "      File \"/tmp/pip-build-u4k0g0te/python-dateutil/.eggs/setuptools_scm-6.0.1-py3.5.egg/setuptools_scm/version.py\", line 42", "        trace(f\"tag '{tag}' parsed to {result}\")", "                                              ^", "    SyntaxError: invalid syntax", "    ", "    ----------------------------------------"]}
```
Working hypothesis is that this is due to setuptools_scm 6.x dropping support for .egg format packaging.

## Steps to Reproduce

Run `make build-debs` against `develop`

## Expected Behavior

Success!

## Actual Behavior

Failure as above

**Comment by conorsch** [comment]
The specific syntax noted in the error output, the fstrings, is only supported in python3.6 and above. Looks like `setuptools_scm` dropped support for python3.5, which Xenial uses, as of v6.0.0, not v6.0.1:

```
$ git diff v5.0.2..v6.0.0 | grep python_version | head -n2
-        python_version: [ '2.7', '3.5', '3.6', '3.7', '3.8', 'pypy2', 'pypy3' ]
+        python_version: [ '3.6', '3.7', '3.8', '3.9', 'pypy3' ]
```

So I'd guess that pinning to `<6.0.0`, rather than `<=6.0.0`, would resolve for now. Will try that locally.

**Comment by zenmonkeykstop** [comment]
The revised requirement files that I added pin it at 5.0.2 iirc. Still no joy

**Comment by conorsch** [comment]
Already pinned to `5.0.2` in https://github.com/freedomofpress/securedrop/pull/5875/files#diff-fce7a98d75a48de1db3dc18b0b44239ef29db3dc2b4bb0459d5a623cc2ef3316R594-R597, and that's clearly not enough. Looks like we're getting a newer version than we want inside the build context.

**Comment by conorsch** [comment]
Well, this is unfortunate. It appears that `python-dateutil==2.7.2`, from approximately 3 years ago, [includes](https://github.com/dateutil/dateutil/blob/ff03c0f14caa1b11c604906b854dce18c7d0a7a3/setup.py#L66) `setup_requires=['setuptools_scm']` in its `setup.py`, which is effectively a requirement in itself, outside the context of pip. Any packages specified there will be easy-installed prior to installation. Since there's no version-pinning in that old dependency, it's _always_ the most recent version of "setuptools_scm" that will be pulled in. Since the latest versions break compatibility with python3.5, that's bad. 

Here's what the [setuptools v46.0.0 docs say](https://github.com/pypa/setuptools/blob/50f3575da42ce5b7c013c28ff623ce16c231455d/docs/setuptools.txt#L282-L296) about the `setup_requires` arg. 

Even the latest versions of dateutil don't pin the version of setuptools_scm, but on 2.8.1 I'm at least getting a zero exit code from some of the scm version tooling: 

```
root@03403bb58205:/tmp/dateutil# python3 setup.py --version
setup.py:20: UserWarning: python_requires requires setuptools version > 24.3
  UserWarning)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
0.0.0
```

which is progress? I'll try pinning dateutil 2.8.1 and see if that gets us a working build.

**Comment by conorsch** [comment]
> I'll try pinning dateutil 2.8.1 and see if that gets us a working build.

No, same problem: setuptools_scm 6.0.1 is pulled in via easyinstall, and fails due to lack of python3.5 support. However, it appears that we can satisfy the `setup_requires` condition (which, again, is not bounded with a version constraint) by preinstalling setuptools_scm, at the version we specify, into the virtualenv prior to running the install from the requirements file. That's based on the discussion here: https://github.com/pypa/setuptools_scm/issues/541#issuecomment-801313647 and initial testing locally says that's a promising workaround for now.

**Comment by zenmonkeykstop** [comment]
I tried that locally, just with a pip install before the main one, no joy. Also has the disadvantage of not checking hashes.
