### ISSUE TITLE
Task install the grsecurity-patched kernel fails

### ISSUE THREAD

**Issue by cbetit** [freedomofpress/securedrop#5943]
I am trying to install securedrop on proxmox VMs each running Ubuntu 20.04 
My admin workstation is running from a tails usb on a laptop

Installation fails on this task: install the grsecurity-patched kernel
Error reads; ansible async task did not complete within the requested time

![Securedrop Error](https://user-images.githubusercontent.com/84191926/118359758-4a7e4880-b585-11eb-9d8d-09c982455b2f.jpg)

Is there any setup regarding virtual machines that I am missing?

Thank you in advance for your assistance

**Comment by zenmonkeykstop** [comment]
Hi @cbetit - we strongly recommend against the use of virtualization for SecureDrop servers due to security concerns. See https://docs.securedrop.org/en/stable/hardware.html?highlight=virtualization#required-hardware and the threat model at https://docs.securedrop.org/en/stable/threat_model/threat_model.html for more information on that.

If you're looking to set up a public SecureDrop, FPF can help - please contact us via the support portal at https://support.freedom.press or via GPG-encrypted email to securedrop@freedom.press . 

If you're just looking to set up a development or test environment, an alternative to Proxmox would be to use our development virtualized environments (note that these are also *not* suitable for use in production): https://docs.securedrop.org/en/stable/development/virtual_environments.html

**Comment by cbetit** [comment]
@zenmonkeykstop thank you for your response.
Thank you for the suggestion. Let me sort out my hardware, I will most definitely get in touch via the channels recommended.

👍
