### ISSUE TITLE
fwupd generates OSSEC alerts from syslog

### ISSUE THREAD

**Issue by elfranne** [freedomofpress/securedrop#6097]
## Description

fwupd is creating a log entry:
```
fwupd[135244]: 19:33:15:0929 FuPluginLinuxSwap    could not parse /proc/swaps: failed to call org.freedesktop.UDisks2.Manager.GetBlockDevices(): The name org.freedesktop.UDisks2 was not provided by any .service files
```
That is being captured by OSSEC and generating an alert level 2. 
It seems that udisk2 package was either not included or removed by Ansible.

## Steps to Reproduce
I installed Secure Drop according to the manual.

## Expected Behavior
Reduce notifications

## Comments
Is fwupd even required ?

**Comment by eloquence** [comment]
Thanks for the report @elfranne. I'm also observing those alerts. #5882 silenced some of these messages, but it looks like additional work may be required to avoid unnecessary alerts related to `fwupd`.

**Comment by conorsch** [comment]
Confirmed, I'm seeing a lot of these from a test instance, as well. Another closely related message is 

```

Received From: mon->/var/log/syslog
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

Sep 18 13:32:22 mon fwupd[134454]: 13:32:22:0632 FuEngine             failed to get chassis type: no structure with type 03
```

While it would be grand to support fwupd at some point in the future, we definitely don't now, and won't without serious consideration for hardware compatibility. For now, let's just silence these alerts, since there's no action an admin can take to remedy the situation. @cfm offered to take a first pass, I'm happy to review!
