### ISSUE TITLE
Make targets `build-debs[-notest]` fails on new circular dependency between PyPI packages `flit_core` and `tomli`

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6137]
## Description

Since October 10, `staging-test-with-rebase` fails in `make build-debs-notest`.  This is likely to bork `make build-debs` for the current production release cycle too.

## Expected Behavior

https://app.circleci.com/pipelines/github/freedomofpress/securedrop/3075/workflows/6c173f25-a21a-40f6-a476-7b6f9c996b2b/jobs/57150

## Actual Behavior

https://app.circleci.com/pipelines/github/freedomofpress/securedrop/3076/workflows/4a156c36-7049-4645-a6a8-c5583f658e99/jobs/57152

## Comments

This looks like takluyver/flit#451, for which the resolution [may be to update pip ≥ 21](https://github.com/takluyver/flit/issues/451#issuecomment-941075197).

**Comment by cfm** [comment]
To be exact:  `flit`/`flit_core` 3.4.0 [switched](https://github.com/takluyver/flit/compare/3.3.0...3.4.0#diff-d5423f1e62fdcd5eb981c27e6c54d99fc60deb9d2614635c32ebf9c15a554ec5R340) its TOML parser from [`toml`](https://github.com/uiri/toml), [which has no dependencies](https://libraries.io/pypi/toml), to [`tomli`](https://github.com/hukkin/tomli), which [requires](https://github.com/hukkin/tomli/blob/master/pyproject.toml#L2) `flit_core`.

<details>
<summary><strong>Dependency graph (excluding version constraints):</strong><br/>

<img src="https://user-images.githubusercontent.com/357435/137046840-9504cba0-3fbc-4558-9888-ed7c5013db32.png">
</summary>

```
graph TD

setuptools-rust --> setuptools
setuptools-rust --> setuptools_scm["setuptools_scm[toml]"]
setuptools_scm --> setuptools
setuptools_scm --> tomli
tomli --> flit_core
flit_core --> tomli
```

</details>

`stg-6137-translation-requirements` is now [testing](https://app.circleci.com/pipelines/github/freedomofpress/securedrop?branch=stg-6137-translation-requirements) whether pip ≥ 21 can handle this circular dependency.  We'll then have to decide whether that upgrade is acceptable (pending a diff review) at this point in the release process.

Meanwhile, `stg-6137-translation-requirements-2` is [testing](https://app.circleci.com/pipelines/github/freedomofpress/securedrop?branch=stg-6137-translation-requirements-2) whether pinning `flit_core<3.4` in our top-level `translation-requirements.in` will satisfy the version constraints of the `setuptools-rust` dependency graph.

**Comment by conorsch** [comment]
Summarizing synchronous discussion from today. We basically have two options here:

1. Stop building all python reqs from source, and fetch wheels from pypi. Doing so avoids the dependency conflicts in the build-deps described above, but involves a significant shift in our [dependency management policies](https://github.com/freedomofpress/securedrop/wiki/Dependency-Update-Policies), so we consider it a last resort.
2. Update `pip` within the build environment from Focal's system version, `20.0.2-5ubuntu1.6`, to PyPI version `21.3`. This is also a slight departure, but it unbreaks the build, so we're happy with it for now.

Option 2, then, is our path forward. It's got some shortcomings in that we cannot pin the hash in all places, particularly in the `debian/rules` file used by dh-virtualenv. Punting on a larger refactor of the build logic until we're out of QA period. As part of the pip update, I will not be submitting a diff review, since pip is a foundational tool in the Python ecosystem, and re-reviewing that widely used dependency feels superfluous. 

I'll aim to have a PR up by EOD, then toss to @cfm for review and backporting!
