### ISSUE TITLE
investigate and implement improvements to header-based tor2web detection for current active tor2web proxies

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6293]

**Comment by legoktm** [comment]
From poking at it a bit and reviewing the tor2web source code, I came up with https://github.com/freedomofpress/securedrop/pull/6304, which relies on buggy URL mangling on the `/create` form. I've marked it as a draft because the UX is pretty bad, you have to click through like 2 forms and only then do we fire the tor2web alert. How bad would it be if the very first "Get started" button was actually a `<form>` that POST'd to `/generate`, so we could include the hidden form field and do the detection at the very first step?

**Comment by zenmonkeykstop** [comment]
This is really neat - I'm trying to think of downsides to converting the Get Started button to a POSTed form but none spring to mind. Does it detect tor2web specifically tho, or any proxy that rewrites links? Both are bad, but we might need to make the language more general on the warning page in the latter case.

It would still be good to detect tor2web via headers if possible. It has fewer UX implications and it could happen on the first connection. But this is a great extra defense.

**Comment by eaon** [comment]
Oh my, I *love* this! I don't think there's downsides to a `POST`ed Get Started button - it'd be bad for search engines, but messing with those is an upside in our case anyway.

> Does it detect tor2web specifically tho, or any proxy that rewrites links?

Given that it's based on a `href=` inside an attribute, I'd expect other naïve proxies that do simple substitution to trip over this as well, but realistically speaking, how many of those are configured to access onion services and would they be used for anything other than a service that's essentially the same as Tor2Web? I think it'd be enough to adapt the language on the warning to something along the lines of "If you use a Tor2Web or similar proxy"

**Comment by zenmonkeykstop** [comment]
Yeah I think we're all of the same mind here, will tweak the language in #6300 a little. @legoktm I would say go for it on the change to the Get Started button.

**Comment by legoktm** [comment]
The rewrites that tor2web do are pretty naive, it's entirely possible that it becomes more robust in the future (e.g. using a proper HTML parser) and we need some other detection mechanism. I think this should catch any similarly naive proxy that wants to make onion services accessible on the clearnet, because they have to hijack any *.onion URL.
