### ISSUE TITLE
Add honeypot field to SI message form to block automated submissions

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6295]
## Description

The Source Interface has limited protections in place to block bots. One simple bot-blocking measure would be to add a hidden form field on the message submission form, and reject submissions that include a value for the field.

## User Research Evidence

Spam reports from instance maintainers.

## User Stories

As a journalist, I want to save time by not having to review spam messages.

**Comment by legoktm** [comment]
For reference, MediaWiki does this with https://gerrit.wikimedia.org/g/mediawiki/core/+/4afd0f7c3e017b84adef7938a31bc40a69304e62/includes/EditPage.php#2981

The intention is to block generic form-filling spambots. Anything designed to spam SecureDrops will eventually adapt.

**Comment by kushaldas** [comment]
>The Source Interface has limited protections in place to block bots. One simple bot-blocking measure would be to add a hidden form field on the message submission form, and reject submissions that include a value for the field.

How much effective will this be? I am wondering if someone is targeting SecureDrop instances, that is much targeted than random spambots.

**Comment by ninavizz** [comment]
@kushaldas I don't think we'll know until we try mitigations like this, 1:1. That said—I do think this one back(ish)-end mitigation, should go in before any others—so that its effectiveness on its own, can be measured against other bot mitigations.

While I'm not a fan of the "bounce" remediation prior to other UX measures going in before it, entirely separate from that opinion I would like to see _different_  spam mitigations go out in different releases... as the source of the spam is not known at this time.  We'll never know, unless 1:1 they're deployed with methodical research endeavored following each release, to learn more.

**Comment by zenmonkeykstop** [comment]
@kushaldas I don't expect that it will help with much tbh, but dealing with low-hanging fruit first (see the rest of https://github.com/freedomofpress/securedrop/milestone/77). Targeted spam is gonna require more work, probably the best mitigations there would require the use of SecureDrop Workstation.

**Comment by cfm** [comment]
@legoktm in https://github.com/freedomofpress/securedrop/issues/6295#issuecomment-1045303533:

> For reference, MediaWiki does this with https://gerrit.wikimedia.org/g/mediawiki/core/+/4afd0f7c3e017b84adef7938a31bc40a69304e62/includes/EditPage.php#2981
> 
> The intention is to block generic form-filling spambots. Anything designed to spam SecureDrops will eventually adapt.

Seconding this example's use of `display: none`, which will [correctly hide the honeypot field both visually and in the accessibility tree (but of course leave it reachable in the DOM)](https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html).
