### ISSUE TITLE
Add check for codename-only messages in Source Interface

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6298]
## Description

Some production instances have seen an uptick in initial messages from sources containing only a source codename and no actionable content. This may be attributable to bots, or to UX failures, or a combination of both. Planned changes to the source workflow will mitigate both cases, but in the interim a check should be added to reject codename-only initial messages.

This change should take account of the following:

• the requirement should be applied on initial submissions only. Returning sources will have had to save their codenames and use them to log in, and therefore can reasonably be expected to do the right thing
• rejected messages should result in useful feedback to sources, and should not prevent them from submitting a valid message afterwards
• the feature should be configurable by admins in the JI instance config panel, and it should be disabled by default.

## User Research Evidence

Spam reports by instance admins.

**Comment by eloquence** [comment]
As discussed in sprint planning, some potential concerns with this approach:
- it could alarm users to realize that the software inspects messages they send
- it does not necessarily address the underlying misunderstanding that causes the user to submit a passphrase

My own view is that this should still be implemented as-is, and IMO not optional, because the argument that an accidental passphrase submission is a major operational security issue prevails over other considerations -- but we should view it as a stopgap measure until we've fully validated and implemented other improvements to the authentication flow. The concerns above could, in my view, be mitigated with clear error messaging.

But let's definitely take time to kick around the pros and cons on this one.

**Comment by eloquence** [comment]
The UX improvements we could make this change (optional or not) contingent on are described in #6311.
