### ISSUE TITLE
Test securedrop-admin with Tails 5.0

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6400]
## Description

https://tails.boum.org/news/test_5.0-beta1/

Tails 5.0 is based on Debian Bullseye, which means it's using a newer Python version (3.9) among plenty of other things.

It's probably worth walking through a full SD install + backup/restore to make sure it works as expected.

**Comment by zenmonkeykstop** [comment]
In-progress comment for notes as I go through a (virtualized) from-scratch setup on 5.0:
- :warning: menubar layout has changed (**Activities** is first option, screenshots and docs will need revising)
- :warning: initial ./securedrop-admin setup failed because the torified  torproject mirror was not available - could be a flake
- :x:  was a flake but looks like the `ccontrol` package has been dropped from Bullseye, so the initial installation of apt deps is gonna fail. Updating admin/bootstrap.py to remove it and retrying.
- :heavy_check_mark: with ccontrol gone, got as far as virtualenv install and failed a few times, getting name resolution failures for files.pythonhosted.org - finally venv setup succeeded 
- :x: `./securedrop-admin sdconfig` and `./securedrop-admin install` completed successfully, but `tailsconfig` fails as there is no `python` executable in Tails5, just `python3`. Updating the ansible task accordingly... and it works.
- :heavy_check_mark: GUI updater updates from `develop` to 2.3.1 with no issues, with the changes above.
- :heavy_check_mark: on an local-ssh install, `ssh app` and `ssh mon` work correctly
- :heavy_check_mark: Source and Journalist Interfaces are available via shortcuts
- :heavy_check_mark: backup and restore work without errors
-  :heavy_check_mark: testinfra deps installed without issue and testinfra tests run happily

**Comment by zenmonkeykstop** [comment]
Looks like ccontrol is a vestigial install left over from the days of Tails 3, removing it doesn't appear to have any effect on setup in Tails 4.29. Also, changing `python` to `python3` in in the tailsconfig task seems to work fine too. So with those changes basic functionality should be the same in 4 and 5, leaving aside some look-and-feel differences.

**Comment by legoktm** [comment]
> - :heavy_check_mark: with ccontrol gone, got as far as virtualenv install and failed a few times, getting name resolution failures for files.pythonhosted.org - finally venv setup succeeded 

I've been unable to get past this, it keeps failing on name resolution for files.pythonhosted.org.

**Comment by legoktm** [comment]
Scratch that, I think I just got a bad circuit or something. After a restart it installed pretty quickly. Theoretically we could use https://pip.pypa.io/en/stable/cli/pip/?highlight=timeout#cmdoption-timeout to bump the pip timeout, but I don't know if that would actually help with DNS lookups.

**Comment by zenmonkeykstop** [comment]
> Scratch that, I think I just got a bad circuit or something. After a restart it installed pretty quickly. Theoretically we could use https://pip.pypa.io/en/stable/cli/pip/?highlight=timeout#cmdoption-timeout to bump the pip timeout, but I don't know if that would actually help with DNS lookups.

Worked first time for me this time on a fresh tails5 stick, gonna see how the upgrade process in your PR goes next.
