### ISSUE TITLE
Remove JS minification from the web applications.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6415]
## Description

In order to improve performance of the web applications, support for minification for JS and CSS files was added in https://github.com/freedomofpress/securedrop/commit/e74b39075fa4d407bf929ab8bc5ab24abad79f70, using `flask-assets`, `cssmin`, and `jsmin`.

Since then the application has started using SASS for CSS minification (see #2808), meaning only JS is being minified. Only 2 files are currently being minified, `static/js/{source,journalist}.js`, with savings of <1k and <2k respectively. 

To reduce code complexity at the cost of 1-2k in page size, it would make sense to drop JS minification as well. Alternatively, the files could be minified during the build process (tho IMO it's overkill given the minimal gains).

One other disadvantage of server-side minification is that the Apache user needs to be able to write the minified files somewhere on the webroot. Removing it would allow for tightening up the relevant apparmor profile, removing the related write perms

## User Research Evidence
n/a

## User Stories
n/a

**Comment by legoktm** [comment]
Once you factor in gzip, the benefit of minification becomes pretty negligible. For source.js on 2.3.1:
```
$ du -b securedrop/static/js/source*.js* | sort
1167	securedrop/static/js/source.min.js.gz
1578	securedrop/static/js/source.js.gz
3271	securedrop/static/js/source.min.js
4501	securedrop/static/js/source.js
```

So +1 to getting rid of this extra complexity. The jsmin package is also unmaintained (c.f. https://github.com/tikitu/jsmin/issues/33#issuecomment-914040205) and problematic because the version we're on uses a now-removed setuptools option, which I had to workaround in https://github.com/freedomofpress/securedrop/issues/6358#issuecomment-1076844034.
