### ISSUE TITLE
Complete Basic server testing for 2.5.0~rc3

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6597]

**Comment by zenmonkeykstop** [comment]
### Environment

- Install target: VMs
- Tails version: 5.4
- Test Scenario: install
- SSH over Tor: no
- Release candidate: RC3
- General notes:

### Basic Server Testing
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [ ] ~~After performing Application Acceptance Testing, `./securedrop-admin verify` tests still pass.~~
- [x] QA Matrix checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [ ] ~~If doing upgrade testing, make a backup on 2.4.2 and restore this backup on this release candidate~~
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] ~~Can successfully add journalist account with HOTP authentication~~

**Comment by cfm** [comment]
### Environment

- Install target:  VMs
- Tails version:  5.4
- Test Scenario:  upgrade
- SSH over Tor:  yes
- Release candidate:  RC3
- General notes:  Tor is still both slower and flakier than usual, but it's tolerable.

### Basic Server Testing
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [ ] ~After performing Application Acceptance Testing, `./securedrop-admin verify` tests still pass.~
- [x] QA Matrix checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] If doing upgrade testing, make a backup on 2.4.2 and restore this backup on this release candidate
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] ~Can successfully add journalist account with HOTP authentication~

Not applicable on VMs (with virtualized Tails).

**Comment by cfm** [comment]
### Environment

- Install target:  NUC11s
- Tails version:  5.2
- Test Scenario:  upgrade
- SSH over Tor:  yes
- Release candidate:  RC3
- General notes:

### Basic Server Testing
- [ ] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
  
No; stalled due to Tor flakiness.
  
- [x] After performing Application Acceptance Testing, `./securedrop-admin verify` tests still pass.

Succeeded with `ssh -M app` and `ssh -M mon` in the background.

- [x] QA Matrix checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] If doing upgrade testing, make a backup on 2.4.2 and restore this backup on this release candidate
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [x] Can successfully add journalist account with HOTP authentication

**Comment by nathandyer** [comment]
### Environment

Install target: NUC11s
Tails version: 5.2
Test Scenario: Clean Install
SSH over Tor: Not during install, but post-install
Release candidate: RC3
General notes:

### Basic Server Testing
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [x] After performing Application Acceptance Testing, `./securedrop-admin verify` tests still pass.
- [x] QA Matrix checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [ ] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
    (I think this is an error on my side with the way I have SMTP configured through Gmail, I've never received any alerts. I'll debug more when I have time, but we can ignore this failure)
- [x] Can successfully add journalist account with HOTP authentication
