### ISSUE TITLE
Image on /lookup does not take you back to the homepage

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#682]
Say the source is on /lookup and has just submitted something and wishes to go back to the homepage. The logical step would be to click on the SecureDrop logo on the left, but doing so seems to just refresh the page the source is currently on. Is this the expected behavior? If so, do we want to require users to edit the URL to go back to the homepage?

**Comment by garrettr** [comment]
This is straightforward to fix, but a little tricky because you need to handle what happens if the source reloads the `/generate` page after having already created a codename (since this is easy to do by hitting the "Back" button). Since we re-use the same key in the session on both `/generate` and `/lookup`, re-visiting `/generate` would pop the original codename, effectively locking you out if you had failed to memorize or write down the first codename.

The current behavior is intentional, and is designed to prevent this outcome (since it is potentially disastrous, definitely confusing, and very easy to do by accident). We can improve this (and restore the intuitive behavior of clicking on the logo on `/lookup`), but will need to add supporting UX changes as well.

**Comment by redshiftzero** [comment]
Looks like this was implemented in PR #1165. Closing...
