### ISSUE TITLE
It is (probably) okay to decrypt a message with a revoked, expired or weak key

### ISSUE THREAD

**Issue by nwalfield** [freedomofpress/securedrop#6991]
`secret_key_from_cert` is used by `decrypt` to decrypt a message:

https://github.com/freedomofpress/securedrop/blob/8d00ba5d9d3835a22a09bcd3a338b65aee697e7d/redwood/src/keys.rs#L40-L48

But, there is no reason to not decrypt a message if it key is expired, revoked, the policy says the algorithms are no longer strong enough.  Is there?

**Comment by legoktm** [comment]
In the current context of SecureDrop it's a bit theoretical. Source keypairs are fully created and managed by SecureDrop, so there should never be a scenario with an expired or revoked key. 

AFAIK SecureDrop has always generated keys that are compliant with the current standard policy, but I agree with you that it doesn't make sense to prevent decryption of messages because of that.
