### ISSUE TITLE
Custom message on source interface homepage

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/securedrop#774]
At The Intercept we have a terrible spam problem with our securedrop instance. We're planning on editing our homepage template to write a simple message, something like: "This a secure submission system for sources, not for general inquiries" and maybe other instructions.

It would be cool if a custom message were officially supported, so we didn't have to edit the template.

**Comment by b4rton** [comment]
1. Because your Source page is necessarily generic, it makes no reference to the journalist or organization hosting it. That could be disorienting or even alarming. Is the source in the right place? In the ideal world, I'd like to be able to put my organization's name and logo alongside the SecureDrop logo. With or without that, how about intro language like: 

"Welcome to the SecureDrop site for confidential communications with [journalist or organization]. If you are seeing this page, your connection is encrypted and anonymous."

2. I think "submit documents" could scare some people off. Some potential sources don't think of themselves as sources at all, or are just dipping a toe, or might get the message that a message is unwelcome without documents. To avoid the presumption:

~~Submit documents for the first time~~
**First time here?**

~~If this is your first time submitting documents to journalists, start here.~~
**If this is your first visit, click the button below to begin a conversation or send a document.**

~~Submit Documents~~
**Get started**

~~Already submitted something?~~
**Been here before?**

~~If you have already submitted documents in the past, log in here to check for responses.~~
**If you have already sent a message or document, use your 'secret phrase' to check for a reply.**

~~Check for a response~~
**Log in**

----------

I would edit the first-time visitor page as well, if possible:

~~Remember this code and keep it secret~~
**Please remember this secret phrase and keep it secure**

~~To protect your identity, we're assigning you a unique codename.~~
**The secret phrase is unique to you and shields your identity. You will need it when you return to the site.**


~~Store this code somewhere safe, or memorize it. It can be used to compromise your anonymity.~~
**Store your secret phrase somewhere safe, or memorize it. Anyone who steals it can read your messages and our replies.**

~~Important: After you submit documents and messages, you will need this code to log in and read replies. This is the only way we can communicate back to you. You can also use your code to log in to submit more files and messages.~~
**Important: After you send a message or document, please return to the site and check for a reply. (Depending on circumstances, that may take a few days.) You will need your secret phrase to log back in. There is no other way for us to respond to you. If you forget it, you will have to begin again as a first-time visitor.**

---

On the page for returning visitors ("Log in to check for responses"):
~~Enter your code name~~
**Enter your secret phrase**

**Comment by redshiftzero** [comment]
Implemented in #1399
