### ISSUE TITLE
https deployment instructions for news orgs

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#821]
I talked a bit with Alex Halderman after our RWC2015 talk about HTTPS on news sites. He suggested:
1. Giving them instructions on how to deploy HTTPS on a single page without HTTPS for the entire domain. This would hopefully stop orgs from having pages like https://securedrop.example.com.
2. TIps on how to get to full HTTPS support. Anecdotally it seems that ads (mixed content) are a big factor; AFAICT the best solution is to proxy ads. (Yahoo does this.)

(@garrettr edited comment slightly for readability)

**Comment by garrettr** [comment]
@diracdeltas We have some specific recommendations for landing page deployment in the [Deployment Practices](docs/deployment_practices.md) doc. That would be a good location for further recommendations like the ones you're suggesting.

**Comment by garrettr** [comment]
@ageis These would be good additions to the Deployment Best Practices doc. What do you think?

**Comment by ageis** [comment]
I like the idea about HTTPS for a single page. I can update our doc with an example config. I'm also glad to write and include an example for reverse-proxying advertisements. Currently the doc is geared more to Apache2 but nginx coverage could be rounded out as part of this.

**Comment by conorsch** [comment]
This issue is out of scope for the SecureDrop project. We routinely encounter news organizations struggling with HTTPS deployments, so much so that we launched a separate project, Secure the News, to track progress there across general news sites: https://securethe.news. The documentation on that website, along with the [Deployment Best Practices](https://docs.securedrop.org/en/stable/deployment_practices.html#landing-page) guide, should be sufficient for orgs trying to make the switch to HTTPS.

In #1605 we're tracking stronger support and clearer documentation for enabling HTTPS on the Source Interface. For the Landing Page, which was the original focus of this issue, we have decent coverage already on the technical implementation details. In #1608 we can consider templating out content to make standing up a Landing Page simpler for orgs running SecureDrop for the first time.
