### ISSUE TITLE
Document Yubikey setup and use for all two-factor use cases

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#825]
Under the definition of "Two-Factor authenticator" in install.md, it is suggested that journalists and admins can use either the Google Authenticator app or a Yubikey for the various places where we require two-factor authentication. To recap, those places are:
1. To login to the _Document Interface_ (both journalists and admins)
2. To SSH to either the App or Monitor server (just admins)

Actually, we only support Yubikey for the first use case. It is possible to use Yubikey for the second use case (see https://github.com/Yubico/yubico-pam), but if so we need to document and test that. From a quick skim of the yubico-pam docs, it appears to be a fiddly manual process (not as easy as running `google-authenticator`).

**Comment by flamsmark** [comment]
It seems as though any 2FA option for the SSH process creates trouble for Ansible. Given the amount of physical separation associated with a SecureDrop deployment, a Yubikey doesn't represent a material inconvenience. I strongly suspect that the `yubico-pam` process can be automated without a lot of worry, given the similarity between SecureDrop instances. I would prefer to use Yubikeys throughout, though that doesn't solve the Ansible problem.

**Comment by redshiftzero** [comment]
To recap the current state of this issue: we already have pretty good documentation for using Google Authenticator for [SSHing into the servers](https://docs.securedrop.org/en/latest/google_authenticator.html) and [logging into the journalist interface](https://docs.securedrop.org/en/latest/admin.html#google-authenticator) and for setting up and using [Yubikeys for logging into the journalist interface](https://docs.securedrop.org/en/latest/admin.html#yubikey), so I think all use cases except using Yubikeys for SSH 2FA are covered pretty well. 

So at this point, this issue is for figuring out and documenting for how to use Yubikeys for 2FA for SSH. While this would be a nice feature, it might be a bit out of scope for the upcoming 0.4 release, so I think we should push this off the 0.4 milestone. Any disagreement?

**Comment by justintroutman** [comment]
As to more thoroughly test this, I'm in favor of pushing it off the 0.4 milestone. It's something I can start revisiting, to get some context on what the process might look like now.

**Comment by conorsch** [comment]
We've greatly improved the Yubikey documentation for use with the Journalist Interface since this issue was opened (see #2186, #2310, and #2311). As for using a Yubikey for SSH authentication, unfortunately our use of Ansible prohibits use of challenge-response authentication for the SSH daemon—see details in https://github.com/freedomofpress/securedrop/issues/1283#issuecomment-218895743. 

Closing this issue since we will not be implementing further 2FA for SSH for the reasons outlined in #1283.
