### ISSUE TITLE
Consider whether the SVS Tails USB should have persistence

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#827]
In install.md, it says:

> To set up the Secure Viewing Station, start by creating a Tails Live USB with persistence on the offline USB stick.

The Tails Live USB has persistence to make it more convenient to store the Application GPG key. With persistence, you generate the key on the SVS and it is automatically saved and persisted on the persistent volume. Future use of the SVS has the keypair automatically available if persistence is enabled when booting Tails.

However, this also creates a vector for persistent malware. Given the risk, I think we need to trade off usability to eliminate this vector. There are two ways to do this:

1. The SVS boots from Tails *without* persistence. Once the key is generated, the public key is exported to one USB drive to both copied to the Admin Workstation for the installation. The public *and private* keys are copied to a second (ideally encrypted, or else the private key needs to be encrypted) USB, called "key storage". This USB must be mounted, decrypted, and the GPG keys imported into each (ephemeral) Tails session.
2. Use the current system, but require the persistent volume be mounted "Read-only" after the initial boot where the key is set up. This is significantly easier to use than the first option, but requires that people remember to tick the "read-only" box every time they boot the SVS Tails.

**Comment by garrettr** [comment]
Discussed this with @dolanjs.

Note that option 1 must have a strict protocol for loading the keys for each session:

1. Boot Tails on the SVS (ephemeral session)
2. Plug in the **key storage**, double-click to import the keys into the Tails session. This is supported by Tails' memory-backed amnesiac filesystem, and will not be persisted across reboots.
3. **Eject** the key storage device, so it cannot become a vector for persistent malware.
4. Plug in the **transfer device**, which we assume may be compromised or contain submissions that could be malware (persistent malware on the transfer device is a separate problem).

**Comment by dolanjs** [comment]
I think that option #2 (selecting Read-Only) when booting the SVS is something we should recommend.

**Comment by flamsmark** [comment]
I don't think that changing this represents a good tradeoff.

Dealing with different read-only filesystems and so on is a lot of work and effort for the journalist using the SVS. It only protects against someone who (1) has an exploit for an unpatched vulnerability in some client software you're running, but (2) does not have an exploit for an unpatched vulnerability in the kernel. This is big commitment to defend against a narrow band of attackers.

I think that if you're worried about (1), you shouldn't assume (2). Assume that someone who can exploit your software can exploit your kernel use physically read-only media: DVDs for the SVS Tails, the DTD, and to store the key. Or maybe read-only USB thumb drives, if such things actually work.

**Comment by fowlslegs** [comment]
> Or maybe read-only USB thumb drives, if such things actually work.

There are affordable USBs sold with “hardware” write-protect switches (someone maintains a slightly out-of-date list [here](http://www.fencepost.net/2010/03/usb-flash-drives-with-hardware-write-protection/)).  While the switch is in fact physical, it is up to the firmware to observe the position of the switch and correctly implement write-protection. If the firmware implementation is sane and you turn on write-protection before inserting the USB, it *should* work as expected.

The good thing about USBs in this context is that, unlike SD cards, the write controllers in USBs are internal. Thus, a compromised OS cannot simply ignore the position of the physical switch. If the firmware can be overwritten, however, as in BadUSB attacks, we cannot rely on the write-protect switch helping us.

There are vendors who, in accordance with certain FIPS guidelines (e.g., FIPS 140-2 Level 2+), only allow digitally signed firmware to run on their devices. This throws quite a wrench into an already advanced attack. And, with binary blobs as much free software packages, we must trust that the private keys that signed them have not been compromised. (Of course reproducible builds coupled with an active community can strongly mitigate this attack vector, but that is of course not a possibility in this case.)

While dedicated USB write-blockers, as used by forensic data analysts, seem to start near $200. There are free software implementations such as [UDeck](https://github.com/ppolstra/UDeck) that run on hardware such as the BeagleBone black, which sells for a more modest $45. However, even assuming the code in such an implementation is reasonably correct and the admin has the experience to correctl set it up, configuring such a setup presents significantly more work (implying more room for error) than using a write-protected USB. Additionally, it adds a whole new attack surface. I imagine that some write-blockers (more likely higher-end commercial devices) have implemented signature checking, which should of course be preferred.

With this in mind, I propose another option, most similar to your option (2):

(3) With write-protection/blocking disabled, first create a persistent Tails USB and generate a GPG keypair. In the tails-persistence-setup menu, only the "GPG, SSH, and OTR key pairs" option should be checked. Poweroff, then enable write-protection/blocking *permanently*. Preferably, your write-protect/block device implements signature checking. It might be wise to select mount ro in Tails--more so to avoid possible errors than for security reasons.

Over option (2) option (3) has two advantages. First, a kernel exploit cannot directly grant the ability to plant persistent malware. Second, the write-protection simply needs to be enabled once—the journalist cannot simply forget to check the ro box.

Another device that could help solve this issue is a OpenPGP-compatible smartcard. The use of such a card would almost guarantee that the private key was never compromised and provides an alternative to option (1). There are now free hardware and software models, such as the [Nitrokey series](https://shop.nitrokey.com/shop) (the starting model goes for 35€).  Further, the default Tails install has supported OpenPGP smartcards since version 0.17. This presents a fourth possible solution:

(4) Run Tails w/o persistence on the SVS and store the GPG keys on an OpenPGP-compatible smartcard.

While this would provide serious protection against private key exfiltration, it would not protect against an attacker with a kernel exploit, as @flamsmark mentioned.

Lastly, we could combine solutions (3) and (4) to create the strongest defense against persistent malware:

(5) Run Tails w/o persistence from a write-protected/blocked USB (or from a DVD-R or CD-R that has been finalized) on the SVS and store the the private keys on a private server. If a USB or USB write-blocker instead of a disk is used, it is preferred it checks firmware signatures.

If one were to buy the Kanguru FlashTrust and the Nitrokey Starter, they would be able to easily implement option 5 (with firmware signature checking) for $70—a reasonable price for most journalist organizations.

Employing (5), the SVS would certainly still be susceptible to persistent malware, but it would require a kernel exploit or physical presence. Attacks like BIOS rootkits are increasingly difficult to execute with newer BIOSs. Unfortunately, the SVS may be running a BIOS with known vulnerabilities, but at this point we’re likely looking at a 3-step attack involving a client software exploit → kernel exploit → BIOS signed-code-enforcement exploit.

**Comment by conorsch** [comment]
I'm with @flamsmark on this one. Making _recommendations_ about booting into the SVS read-only is not only impossible to enforce, but is tedious and error-prone. If a journalist forgets just one time out of a hundred to check the box, is the recommendation worthwhile? 

The hardware USB lockers that @fowlslegs mentions are interesting, but would complicate the architecture for questionable benefit. 

> Another device that could help solve this issue is a OpenPGP-compatible smartcard. 

That's the most workable suggestion in my mind, but it would mean that three (3!) USB sticks and an airgapped machine would be required to access a submission on the SVS. Having jumped through the hoops required to configure a GPG smartcard on an airgapped Tails workstation before, I do not look kindly upon the prospect of recommending that setup even to Admins, let alone Journalists.

I vote for closing this issue, and sticking with the current recommendation of enabling persistence for the SVS.

**Comment by garrettr** [comment]
Agree with @conorsch. Additionally, if we radically rework the journalist workflow in the manner that we've been discussing internally, then fine-tuning the Tails-based airgap workflow is a waste of time because it will be replaced entirely.
