### ISSUE TITLE
install grsec package from fpf repo failed

### ISSUE THREAD

**Issue by FredRa** [freedomofpress/securedrop#873]
Hi, 
according the installation guide, following message appears after starting the ansible-playbook command:

msg: 'apt-get install 'securedrop-grsec'' failed: E: There are problems and -y was used without --force-yes

The installation also fails when trying to install the securedrop-grsec package manually on the server, also with importing the repository keys.

Is this a bug or is there something missing in the documentation?
Thank you!

**Comment by runasand** [comment]
I am not able to reproduce this error. Did you clone the SecureDrop repository and check out the 0.3 tag?

**Comment by dolanjs** [comment]
@FredRa the grsec package it pretty large are you trying to install this over a spotty internet connection? Other issues could be a slow VPS due to the hosts processor/ram that causing the securedrop-grsec package to timeout while downloading. 

The securedrop-grsec deb package is just a meta package that lists the current version of the grsec patched kernel as a dependency. So it is more likely that it the `linux-image-3.14.32-grsec` package that is timing out.

**Comment by dolanjs** [comment]
@FredRa also @ageis had an issue similar to this in issue #760 and provided a couple of suggestions for dealing with it. Not sure of your exact setup or if it the same issue he experienced.

**Comment by FredRa** [comment]
Thank you so much for your response. To be honest i have no idea where the issue came from, now i reinstalled all the usb sticks and did the same procedure as before (at least i think so ;-) ).
Anyway, everything is working fine now, thanks again for your support!
