### ISSUE TITLE
OSSEC email contains IP address of App Server in subject line

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#874]
The subject line of an email about the app server differs from the subject line of an email about the mon server. An email about the mon server will have a subject line similar to "OSSEC notification - mon - Alert level 3," while an email about the app server will have a subject line similar to "OSSC notification - (app) 192.168.1.51 - Alert level 2."

**Comment by dolanjs** [comment]
@runasand this is OSSEC setting all remote agents get their IP address attached to the alerts. The monitor server doesn't get it because it the OSSEC server not an remote agent.

This is not configurable in OSSEC, but on the monitor server we could modify `/var/ossec/send_encrypted_alarms.sh` script `securedrop/install_files/ansible-base/roles/ossec_server/templates/send_encrypted_alarm.sh` $SUBJECT part to change the subject line of all alerts. But this will apply to more than just OSSEC email alerts. The SecureDrop procmail config will forward any email send to to `root@localhost` to the designated admin email address. So any non OSSEC alerts sent to `root@localhost` will also be modified.

Also since we recommend the internal IP addresses for the orgs in our public github/install directions to use that IP address is pretty well known.

**Comment by garrettr** [comment]
Since this is in the (unencrypted) subject line of an email, it seems like an information leak. However, since this is just an internal IP address (and is likely to be the publicly recommended default) there isn't much value in it for an adversary.

**Comment by garrettr** [comment]
@dolanjs Seems like modifying the "$SUBJECT" in `send_encrypted_alarms.sh` would be a little tricky (remove anything that matches the regex for an IP address?) and definitely has potential to cause collateral damage.

**Comment by dolanjs** [comment]
@garrettr was actually thinking of replacing the `$SUBJECT` with just a static string like `"SD Alert"`.

Currently $SUBJECT contains:
* Hostname
* IP address if it is a remote host (not the monitor server)
* Alert level or Report name

The hostname, alert level is included in the bodies of the email.

The two reports; OS authentication (excluding the source interface), and file integrity are sent at the same time everyday which should make it identifiable to the admin at quick glance. The alerts are gpg encrypted to the admin personnel gpg key. This typical means that the admin will just check all of the backlogged alerts once a business day. So don't think not having a detailed email subject line would decrease the usability for the admin

**Comment by garrettr** [comment]
This was resolved by #915.
