### ISSUE TITLE
Restart submission counter after deleting submissions

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#877]
The first time the source "positive toast" sends a message, the submission is given the filename "1-positive_toast-msg.gpg" in the Document Interface. The second time the source sends a message, the submission is given the filename "2-positive_toast-msg.gpg," the third time "3-positive_toast-msg.gpg," and so on. 

If a journalist decided to delete the three submissions, but keep the source in the system, the Document Interface would simply say that there are no documents to display. If "positive toast" sent a new message at this point, the submission would be given the name "4-positive_toast-msg.gpg."

The filename makes it clear that "positive toast" and the journalist have communicated before. I realize the number is a way to help journalists keep track of the submissions when using the Secure Viewing Station, but it seems a bit unfortunate that it also leaks whether a source has communicated with a journalist - and how much. 

I think it would be fine to keep it this way as long as the submissions exist in the system, but perhaps restart the counter when submissions are deleted? That could cause some issues with submissions being overwritten on the Transfer Device or Secure Viewing Station, however.

**Comment by ThomasWaldmann** [comment]
if you want to avoid the "has communicated before" information (like: a year before, in another case maybe), it is likely much better to not keep the source in the system, but letting the source start from scratch with a new identifier. also, the numbering will start from 0 again in that case.

If a case is ongoing, I think having incrementing numbers (and not creating filename conflicts by resetting to 0) should be the way to go, otherwise things might go wrong when handling the conflicting filenames (like overwriting files, like confusing files, like referring to the wrong file, ...).

**Comment by garrettr** [comment]
> That could cause some issues with submissions being overwritten on the Transfer Device or Secure Viewing Station, however.

@runasand Yeah, that's exactly why we always increment the "interaction count". People often keep downloaded submissions in cold storage and delete them from the server, and resetting the counter would cause new submissions' names to overlap with those of old submissions, which could lead to confusion/accidental overwriting of important files.

**Comment by garrettr** [comment]
Given the risk of accidental damage and confusion, I am closing this issue.

Some of the ideas that we have been discussing for the "ultimate viewing station" could potentially resolve this issue, and it is good to keep this in mind for those design discussions.
