### ISSUE TITLE
SESSION_COOKIE_SECURE = True?

### ISSUE THREAD

**Issue by ThomasWaldmann** [freedomofpress/securedrop#887]
Not sure if it is needed, but maybe it wouldn't harm either to have this for production mode.

The setting makes sure the cookie is only transmitted over https and never over http.
Of course this makes only sense IF you use https.

**Comment by dolanjs** [comment]
It wasn't possible to get SSL certs for onion addresses until recently so it wasn't something that was implemented for SD installs previously. We should add a SSL for the Tor hidden services option for the orgs that want it in the ansible playbook. But right now it would require manual changes.

**Comment by garrettr** [comment]
> maybe it wouldn't harm either to have this for production mode

I haven't tested this, but I think it actually *would* harm. The reason is that SecureDrops are always a Tor Hidden Service (so the transport is end-to-end encrypted), but the browser (Firefox/Tor Browser) does not know that and just sees an "insecure" scheme, `http://`. As a result, it would be logical that setting `SESSION_SECURE_COOKIE` would tell the browser not to send cookies (since, from the brower's perspective, it is not a secure scheme). This would break SecureDrop in the standard use case.

If we optionally support SSL certificates for hidden services in the future, it would make sense to set this flag for those (and only those) SecureDrop instances that use the feature. Until then, it does not add anything and would probably break the sites in production.

**Comment by garrettr** [comment]
I am going to close this issue for now since it depends on the future (and even in that case, optional) support for HTTPS hidden services. I have created a [Trello card](https://trello.com/c/JBb8MdCz/6-optionally-support-the-use-of-https-for-securedrop-hidden-services) to capture this discussion. It is on the "Proposed" list for 0.4, so we can reconsider it at a later date.

**Comment by fowlslegs** [comment]
@micahflee The Intercept could actually use this now. Doesn't seem like a super crucial protection, but it shouldn't break anything (hypothetically).
