### ISSUE TITLE
usage of undocumented / internal python stdlib class _TemporaryFileWrapper 

### ISSUE THREAD

**Issue by ThomasWaldmann** [freedomofpress/securedrop#888]
... by secure_tempfile module.

There is no docs about why it is not simply using NamedTemporaryFile or TemporaryFile.

It looks like the computed random filename has better randomness as it is using 32 bytes from os.urandom().

OTOH, it could be checked whether a filename is needed at all or maybe a nameless file created by TemporaryFile is maybe not even better. Or whether the less great randomness of the stdlib generated filename is not also good enough for the purpose.

**Comment by garrettr** [comment]
There are several things that could potentially be improved here.

## Use of _TemporaryFileWrapper

The motivation for using this class is to get the "auto delete on close" behavior. We are injecting this into Flask (see `request_that_secures_file_uploads.py`), so we don't have an opportunity to do explicit cleanup and instead must rely on close eventually being called. It would not be hard to implement this ourselves, but there is some subtlety and corner cases that need handling, so why not re-use the existing implementation in _TemporaryFileWrapper?

I guess the alternative would be:

1. Don't inherit from `_TemporaryFileWrapper`
2. In `__init__`, `self.file = tempfile.NamedTemporaryFile(...)`
3. When `SecureTemporaryFile` is GC'ed, `self.file` will be GC'ed, and `.close` will be called automatically (right?)

The last step would need to be verified. I am not sure whether Flask calls `.close` on the `_secure_file_stream` explicitly or if it is implicit from the GC.

## Filenames

I think the 32 bytes of randomness for the filename is actually overkill, and the filenames generated by `tempfile._mkstemp_inner` would work just as well. The only thing you want to avoid is accidentally overwriting other files, or running out of possible filenames under normal use. I didn't write code to make sure `tmp_file_id` is unique before using, and just assume that the probability of a random 32-byte collision is small enough that it would not be a concern. The approach taken in tempfile is to use a much shorter filename with less entropy, but it loops over the filenames and [makes sure it has a unique name](https://hg.python.org/cpython/file/2.7/Lib/tempfile.py#l243) before continuing.

In retrospect, I prefer the approach taken by tempfile and think it would be good to change `SecureTemporaryFile` to do that instead.

## Do we need a name at all?

Good question. Originally we did because we wanted to use `shred` to securely delete the file, and we needed a filename to pass to it (in that incarnation, we did *not* use the "auto delete on close" behavior). However, now that the file is encrypted with an ephemeral key, `shred` is less important (and of dubious utility on modern drives anyway).

I did like having a filename when I was debugging this - it made it easy to `watch ls -lht /tmp` to visualize how everything was being streamed into the encrypted temporary file.

So in general, it seems at this point that we don't even need a filename anymore.

**Comment by eloquence** [comment]
See the above explanation and internal code docs that have since been added; we see no reason at present to move away from this implementation (we are in fact using `shred` to securely delete files on disk).
