### ISSUE TITLE
potential timing attacks on Journalist.login and user.valid_password?

### ISSUE THREAD

**Issue by ThomasWaldmann** [freedomofpress/securedrop#889]
it first checks for the user being valid (existing), raises exception if not.
then verifies token, raises exception if not.
then verifies password, raises exception if not.

an attacker can see the timing (maybe even the kind of exception / error msg) and make educated guesses about what was wrong.

user.valid_password does not use a constant time string comparison internally. see pyotp.utils.strings_equal for a better way.

**Comment by ageis** [comment]
Interesting, would just note that the attacker would have to compromise the journalits's Tor HidServAuth value first to try this.

**Comment by garrettr** [comment]
@ageis is right. In addition:

Theoretically, an attacker could use timing attacks based on the current structure of `Journalist.login` to learn the following (in order):

1. Username
2. Token
3. Password

I do not think learning the username is very useful for an adversary, and mitigating that is probably not worth the complexity. Note that we intentionally check the two-factor token *before* the password - this is to prevent password brute force attempts for attackers who don't have the two-factor token.

I think the throttling (implemented in `verify_token` and `throttle_login`) makes it very difficult to exploit anything like this. The TOTP token comparison is constant time, and even if it wasn't you're only allowed to make up to 5 login attempts / minute so you don't get a lot of guesses for the 6-digit value.

Finally, I don't think `valid_password` using a non-constant time string comparison matters because it is comparing the hashed passphrases. Unless you have a preimage attack on the hash function (scrypt), I can't see how this would help you guess the passphrase.

So, at the moment I don't think any of the valid issues raised lead to exploitable security bugs. Please let me know if you think I have overlooked anything!

**Comment by fowlslegs** [comment]
All the points Garrett makes are good. I'd just like to reinforce one point. For a cryptographically secure hash function, the [avalanche effect](https://en.wikipedia.org/wiki/Avalanche_effect) will be very strong. Therefore, the scrypt hash of `passworc` is going to be totally different from that of `password`, and the way in which it differs will be unpredictable for _any_ PPT adversary. Therefore, even if we didn't have all these other mitigations to even trying out an admin/journalist password, it makes a negligible (in the cryptographic sense) difference whether we use a constant-time string comparison function here or not.
