### ISSUE TITLE
Servers don't boot into grsec kernel automatically as GRUB default

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#913]
This is a critical issue I found yesterday with the latest Ubuntu Server, and reproduced it again today.

Steps to reproduce:
* Install Ubuntu Server 14.04.2
* Install SecureDrop / run Ansible playbooks
* TASK: install grsec package from fpf repo
* TASK: setup cron-apt, perform safe upgrade of all packages
* TASK: reboot, server comes back

End result: Server boots generic kernel, subsequent playbook runs fail on the sysctl task with `cannot stat /proc/sys/kernel/grsecurity/*`. SecureDrop installation fails, only way to finish the install is to manually reboot and select the grsec kernel from the boot loader and run the playbook again, which still doesn't fix the default kernel selection so it would have to be selected on every boot.

I believe what's happening is that the new kernel installed during the safe upgrade task, right after the grsec kernel is installed, (`linux-image-3.16.0-31-generic`) is taking precedence over grsec in the boot loader. We need to fix this by making sure the grsec kernel (`linux-image-3.14.32-grsec`) is the GRUB default and first option.

**Comment by garrettr** [comment]
I think your hunch is probably right. We've never seen this issue before, but until [recently](http://www.omgubuntu.co.uk/2015/02/ubuntu-14-04-2-lts-released-includes-3-16-kernel) Ubuntu 14 used the 3.13 kernel, while we used 3.14.x kernels with grsecurity. The recent move to 3.16 by default may indeed be causing this issue.

My understanding was that setting the default kernel was handled by the `linux-image` deb package, but either that was a misunderstanding or there is something wrong with that package.

**Comment by dolanjs** [comment]
@garrett so grub handles which kernel gets booted. Since the kernels listed in the securedrop-grsec meta package where a higher version than the ones in linux-generic-lts-trusty meta-package wasn't an issue before. @ageis we do not want to define the specific kernel in the grub config. What we should do is uninstall the linux-generic--lts-trusty metapackage after installing the grsec package so it isn't an issue going forward and also save disks space in /boot

**Comment by ageis** [comment]
yep, exactly. This was probably introduced with 14.04.2 and the 3.16 kernel. as far as update-grub is concerned 3.14.32-grsec is treated as older than 3.16.0-31-generic. 

@dolanjs that sounds like an appropriate way to resolve. wouldn't that leave the system as grsec only with no other kernel for debugging?

**Comment by dolanjs** [comment]
Well autoremove wont remove the last two kernels and certain situations 3
```
 cat /etc/kernel/postinst.d/apt-auto-removal 
#!/bin/sh
set -e

# Author: Steve Langasek <steve.langasek@canonical.com>
#
# Mark as not-for-autoremoval those kernel packages that are:
#  - the currently booted version
#  - the kernel version we've been called for
#  - the latest kernel version (determined using rules copied from the grub
#    package for deciding which kernel to boot)
#  - the second-latest kernel version, if the booted kernel version is
#    already the latest and this script is called for that same version,
#    to ensure a fallback remains available in the event the newly-installed
#    kernel at this ABI fails to boot
# In the common case, this results in exactly two kernels saved, but it can
# result in three kernels being saved.  It's better to err on the side of
# saving too many kernels than saving too few.
#
# We generate this list and save it to /etc/apt/apt.conf.d instead of marking
# packages in the database because this runs from a postinst script, and apt
# will overwrite the db when it exits.
```

**Comment by garrettr** [comment]
It's good that autoremove has this special logic to deal with the potential case where a new kernel update results in a system that cannot boot, and so naturally provides for a fallback. I wasn't aware of this, and thought we would have to implement this log ourselves in the postinst of the `securedrop-grsec` metapackage in a release or two. That means we can easily modify our cron-apt configuration to use `apt-get autoremove` to keep the `/boot` partition from overflowing. I've filed #914 for us to work on this.

However, I do not think autoremove will actually solve **this** issue. Since autoremove leaves at least the previous kernel behind, `apt-get remove linux-generic--lts-trusty` as @dolanjs [suggested](https://github.com/freedomofpress/securedrop/issues/913#issuecomment-82608862) will probably still leave the non-grsec kernel (with the higher version number) installed, which means it will still appear first in the GRUB menu, which means grub will still pick it by default.

This is worth testing. In the meantime, I am afraid we may have to muck with `GRUB_DEFAULT` after all (something we've been hoping to avoid since it is hard to get right and maintain across kernel updates).

**Comment by garrettr** [comment]
An idea that might work:

1. Installation starts with a 3.13.x kernel from the .iso.
2. Set up the FPF repo, apt-get update
3. Install the FPF packages, including the grsecurity kernel.
4. Reboot. Since the grsecurity kernel is 3.14.x, it will automatically take precedence over the 3.13.x generic kernel and will be chosen for boot.
5. apt-get remove the generic kernel package after reboot
6. apt-get update && upgrade to bring all packages up to date. Since we removed the generic kernel package, it will not install 3.16.x, which would override the grsec kernel.

This works well because we make sure we can reboot into the grsec kernel before removing the default kernel. That way, if the grsec kernel is incompatible for some reason, the Ansible playbook will fail before removing the generic kernel. We will be able to reboot the machines using the generic kernel, then re-run the playbooks, skipping the grsec tag so we can set up SecureDrop without grsec.

For this idea to work, the installation *must* use the [Ubuntu 14.04.1 .iso](http://releases.ubuntu.com/14.04/ubuntu-14.04.1-server-amd64.iso). It *cannot* use the latest [Ubuntu 14.04.2 .iso](http://releases.ubuntu.com/14.04/ubuntu-14.04.2-server-amd64.iso), available on the [same page](http://releases.ubuntu.com/14.04/), since it comes with the 3.16.x kernel on the .iso.

**Comment by dolanjs** [comment]
agree that this is another temp solution but can see telling people to ensure that they used the ubuntu 14.04.1 iso instead of the current will cause us a lot of issues.

**Comment by garrettr** [comment]
@dolanjs Yeah, I agree that part is not ideal. The only other solution that I can think of is to modify GRUB_DEFAULT (described in my prior comment). Which solution do you prefer (or is there another that you can think of?)

**Comment by dolanjs** [comment]
well, since we are using grub2, if we edit the grub.cfg directly the first time that grsec is installed via ansible (and before the server reboots), it will be overwritten the next time `update-grub` is ran. As long as we don't modify the grug.d/* config files.

**Comment by ageis** [comment]
Here's our current thinking/proposal on this:

1. introduce logic to the grsec Deb package (or metapackage) postinst (we want the latest grsec to be set default every time, so Ansible is not the right place for this)
2. fetch the most recent grsec kernel string from `/boot/grub/grub.cfg` - IT HAS TO BE THERE FIRST! so update-grub has to run at least once beforehand, gotta figure out when in the dpkg install process that happens.
3. sed replace that string to set `GRUB_DEFAULT` in `/etc/default/grub`
4. run update-grub again, now grsec is the default kernel
5. reboot

Hypothetically, we don't even have to remove the old kernels with the playbooks if we don't want to. Because `/etc/default/grub` should almost never be overwritten, GRUB will set grsec to the default every time `update-grub` is run. That should take care of it.

In any event the generic kernel metapackage name varies depending on your starting point: 14.04.1 vs. fully updated vs. Vagrant cloud image (Ubuntu Server installs a kernel with the name utopic which is actually from 14.10).

Right now I am getting a build environment set up for grsec so I can code the postinst hook and test it with a self-signed package. This plan seems to make sense and I think is more ideal than requiring an old ISO (though we have that ready as a fallback). There are a few question marks that we'll figure out in the process, but hopefully I can bang this out!

**Comment by garrettr** [comment]
Confirmed that this also works on staging!

1. Boots into grsec kernel
2. Only grsec kernel is in `/boot`

:+1:
