### ISSUE TITLE
Graphical installation assistant

### ISSUE THREAD

**Issue by ageis** [freedomofpress/securedrop#924]
We have raised the possibility of offering a graphical installation wizard/frontend in a future version of SecureDrop. This program (written in a language and UI toolkit to be determined) would help the admin fill out `prod-specific.yml`, select keys and fingerprints, and also validate all of the inputs before running Ansible.

I'm highly interested in working on this since it's within reach of my average programming skills.

**Comment by conorsch** [comment]
Certainly some form of setup utility beyond `ansible-playbook` would be useful to admins, but I'm not convinced that a graphical client for the setup wizard is worth the effort right now. Once we have the Ansible config tightened up a bit, it'll be easy to smooth over some rocky workflows, such as:

* admin must manually substitute .onion urls for local ips in inventory file (dynamic inventory would solve this)
* admin must manually configure all firewall rules (providing a template with aliases may speed this along, and prevent typos)

Surely there are many more, feel free to document them here.

**Comment by conorsch** [comment]
First-time installation is greatly improved since the addition of the `securedrop-admin` helper script (#1781 and #1803). 

> admin must manually substitute .onion urls for local ips in inventory file (dynamic inventory would solve this)

We now have dynamic inventory support as of #1774.

> I'm not convinced that a graphical client for the setup wizard is worth the effort right now.

Two years later and I stand by that statement. The Admin experience is improving, and I view it as a higher priority to minimize mistakes through competent scripting, and dedicate GUI improvements to the Journalist workflow, rather than the Admin workflow.
