### ISSUE TITLE
ansible notify task to reload tor

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#940]
The ansible tasks that reloads tor if the torrc file changes will break the playbook run for existing installs if the torrc file changed (for instance when we changed the default ATHS port for the document interface from 8080 to 80). Ansible will reload tor and try to move on to next task before giving it time to reload.

The reload task should be set as fire and forget and another task added to poll for when it is done.

**Comment by conorsch** [comment]
We changed the ports on these interfaces during the 0.3 upgrade, but aren't planning to do so in 0.4. We may, however, update the name of the Document Interface to Journalist Interface, which would necessitate a similar strategy to ensure stable connections. See #1614 for discussion there.

Leaving this on the 0.4 milestone until #1614 is resolved.

**Comment by conorsch** [comment]
Not as straightforward as it may seem, unfortunately. While it's rather simple to bounce the tor service in an asynchronous manner (using `shell` rather than `service` due to problems with [certain versions of Ansible](https://github.com/ansible/ansible/issues/18965)), we cannot use `local_action` with `wait_for` to poll for the SSH port opening back up, since wait_for is not smart enough to read the custom connection info that specifies the Onion URL for the SSH hostname. Therefore we'll more simply just wait for an entire interval, e.g. 90 seconds, if the playbook is being run against an Onion URL.
