### ISSUE TITLE
torify vs no-torify for admin running ansible-playbook

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#941]
On tails when you run the ansible playbook without pre-pending it with `torify` It prompts for the `SOCKS5 password for amnesia@localhost` (which is blank). Depending on how long the playbook takes to run it can prompt for that multiple times. If an admin is not paying attention to hit enter when prompted then the playbook will fail.
We should consider changing the directions to tell admin to prepend the `ansible-playbook` command with torify to avoid this.

**Comment by conorsch** [comment]
Can anyone reproduce this? I've never run into this problem. As long as Tails has announced that `Tor is ready`, using `ansible-playbook` without prepending `torify` works just fine for me. None of our docs recommend prepending `torify` to Ansible commands run from the Admin Workstation, so I'm assuming it's not an issue for admins of production instances, either.

**Comment by conorsch** [comment]
Haven't been able to reproduce this issue. Since the original issue was opened, Tails v2 was released, and the SecureDrop Tails Tor configuration was updated in 0.3.7 to accommodate ([docs](https://docs.securedrop.org/en/stable/upgrade/0.3.6-to-0.3.7.html)). 

To be clear, Admins do not need to prepend ansible commands with `torify` when connecting to the servers' .onion addresses, since Tails automatically routes the traffic over Tor. The Admin Workstation setup scripts will handle installing the HidServAuth values for the SSH ATHS URLs ([docs](https://docs.securedrop.org/en/stable/configure_admin_workstation_post_install.html)).
