### ISSUE TITLE
Time out for secure-delete of backups

### ISSUE THREAD

**Issue by dolanjs** [freedomofpress/securedrop#942]
The ansible tasks to secure-delete the encrypted backup off the app server is set with a timeout of 300 seconds. For existing installs who have either a lot of sources or large submission this may not be enough. We should consider extending the timeout to a larger value. As Garrett mentioned we could also move this to the last task after the final reboot and make it just a fire and forget task.

**Comment by garrettr** [comment]
Another idea that might make more sense would be to have two different types of backups:

1. Backup of essential configuration.
2. Backup of server state (`/var/lib/securedrop` directory).

Type 1 is simple and can be done as part of the ansible playbook, as it is now. Type 2 does not work well when run as part of the Ansible playbook once the amount of state stored on the server grows past a certain size - copying the backup is extremely time-consuming (over Tor), liable to be interrupted due to circuit flakiness (due to Tor), and the secure-remove step can take too long given the Ansible timeout (which is the top comment for this issue).

This basically reiterates the conversation we've already had in #606. For 0.4, I propose we:

1. Only backup essential configuration as part of the Ansible playbook (this has a small, fixed size, and is not problematic in the context of timeouts.
2. Figure out some solution for periodic backups of server state (type 2 backups).

**Comment by conorsch** [comment]
I'm in favor of splitting up the backup role into two types. Making the secure delete process fire-and-forget is also a good compromise—simply incrementing the timeout counter is essentially kicking the can down the road. Any objections?

**Comment by conorsch** [comment]
#1273 removed the use of secure-delete (via `srm`), so the concerns listed here are no longer relevant. Closing.
