### ISSUE TITLE
Server Certificate not verified

### ISSUE THREAD

**Issue by SteveNor** [freedomofpress/securedrop#957]
Hi there,

i got a strange issue with my securedrop installation.
Everything was working fine, but out of the blue OSSEC stopped sending mails to my gmail account.
The mail log gives me following information:
- Server certificate not verified
- Network unreachable

Iam able to connect to my app / monitor server through TOR / SSH without any problems, and my setup was running fine all the time.

Can you please give me a hint whats going on?

Thank you,
greetings,
Steve

**Comment by dolanjs** [comment]
The Postfix config verifies the SMTP relay's cert fingerprint. Google rotated their certs I think around the 23rd. So if you are using them like the examples provided then in your prod-specific.yml (or if it a dev environment then the staging-specific.yml config) you will need to update the fingerprint and re-run the playbook to update the value verified.

Our documentation in develop was updated with the current fingerprint or can run the openssl_client command to retrieve the value.

https://github.com/freedomofpress/securedrop/blob/develop/docs/ossec_alerts.md

We also have github issues open to improve this detection when the verified alerts are not sent. It is a bit of a chicken and egg issue. #858

**Comment by SteveNor** [comment]
Thanks for your fast response!!!
So, do i really have to run the playbook again, or is it enough to change the fingerpringt within the main.cf of postfix and restart the process? (because iam afraid when i rerun the whole playbook process the installation will override settings like access data / tor onions, and i also have to open my the ports on the firewall again)

**Comment by dolanjs** [comment]
Re-running the playbook will not overwrite the onion, securedrop config file or other instance specific files. The only time re-running the playbook becomes and issue is if

* you locally modified files on the app/monitor server, since those could be overwritten. 
* you change the client name for the ssh ATHS connections manually in the ansible playbook, the standard is just admin. (since this will re-generate the ATHS values for ssh and lock you out).

Technically in this scenario (just changing the fingerprint) if you update the value in main.cf and also update the value in the ansible config you will be fine. Just in case you do run the playbook again for some other reason you wont overwrite your locally modified version. But that fingerprint is only used in the main.cf so there should be no other places on the server you would need to update it.

**Comment by SteveNor** [comment]
Thank you so much for your support and the background information dolanjs.
I changed the fingerprint, restarted postfix and voila, receiving messages again!
Can only hope that Google wont change their SMTP relay cert anytime soon ;-)

Thanks again!
Greetings
Steve

**Comment by dolanjs** [comment]
@SteveNor no worries and any time. Unfortunately believe that google *will* be rotating their keys more often. Between issues #858 and #950 we are going to be looking at some type of more permanent fix. 

The OSSEC setup will at a min send two reports a day. If you don't receive those then something is wrong.

**Comment by garrettr** [comment]
@SteveNor Additionally, I highly recommend updating the value for `smtp_relay_fingerprint` in your `install_files/ansible-base/prod-specific.yml`. While you just fixed the issue manually, if you ever re-run the playbook in the future without updating this value, the new value you manually changed will be replaced with the old value by Ansible and your OSSEC alerts will break again.

We anticipate that some future upgrades will require re-running the playbook, and will also be working to provide fixes for issues like this via custom playbook roles (to minimize the amount of error-prone manual maintenance on the part of each admin).

**Comment by garrettr** [comment]
This issue was resolved by explaining the situation and supplying the updated fingerprint. We should track progress towards [improving this situation in general](https://github.com/freedomofpress/securedrop/issues/957#issuecomment-87032084) in separate, dedicated issues.
