### ISSUE TITLE
Optionally generate vanity .onion during installation

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#971]
Organizations often ask us about generating a "vanity" .onion with a prefix that corresponds to the name of their organization. Some [current installations](https://freedom.press/securedrop/directory) already have vanity addresses. We have been generating, integrating, and storing these in an ad hoc way. It would not be hard to add an optional tag to Ansible to generate a vanity .onion with some prefix specified in `prod-specific.yml`.

Vanity addresses can be generated with [shallot](https://github.com/katmagic/Shallot), [scallion](https://github.com/lachesis/scallion), or eschalot. We will have to consider some tradeoffs to choose the right one. scallion is faster, but requires some weird dependencies (Mono, OpenCL) to run, and it might not be much faster if you don't have a beefy GPU for it to use. shallot is just C code so easy to build, but is slower and unmaintained. It appears it might require manual patching to work around https://github.com/katmagic/Shallot/issues/4, see https://github.com/katmagic/Shallot/issues/4#issuecomment-15142292.

**Comment by ageis** [comment]
Based on some attempts I made just now, I think getting scallion to work on Tails is going to be fraught with obstacles. Like you said, the OpenCL and Mono dependencies are one thing, but also just in order to use OpenCL you most likely need the non-free drivers for your card. For an Intel card you would have to download and install their [OpenCL runtime](https://software.intel.com/en-us/articles/opencl-drivers), for an AMD card you'd need the non-free fglrx (i.e. not radeon) driver and the [AMD APP SDK](http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/) and for an Nvidia card you'd need the non-free nvidia driver (i.e. not nouveau) which should have OpenCL support built-in. Since the Tails persistence only applies to userspace and you can't specify what kernel modules get loaded, I think this would basically be impossible to do on Tails.

**Comment by garrettr** [comment]
> A better bet is doing it on the App or Mon servers rather than the Admin Workstation, although the same driver requirements apply.

Installing software (and increasing attack surface) on the actual SecureDrop servers for a one-time (and somewhat frivolous) task like generating a vanity .onion is unacceptable. Especially when the dependencies include non-free graphic card drivers, because they are notoriously full of bugs and problematic on open source OS's.

**Comment by garrettr** [comment]
It seems like Shallot is the way to go, although I have concerned that it:

1. Is unmaintained
2. Has several open bugs which require patching to fix serious issues

One option would be for us to fork it, maintain the fork on the freedomofpress remote, apply those patches, and provide a package via the FPF apt repo. This is a significant amount of work and should be considered low priority.

Another good idea would be to ask around on the `#tor-dev` IRC, or tor-dev/tor-talk mailing lists, to get an idea of the current "state of the art."

**Comment by flamsmark** [comment]
I think that vanity `.onions` are a poor idea. They train people to verify exactly the part of the address that can be brute-forced, and encourage a behavior of *not* verifying `.onion` addresses. Although it's impractical to *prevent* orgs from generating vanity onions, rather than supporting it, I think you should strongly advise against the practice.

**Comment by redshiftzero** [comment]
I agree with @flamsmark and don't think we should encourage this practice of not verifying the entire `.onion` address by organizations creating a short (and thus easy to brute force) recognizable prefix in the onion address. Added "Pending close" label.

**Comment by heartsucker** [comment]
Agree. I have no specific data to back this up, but I'm pretty sure vanity onion addresses would increase the likelihood of successful phishes. Basing this off other clear-web phishing work I've done.

**Comment by freddymartinez9** [comment]
I also +1 closing this, particularly since I think _potential sources_ could be spooked if a news organization moved from a vanity onion to a non-vanity onion (in case they had to reinstall for example).
