### ISSUE TITLE
Revisit using PhantomJS for functional tests

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#990]
#988 is a good excuse to revisit using PhantomJS for the functional tests. We originally used PhantomJS, but there was a whole series of frustrating PhantomJS/Selenium compatibility issues (their release schedules were out of sync) that led us to switch to Firefox + xvfb.

The main benefits of PhantomJS over Firefox (assuming those compat issues have been resolved in the meantime) are:
1. PhantomJS is faster, => tests run faster
2. PhantomJS is smaller (14.5 MB vs. 39.7 MB for Firefox), which speeds up tests and also Vagrant provisioning.

**Comment by redshiftzero** [comment]
This was attempted [here](https://github.com/freedomofpress/securedrop/issues/2205#issuecomment-325163185) with little success, and we're going to switch to Tor Browser anyway, which makes sense given our use case. I'd rather we spend energy parallelizing the existing tests than migrating over to PhantomJS since parallelization will lead to bigger wins. Closing for now!
