### ISSUE TITLE
No error response returned when submission size exceeds LimitRequestBody

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#992]
We currently limit upload sizes to 500MB with the `LimitRequestBody` option in the source interface's Apache configuration. According to the [docs](https://httpd.apache.org/docs/current/mod/core.html#limitrequestbody),

> If the client request exceeds that limit, the server will return an error response instead of servicing the request.

The expected response can currently be observed in production. It can also be observed in the staging environment when it is accessed via the .onion, but (weirdly) is not observed when the staging environment is accessed on the local loopback interface.

# STR

1. Navigate to `/lookup` on the Source Interface
2. "Browse..." for a file and choose a file > 500MB.
3. Click "Submit".

**Expected Result:** In the bottom left corner of the browser, the connection status changes from "Connecting..." to "Sending request to xyz..." and then you get an error page that says "The connection was reset".

This is the error returned by Apache and can be observed in production and on the staging environment when accessed via the .onion.

**Actual Result:** The connection status in the bottom left corner says "Sending request to 127.0.0.1..." and a progress indicator is spinning in the tab at the top of the screen. This continues indefinitely. No data is ever uploaded to the server (you can check this by running `iotop` on the application server, or by watching `/tmp` for the SecureTemporaryFiles that are created there to handle large uploads: `watch -n 0.5 ls -lht /tmp/`).

This is only observed when accessing the Source Interface on staging via the local interface, e.g. `127.0.0.1:8082/lookup`.

**Comment by ageis** [comment]
My judgment for the moment is that this is actually a client-side issue pertaining to the browser having different behavior for POST requests and their responses on the loopback interface as opposed to the internet. I will explain the deduction and analysis I did to reach that conclusion below.

To recap a little, the `LimitRequestBody` functionality works by the server checking the `Content-Length` header that was submitted by the HTTP client in their POST request. If that value in bytes exceeds the allowed length, then an HTTP response code 413 ("Request Entity Too Large") will be returned.

It's relatively easy to confirm that with logging enabled on the source interface, if one uploads an >500MB file, the limit is recognized and that event is output to the log, no matter whether the client is originating from Tor or localhost. Furthermore if you look at the relevant [ttps://github.com/apache/httpd/blob/trunk/modules/filters/mod_request.c#L65](section of the Apache2 source code) that handles incoming requests, there are no cases applying to us where this check would get skipped:

```
[Tue Apr 14 02:29:55.705866 2015] [http:info] [pid 15716:tid 2837118256896] [client 127.0.0.1:51833] AH01588: Requested content-length of 1028653579 is larger than the configured limit of 524288000, referer: http://ymo6fpbcd5mtl2ph.onion/lookup
[Tue Apr 14 02:30:26.746646 2015] [http:info] [pid 15716:tid 2837000341248] [client 10.0.2.2:45961] AH01588: Requested content-length of 1028653583 is larger than the configured limit of 524288000, referer: http://127.0.0.1:8082/lookup
```

So the server seems to be doing the right thing. Now we can double check this with a packet capture on the client side. There really should be no substantive difference between the HTTP requests and responses whether the transport is loopback or Tor—that wouldn't make sense, and we can assume that the `Content-Length` header and `LimitRequestBody` directive is always functioning as it should.

![wireshark_shot](https://cloud.githubusercontent.com/assets/1161532/7131177/93334a1e-e230-11e4-926d-03a5fbb406c3.png)

But as is shown in the above Wireshark screenshot, there *is* actually an HTTP 413 "Request Entity Too Large" packet being sent to the client; the problem is that the browser is not processing it and stopping the upload. 

While the behavior of Firefox ("Sending request...") and Google Chrome ("Uploading 3%...") is similar, they are both not handling the 413 response as they should.

For background, there was actually [an issue opened against Chromium](https://code.google.com/p/chromium/issues/detail?id=174906) about this, which includes discussion about how to interpret the RFC and how the browser should behave when there is a 413 response during a file upload. They considered it a low priority then but it might be fixed in an upcoming version. 

Also see [this great StackOverflow post](http://stackoverflow.com/questions/18367824/how-to-cancel-http-upload-from-data-events/18370751#18370751), which notes how all major browsers are in violation of the RFC, which left open the question of whether the connection should be closed when there's a 413 or not. To quote directly:

> If you leave the socket open, all browsers (Chrome 30, IE 10, Firefox 21) will keep sending data until the entire file is uploaded. Then and only then, the browser will display your error message. This really sucks since the user must wait for the entire file to complete the upload, only to find out the server rejected it. It also wastes your bandwidth.

My guess is that the difference underlying this issue is in handling of state changes between TCP/IP sockets vs. IPC. Over Tor, the socket is properly closed, while on loopback the socket remains open, so what's presenting is expected behavior for how the major browsers have currently implemented the HTTP spec and status codes, which is lacking.

**Comment by garrettr** [comment]
Great analysis, @ageis! This is clearly a browser bug and there is nothing we can do about it. Fortunately it is an edge case that only occurs in the development environment. This issue will serve as documentation in case somebody else encounters this confusing behavior in the future.
